### ISSUE TITLE
When grouping, the values ​​in the cells disappear

### ISSUE THREAD

**Issue by FedorPRG** [bosskmk/pluto_grid#1005]
### Steps to reproduce the bug
1. changed the date type column format to MM/dd/yyyy
2. I click grouping in the menu and the values ​​in the cells disappear

### Expected results
When grouping, the value must remain in the cell

### Actual results
When grouping, the values ​​in the cells disappear

### Code sample
```dart
  PlutoColumn(
    filterPadding: EdgeInsets.zero,
    titleSpan: TextSpan(
        text: 'Date',
        style: TextStyle(
          color: Colors.black,
          fontSize: 16,
          fontWeight: FontWeight.w400,
        )),
    width: 150,
    title: 'Date',
    field: 'data',
    type: PlutoColumnType.date(format: 'MM/dd/yyyy'),
  ),
```

### Execution Environment
**Flutter version**
Flutter version is 3.16.4

**PlutoGrid version**
PlutoGrid version is 7.0.2

**OS**
Ubuntu 22.04.3 LTS
![2024-01-11_10-20](https://github.com/bosskmk/pluto_grid/assets/102856146/bfdf09cd-8abc-4864-bcd7-d09d9f7b5fbd)
![2024-01-11_10-21](https://github.com/bosskmk/pluto_grid/assets/102856146/f41f5b7d-d507-4232-a999-58cc66ab7076)

**Comment by FedorPRG** [comment]
I took the example of the date type column type and added grouping. Values ​​in cells with non-standard formatting disappear
![2024-01-11_11-04](https://github.com/bosskmk/pluto_grid/assets/102856146/91729baf-2a97-4e6b-be1b-95efc1e59871)
![2024-01-11_11-05](https://github.com/bosskmk/pluto_grid/assets/102856146/c7d73b42-9b73-4703-81eb-34ea7f06157c)

**Comment by dorklein** [comment]
I also ran into the same issue.

**Comment by FedorPRG** [comment]
![image](https://github.com/bosskmk/pluto_grid/assets/102856146/20b4588a-9370-4abf-a633-cacc20615bb2)
