### ISSUE TITLE
[Bug] Horizontal Scrollbar Freezes on Firefox

### ISSUE THREAD

**Issue by EduardoYamauchi** [bosskmk/pluto_grid#1014]
### Steps to reproduce the bug

1. Open the Firefox browser.
2. Navigate to https://weblaze.dev/pluto_grid/build/web/#feature/cell-selection
3. Scroll the grid to the bottom part of the Grid.
4. With the mouse, click on the horizontal scrollbar.
5. Quickly move to the end and start of the rows.

Result: The scroll becomes stuck.

https://github.com/bosskmk/pluto_grid/assets/13737650/4ed48303-c830-4725-b620-19dafd195871

## Software versions

Flutter version: 3.16.9
PlutoGrid version: 7.0.2
macOS Sonoma: 14.3
Firefox browser version: 122.0 (64-bit)

**Comment by FilipeMoreira** [comment]
Same here

Flutter version: 3.16.8
PlutoGrid version: 7.0.2
Windows: 11 22H2
Firefox browser version: 122.0.1 (64-bit)

**Comment by PabloCurty** [comment]
Same here.

Flutter version: 3.16.8
PlutoGrid version: 7.0.2
Windows: 11 22H2
Firefox browser version: 122.0.1 (64-bit)

**Comment by EduardoYamauchi** [comment]
Waiting for answers.

**Comment by EduardoYamauchi** [comment]
@bosskmk waiting for answers, please reopen this issue.
