### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by agustin-garcia** [bosskmk/pluto_grid#1018]
Hello,
After today's flutter upgrade, I started getting the compilation error: "
       pluto_grid-7.0.2/lib/src/manager/shortcut/pluto_grid_shortcut.dart:33:39: Error: The argument type 'RawKeyEvent' 
       can't be assigned to the parameter type 'KeyEvent'.
       - 'RawKeyEvent' is from 'package:flutter/src/services/raw_keyboard.dart' ('/D:/DevTools/flutter/packages/flutter/lib
          /src/services/raw_keyboard.dart').
       - 'KeyEvent' is from 'package:flutter/src/services/hardware_keyboard.dart' ('/D:/DevTools/flutter/packages
          /flutter/lib/src/services/    hardware_keyboard.dart')
    "
I'm trying it under the tech stack shown below. I've been looking into different forums but I'm unable to find any help/guidance on what to do.

  • Flutter version 3.19.0 on channel stable
  • Framework revision bae5e49bc2 (5 days ago), 2024-02-13 17:46:18 -0800
  • Engine revision 04817c99c9
  • Dart version 3.3.0
  • DevTools version 2.31.1
  • Windows 11
  • Platform android-34, build-tools 34.0.0
  • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

Thanks

**Comment by jayakumarzoftsol** [comment]
same issue here ....

**Comment by agustin-garcia** [comment]
Just as an update, I did downgraded to Flutter's previous version and all pluto_grid functions are working again.
Not sure if this issue should be reported here or somewhere else.
Regards

**Comment by darkomenx** [comment]
I also confirm in my part the same issue just after upgrade flutter channel stable.
You need to create issue with correct and efficiency title (help title is the worst title of the world)

**Comment by hombre-geek** [comment]
I have the same problem as mentioned, the solution was to return to Flutter version 3.16.8 on channel stable. I hope they can solve it soon, so I can continue working with this package.
