### ISSUE TITLE
Reopening Android Back Button not working once Pluto Grid is rendered on screen

### ISSUE THREAD

**Issue by meetcse** [bosskmk/pluto_grid#1022]
This is the same issue as mentioned in below issue
https://github.com/bosskmk/pluto_grid/issues/932

Once Pluto grid is rendered, android native back button or swipe gestures is not working for popping out the screen. On tapping that back button displays following error :
════════ Exception caught by widgets library ═══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

**Comment by KaushikGupta007** [comment]
Still not resolved

**Comment by KaushikGupta007** [comment]
> Still not resolved

https://github.com/bosskmk/pluto_grid/issues/1066

**Comment by KaushikGupta007** [comment]
Any workaround for the same?
