### ISSUE TITLE
[Bug] The argument type 'RawKeyEvent' can't be assigned to the parameter type 'KeyEvent'.

### ISSUE THREAD

**Issue by hungmt** [bosskmk/pluto_grid#1024]
I got a error, can resolve, upgrade to 8.0.0 so got error intl 19
![image](https://github.com/bosskmk/pluto_grid/assets/135787831/1e199d54-d6dd-422c-8a57-15a0ece891c2)
Error Text:
/C:/Users/Admin/AppData/Local/Pub/Cache/hosted/pub.dev/pluto_grid-7.0.2/lib/src/manager/shortcut/pluto_grid_shortcut.dart:33:39: Error: The argument type 'RawKeyEvent' can't be assigned to the parameter type 'KeyEvent'.
 - 'RawKeyEvent' is from 'package:flutter/src/services/raw_keyboard.dart' ('../../../../Flutter/flutter/packages/flutter/lib/src/services/raw_keyboard.dart').
 - 'KeyEvent' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../../../Flutter/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
      if (action.key.accepts(keyEvent.event, state)) {
....
Please help me check

**Comment by leva0212** [comment]
I am facing the same trouble since today.

**Comment by shayneoneill** [comment]
Same problem. On Macos. Absolutely bamboozled by it as I'm not going anywhere near that code.

**Comment by psarridis** [comment]
Same problem here.

Using Flutter version 3.19.2
Pluto grid version 8.0.0

So in flutter 3.19.2 the intl version is pinned to 0.18.1 check [flutter repo](https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml)
But in pluto grid 8.0.0 the intl version is 0.19.0 check [pluto grid repo](https://github.com/bosskmk/pluto_grid/blob/master/pubspec.yaml)

**Comment by stoneLee81** [comment]
pluto_grid_plus can solve this issue.

**Comment by kutsaltekbas** [comment]
using pluto_grid_plus worked for me

**Comment by leva0212** [comment]
> using pluto_grid_plus worked for me

After having lost all hope I read your comment about pluto_grid_plus and I was able to restore my pluto gris as I had them, thank you very much

**Comment by naidu199** [comment]
if (action.key.accepts(keyEvent.event, state)) 
     change this line of code in the /C:/Users/Naidu/AppData/Local/Pub/Cache/hosted/pub.dev/pluto_grid-7.0.2/lib/src/manager/shortcut/pluto_grid_shortcut.dart:33:40: in this in your terminal with this 
           if (action.key.accepts(keyEvent as KeyEvent, state as HardwareKeyboard)) 
           By this this error has been resolved for me
