### ISSUE TITLE
[Bug] Use PlutoGridStateManager to select one row is not working when mode is select or selectWithOneTap

### ISSUE THREAD

**Issue by yuanhoujun** [bosskmk/pluto_grid#1032]
### Steps to reproduce the bug
1. Set `PlutoGrid` mode to `PlutoGridMode.select`.
2. Call code as follow to select one row: 
```
 _stateManager.setCurrentSelectingRowsByRange(event.rowIdx, event.rowIdx);
```

### Execution Environment
**Flutter version**
Flutter version is 3.19.2

**PlutoGrid version**
PlutoGrid version is 8.0.0

**OS**
macOS 14.2.1

**Comment by zzt741** [comment]
Same question, when the mode is selectWithOneTap etc, the PlutoGridSelectingMode will be set to PlutoGridSelectingMode.none, and when the mode is none, stateManager.setCurrentSelectingPosition and so on will has no effect, I even can't set SelectingMode manually, this is very unreasonble!
