### ISSUE TITLE
[Bug] ++ pubspec.yaml for pluto_grid_export

### ISSUE THREAD

**Issue by flutter-painter** [bosskmk/pluto_grid#1035]
Because pluto_grid_export 1.0.6 depends on pluto_grid >=3.0.2 <8.0.0 and no versions of pluto_grid_export match >1.0.6 <2.0.0, pluto_grid_export ^1.0.6 requires pluto_grid >=3.0.2 <8.0.0.

**Comment by sharpsaravanan** [comment]
please update

**Comment by flutter-painter** [comment]
?
