### ISSUE TITLE
[Help] Copy the content of selecting cell to the clipboard

### ISSUE THREAD

**Issue by sinhpn92** [bosskmk/pluto_grid#1042]
Hello team,

I need to implement a PlutoGrid with a large list for our app running on MacOS. Currently, users are unable to copy the content of the selecting cell to the clipboard using standard copy shortcuts. We need to ensure that after users select the content of the cells, they can copy it to the clipboard seamlessly.

<img width="854" alt="Screenshot 2024-04-13 at 16 22 46" src="https://github.com/bosskmk/pluto_grid/assets/9253441/5ea466cc-1680-41c3-806a-f5fdb47c497c">

Thank you.

**Comment by bosskmk** [comment]
You can copy with control + c and paste with control + v. Please refer to the link below to change the shortcut key.

https://pluto.weblaze.dev/shortcuts

**Comment by sinhpn92** [comment]
Thank you so much. 
On MacOS It's working with Command + C. I will update this custom shortcut key.
