### ISSUE TITLE
TextField Focus issue 

### ISSUE THREAD

**Issue by irshad-hz** [bosskmk/pluto_grid#1045]
A Textfield is placed above the plutogrid tabel if i focus that textfield plutogrid first row is focusing automatically in selectWithOneTap mode if i change it to readonly then it is working fine but i want ontap too , is there any way to handel this?

**Comment by hitashaRajesh** [comment]
I also faced a similar issue.
A search Text field is placed above the pluto grid table . If i focus that textfield , pluto grid is rebuilt and automatically dismisses the opened keyboard in selectWithOneTap mode. If I change it to readOnly mode then it is working fine but i want that to work in selectWithOneTap mode.

**Comment by FedorPRG** [comment]
![Screenshot from 2024-08-29 08-28-12](https://github.com/user-attachments/assets/398ba1fb-8a7b-46e6-90c6-9fcd564df0af)

Line 578 takes focus, try commenting it out.

**Comment by MTaimoor99** [comment]
This looks like a platform specific issue. On web, the textfields do not lose focus by using selectWithOneTap. They do lose focus by using selectWithOneTap on Android 10 and 13. 

The textfields do not lose focus in Android 15 though.
