### ISSUE TITLE
pluto_grid_export is not compatible with Flutter 3.22.2 and Dart 3.4.3

### ISSUE THREAD

**Issue by CesareIsHere** [bosskmk/pluto_grid#1072]
When running pluto_grid_export in a repo with Flutter 3.22.2 and Dart 3.4.3 , the compiler returns error.

**Comment by chandlery54** [comment]
This is a major issue that we keep running into as well. Is `pluto_grid_export` not supported anymore??

**Comment by VittorioParagallo** [comment]
this package is not maintained https://github.com/bosskmk/pluto_grid/issues/968 there is a fork taking over it with a lot of commits ahead, may be you want to check it there https://github.com/doonfrs/pluto_grid_plus there is also pluto_grid_export plus
