### ISSUE TITLE
[Help] Can we create a custom widget in cells instead of standard ones like text, number, date, time, etc? 

### ISSUE THREAD

**Issue by nitishabraham20** [bosskmk/pluto_grid#1078]
I have a requirement where we need to create a custom widget and display it after selecting a row cell. Is it possible?

**Comment by VittorioParagallo** [comment]
this package is not maintained https://github.com/bosskmk/pluto_grid/issues/968 there is a fork taking over it with a lot of commits ahead, may be you want to ask there https://github.com/doonfrs/pluto_grid_plus
