### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wamunyima3** [bosskmk/pluto_grid#1083]
Cannot not leave a cell blank, For example
For example i create a table
columns:
sn, username, email, score

rows:
sn  value = 1, username value = 'user1', email value = 'test@gmail.com', score value = 10
sn  value = 2, username value = 'user2', email value = 'test1@gmail.com', 

on the second user there is no score because they have not yet attempted the quiz, now i get a null value error

here is the sample code

  bool _isLoading = true;
  User? _user;
  String? _profileImageUrl;
  String? _email;

  PlutoGridStateManager? stateManager;
  final List<PlutoColumn> columns = [
    PlutoColumn(
      title: 'SN',
      field: 'sn',
      type: PlutoColumnType.number(),
    ),
    PlutoColumn(
      title: 'Username',
      field: 'username',
      type: PlutoColumnType.text(),
    ),
    PlutoColumn(
      title: 'Email',
      field: 'email',
      type: PlutoColumnType.text(),
    ),
  ];
  final List<PlutoRow> rows = [];

  @override
  void initState() {
    super.initState();
    _loadUserDetails();
    loadGridData();
  }

  Future<void> _loadUserDetails() async {
    setState(() {
      _isLoading = true;
    });

    final user = Supabase.instance.client.auth.currentUser;
    if (user != null) {
      setState(() {
        _user = user;
        _profileImageUrl = user.userMetadata?['avatar_url'] as String?;
        _email = user.email;
      });
    }

    setState(() {
      _isLoading = false;
    });
  }

  Future<void> loadGridData() async {
    setState(() {
      _isLoading = true;
    });

    // Fetch user scores, lesson titles, and usernames
    final scores = await supabase.from('userscore').select(
        'score, profiles:userid(email, full_name), quiz:quizid(thoughtquestion, lesson:lessonid(title)))');

    print(scores);
    
    // Add lesson columns dynamically
    Set<String> titles = {};
    for (var column in scores) {
      String lessonTitle = column['quiz']['lesson']['title'];
      if (!titles.contains(lessonTitle)) {
        titles.add(lessonTitle);
        columns.add(
          PlutoColumn(
            title: lessonTitle,
            field: lessonTitle,
            type: PlutoColumnType.number(),
          ),
        );
      }
    }

    // Create rows
    var i = 0;
    Map<String, PlutoRow> userRows = {};

    for (var score in scores) {
      String email = score['profiles']['email'];
      if (!userRows.containsKey(email)) {
        var cells = <String, PlutoCell>{};

        cells['sn'] = PlutoCell(value: ++i);
        cells['username'] = PlutoCell(value: score['profiles']['full_name']);
        cells['email'] = PlutoCell(value: email);

        userRows[email] = PlutoRow(cells: cells);
      }

      userRows[email]!.cells[score['quiz']['lesson']['title']] =
          PlutoCell(value: score['score']);
    }

    rows.addAll(userRows.values);

    setState(() {
      _isLoading = false;
    });

    // Insert columns and rows into the state manager if it is initialized
    if (stateManager != null) {
      stateManager!.insertColumns(0, columns);
      stateManager!.insertRows(0, rows);
    }
  }
  
  
  PlutoGrid(
              columns: columns,
              rows: rows,
              onLoaded: (event) => setState(() {
                stateManager = event.stateManager;
              }),
            ),
            
            

the simple walk around i had done is 

    for (var score in scores) {
      String email = score['profiles']['email'];
      if (!userRows.containsKey(email)) {
        var cells = <String, PlutoCell>{};

        cells['sn'] = PlutoCell(value: ++i);
        cells['username'] = PlutoCell(value: score['profiles']['full_name']);
        cells['email'] = PlutoCell(value: email);

        // Initialize all lesson columns with empty strings
        for (var title in titles) {
          cells[title] = PlutoCell(value: '');
        }

        userRows[email] = PlutoRow(cells: cells);
      }

      // Update the cell with the actual score if it exists
      userRows[email]!.cells[score['quiz']['lesson']['title']] =
          PlutoCell(value: score['score'] ?? '');
    }
    
    
    so please add a way to pass a default value to the grid without storing it to the database or creating a mess in my code

**Comment by VittorioParagallo** [comment]
this package is not maintained https://github.com/bosskmk/pluto_grid/issues/968 there is a fork taking over it with a lot of commits ahead, may be you want to commit there https://github.com/doonfrs/pluto_grid_plus
