### ISSUE TITLE
Onchanged function is not called correctly

### ISSUE THREAD

**Issue by Anandh2708** [bosskmk/pluto_grid#1086]
### Code sample
```dart
/// If you have a code sample here, please attach it.
```

### Execution Environment
**Flutter version**

**PlutoGrid version**

**OS**

**Comment by VittorioParagallo** [comment]
this package is not maintained https://github.com/bosskmk/pluto_grid/issues/968 there is a fork taking over it with a lot of commits ahead, may be you want to ask there https://github.com/doonfrs/pluto_grid_plus
