### ISSUE TITLE
[Bug] Because pluto_grid_export >=1.0.5 depends on pluto_grid >=3.0.2 <8.0.0 and getx_admin_panel depends on pluto_grid ^8.0.0, pluto_grid_export >=1.0.5 is forbidden. So, because getx_admin_panel depends on pluto_grid_export ^1.0.5, version solving failed.   You can try the following suggestion to make the pubspec resolve: * Consider downgrading your constraint on pluto_grid: flutter pub add pluto_grid:^7.0.2

### ISSUE THREAD

**Issue by minahil57** [bosskmk/pluto_grid#1089]
### Code sample
```dart
/// If you have a code sample here, please attach it.
```

### Execution Environment
**Flutter version**

**PlutoGrid version**

**OS**

**Comment by VittorioParagallo** [comment]
this package is not maintained https://github.com/bosskmk/pluto_grid/issues/968 there is a fork taking over it with a lot of commits ahead, may be you want to ask there https://github.com/doonfrs/pluto_grid_plus

**Comment by AlecDr** [comment]
have you tried downgrading pluto_grid to 7.0.2? as stated in the error message

**Comment by henry2man** [comment]
It looks that https://pub.dev/packages/pluto_grid_plus do support recent Flutter versions. As the father of `pluto_grid_export` I don't know what to expect of this package :/
