### ISSUE TITLE
[Help] Dynamic height as the number of Rows of the table

### ISSUE THREAD

**Issue by ErsinMandaci** [bosskmk/pluto_grid#1098]
How do I ensure that PlutoGrid gets dynamic height as much as the row in the table?

**Comment by VittorioParagallo** [comment]
this package is not maintained https://github.com/bosskmk/pluto_grid/issues/968 there is a fork taking over it with a lot of commits ahead, may be you want to ask there https://github.com/doonfrs/pluto_grid_plus

**Comment by AlecDr** [comment]
have you tried using layoutbuilder?

I havent tried but i think that would work
