### ISSUE TITLE
[Help] How to show text on  grouped rows

### ISSUE THREAD

**Issue by aike1202** [bosskmk/pluto_grid#1108]
I want show sum of grouped items on grouped row , is it supported ,if not  will be support in Feature 
Thanks 
![QQ20240912-165651](https://github.com/user-attachments/assets/cc74e995-8cba-429c-ae28-70cc0d93c34a)

**Comment by epiphanizer** [comment]
Would love to do this as well --- we are stuck in our use-case at the same spot.
