### ISSUE TITLE
Filter by code

### ISSUE THREAD

**Issue by JesusMayuri7** [bosskmk/pluto_grid#117]
Congratulations on the great work.

One question, can you filter by code from outside the grid?

**Comment by JesusMayuri7** [comment]
`PlutoGrid(
              columns: myData.columns,
              rows: myData.rows,
              onLoaded: (PlutoOnLoadedEvent event) {
                stateManager = event.stateManager;
              },
            ),


  buscar() {
    stateManager.setFilter((element) {
      return element.cells.entries.elementAt(2).value.value.contains('item2');
    });
  }

  liberar() {
    stateManager.setFilter(null);
  }

`

**Comment by bosskmk** [comment]
Well done.
I will document the filter related things.

**Comment by aadi-github** [comment]
> PlutoStateManager stateManager;
> 
> `PlutoGrid( columns: myData.columns, rows: myData.rows, onLoaded: (PlutoOnLoadedEvent event) { stateManager = event.stateManager; }, ),
> 
> filter() { stateManager.setFilter((element) { // Number 2 is column return element.cells.entries.elementAt(2).value.value.contains('item2'); }); }
> 
> reset_filter() { stateManager.setFilter(null); } `

Based on JesusMayuri7's answer I have modified the code a little bit as per my usage. Thanks for your contribution.

_searchController.addListener(() {
      _plutoGridStateManager!.setFilter((element) {
        bool matched = element.cells.entries.any((obj) => obj.value.value
            .toString()
            .toLowerCase()
            .contains(_searchController.text.toLowerCase()));
        return matched;
      });
//This setState does not rebuild Table, as that requires a new key or change in key to be provided.//
//But this will filter the data inside the table very efficiently. Really awesome plugin.//
      setState(() {});
    });

**Comment by coda538** [comment]
Is there a way to retrieve column index by its name?
Something like:
`colIdx = ...;
return element.cells.entries.elementAt(colIdx).value.value.contains('item2');`
