### ISSUE TITLE
Header multiline

### ISSUE THREAD

**Issue by gcomm-trile** [bosskmk/pluto_grid#120]
Can i config header of a column  with multiline?
Here is my code :PlutoColumn( title: 'Welcome\nto\nMyWorld\nHello\nWorld\n')

**Comment by bosskmk** [comment]
Currently, the height of the column is fixed.
It needs work to be able to change it.
I will try to make it up to the next version.

**Comment by merabtenei** [comment]
Up.
Is there any update on this ?
I have a use case where I have many columns like Initial quantity, final quantity that I want to display as Initial\nquantity. Display Initial on one line and quantity below this will display the whole information without cropping it and just display Initial ...

I tried with titleSpan but it didn't seem to work.
Is there any workaround for this ?

**Comment by bosskmk** [comment]
@merabtenei 
Can you attach the code and screenshots you tried?

**Comment by yairsts** [comment]
You can try this:

  final columns = state!.columns;
  for (var element in columns) {
    state!.resizeColumn(element, 0.1);
    state!.resizeColumn(element, -0.1);
  }
  state!.notifyResizingListeners();
}
