### ISSUE TITLE
Problem dependency intl 

### ISSUE THREAD

**Issue by jeansebastienZ** [bosskmk/pluto_grid#124]
Hello , 

Getting this error : 
`flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2 and pluto_grid >=0.1.1 depends on intl ^0.16.1`

Have you got the possibility to upgrade your package dependency ?

The personal solution i use to override this problem is :
```
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
```
But don't know what it imply.

**Comment by milodude** [comment]
@jeansebastienZ  solution is a great workaround but would be nice to have those dependencies updated.
