### ISSUE TITLE
Request to add new feature - row ontap to nagivate 

### ISSUE THREAD

**Issue by dktiong** [bosskmk/pluto_grid#126]
Hi, 

i would like to request to enhance the new feature at row by adding in ontap, ondoubletap function

**Comment by dktiong** [comment]
this package will be perfect if the requested enhancement has been added

**Comment by chrislaurie-bs** [comment]
Internally, there is something that happens when you tap on a row or column: the row turns light blue, and the cell you have clicked on gets a darker blue border. If there could be a onHighgthed / onTap event that can be trapped here, it would be perfect.
