### ISSUE TITLE
Cannot use setState() to change row data

### ISSUE THREAD

**Issue by cuitao1988** [bosskmk/pluto_grid#131]
newbie in programming.Pls help

**Comment by cuitao1988** [comment]
I find data is set to PlutoGrid.rows,but not show on the widget.I use "auto fit " in the menu of one column,data shows on the widget.Pls HELP

**Comment by bosskmk** [comment]
I need minimal code to reproduce the problem, but
Guessing, here are two suggestions for solving the problem.

1. When you want to directly change the rows property you pass when creating the grid, you need to call notifyListeners.
```dart
PlutoGridStateManager stateManager;

var rows = [];

var grid = PlutoGrid(
  columns: columns,
  rows: rows,
  onLoaded: (PlutoGridOnLoadedEvent event) {
    stateManager = event.stateManager;
  },
);

rows = [PlutoRow(...)];
// If you want to change the rows property directly, you must call notifyListeners for the change to be reflected.
stateManager.notifyListeners();
```

2. Use the stateManager's insertRows, prependNewRows, prependRows, appendNewRows, appendRows, removeCurrentRow, and removeRows methods to change the state of rows.

**Comment by cuitao1988** [comment]
Thank you so much.It works!
