### ISSUE TITLE
Focusproblem with flutter master on WEB

### ISSUE THREAD

**Issue by exomaniac** [bosskmk/pluto_grid#132]
In flutter beta the column heading disapears if you enable a column filter.
In master this is fixed, but the textfields dont get focus anymore.

the fix here is to change to the new keyhandled signature:

```dart
KeyEventResult handleOnKey(FocusNode node, RawKeyEvent event) {
    return  KeyEventResult.ignored;
}
```
After i changed this in 'pluto_colum_filter.dart' ad 'pluto_grid.dart' filter could be used again.

**Comment by bosskmk** [comment]
First of all, thank you for the bug report.

If it returns true, it seems to be KeyEventResult.handled, and if it returns false, it might be changed to KeyEventResult.ignored.

I refer to the flutter code below.

I will release it as 1.1.1 by modifying it like this.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/focus_manager.dart

```dart
// 1630 line
bool _handleRawKeyEvent(RawKeyEvent event) {
    // Update highlightMode first, since things responding to the keys might
    // look at the highlight mode, and it should be accurate.
    _lastInteractionWasTouch = false;
    _updateHighlightMode();

    assert(_focusDebug('Received key event ${event.logicalKey}'));
    if (_primaryFocus == null) {
      assert(_focusDebug('No primary focus for key event, ignored: $event'));
      return false;
    }

    // Walk the current focus from the leaf to the root, calling each one's
    // onKey on the way up, and if one responds that they handled it or want to
    // stop propagation, stop.
    bool handled = false;
    for (final FocusNode node in <FocusNode>[_primaryFocus!, ..._primaryFocus!.ancestors]) {
      if (node.onKey != null) {
        // TODO(gspencergoog): Convert this from dynamic to KeyEventResult once migration is complete.
        final dynamic result = node.onKey!(node, event);
        assert(result is bool || result is KeyEventResult,
            'Value returned from onKey handler must be a non-null bool or KeyEventResult, not ${result.runtimeType}');
        if (result is KeyEventResult) {
          switch (result) {
            case KeyEventResult.handled:
              assert(_focusDebug('Node $node handled key event $event.'));
              handled = true;
              break;
            case KeyEventResult.skipRemainingHandlers:
              assert(_focusDebug('Node $node stopped key event propagation: $event.'));
              handled = false;
              break;
            case KeyEventResult.ignored:
              continue;
          }
        } else if (result is bool){
          if (result) {
            assert(_focusDebug('Node $node handled key event $event.'));
            handled = true;
            break;
          } else {
            continue;
          }
        }
        break;
      }
    }
    if (!handled) {
      assert(_focusDebug('Key event not handled by anyone: $event.'));
    }
    return handled;
  }
```

**Comment by bosskmk** [comment]
As a result of checking, changing the return value from bool to KeyEventResult has nothing to do with that problem.

I think the problem is that the behavior according to the return value of onKey of RawKeyboardListener in Web and Desktop is different.

I have registered the issue at the link below.

https://github.com/flutter/flutter/issues/74497

**Comment by exomaniac** [comment]
Thank you for your response.
Indeed did changing the results to KeyEventResul.ignored give us a functionen web version, but we did not test all cases of plutogrid. 

For my understanding it was correctbehavior that the key event was consumed if you return that you handled to event.
Thank you for the issu @ flutter.
It will be interessting to see if the handling on web is wrong or on windows for example.
