### ISSUE TITLE
Number column formatting for value 0.000 displays 0

### ISSUE THREAD

**Issue by bmulvaney** [bosskmk/pluto_grid#135]
PlutoColumn(
        title: 'Measure',
        field: 'measure',
        type: PlutoColumnType.number(format: '#,###.###',),
        width: 80,)

If the value for the cell is 0.000 you get 0 displayed. If 0.001 is used it is displayed correctly ?

**Comment by bosskmk** [comment]
Yes, if it is 0.000, 0 is displayed, and if it is 0.001, 0.001 is displayed. What's wrong with this?

**Comment by bmulvaney** [comment]
My use case is a grid of measurements to three decimal places - so assumed that it would honor the .### format and not truncate if the last digit is zero? Could the truncation be optional ?

**Comment by bosskmk** [comment]
It is possible to pad the decimal places with zeros. However, 0.0 is assigned as the actual value, and only 0.000 displayed on the screen can be expressed.

https://github.com/bosskmk/pluto_grid/wiki/column-definition-for-english#formatter-example

```dart
      PlutoColumn(
        title: '3 decimal places',
        field: 'three_decimal',
        type: PlutoColumnType.number(
          format: '#,###.###',
        ),
        formatter: (dynamic v) {
          return v.toDouble().toStringAsFixed(3);
        },
      ),
```

Further development is required to keep 0.000 in edit state.

For example, a number of million can be displayed as 1,000,000, but it is currently 1000000 in the editing state.

**Comment by bmulvaney** [comment]
That works fine

**Comment by bmulvaney** [comment]
Thanks for the response - formatter works as explained
