### ISSUE TITLE
Unable to start my app after upgraded to version from 1.0.0 to 1.1.1

### ISSUE THREAD

**Issue by allenlim0627Enterprise** [bosskmk/pluto_grid#145]
Hi, 

I try to use the column hiding function so I upgraded my pubspec to version 1.1.1, but ever since that upgrade, I keep hitting "Error: Type 'KeyEventResult' not found" error whenever I try to run my app. I will attach the file with all the message in debug console. I even try to downgrade my app back to version 1.0.0 but it still hit the same error. Please kindly advise how should I get rid of the issue.
[errorMessage.txt](https://github.com/bosskmk/pluto_grid/files/5949915/errorMessage.txt)

Thank you so much.

**Comment by jeansebastienZ** [comment]
Hello men ,

First did you clean , invalidate file and restarted your app ?
Second could you give some reproducible code , thanks you !

**Comment by jeansebastienZ** [comment]
> Hello men ,
> 
> First did you clean , invalidate file and restarted your app ?
> Second could you give some reproducible code , thanks you !

I did update yesterday and did not get any problem , so for sure we can find out where the problem come from !

**Comment by codeliu6572** [comment]
@jeansebastienZ @allenlim0627Enterprise I still meet this question when run at iOS
Launching lib/main.dart on iPhone 12 in debug mode...
Running Xcode build...
Xcode build done.                                           18.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    ../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/pluto_grid-1.1.1/lib/src/pluto_grid.dart:217:3: Error: Type 'KeyEventResult' not found.
      KeyEventResult handleGridFocusOnKey(FocusNode focusNode, RawKeyEvent event) {
      ^^^^^^^^^^^^^^
    ../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/pluto_grid-1.1.1/lib/src/ui/columns/pluto_column_filter.dart:94:3: Error: Type 'KeyEventResult' not found.
      KeyEventResult handleOnKey(FocusNode node, RawKeyEvent event) {
      ^^^^^^^^^^^^^^
    ../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/pluto_grid-1.1.1/lib/src/ui/cells/mixin_popup_cell.dart:108:3: Error: Type 'KeyEventResult' not found.
      KeyEventResult _handleKeyboardFocusOnKey(
      ^^^^^^^^^^^^^^
    ../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/pluto_grid-1.1.1/lib/src/pluto_grid.dart:223:12: Error: The getter 'KeyEventResult' isn't defined for the class '_PlutoGridState'.
     - '_PlutoGridState' is from 'package:pluto_grid/src/pluto_grid.dart' ('../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/pluto_grid-1.1.1/lib/src/pluto_grid.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'KeyEventResult'.
        return KeyEventResult.handled;
               ^^^^^^^^^^^^^^
    ../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/pluto_grid-1.1.1/lib/src/ui/columns/pluto_column_filter.dart:124:12: Error: The getter 'KeyEventResult' isn't defined for the class '_PlutoColumnFilterStateWithChange'.
     - '_PlutoColumnFilterStateWithChange' is from 'package:pluto_grid/src/ui/columns/pluto_column_filter.dart' ('../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/pluto_grid-1.1.1/lib/src/ui/columns/pluto_column_filter.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'KeyEventResult'.
        return KeyEventResult.handled;
               ^^^^^^^^^^^^^^
    ../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/pluto_grid-1.1.1/lib/src/ui/cells/mixin_popup_cell.dart:119:18: Error: The getter 'KeyEventResult' isn't defined for the class 'MixinPopupCell<T>'.
     - 'MixinPopupCell' is from 'package:pluto_grid/src/ui/cells/mixin_popup_cell.dart' ('../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/pluto_grid-1.1.1/lib/src/ui/cells/mixin_popup_cell.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'KeyEventResult'.
              return KeyEventResult.handled;
                     ^^^^^^^^^^^^^^
    ../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/pluto_grid-1.1.1/lib/src/ui/cells/mixin_popup_cell.dart:124:12: Error: The getter 'KeyEventResult' isn't defined for the class 'MixinPopupCell<T>'.
     - 'MixinPopupCell' is from 'package:pluto_grid/src/ui/cells/mixin_popup_cell.dart' ('../../../../opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/pluto_grid-1.1.1/lib/src/ui/cells/mixin_popup_cell.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'KeyEventResult'.
        return KeyEventResult.ignored;
               ^^^^^^^^^^^^^^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Flutter' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 12.

**Comment by bosskmk** [comment]
@codeliu6572 
Please use version 1.1.0 for now.
This error occurs because KeyEventResult is not in the stable or beta channel.
