### ISSUE TITLE
Cannot typing on table

### ISSUE THREAD

**Issue by BangPei** [bosskmk/pluto_grid#146]
hi, after i upgrade flutter to version 1.26.0-17.3.pre i cannot typing anything inside table. and i try to open your documentation and cannot typing anything inside table.
this link https://weblaze.dev/pluto_grid/build/web/#feature/number-type-column

can you help me?

**Comment by JamesBewley** [comment]
I notice this on the example website wasn't accepting input for editable fields and thought I was going mad!

Found it works in my dev environment Flutter 1.25.0-8.3.pre so I guess something has broken in the newer release.

**Comment by BangPei** [comment]
oke note, so i must downgrade flutter version?

**Comment by JamesBewley** [comment]
Downgrading is hopefully one workaround but obviously needs to be investigated and fixed by the Pluto devs.

**Comment by BangPei** [comment]
ok thanks, i try to downgrade flutter first.

**Comment by bosskmk** [comment]
Since flutter's web and desktop are not yet stable versions, these problems have often been encountered.
In case of this problem you will have to wait for the problem to be resolved in the master channel.

Or, as mentioned above, you should run it on a non-issue version.

**Comment by BangPei** [comment]
thanks, i try to downgrade flutter

**Comment by JamesBewley** [comment]
@bosskmk does the web demo always use the latest version of flutter beta?  Would it be OK to simply check if the web demo is working to determine if it is safe to upgrade flutter?

**Comment by bosskmk** [comment]
Operates based on the master channel.  Integration tests should be added for each platform.

**Comment by JamesBewley** [comment]
@bosskmk sorry, I mean is the web demo built using the head of the beta channel of flutter?

**Comment by bosskmk** [comment]
web demo is built on master channel.

**Comment by JamesBewley** [comment]
@bosskmk OK, I'm just starting out with flutter web and still building my knowledge.  I assumed from the flutter docs that flutter web is only available in the beta channel.

Thanks.

**Comment by bosskmk** [comment]
Yes, it can also be used in develop and master channels, which are the latest channels than beta channels. 

For reference, I plan to change my development channel to beta when the desktop is supported in beta.

**Comment by BangPei** [comment]
when i switched to master channel i can type everything in table, but i can't move my focus column by keyboard even i press enter to change my value.

**Comment by bosskmk** [comment]
@BangPei 
I had the same problem on the master channel last time, but it was resolved after a while.

I don't know if this is the same problem or if the way keyboard events are handled has changed overall.

I think I could solve it myself, but I hope that the flutter version will be changed and it will be solved automatically.

**Comment by JamesBewley** [comment]
I'm in a situation where another package I'm using has issues in the beta channel.  I tried upgrading to master branch and the charts package now works but I have the input issue with pluto grid.

Weirdly if I open developer tools the issue goes away and I can edit cells again .

**Comment by amasahara** [comment]
i have same problem, i cannot edit cell when typing something, on web i meet same problem. hope you can fix it soon

**Comment by michelemazzei** [comment]
Hi, I have the same problem on flutter 2 (build for web). I cannot make any filter on the table because it does not accept any key typing. I've tested it on chrome for pc.
