### ISSUE TITLE
Custom Cell Types (checkbox cell)

### ISSUE THREAD

**Issue by JamesBewley** [bosskmk/pluto_grid#147]
Hello,

I really like the look of this grid but want a couple of additional cell types, initially a checkbox cell type.  Is there a recommended pattern to achieve this sort of thing?

If not, is there a cell type where I can display my own widget?

EDIT: I've found the web demo; great work!

**Comment by kevinxxq** [comment]
Hi James,
_If not, is there a cell type where I can display my own widget?_

Would you please share the web demo? I can't find it from https://weblaze.dev/pluto_grid/build/web/#/

Thanks.

**Comment by kevinxxq** [comment]
> You can use a custom cell renderer
> 
> https://weblaze.dev/pluto_grid/build/web/#feature/cell-renderer

Thank you.
