### ISSUE TITLE
New Feature - Move row programatically

### ISSUE THREAD

**Issue by JamesBewley** [bosskmk/pluto_grid#149]
Hello,

I'm loving the package but have a problem I'm not sure how to solve.  I want to change the position of a row depending on the value of the first column.

At the moment I'm catching an PlutoGridOnChangedEvent and doing some collision detection so a user isn't able to set a value that already exists.  Next I need to be able to move the row to it's new position based on that value but the RowSstate.moveRows method is that only thing I can see that might do it.  But how do I use the offset parameter if I just need to move a row from position 3 to position 5 etc?

**Comment by JamesBewley** [comment]
This is the code I'm using and it works for my purposes.

It's using the stateManager.moveRows and screen offsets but would be nicer to have a specific function for moving rows.

Thanks again for developing this package, it's great 


```dart
void onChange(PlutoGridOnChangedEvent event) {

    if(event.columnIdx == 0) {

      // Check the addres doesn't already exist
      var addressList = stateManager.rows.map((row) => row.cells['address_field'].value as int).toList();
      var hasDuplicates = addressList.toSet().length != addressList.length;

      if(hasDuplicates) {
        // Error the address already exists change value back and notify
        stateManager.changeCellValue(
          event.row.cells['address_field'].key,
          event.oldValue,
          callOnChangedEvent: false);
      }
      else {
        var currentPosition = addressList.indexOf(event.value);
        var newPosition;

        if(event.value < event.oldValue) {
          if(currentPosition == 0) return;

          for(newPosition=0;newPosition<=currentPosition;newPosition++) {
            if(event.value < addressList[newPosition]) break;
          }
        }
        else {
          if(currentPosition == addressList.length-1) return;

          for(newPosition=addressList.length;newPosition>=currentPosition;newPosition--) {
            if(event.value > addressList[newPosition-1]) {
              newPosition--;
              break;
            }
          }
        }
        
        var offset = (stateManager.bodyTopOffset - stateManager.scroll.verticalOffset) + (stateManager.rowTotalHeight * newPosition);

        stateManager.moveRows([stateManager.rows[event.rowIdx]],offset,notify: true);
      }
    }
  }
```

**Comment by bosskmk** [comment]
I am updating version 1.2.0.
moveRows is changed to moveRowsByOffset,
moveRowsByIndex is added.

Passing the rows and index you want to move to moveRowsByIndex will be the function you want. Is that right?

**Comment by JamesBewley** [comment]
Yes moveRowsByIndex will do nicely thank you.
