### ISSUE TITLE
Change Between Read Only and Edit Mode

### ISSUE THREAD

**Issue by JamesBewley** [bosskmk/pluto_grid#150]
I have a table I'd like to present in read-only mode and give the user the option to switch to edit mode on the click of a button.  I'm not sure there is a way to do this currently without rebuilding the whole widget?

**Comment by exomaniac** [comment]
i am not sure if you just want to disable editing or not.
```dart
mode: PlutoGridMode.select,
```

is the way to set this

**Comment by bosskmk** [comment]
```dart
  void handleToggleEditing() {
    final isEditing = !columns.first.enableEditingMode;

    stateManager.resetCurrentState(notify: false);

    columns.forEach((element) {
      element.enableEditingMode = isEditing;
    });

    stateManager.notifyListeners();
  }
```

The example above toggles the editing state of all columns.

If you don't know the stateManager, please refer to the link below.
https://github.com/bosskmk/pluto_grid/wiki/pluto-state-manager-for-english
