### ISSUE TITLE
error KeyEventResult not found

### ISSUE THREAD

**Issue by juliopuebla** [bosskmk/pluto_grid#151]
Hi. 
When I run the example, I get the following error:

Launching lib/main.dart on Mi A1 in debug mode...
Running Gradle task 'assembleDebug'...
../lib/src/pluto_grid.dart:217:3: Error: Type 'KeyEventResult' not found.
  KeyEventResult handleGridFocusOnKey(FocusNode focusNode, RawKeyEvent event) {
  ^^^^^^^^^^^^^^
../lib/src/ui/columns/pluto_column_filter.dart:94:3: Error: Type 'KeyEventResult' not found.
  KeyEventResult handleOnKey(FocusNode node, RawKeyEvent event) {
  ^^^^^^^^^^^^^^
../lib/src/ui/cells/mixin_popup_cell.dart:108:3: Error: Type 'KeyEventResult' not found.
  KeyEventResult _handleKeyboardFocusOnKey(
  ^^^^^^^^^^^^^^
../lib/src/pluto_grid.dart:223:12: Error: The getter 'KeyEventResult' isn't defined for the class '_PlutoGridState'.
 - '_PlutoGridState' is from 'package:pluto_grid/src/pluto_grid.dart' ('../lib/src/pluto_grid.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'KeyEventResult'.
    return KeyEventResult.handled;
           ^^^^^^^^^^^^^^
../lib/src/ui/columns/pluto_column_filter.dart:124:12: Error: The getter 'KeyEventResult' isn't defined for the class '_PlutoColumnFilterStateWithChange'.
 - '_PlutoColumnFilterStateWithChange' is from 'package:pluto_grid/src/ui/columns/pluto_column_filter.dart' ('../lib/src/ui/columns/pluto_column_filter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'KeyEventResult'.
    return KeyEventResult.handled;
           ^^^^^^^^^^^^^^
../lib/src/ui/cells/mixin_popup_cell.dart:119:18: Error: The getter 'KeyEventResult' isn't defined for the class 'MixinPopupCell<T>'.
 - 'MixinPopupCell' is from 'package:pluto_grid/src/ui/cells/mixin_popup_cell.dart' ('../lib/src/ui/cells/mixin_popup_cell.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'KeyEventResult'.
          return KeyEventResult.handled;
                 ^^^^^^^^^^^^^^
../lib/src/ui/cells/mixin_popup_cell.dart:124:12: Error: The getter 'KeyEventResult' isn't defined for the class 'MixinPopupCell<T>'.
 - 'MixinPopupCell' is from 'package:pluto_grid/src/ui/cells/mixin_popup_cell.dart' ('../lib/src/ui/cells/mixin_popup_cell.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'KeyEventResult'.
    return KeyEventResult.ignored;
           ^^^^^^^^^^^^^^

**Comment by bosskmk** [comment]
https://github.com/bosskmk/pluto_grid/issues/145

Still having problems?

It looks like a flutter clean or version of flutter or a channel issue.
