### ISSUE TITLE
Renderer Trigger Re-render

### ISSUE THREAD

**Issue by JamesBewley** [bosskmk/pluto_grid#152]
I have a custom renderer that has a button to launch a dialog that changes the value of the cell.  Is there a way to get the cell to re-render once the cell value has been changed?

I'm searching around for something RenderContext at the moment.

**Comment by bosskmk** [comment]
The widget returned by the renderer should be statefulWidget, and the widget should handle rendering according to the state.

**Comment by JamesBewley** [comment]
I got around it by using StatefulBuilder
