### ISSUE TITLE
Row Color

### ISSUE THREAD

**Issue by BangPei** [bosskmk/pluto_grid#154]
Hi, Can we set different background-color for every row?

**Comment by bosskmk** [comment]
Currently, there is no function mentioned.
I'll implement it because it's a necessary function, but...
I'm working these days, so I don't have enough personal time.
Thank you for your understanding.

**Comment by BangPei** [comment]
Hi, thanks for your response.
So far the library so nice.

**Comment by christianarduino** [comment]
Any update?

**Comment by bosskmk** [comment]
Updated PlutoGrid 2.6.0
