### ISSUE TITLE
onSelected event does not fire

### ISSUE THREAD

**Issue by tilongzs** [bosskmk/pluto_grid#155]
```
onSelected: (PlutoGridOnSelectedEvent event){
            print(event);
          }
```

or

`_gridManager.setOnSelected(onGridSelect);`

pluto_grid: ^1.1.1
Run on windows-x64 platform.

> D:\FlutterStudy\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel dev, 2.1.0-10.0.pre, on Microsoft Windows [Version 10.0.19042.844], locale zh-CN)
    • Flutter version 2.1.0-10.0.pre at D:\FlutterStudy\flutter
    • Framework revision cc9b78fc5c (2 weeks ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\tilongzs\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.8.6)
    • Visual Studio at C:\Program Files\VS2019
    • Visual Studio Professional 2019 version 16.8.31019.35
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.844]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.81

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by tilongzs** [comment]
import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PlutoGrid Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final myData = MyGridData();
  PlutoGridStateManager _fileTableManager;

  void onFiletableSelect(PlutoGridOnSelectedEvent event) {
    print(event);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: const Text('PlutoGrid Demo'),
      ),
      body: Container(
        padding: const EdgeInsets.all(30),
        child: PlutoGrid(
          columns: myData.columns,
          rows: myData.rows,
          onLoaded: (PlutoGridOnLoadedEvent event) {
            _fileTableManager = event.stateManager;
            _fileTableManager.setOnSelected(onFiletableSelect);
          },
          onSelected: (PlutoGridOnSelectedEvent event){
            print(event);
          },
        ),
      ),
    );
  }
}

class MyGridData {
  List<PlutoColumn> columns;
  List<PlutoRow> rows;

  MyGridData() {
    columns = [
      PlutoColumn(
        title: 'Text',
        field: 'text_field',
        type: PlutoColumnType.text(),
        enableRowChecked: true,
      ),
      PlutoColumn(
        title: 'Number',
        field: 'number_field',
        type: PlutoColumnType.number(),
      ),
      PlutoColumn(
        title: 'Select',
        field: 'select_field',
        type: PlutoColumnType.select(['item1', 'item2', 'item3']),
      ),
      PlutoColumn(
        title: 'Date',
        field: 'date_field',
        type: PlutoColumnType.date(),
      ),
    ];

    rows = [
      PlutoRow(
        cells: {
          'text_field': PlutoCell(value: 'Text cell value1'),
          'number_field': PlutoCell(value: 2020),
          'select_field': PlutoCell(value: 'item1'),
          'date_field': PlutoCell(value: '2020-08-06'),
        },
      ),
      PlutoRow(
        cells: {
          'text_field': PlutoCell(value: 'Text cell value2'),
          'number_field': PlutoCell(value: 2021),
          'select_field': PlutoCell(value: 'item2'),
          'date_field': PlutoCell(value: '2020-08-07'),
        },
      ),
      PlutoRow(
        cells: {
          'text_field': PlutoCell(value: 'Text cell value3'),
          'number_field': PlutoCell(value: 2022),
          'select_field': PlutoCell(value: 'item3'),
          'date_field': PlutoCell(value: '2020-08-08'),
        },
      ),
    ];
  }
}

**Comment by bosskmk** [comment]
https://github.com/bosskmk/pluto_grid/blob/master/lib/src/pluto_grid.dart#L37

onSelected must pass the mode of PlutoGrid's constructor to select.

```dart
PlutoGrid(
  columns: columns,
  rows: rows,
  onSelected: (PlutoGridOnSelectedEvent event) {
    // 
  },
  mode: PlutoGridMode.select,
);
```

**Comment by hongsw** [comment]
I would like to suggest an enhancement for the PlutoGrid behavior on Windows platforms to better align with user habits. Specifically, the mode: `PlutoGridMode.selectWithOneTap` configuration is more intuitive for Windows users compared to the .select mode, which requires a double-click for selection.

Additionally, I have encountered issues with the `onRowDoubleTap` function when it's integrated directly within the PlutoGrid's constructor. This approach does not work effectively and often leads to functionality issues.

Furthermore, I recommend refraining from calling `setState()` within the grid's constructor. The current implementation triggers a re-render of the grid and automatically selects the first row, which can be disruptive for the user experience.

These adjustments could significantly enhance usability and align the grid's behavior with typical Windows user interactions.
