### ISSUE TITLE
Get a list of indexes from group seleciton.

### ISSUE THREAD

**Issue by asadamatic** [bosskmk/pluto_grid#160]
Hi there, 

Does pluto grid allow to get the list of indexes of all the elements selected?

 **I want to change the values in the list corresponding to the selected rows**

**Comment by bosskmk** [comment]
With PlutoGrid set as row mode.
```dart
child: PlutoGrid(
  columns: columns,
  rows: rows,
  onChanged: (PlutoGridOnChangedEvent event) {
    print(event);
  },
  onLoaded: (PlutoGridOnLoadedEvent event) {
    event.stateManager.setSelectingMode(PlutoGridSelectingMode.row);

    stateManager = event.stateManager;
  },
),
```

You can access the selected rows with `stateManager.currentSelectingRows`.


[Method to change cell value](https://github.com/bosskmk/pluto_grid/blob/master/lib/src/manager/state/editing_state.dart#L28)

[Row selection example](https://github.com/bosskmk/pluto_grid/blob/master/example/lib/screen/feature/row_selection_screen.dart)

**Comment by asadamatic** [comment]
With the above code and few additions, I was able to achieve what I needed. Thanks :)

```
void managePriceForSelectedRows() async {
    List<PlutoCell> cells = [];

    if (stateManager != null) {
      stateManager.currentSelectingRows.forEach((element) {

        cells.add(element.cells['price']);
      });

    }
  }
```

**Comment by kevinxxq** [comment]
> With PlutoGrid set as row mode.
> 
> ```dart
> child: PlutoGrid(
>   columns: columns,
>   rows: rows,
>   onChanged: (PlutoGridOnChangedEvent event) {
>     print(event);
>   },
>   onLoaded: (PlutoGridOnLoadedEvent event) {
>     event.stateManager.setSelectingMode(PlutoGridSelectingMode.row);
> 
>     stateManager = event.stateManager;
>   },
> ),
> ```
> 
> You can access the selected rows with `stateManager.currentSelectingRows`.
> 
> [Method to change cell value](https://github.com/bosskmk/pluto_grid/blob/master/lib/src/manager/state/editing_state.dart#L28)
> 
> [Row selection example](https://github.com/bosskmk/pluto_grid/blob/master/example/lib/screen/feature/row_selection_screen.dart)

Hi @bosskmk ,
I want to get the number of selected rows, it should be stateManager.currentSelectingRows.length.

How can I get it when the stateManager.currentSelectingRows changed? there should be a event(the checkbox on header row can change status accordingly) but I can't find it.

I have try your answer for another question:
stateManager?.addListener(() {
            if (stateManager != null &&
                stateManager?.currentSelectingRows != null) {
              _selectedItemQuantity.value =
                  stateManager!.currentSelectingRows.length;
            }
          });
But the quantity is not changed as expected.

Please help, thank you.
