### ISSUE TITLE
Best fit

### ISSUE THREAD

**Issue by diegoruidiaz** [bosskmk/pluto_grid#161]
Add functionality that allows all columns to fit the entire container, so there is no margin to the right.

**Comment by bosskmk** [comment]
Would each column be changed to the same width?

However, there is a minimum width for drawing the grid, but if the overall width is insufficient, scrolling may occur as an exception.

**Comment by amasahara** [comment]
I try this code but it work not fine. it fit by column that size biggest

**Comment by chrislaurie-bs** [comment]
What worked for me is to use the columns from the statemanager:
`
  onLoaded: (event){
   stateManager = event.stateManager;
   stateManager?.columns.forEach((col) => stateManager?.autoFitColumn(context, col));
 }
`

**Comment by prooshani** [comment]
None of the above working for mine.
The autofit on StateManger only works on PlutoColumnType.number()

It really needs a global setter to fit all columns on loading. It is very hard for tables with many columns to autofit every single column manually.

**Comment by bosskmk** [comment]
```dart
stateManager?.columns.forEach((col) => stateManager?.autoFitColumn(stateManager!.gridKey!.currentContext!, col));
```

If you do the above, it will work.
But I think some modifications are needed.
It is not considered when rendering custom cells with renderer, or when there is drag, checkbox, etc.

**Comment by prooshani** [comment]
Thanks, but I have switched to other Package for now.

Good luck everyone.

**Comment by SittiphanSittisak** [comment]
`stateManager?.columns.forEach((col) => stateManager?.autoFitColumn(stateManager!.gridKey!.currentContext!, col));`
Not work.
Can ...
1. Auto fit by widget width of the column?
2. Auto fit by widget width of the maximum ceil?
3. Fix the width of each column?


![image](https://user-images.githubusercontent.com/59549741/162368398-0bd1b568-6f02-4e75-a71d-96a6f3f598ce.png)
