### ISSUE TITLE
How to make plutoGrid fit the screen and avoid horizontal scroll?

### ISSUE THREAD

**Issue by asadamatic** [bosskmk/pluto_grid#163]
I have 9 columns to display in the grid, and that when rendered do not show all the columns at once, rather there's horizontal scroll.

How to avoid this and display all columns at once?

**Comment by bosskmk** [comment]
You can set the width when creating the PlutoColumn. However, the minimum value is 80.
Under these conditions, you can set the column width to fit the maximum width.


runtime 에서 변경 하려면 `stateManager.resizeColumn` 을 호출하여 변경 할 수 있습니다.
