### ISSUE TITLE
row check event

### ISSUE THREAD

**Issue by soheilqk** [bosskmk/pluto_grid#169]
Hi, how can I get notified when a row is checked or unChecked?
I could not find anything related

**Comment by bosskmk** [comment]
Basically, stateManager has the following methods and properties.

`stateManager.checkedRows` : Currently checked rows.

`stateManager.unCheckedRows` : Rows not currently checked.

`stateManager.hasCheckedRow` : Whether there are currently checked rows.

`stateManager.hasUnCheckedRow` : Whether there are currently unchecked rows.

You can check the change of `checkedRows` and `unCheckedRows` when an event occurs through `stateManager.addListener`.

But I will add a callback event later to make it easier to detect the event.
