### ISSUE TITLE
responsiveness on column width

### ISSUE THREAD

**Issue by soheilqk** [bosskmk/pluto_grid#170]
Hi, I set the columns width based on a LayoutBuilder constraints, but after resizing the window constraints changes but table does not updates columns width. how can I do this, its so important for my design

**Comment by bosskmk** [comment]
The width of each column is fixed to the initially set value. You can change it using stateManager's resizeColumn.

If the total width of the grid doesn't change, you'll need to look at your code to find out.

**Comment by soheilqk** [comment]
> The width of each column is fixed to the initially set value. You can change it using stateManager's resizeColumn.
> 
> If the total width of the grid doesn't change, you'll need to look at your code to find out.

I changed the source code with some Flexible widgets, passing the flex number when creating the column
column example
![image](https://user-images.githubusercontent.com/75607402/113995027-1e2b2a00-986b-11eb-816f-08f7cf64d228.png)
pluto_body_columns
![image](https://user-images.githubusercontent.com/75607402/113995605-a4477080-986b-11eb-9df2-75b0b661273e.png)
pluto_body_rows
![image](https://user-images.githubusercontent.com/75607402/113995746-c3de9900-986b-11eb-929c-72139a914495.png)
result:
[Screen Recording (4-8-2021 12-47-00 PM).zip](https://github.com/bosskmk/pluto_grid/files/6277325/Screen.Recording.4-8-2021.12-47-00.PM.zip)

if you was interested and had question I can explain more

**Comment by bosskmk** [comment]
`stateManager.notifyListeners();` Try calling it.
Then the grid state change is applied.

**Comment by soheilqk** [comment]
> `stateManager.notifyListeners();` Try calling it.
> Then the grid state change is applied.

because I have changed the source code a lot I think that not gonna work for me😅, but any way thanks for your great affords preparing this package, it saved us lots of time❤
