### ISSUE TITLE
Date format issue 

### ISSUE THREAD

**Issue by jeansebastienZ** [bosskmk/pluto_grid#173]
Date format is a problem  for filter .
If it's not yyyy-MM-dd , we can't use filter , is there any way to handle french format (dd-MM-yyyy) or any other format ?

**Comment by jeansebastienZ** [comment]
Find out a way.
You need to be sure that the initial format is  dd-MM-yyyy 
Caution this is not the way it should be handle , but as it's an urgent needed it will fit my case right now .

```
dynamic makeCompareValue(dynamic v) {

      DateTime dateTimes ;
      var splitted = v.toString().split('-');
      if(splitted.length >=2) {
        var day = splitted[0];
        var month = splitted[1];
        var year = splitted[2];
        var formatted = '$year-$month-$day';
        print("formatted" + formatted);
        dateTimes = DateTime.parse(formatted);
        print("dateTimes" + dateTimes.toString());
        print("dateTimes" + formatted.toString());
        return dateTimes;
      } 
      dateTimes = null;
      return dateTimes;
  }

String applyFormat(dynamic value) {
    return  value.toString();
  }
  bool isValid(dynamic value) { 
    return true;
  }
```

**Comment by bosskmk** [comment]
https://weblaze.dev/pluto_grid/build/web/#feature/date-type-column

Have you tried adding format when creating PlutoColumn?

Apply the compare function according to the format.

If your date format is dd-mm-yyyy, it will work normally if it is set as follows.

```
PlutoColumn(
  title: 'MM-dd-yyyy',
  field: 'mm-dd-yyyy',
  type: PlutoColumnType.date(
    format: 'MM-dd-yyyy',
  ),
),
```

**Comment by jeansebastienZ** [comment]
> https://weblaze.dev/pluto_grid/build/web/#feature/date-type-column
> 
> Have you tried adding format when creating PlutoColumn?
> 
> Apply the compare function according to the format.
> 
> If your date format is dd-mm-yyyy, it will work normally if it is set as follows.
> 
> ```
> PlutoColumn(
>   title: 'MM-dd-yyyy',
>   field: 'mm-dd-yyyy',
>   type: PlutoColumnType.date(
>     format: 'MM-dd-yyyy',
>   ),
> ),
> ```

I have to reopen the issue  as the problem is still there 

here full data example :


```
List<PlutoColumn> columns = [

  PlutoColumn(
    title: 'MM-dd-yyyy',
    field: 'mm-dd-yyyy',
    type: PlutoColumnType.date(
      format: 'MM-dd-yyyy',
    ),
  ),

];

List<PlutoRow> rows = [
  PlutoRow(
    cells: {
      'text_field': PlutoCell(value: 'Text cell value1'),
      'number_field': PlutoCell(value: 2020),
      'select_field': PlutoCell(value: 'item1'),
      'date_field': PlutoCell(value: '18-03-1991'),
      'time_field': PlutoCell(value: '12:30'),
    },
  ),

];
```

**Comment by bosskmk** [comment]
The value itself must be in the form yyyy-mm-dd.
format only affects the display.

pluto_grid uses the intl package. That's why there are rules like this.

Below is an example that can be handled by the parse method of the intl package.

```dart
  /// Examples of accepted strings:
  ///
  /// * `"2012-02-27"`
  /// * `"2012-02-27 13:27:00"`
  /// * `"2012-02-27 13:27:00.123456789z"`
  /// * `"2012-02-27 13:27:00,123456789z"`
  /// * `"20120227 13:27:00"`
  /// * `"20120227T132700"`
  /// * `"20120227"`
  /// * `"+20120227"`
  /// * `"2012-02-27T14Z"`
  /// * `"2012-02-27T14+00:00"`
  /// * `"-123450101 00:00:00 Z"`: in the year -12345.
  /// * `"2002-02-27T14:00:00-0500"`: Same as `"2002-02-27T19:00:00Z"`
```
