### ISSUE TITLE
Applying filter not re-loading Column init

### ISSUE THREAD

**Issue by jeansebastienZ** [bosskmk/pluto_grid#175]
Hello,

When i load all my plutoColumn it contains a certain logical that allow me to show cell color depending on cell value.
Filtering the column, seems to not maintain this logical , is there a callback from pluto_grid when someone apply filter wich allow me to know when i have to reload the logical  ? 

Concrete example : If my third row color is blue , i filter all values , the third column will still blue ( even if the value filtered not respecting the test i do at the init . 
1) So in my logical i should reload column render context once someone click the filtering option, is there any direct callback once data are filtered ?
2) Whats the process to update Column ? 
3) if i update Column like this, it will update column but lose the filter done at the same time :
```

stateManager.addListener(() {
                if (stateManager.hasFilter&&!alreadyUploaded)
                {
                  alreadyUploaded = true; 
                  UpdateColumns(); 
                  setState(() {

                  });
                }

              });
```
 4) More than the technical aspect , i want to understand how you update your column style renderer once someone clicked on filter . 
5) Same question when you filter by ascendant descendent .

All question are related but the aim is to help you understanding the need .
Thanks you

**Comment by bosskmk** [comment]
Have you tried calling `stateManager.notifyListeners()`?

**Comment by jeansebastienZ** [comment]
Hello @bosskmk  , yes it still not reloading it . 

You can check out with this video :
[](https://streamable.com/wkqiid)

**Comment by bosskmk** [comment]
The video helped me understand your problem.
I'll check this out when I have time.
Thank you.

**Comment by bosskmk** [comment]
@jeansebastienZ 
I tried to reproduce the error, but it didn't.

Could you please provide a minimal code to reproduce the same error?

**Comment by jeansebastienZ** [comment]
Right now my project is too complex to give a minimal code to reproduce , ( using VPN to connect to specific server to extract  delicate data and lot of sub classes to handle various collision ) In term of design patter thats a nightmare there  . I can however help you this way  .
Here the way i init the column  ( i deleted some call but the core logic is here ) .

```
void loadAllPlutoColumn() async { // init all column 
    columns.clear(); 
    for (int i = 0; i < OrdreReparation.columnKey.values.length; i++) {
     if (OrdreReparation.columnKey.values.elementAt(i).toString() ==
          "Specific column") {
        columns.add(PlutoColumn(
          width: 80,
          title: OrdreReparation.columnKey.values.elementAt(i).toString(),
          field: i.toString(),
          type: PlutoColumnType.text(),
          renderer: (rendererContext) {
            return Container(
                height: 200,
                color: ordreReparationCon.data[rendererContext.rowIdx].StatCde
                    .toString() .contains('x thing')
                    ? Colors.red
                    : ordreReparationCon.data[rendererContext.rowIdx].StatCde
                    .toString() .contains('y thing') 
                    : Colors.yellow,
                child: Text(
                  rendererContext.cell.value.toString(),
                  style: TextStyle(
                    color: ordreReparationCon
                        .data[rendererContext.rowIdx].StatCde
                        .toString()
                        .contains('Pas de commande')
                        ? Colors.white
                        : ordreReparationCon
                        .data[rendererContext.rowIdx].StatCde
                        .toString()
                        .contains('reçue')
                        ? Colors.red
                        : Colors.black,
                    fontSize: 11.0,
                  ),
                ));
          },
        ));
      }  
    if (mounted)   setState(() {});
  }

```
I think the core problem is there as the once click on the filter its not re loading reloading the logic there .
If it's not helping you please tell me , i'll take one full day to make a full example working minimal code .

**Comment by bosskmk** [comment]
`rendererContext.rowIdx` can be changed by `sort`, `filter`, etc.
It is recommended to control the color change using the `key` of the `row` or some other unique value of the `cells`.

**Comment by jeansebastienZ** [comment]
> `rendererContext.rowIdx` can be changed by `sort`, `filter`, etc.
> It is recommended to control the color change using the `key` of the `row` or some other unique value of the `cells`.

So what you suggest in my loop in my column init, in the redererContext i should use a  "if" , with a specific key of the cell ?
I can attribute a specific key for each cell , but I don't really understand how you would handle that , could you make a simple example please @bosskmk  on how i could handle it in the algorithm below or telling me if i did understand what you sugget ?
```
void loadAllPlutoColumn() async { // init all column 
 
    for (int i = 0; i < OrdreReparation.columnKey.values.length; i++) {
 columns.add(PlutoColumn(
          width: 80,
          title: OrdreReparation.columnKey.values.elementAt(i).toString(),
          field: i.toString(),
          type: PlutoColumnType.text(),
          renderer: (rendererContext) {
// ???? should i compare the rendererContext.cell.key value , that's what you suggest ?
}));
}
}
```

**Comment by bosskmk** [comment]
```dart
orderReparationCon.data.firstWhere((e) => e.id == rendererContext.row.cells['id'].value)
// or
orderReparationCon.data.firstWhere((e) => e.rowKey == rendererContext.row.key)
```
