### ISSUE TITLE
Pluto grid "onSelected" event

### ISSUE THREAD

**Issue by jagadeeshtmr** [bosskmk/pluto_grid#177]
We are trying to have "onSelected" working . Any specific contrguration or property be set on PlutoGrid to have that working.
Kindly let us know

**Comment by bosskmk** [comment]
The onSelected event only works when the grid is running in select mode.

You can pass the mode value when creating the PlutoGrid.

Editing is not possible in select mode and is used for list selection.

```dart
  /// [PlutoGridMode.normal]
  /// Normal grid with cell editing.
  ///
  /// [PlutoGridMode.select]
  /// Editing is not possible, and if you press enter or tap on the list,
  /// you can receive the selected row and cell from the onSelected callback.
  final PlutoGridMode? mode;


body: PlutoGrid(
  columns: columns,
  rows: rows,
  mode: PlutoGridMode.select,
  onSelected: (PlutoGridOnSelectedEvent event) {
    print(event);
  },
),
```

**Comment by maitlandmarshall** [comment]
onSelected seems to only work if I double click, rather when the selected row actually changes?

**Comment by bosskmk** [comment]
Yes, that's right. I don't think that having to move a specific row is not selecting a row. Because it sometimes moves rows to scroll. Therefore, the onSelected event is triggered only when the Enter key or the selected state is selected again (double click).

**Comment by maitlandmarshall** [comment]
fair enough! thanks for letting me know.

**Comment by jeffersonmello** [comment]
> Yes, that's right. I don't think that having to move a specific row is not selecting a row. Because it sometimes moves rows to scroll. Therefore, the onSelected event is triggered only when the Enter key or the selected state is selected again (double click).

Its possible change fot one click? i using in the web and desktop need this action.

**Comment by bosskmk** [comment]
Consider adding a property in PlutoGridMode.select to make the onSelected callback behave as a double-click or one-click.

**Comment by bosskmk** [comment]
I will modify the action of the onSelected callback in the PlutoGridMode.select state to operate as a single tap and reflect it in the next version.
Therefore, if the mode property in the PlutoGrid constructor is executed as PlutoGridMode.select , the onSelected callback works.

The event that triggers the callback is a single tap or pressing the Enter key on the current line.

**Comment by bosskmk** [comment]
```dart
child: PlutoGrid(
  columns: columns,
  rows: rows,
  mode: PlutoGridMode.selectWithOneTap,
  onChanged: (PlutoGridOnChangedEvent event) {
    print(event);
  },
  onLoaded: (PlutoGridOnLoadedEvent event) {
    stateManager = event.stateManager;
    stateManager!.setSelectingMode(gridSelectingMode!);
    stateManager!.setShowColumnFilter(true);
  },
  onSelected: (event) {
    print(event.cell!.value);
  },
```

The final fix was to add PlutoGridMode.selectWithOneTap .
It is necessary to tap once more after selecting in the existing time type column.
https://weblaze.dev/pluto_grid/build/web/#feature/time-type-column

The user has to select the left value and select the right value by changing the scroll in the grid divided into left and right.
In this case, there is a problem with the operation as the selection is completed in one tap.

If you set PlutoGridMode to selectWithOneTap , the onSelected callback is triggered with a single tap.
