### ISSUE TITLE
How can I give particular color to single row or particular row text color ? , Any idea ?

### ISSUE THREAD

**Issue by PriyankManiya** [bosskmk/pluto_grid#178]

**Comment by jeansebastienZ** [comment]
The way you can handle is by using renderer: like this for example:

```
PlutoColumn(enableFilterMenuItem :false,
        width: 80,
        title: "Afficher",
        field: 'Voirlafiche',
        type: PlutoColumnType.text(),
        renderer: (rendererContext) {
})
```


The problem with this , as explain in another topic wich is waiting for @bosskmk  update , is that when filtering is used , any logic here will be broken . For example if you say 

yourRowData.data[rendererContext.rowIdx].color =="red" -> Then you color your row in red 

if you use the filtering option , it will not keep the logic . However without caring about filtering everything works perfectly like this .

**Comment by PriyankManiya** [comment]
> The way you can handle is by using renderer: like this for example:
> 
> ```
> PlutoColumn(enableFilterMenuItem :false,
>         width: 80,
>         title: "Afficher",
>         field: 'Voirlafiche',
>         type: PlutoColumnType.text(),
>         renderer: (rendererContext) {
> })
> ```
> 
> The problem with this , as explain in another topic wich is waiting for @bosskmk update , is that when filtering is used , any logic here will be broken . For example if you say
> 
> `yourRowData.data[rendererContext.rowIdx].color =="red" -> Then you color your row in red `
> 
> if you use the filtering option , it will not keep the logic . However without caring about filtering everything works perfectly like this .

Thank you so much for replying me, And thank you for your time :)
