### ISSUE TITLE
pre selected row

### ISSUE THREAD

**Issue by soheilqk** [bosskmk/pluto_grid#182]
how can I pre select a row in table?
I mean when the table is loaded in the first time

**Comment by bosskmk** [comment]
### Call these functions in the onLoaded callback function when creating the grid.
```dart
// This selects rows 0 to 10.
stateManager!.setCurrentSelectingRowsByRange(0, 10);

// This selects or deselects row 11.
stateManager!.toggleSelectingRow(11);
```

**Comment by soheilqk** [comment]
> ### Call these functions in the onLoaded callback function when creating the grid.
> ```dart
> // This selects rows 0 to 10.
> stateManager!.setCurrentSelectingRowsByRange(0, 10);
> 
> // This selects or deselects row 11.
> stateManager!.toggleSelectingRow(11);
> 
> // Select all rows.
> stateManager!.setAllCurrentSelecting();
> 
> // Un-select all rows.
> stateManager!.clearCurrentSelectingRows();
> ```

thanks man❤
