### ISSUE TITLE
 FocusableActionDetector | not able to use

### ISSUE THREAD

**Issue by NiranjanShah** [bosskmk/pluto_grid#192]
With Plutgrid FocusableActionDetector is not working.

Simulation :

Have a Plutogrid and enable the FocusableActionDetector , define any key to test it.

With Plutogrid-> visible, actions of the FocusAbleDetector will **NOT FIRE.**

Now : make PlutoGrid-> vislble = false, FocusAbleDetector will **FIRE**

**Key Board access is required for Desktop / Web Application and hence must be supported by PlutoGrid**

PS: I have used Meta A , Alt A which are not trapped by PlutoKeyManager, still it is not working.....

**Comment by NiranjanShah** [comment]
Can you please provide your input/solution for the above

**Comment by bosskmk** [comment]
https://weblaze.dev/pluto_grid/build/web/#feature/listing-mode

If you look at the example in the link above, there is something that triggers the Control + C keys that are not implemented in PlutoGrid.

If you check the source code, you can add the desired key action.

```dart
  void handleKeyboard(PlutoKeyManagerEvent event) {
    // Specify the desired shortcut key.
    if (event.isKeyDownEvent && event.isCtrlC) {
      openNewRecord();
    }
  }
...
...
      body: PlutoGrid(
        columns: columns,
        rows: rows,
        onChanged: print,
        onLoaded: (PlutoGridOnLoadedEvent event) {
          stateManager = event.stateManager;

          removeKeyboardListener =
              stateManager!.keyManager!.subject.stream.listen(handleKeyboard);

          stateManager!.setSelectingMode(PlutoGridSelectingMode.none);
        },
        onSelected: (PlutoGridOnSelectedEvent event) {
          if (event.row != null) {
            openDetail(event.row);
          }
        },
        mode: PlutoGridMode.select,
      ),
```

**Comment by NiranjanShah** [comment]
in this case, will have to manage the keyboard listener @ all the places where we use PlutoGrid.

There are standard widgets which are created @ single place and use across the application, these will require changes in the whole app.

The response is not scalable when we think of large application.

Suggestion :

in case, if there are keys which have not been handled by Pluto Grid, must be propagated to other listener.

so let us say Pluto grid uses F2,A-Z, 0-9 + few other keys, if user has pressed key apart from those, Pluto Grid must return “false” to keyboard listener.

I am very sure, this requirement will come from many people, once Pluto Grid is used extensively.

**Comment by NiranjanShah** [comment]
Any thoughts on this ?
