### ISSUE TITLE
Getting error on github actions

### ISSUE THREAD

**Issue by asadamatic** [bosskmk/pluto_grid#193]
Hi there, I'm getting the following error in github actions, while the app compiles well locally.

```
Compiling lib/main.dart for the Web...                          
Target dart2js failed: Exception: /opt/hostedtoolcache/flutter/2.2.0-stable/x64/.pub-cache/hosted/pub.dartlang.org/pluto_inside-0.2.0/lib/src/widgets/pluto_scrollbar.dart:460:36:
Error: Too few positional arguments: 2 required, 1 given.
  return painter.hitTestInteractive(localOffset);
```

**Comment by bosskmk** [comment]
That issue occurs in 2.1.x or later.
The link below is the modified file.
This error does not occur in PlutoGrid 2.1.0, flutter 2.2.0.

https://github.com/bosskmk/pluto_grid/blob/master/lib/src/widgets/pluto_scrollbar.dart

**Comment by asadamatic** [comment]
I worked, thanks :)

Updated Pluto Grid to 2.1.0 and flutter to 2.2.0
