### ISSUE TITLE
event of changing current row

### ISSUE THREAD

**Issue by bosskmk** [bosskmk/pluto_grid#195]
in one of the discussion u had replied about the currently selected row
"If you run mode as select, you can handle the event when the currently selected row is tapped or the enter key is pressed with the onSelected callback."

The onSelectedCallBack is happening only on **Enter KEY** & **Mouse Double Click** in Desktop/Web App.

However what happens when the user selects the row by **Mouse Single Click** or **Changes the row thru up/down arrow**.

is there any event like "RowFocusChanged" which fires on change of row.

PS: this is for Web/Desktop application.

_Originally posted by @NiranjanShah in https://github.com/bosskmk/pluto_grid/discussions/188_

**Comment by NiranjanShah** [comment]
When scrolling thru arrow keys, it must show the current row# or row idx. (as of now this is possible only thru enter key or mouse click).



ie. let us say, we are at row # 2, and press arrow down, it must fire rowfocuschanged (or something), providing the row#.

basically this will we useful in the scenario where in based on the row# change, other details/popup/overlay can be displayed for that row.

as of now, the same is happening thru Enter key or Mouse Single click, which does not help in the above scenario as , we need to show details when user is scrolling thru arrow keys/pagedown.


Net Net, we must always have currently selected row.

hope it is clear, feel free to ask, in other case.

**Comment by NiranjanShah** [comment]
can the above be also included along with the double tap event which is been merged now ?
