### ISSUE TITLE
a new column data type as PlutoColumnType.bool?

### ISSUE THREAD

**Issue by kevinxxq** [bosskmk/pluto_grid#198]
Hi @bosskmk and team,
Thank you for the package.

Do you think it is necessary and possible to handle a datatype as PlutoColumnType.bool?
A rough idea is as below(copy from PlutoColumnType.Number):

  factory PlutoColumnType.bool({
    bool readOnly = false,
    bool defaultValue = false,
    bool showAsCheckBox = false,   //SwitchButton?
    String format = 'T,F',                   //True,False/Yes,No or some other string localization by system
    
  }) {
    return PlutoColumnTypeBool(
... ...
    );
  }

Or a simple enableColChecked for PlutoColumn.

Then the column can receive onTap to change status between true and false like enableRowChecked.
I have checked that it is possible to get such a column by text-formatting-renderer. It will be much more convenient to have a specific bool type.

Thank you.

**Comment by henry2man** [comment]
@bosskmk Related to https://github.com/bosskmk/pluto_grid/issues/243 (maybe a duplicate!?)

**Comment by bosskmk** [comment]
@henry2man Yes. Thanks.
