### ISSUE TITLE
Drag effects

### ISSUE THREAD

**Issue by kevinxxq** [bosskmk/pluto_grid#208]
Hi All,
Would you please check whether there is an option to drag the whole row not a cell?

I took a video from Reorderable ListView(https://api.flutter.dev/flutter/material/ReorderableListView-class.html):

https://youtu.be/SoTWSkYPAeM

Thank you.

**Comment by bosskmk** [comment]
Is this the function you want?
https://weblaze.dev/pluto_grid/build/web/#feature/row-moving

**Comment by kevinxxq** [comment]
Yes, it is. but my expectation is moving the whole row or column not a cell. Now it is a cell moving during dragging.
