### ISSUE TITLE
PlutoGrid as a children

### ISSUE THREAD

**Issue by ghost** [bosskmk/pluto_grid#217]
What Widgets can wrap around PlutoGrid and be in a list of children?

**Comment by bosskmk** [comment]
https://github.com/bosskmk/pluto_grid/tree/master/example/lib/screen/feature
https://github.com/bosskmk/pluto_grid/blob/master/example/lib/screen/development_screen.dart

It can be a child of a widget that is related to the layout.
Container, Expanded, ...
