### ISSUE TITLE
PlutoGridPopup don't have onRowChecked event

### ISSUE THREAD

**Issue by amasahara** [bosskmk/pluto_grid#218]
I try make an grid popup with checkbox but seem onRowChecked event is missing. Which way i can do with checkbox in PlutoGridPopup

**Comment by bosskmk** [comment]
PlutoGridPopup is similar to DropDownList .
You cannot get a list of checked boxes in PlutoGridPopup .

**Comment by amasahara** [comment]
PlutoDualGrid is same with it. So i need group row with some key. how can i do it
