### ISSUE TITLE
ScrollDelegate, Lazy Loading

### ISSUE THREAD

**Issue by radvansky-tomas** [bosskmk/pluto_grid#231]
What about exposing scroll delegate ? How to get event of reaching end ?

**Comment by bosskmk** [comment]
You can get an instance of PlutoStateManager in the onLoaded callback when creating the grid.
stateManager.scroll has vertical and horizontal properties.
These two properties are https://pub.dev/packages/linked_scroll_controller .

https://github.com/google/flutter.widgets/blob/master/packages/linked_scroll_controller/lib/linked_scroll_controller.dart

If you look at this file, you will find addOffsetChangedListener , removeOffsetChangedListener .

By registering a callback in the event registration function above, you can see that the scroll changes.

**Comment by selvam920** [comment]
_scrollController = new ScrollController();
    _scrollController.addListener(() {
      if (_scrollController.position.maxScrollExtent ==
          _scrollController.position.pixels) {
        var count = totalItems.length;
        var totalPages = (count / AppConstants.pageSize).ceil();
        hasPreviousPage = currentPage > 1;
        hasNextPage = currentPage < totalPages;
        if (hasNextPage) {
          currentPage += 1;
          items.addAll(totalItems
              .skip(currentPage * AppConstants.pageSize)
              .take(AppConstants.pageSize)
              .toList());
          setState(() {});
        }
      }
    });

**Comment by selvam920** [comment]
can we do like above?
i need to load the data from api when scroll position reached end

**Comment by bosskmk** [comment]
https://weblaze.dev/pluto_grid/build/web/#feature/dual-mode

If you look at the example link above, there is a code that receives an event when the grid reaches the left or right edge and performs a specific action. (Moves to the source code when the Source button is clicked)

By referring to that code, you can perform a specific action when you reach the top or bottom.

**Comment by bosskmk** [comment]
Is it possible to handle it in the eventListener of scrollController ? is not it?

**Comment by selvam920** [comment]
yes, possible to handle it in the event listener and also we need to get the position

**Comment by bosskmk** [comment]
yes try that And let me know if you have any problems.

**Comment by selvam920** [comment]
stateManager!.addListener(() {
            
          });

inside that we could not get scrollcontroller

**Comment by bosskmk** [comment]
```dart
stateManager.scroll 
```
Access scrollController with scroll properties.

**Comment by selvam920** [comment]
stateManager!.addListener(() {
            print(stateManager!.scroll!.verticalOffset);
          });

the above log is not printed when scroll by mouse but when change the row by keyboard it's printed

**Comment by christianarduino** [comment]
This could be a way to make a network request when the end of the scroll is reached

```dart
tableManager.scroll!.bodyRowsVertical!.addListener(() {
  if (tableManager.scroll!.maxScrollVertical ==
      tableManager.scroll!.verticalOffset) {
    // Make your api request with your conditions
  }
});
```

In the api request function when you'll get the response:
```dart
tableManager.setShowLoading(true);
final response = await _repository.getSomething();
final List<PlutoRow> rows = response.map((item) => item.toRow);
tableManager.appendRows(rows);
tableManager.setShowLoading(false);
```

**Comment by selvam920** [comment]
great.. i will try this

**Comment by selvam920** [comment]
@christianarduino i tried, listener is working with mouse only when we use by keyboard the listener is not working

**Comment by christianarduino** [comment]
When you say "when we use by keyboard" you mean when you scroll using the keyboard arrows on pc?

**Comment by selvam920** [comment]
Yes
