### ISSUE TITLE
Setting columns : unselecting all leaves no way to undo

### ISSUE THREAD

**Issue by alevinetx** [bosskmk/pluto_grid#232]
I was looking at the demo for column freezing

https://weblaze.dev/pluto_grid/build/web/#feature/column-freezing

And noticed that if you use the `Set columns` option and deselect all columns, everything is gone and no way to undo or reselect.

![image](https://user-images.githubusercontent.com/5067356/123567827-a5ac7900-d788-11eb-8827-c38eb8c255e9.png)
![image](https://user-images.githubusercontent.com/5067356/123567846-b230d180-d788-11eb-8c8a-cede16a460e8.png)

**Comment by bosskmk** [comment]
You can re-open the popup by adding a separate button as in this example.

https://weblaze.dev/pluto_grid/build/web/#feature/column-hiding
