### ISSUE TITLE
2 Pluto Grid in Single View

### ISSUE THREAD

**Issue by NiranjanShah** [bosskmk/pluto_grid#233]
is it possible to use, 2 Pluto grid in single view ?

if yes, please let us know how ?

Currently we have divided the screen into 2, in these we are showing Grids, have defined separate columns & rows for both the grid, however, this is not working. Even the statemanager are set different.

ideally, there must be provision to attach Columns & Rows to the statemanager, this way we can achieve multiple Pluto Grid in single page.

PS: in case, we don't want to use DualGrid. the reason being in between 2 Grids we have some other widget to show.

**Comment by bosskmk** [comment]
You can implement the desired function by referring to the DualGrid code.

https://github.com/bosskmk/pluto_grid/blob/master/example/lib/screen/feature/dual_mode_screen.dart

**Comment by NiranjanShah** [comment]
Nope, I cannot insert any view between 2 Grids, the best solution is to allocate columns and rows to individual grids.

PlutoDualGrid won’t be useful and practically major apps will require separate Grid views and must not be bounded to Single state manager.
