### ISSUE TITLE
Error in show menu

### ISSUE THREAD

**Issue by jomiplaz** [bosskmk/pluto_grid#242]
If cellTextStyle doesn't contains color, the menu in column is not show, due to the "!" in the code. If it is changed to "?" works.

https://github.com/bosskmk/pluto_grid/blob/c0c2fb0e1e91582ee0e7f675e404953078253435/lib/src/helper/show_column_menu.dart#L29

**Comment by bosskmk** [comment]
When does configuration.cellTextStyle.color have no value?
cellTextStyle must be the default or set.
Can you give me the code where the error occurs?
