### ISSUE TITLE
Make PlutoColumnType extendable to allow for custom column types

### ISSUE THREAD

**Issue by cthurston** [bosskmk/pluto_grid#243]
My immediate inclination was to create my own custom column types, for example uuid, bool, or multi-select. However, the way that the column type is implemented doesn't seem to be extendable.

**Comment by afesohromeo** [comment]
I agree with @cthurston. I will like to customize my column to any widget, like an image. Not just "Text, number, date ......".

**Comment by bosskmk** [comment]
@afesohromeo 
I also agree that it is necessary to add other types to PlutoGrid other than text, number, date, etc.

For widgets such as images, you can add a text type column to set the value as an image address and have the renderer output an image instead of text.

I would appreciate it if you could tell me a little more about the situation in which an additional part is needed in the above situation.

**Comment by henry2man** [comment]
Another example is `select` columns. If you have an usual pair of key + corresponding labels, it could be great to have something more versatile for this scenarios, like:

```dart
  /// Provides a selection list and sets it as a selection column.
  factory PlutoColumnType.select(
    Map<dynamic, String>? items, {  // 👈🏻 Change List<dynamic> to this Map to allow to use any type
    dynamic defaultValue = '',
    bool enableColumnFilter = false,
  }) {
  ...
```

**Comment by bdemeure** [comment]
My actual need is to have an autocomplete column (value loaded from remote serveur)

The PlutoColumnTypeSelect has a "static list" and is not very usefull for editing "fast" in the grid

I think i will create a custom column type, with a specific renderer ( rendering a text if not editing, and an autocomplete if cell is currently in edit mode )
But i don't known if i can trigger the onChanged of the grid...

**Comment by henry2man** [comment]
Do we have any plans for support this?

**Comment by niltonvasques** [comment]
Any update on this?

**Comment by junesale** [comment]
> @afesohromeo I also agree that it is necessary to add other types to PlutoGrid other than text, number, date, etc.
> 
> For widgets such as images, you can add a text type column to set the value as an image address and have the renderer output an image instead of text.
> 
> I would appreciate it if you could tell me a little more about the situation in which an additional part is needed in the above situation.

how to do it? I cannot find any documentation to render image in cell

**Comment by design2023** [comment]
> > @afesohromeo I also agree that it is necessary to add other types to PlutoGrid other than text, number, date, etc.
> > For widgets such as images, you can add a text type column to set the value as an image address and have the renderer output an image instead of text.
> > I would appreciate it if you could tell me a little more about the situation in which an additional part is needed in the above situation.
> 
> how to do it? I cannot find any documentation to render image in cell

 Add this code :
 renderer: (rendererContext) {
          final String imageURL = rendererContext.cell.value as String;
          return Image.network(imageURL);
        },

**Comment by PY-Account** [comment]
what about this?
is there  an option to show key+description?

**Comment by PY-Account** [comment]
> Another example is `select` columns. If you have an usual pair of key + corresponding labels, it could be great to have something more versatile for this scenarios, like:
> 
> ```dart
>   /// Provides a selection list and sets it as a selection column.
>   factory PlutoColumnType.select(
>     Map<dynamic, String>? items, {  // 👈🏻 Change List<dynamic> to this Map to allow to use any type
>     dynamic defaultValue = '',
>     bool enableColumnFilter = false,
>   }) {
>   ...
> ```

did you found some solution for this?

**Comment by SnowyTusk** [comment]
Here's a sketch.

```dart
class PlutoColumnDynamic implements PlutoColumnType {
  @override
  int compare(a, b) => 0;

  @override
  bool isValid(value) => true;

  @override
  makeCompareValue(v) {}

  @override
  dynamic defaultValue;
}
```
```dart
  PlutoColumn test() => PlutoColumn(
        title: 'test',
        field: 'test',
        renderer: (rendererContext) => rendererContext.cell.value as Widget,
        type: PlutoColumnDynamic(),
      );
```
```dart
PlutoRow(
   cells: {
    'test': PlutoCell(value: Text('test2')),
   },
),
```

![image](https://github.com/bosskmk/pluto_grid/assets/6566940/53bdf726-7701-4282-9e40-07fe3146c061)

Unfortunately, there remains the problem of automatic height adjustment for PlutoRow, but I will try to solve this in another question (when it works, I will attach a link).
