### ISSUE TITLE
How to make date colum with multiple  format

### ISSUE THREAD

**Issue by amasahara** [bosskmk/pluto_grid#245]
I try make an pluto column type date with format 'yyyy' and 'dd/MM/yyyy' but don't know how to do it. because my data has date like 1965 and 01/10/1965. I don't know which way to format for both of them

**Comment by bosskmk** [comment]
The format set to column follows the intl package.
https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html


As the value of cell, follow the argument of DateTime.parse method of dart.
https://api.dart.dev/stable/1.24.2/dart-core/DateTime/parse.html


The rules of format for column and value of cell follow the restrictions of the above document.

**Comment by amasahara** [comment]
oh that is so hard but i will try by another way
