### ISSUE TITLE
how to make dropdown filter when column is select and set delay when typing on textfilter

### ISSUE THREAD

**Issue by amasahara** [bosskmk/pluto_grid#247]
+ when column type is select. I want it will show data that contains in this column for filter like dropdown text filter
+ when typing filter with large data it very slow and hard for typing many character so which way i can delay maybe 1 or 2 second

**Comment by bosskmk** [comment]
In version 2.4.0, debounce was added when entering text in the filter.

You can pass columnFilterConfig to configuration when creating grid.
https://github.com/bosskmk/pluto_grid/blob/master/lib/src/pluto_grid_configuration.dart#L68

You can also set the debounceMilliseconds value in columnFilterConfig . The default is 300ms.
https://github.com/bosskmk/pluto_grid/blob/master/lib/src/pluto_grid_configuration.dart#L639

**Comment by amasahara** [comment]
thank you for your hard working
