### ISSUE TITLE
web no horizontal scroll

### ISSUE THREAD

**Issue by nzlov** [bosskmk/pluto_grid#249]
## Info
Can't drag
No horizontal scrolling

## Flutter
```
Flutter 2.5.0-1.0.pre • channel dev • https://github.com/flutter/flutter
Framework • revision 184e5871be (4 天前) • 2021-07-26 04:38:02 -0400
Engine • revision a877f6fed6
Tools • Dart 2.14.0 (build 2.14.0-350.0.dev)
```
## Web 
```
Google Chrome 92.0.4515.107 
```

[Example](https://github.com/bosskmk/pluto_grid/blob/master/example/lib/screen/feature/row_selection_screen.dart)

**Comment by bosskmk** [comment]
It is being developed in the flutter stable channel. This is an issue that may disappear when the corresponding version of the dev channel comes to stable.
If the problem persists in stable, we will fix it.

I wonder why you should develop on the dev channel.

**Comment by nzlov** [comment]
Sorry, my problem with layout.

**Comment by nzlov** [comment]
Passed the test on macos, failed on linux.

**Comment by nzlov** [comment]
My problem, it works under stable.
