### ISSUE TITLE
Upgrade rxdart dependency to latest version to resolve version conflicts

### ISSUE THREAD

**Issue by oysterpack** [bosskmk/pluto_grid#252]
I am running into version rxdart version conflicts because of other packages. Please upgrade to latest and greatest rxdart version to resolve the issue.

**Comment by bosskmk** [comment]
What version of PlutoGrid are you using?
Currently PlutoGrid is 2.3.0 and rxdart 0.27.0.
The next version, PlutoGrid 2.4.0, specifies rxdart 0.27.1 (the latest version).
