### ISSUE TITLE
shadow color

### ISSUE THREAD

**Issue by stoneLee81** [bosskmk/pluto_grid#255]
I set parameter gridBorderColor: Color(0xffF1F7FF), borderColor: Color(0xffF1F7FF)  in PlutoGridConfiguration, and get below capture image
![image](https://user-images.githubusercontent.com/18001708/127872581-d7ee061c-3cdf-421e-83b4-780286f7e166.png)

the shadow caused by this code, 
`return Container(
      width: axis == Axis.vertical ? 1 : 0,
      height: axis == Axis.horizontal ? 1 : 0,
      decoration: BoxDecoration(
        color: color ?? Colors.black,
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.15),
            spreadRadius: 1,
            blurRadius: 3,
            offset: reverse == true
                ? const Offset(-3, -3)
                : const Offset(3, 3), // changes position of shadow
          ),
        ],
      ),
    );`
Could you define a parameter to let me decide show this grey shadow or not? because The color scheme is not very beautiful。
Another question is, can I define selected row's color?

**Comment by bosskmk** [comment]
I will add an option to choose shadow exposure in the next version.

**Comment by bosskmk** [comment]
Updated to PlutoGrid version 2.5.0.

https://pub.dev/packages/pluto_grid/changelog
