### ISSUE TITLE
The onSelected event seems to be invalid

### ISSUE THREAD

**Issue by stoneLee81** [bosskmk/pluto_grid#256]
I did a test, the purpose is, click on a table row to open another new interface。 I added onSelected event, and click one row, but it seems invalid, no trigger onSelected event.

**Comment by bosskmk** [comment]
The onSelected callback is called when mode is set to PlutoGridMode.select when creating a PlutoGrid.

```dart
      body: PlutoGrid(
        columns: columns,
        rows: rows,
        onChanged: print,
        onLoaded: (PlutoGridOnLoadedEvent event) {
          stateManager = event.stateManager;

          removeKeyboardListener =
              stateManager!.keyManager!.subject.stream.listen(handleKeyboard);

          stateManager!.setSelectingMode(PlutoGridSelectingMode.none);
        },
        onSelected: (PlutoGridOnSelectedEvent event) {
          // do something
        },
        mode: PlutoGridMode.select, // Required for onSelected callback to work.
      ),
```

**Comment by stoneLee81** [comment]
this code should came from demo listing mode, I tested like below
`body: PlutoGrid(
        columns: columns,
        rows: rows,
        onChanged: print,
        onLoaded: (PlutoGridOnLoadedEvent event) {
          stateManager = event.stateManager;

          removeKeyboardListener =
              stateManager!.keyManager!.subject.stream.listen(handleKeyboard);

          stateManager!.setSelectingMode(PlutoGridSelectingMode.none);
        },
        onRowChecked: (PlutoGridOnRowCheckedEvent event) {
          print('hello');
        },
        onRowSecondaryTap: (PlutoGridOnRowSecondaryTapEvent event) {
          print('hello');
        },
        onRowDoubleTap: (PlutoGridOnRowDoubleTapEvent event) {
          print('hello');
        },
        onSelected: (PlutoGridOnSelectedEvent event) {
          if (event.row != null) {
            openDetail(event.row);
          }
        },
        mode: PlutoGridMode.select,`
When I clicked the row, onSelected event didn't trigger.

**Comment by stoneLee81** [comment]
@bosskmk

**Comment by bosskmk** [comment]
The callback is called when the selected row is tapped, and the unselected tab is tapped twice.

**Comment by stoneLee81** [comment]
When I click on the row, the selected row color changed, but the selected event is not triggered. I need to click that selected column again to trigger the onSelected event.

**Comment by stoneLee81** [comment]
@bosskmk

**Comment by bosskmk** [comment]
@stoneLee81 
Yes, that's right. The onSelected callback is called when the selected row is tapped.

**Comment by stoneLee81** [comment]
> @stoneLee81
> Yes, that's right. The onSelected callback is called when the selected row is tapped.

I have to click the row twice to trigger onSelected row event, the first trigger setCurrentCell, the second will trigger handleOnSelected

**Comment by MaximilianTyrtania** [comment]
The current behavior is counter intuitive. I'd like to enable certain controls depending on which row is selected and can hardly expect the user to double click a row for that purpose. Some event that triggers when the user selects or deselects a row would come in really handy.

**Comment by chrislaurie-bs** [comment]
Fully agree.  One wants a selected event that fires when the user clicks and a selects row, not when he clicks the row again. That can interfere with onDoubleTab - which incidentally fires correctly but does not select the row on the screen, the previous selected row remains showing.

**Comment by Taron133** [comment]
onSelect, onRowDoubleTap does not work with PlutoGridMode.normal

I wand to load second Grid after select row/cell in first Grid. But I need to edit rows in first Grid.
```

PlutoGrid(
  columns: columns,
  rows: rows,
  mode: PlutoGridMode.normal, //not selectWithOneTap
  onSelected: (PlutoGridOnSelectedEvent event) {
    print('onSelected');
  },
  onRowDoubleTap: (PlutoGridOnRowDoubleTapEvent event) {
    print('onRowDoubleTap');
  },
)
```

**Comment by bosskmk** [comment]
Added `PlutoGridMode.selectWithOneTap` property in `PlutoGrid` version 2.6 and later.
Call the `onSelected callback with one tap.

**Comment by Taron133** [comment]
Need `mode: PlutoGridMode.normal` with `onSelected`.
Why is it so hard to do?
`onRowDoubleTap` work with `PlutoGridMode.normal`, but the editing mode is turned on only with 2  OneTaps.
May be need call parent method onRowDoubleTap?? :
`super.onRowDoubleTap(event);`

**Comment by bosskmk** [comment]
@Taron133 
I will consider your opinion.

**Comment by beriaanirudh** [comment]
If anyone is stuck wanting both "onSelected" + "updating a cell", I have done this dirty hack. Dirty because double-click of cell does not work, one needs to click the row / cell, and then click the cell after a ~100ms gap.

Basically, there seems a stream which is listening to all events, subscribe

```
 mode: normal,
.
.
.
                  onLoaded: (PlutoGridOnLoadedEvent event) {
                    stateManager!.streamNotifier.stream.listen((PlutoNotifierEvent event) {
                      if (stateManager!.currentCell != null && stateManager!.currentRow != null) {
                           // maintain some previous row info, and compare if row has changed for less computation 
                           // do your onSelected logic here
                      }
                    });

```

If anyone has found a better / more efficient solution, please do post.
