### ISSUE TITLE
Hover event, change the color of the row

### ISSUE THREAD

**Issue by stoneLee81** [bosskmk/pluto_grid#259]
onHover changes the color of the line, It is common on the desktop, but it seems to be not found in the demo. I want to confirm whether it supports?

**Comment by stoneLee81** [comment]
Is there plan to enhance this issue for desktop? @bosskmk

**Comment by bosskmk** [comment]
I'll consider adding a feature.

**Comment by Crudude** [comment]
Would also love this feature.

If you use the keyboard arrows and move down, it highlights the individual rows in blue. Is there a way to do the exact same if I hover over a row (To show this is the row that will be selected).
