### ISSUE TITLE
Update Sort Icon

### ISSUE THREAD

**Issue by ghost** [bosskmk/pluto_grid#261]
I am using addListener to the Grid to call for a new sort order since I only show a part of the records.  How do you updated the icon in the header to reflect the correct sort order? How would you preset a column sort order icon when data is loaded?

  void gridAHandler() {
    if (stateManager.getSortedColumn != null) {
      widget.headerOnTap(stateManager.getSortedColumn.field);
    }
  }

**Comment by bosskmk** [comment]
There is an error where the icon does not update even when stateManager.sortAscending or sortDescending is called.

For now, you can sort when the grid is loaded by executing it in the onLoaded callback as shown below.

```dart
onLoaded: (PlutoGridOnLoadedEvent event) {
  stateManager = event.stateManager;
  
  columns![0].sort = PlutoColumnSort.descending;
  stateManager!.sortDescending(columns![0]);
},
```
I will fix it in the next version.

thank you.

**Comment by bosskmk** [comment]
https://github.com/bosskmk/pluto_grid/releases/tag/2.8.0

PlutoGrid version 2.8.0 has been deployed.
