### ISSUE TITLE
column freezing

### ISSUE THREAD

**Issue by MOULNIA** [bosskmk/pluto_grid#263]
I have been working on this for a while but i cant freeze it on to one side of the screen. @bosskmk 
This issue is giving me a heard time please fix it as soon as possible

**Comment by MOULNIA** [comment]
thanks for the help man it worked but i have one more question can i permanently freeze one side of the grid

**Comment by bosskmk** [comment]
Please explain in more detail.

**Comment by WiRight** [comment]
seems like in #266 

if run in web - all ok - we can frozen columns on both sides

running on mobile devices - columns not frozen

Flutter 2.5.0

iOS 14+
Android 10+
(Mobile web also not working - try open web demo site and try freeze columns - nothing is happen)

P.S. sorry for my bad english
