### ISSUE TITLE
MacOS Desktop App - Backspace, Delete, Arrows Keys not working

### ISSUE THREAD

**Issue by LiveRock** [bosskmk/pluto_grid#264]
When editing text within the Cell, some keys are not working in the MacOS desktop app created from Flutter.
I tried Flutter stable, dev, master channels. Still the same

**Comment by LiveRock** [comment]
It seems like Windows also have the same issue. Just checked

**Comment by LiveRock** [comment]
The post below seems to suggest it was resolved in MASTER channel but I could't get cell editing to work with Backspace for PlutoGrid 

https://github.com/flutter/flutter/issues/78629

**Comment by amasahara** [comment]
On windows 10 i also meet same problem. but windows 7 is not meet this error. Don't know why

**Comment by bosskmk** [comment]
Resolved PlutoGrid 2.6.0

**Comment by isabelafagundes** [comment]
Hello, could someone help me? 
I tested moving between table cells using the keyboard arrows on Windows and web, and it works well. However, when using Linux (Ubuntu version 22.04.4), the arrows do not work.

**Comment by andreywillians** [comment]
I have the same problem here. It works fine on Windows and Web but didn't on Linux (Ubuntu 24.04)
