### ISSUE TITLE
PlutoColumnFrozen's Problem

### ISSUE THREAD

**Issue by jjvu-xiao** [bosskmk/pluto_grid#266]
Hello, when I used PlutoColumnFrozen, it did not produce the effect of fixed column as expected, which is also the case in example. The Flutter version is 1.22.6.stable and the plugin version is 1.1.0.Thank you for your reply.

**Comment by jjva-xiao** [comment]
I use Android and iOS

**Comment by WiRight** [comment]
In mobile device columns not freezing

**Comment by bosskmk** [comment]
If the total width of the grid is narrow, the column freeze is turned off.
Please leave any additional questions or comments.

**Comment by Akshay-akkay** [comment]
But why is it disabled? What can I do to enable it?

**Comment by bosskmk** [comment]
@Akshay-akkay 
If the column width of the basic body area is less than 200, the column frozen menu is disabled.
