### ISSUE TITLE
Select row height not full height when make row smaller

### ISSUE THREAD

**Issue by amasahara** [bosskmk/pluto_grid#267]
I try add " rowHeight: 28, " into PlutoGridConfiguration but some of column with little choise showing scroll like this image. Which way to config height and select row can be full width not need an empty column on right side

![image](https://user-images.githubusercontent.com/5392719/131464807-c1ed51be-8b41-4fb2-bb10-a38d821b6219.png)

**Comment by bosskmk** [comment]
Does the current 2.7.1 latest version have the same problem?
