### ISSUE TITLE
PlutoColumnType.date too hard for using

### ISSUE THREAD

**Issue by amasahara** [bosskmk/pluto_grid#268]
I have column that using PlutoColumnType.date but when showing choosing date. It very hard to know which month or year for changing. Could you using date column like showDatePicker of flutter.
Another hope you can update an choosing datetime column because my data have some column that contain both date and time value

**Comment by bosskmk** [comment]
The datetime type should be added. It would be nice if someone added it. Or I have to do it myself, but I don't have much time.

**Comment by amasahara** [comment]
yes, hope that you will be update it soon. Long time to see you back
