### ISSUE TITLE
Select first row automatically

### ISSUE THREAD

**Issue by iamkunalpitale** [bosskmk/pluto_grid#272]
How to select first row automatically with activate color? Any idea

**Comment by bosskmk** [comment]
PlutoGrid provides various methods on PlutoStateManager .

https://github.com/bosskmk/pluto_grid/wiki/pluto-state-manager-for-english

```dart
var grid = PlutoGrid(
  columns: columns,
  rows: rows,
  onLoaded: (PlutoGridOnLoadedEvent event) {
    stateManager = event.stateManager;
    stateManager.setCurrentCell(stateManager.firstCell, 0);
  },
);
```

As above, you can select the first cell.

**Comment by iamkunalpitale** [comment]
when i use this method its automatically getting tap and move to other screen i only wish that first selected with active color
