### ISSUE TITLE
Backspace keyboard not working

### ISSUE THREAD

**Issue by k1park** [bosskmk/pluto_grid#277]
Backspace keyboard not working when cell editing
build on
flutter version Flutter 2.5.1
.

build on  2.1
No problem.

**Comment by bosskmk** [comment]
This is a problem that occurs on Windows and Mac builds.
Looks like I'll have to wait for the flutter version update.
In the case of the web version, it does not occur because it is stabilized.

**Comment by k1park** [comment]
Did you check on Android.
Same problem occurs on android.

**Comment by ldsouza93** [comment]
experiencing the same issue here when filtering

**Comment by bosskmk** [comment]
I have registered an issue on flutter.

https://github.com/flutter/flutter/issues/93873

**Comment by bosskmk** [comment]
Text can be entered on the desktop, but the arrow keys and backspace keys do not work.

There is a problem if you have a TextField as a child of FocusScope and implement the onKey callback on the TextField .

FocusScope also has an onKey callback, and if you implement both, the behavior is different on web and desktop.

The same behavior should be updated by the flutter team.

Until then, I will find a solution on my own.

**Comment by bosskmk** [comment]
Fixed in version 2.6.0.
