### ISSUE TITLE
Small box with an X when row text overflows

### ISSUE THREAD

**Issue by cthurston** [bosskmk/pluto_grid#279]
![image](https://user-images.githubusercontent.com/622081/135516798-6e851f3e-484c-4175-b8e5-656431fffc3b.png)

**Comment by bosskmk** [comment]
There is a problem with the ellipsis in the multibyte representation.
This seems to be a problem with flutter, not just with PlutoGrid.

**Comment by bosskmk** [comment]
https://github.com/flutter/flutter/issues/90135

**Comment by bosskmk** [comment]
solution

https://github.com/flutter/flutter/issues/90135#issuecomment-984916656
