### ISSUE TITLE
 The sample application indicates errors

### ISSUE THREAD

**Issue by stephane3434** [bosskmk/pluto_grid#28]
Good widget !!!!

PLUTO version 1.15, the code indicates 6 errors

my flutter environment 
[√] Flutter (Channel master, 1.22.0-10.0.pre.449, on Microsoft Windows [version 10.0.19041.508], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.7.5)
[√] Android Studio (version 4.0)
[√] Connected device (3 available)

**Comment by bosskmk** [comment]
What is the error, can I see it?

**Comment by stephane3434** [comment]
![image](https://user-images.githubusercontent.com/5128215/94823609-55c0a180-0404-11eb-96d1-32ae4c6ed875.png)

![image](https://user-images.githubusercontent.com/5128215/94823675-67a24480-0404-11eb-90ac-d49a745df9b9.png)

![image](https://user-images.githubusercontent.com/5128215/94823716-738e0680-0404-11eb-8ff5-eb99e567f131.png)

**Comment by bosskmk** [comment]
Have you ever tried flutter clean or invalidate caches in the IDE?

**Comment by stephane3434** [comment]
now i have the same error 

+ flutter create .
+ flutter run 

Syncing files to device Chrome...                                       
lib/screen/home_screen.dart:44:24: Error: The argument type 'List<Container>' can't be assigned to the parameter type 'Widget'.
 - 'List' is from 'dart:core'.
 - 'Container' is from 'package:flutter/src/widgets/container.dart' ('/C:/Software/flutter/packages/flutter/lib/src/widgets/container.dart').
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
                child: [
                       ^
Failed to compile application.

**Comment by bosskmk** [comment]
Your HomeScreen file is wrong.
Child of line 44 can have one widget.

```dart

line 44
child: [
  Container(

>>

This is correct.
child: Container

```

**Comment by stephane3434** [comment]
thank you, 

but it's not my file it's the one in the example.
