### ISSUE TITLE
onChanged does not fire on row move.

### ISSUE THREAD

**Issue by chrislaurie-bs** [bosskmk/pluto_grid#281]
I cannot get the onChanged to fire when moving a row. It moves the row, updates the position in the ui but the event does not fire. Is there some confihuration that needs to be added? 

Also, in the example, the onChange is not called.

**Comment by chrislaurie-bs** [comment]
I have trawled the code to the best of my limited ability. There is only one call in the code to onChanged!(... and that is on the edit of a cell. I see no code in there to call onChanged!(... when the drag is completed.

**Comment by bosskmk** [comment]
Resolved da251255.
