### ISSUE TITLE
How to re-render data in grid? 

### ISSUE THREAD

**Issue by ZdenekKrcal** [bosskmk/pluto_grid#283]
Is it possibble to rerender data in datagrid? Im using provider with Consumer. Consumer is running but data doesn't change.

Consumer is embracing complete Plutogrid widget.

**Comment by bosskmk** [comment]
If Provider is used as the parent of PlutoGrid, the entire PlutoGrid is re-rendered, which is very inefficient.

**Comment by ZdenekKrcal** [comment]
I think that I tried stateManager.notifyListeners() but it didn't work. I will try it again.

**Comment by bosskmk** [comment]
Your example is a fragment and I can't run it.
I think there must be a minimum code that I can run to check it.

**Comment by ZdenekKrcal** [comment]
My example is about situation where I regulary fetch data from server by http request. When data are recieved then it is necessary to refresh PlutoGrid and there is my problem, because it is no possible to redraw data in PlutoGrid by Provider and its Consumer. My solution is using setState() and refresh all page with FutureBuilder now. But it would be great to have simple solution to redraw all PlutoGrid when we have another data during the time.

**Comment by lvyandev** [comment]
I also encountered this problem when refresh table with `plutoGridStateManager.notifyListeners()`
however, table can be refresh if 
```dart
stateManager?.removeRows(stateManager.rows);
stateManager?.appendRows(buildRows(_finishedData));
```

**Comment by LiveRock** [comment]
Yes, I would like to have to update PlutoGrid without setState() too.
I use stateManager to change value but the cell UI only refresh when setState().
Anyway to circumvent this?

**Comment by ZdenekKrcal** [comment]
> I also encountered this problem when refresh table with `plutoGridStateManager.notifyListeners()` however, table can be refresh if
> 
> ```dart
> stateManager!.removeRows(stateManager.rows);
> stateManager!.appendRows(buildRows(dataMap));
> ```
> 
> It's kinda like `notifyListeners` won't map changed data to new rows.
> 
> #183 is a similar situation, but I don't think `UniqueKey` is a solution to this.

I will try that solution later. Maybe I will try solution with UniqueKey as well. Thank you.

**Comment by devahmedghanim** [comment]
i think if there override function to rebuild data grid will resovle this problem like syncfusion

**Comment by ZdenekKrcal** [comment]
Is there any update? It would be greate to have method for refreshing records in table.
