### ISSUE TITLE
PlutoGrid does not allow to use . as thousands separators instead of ,

### ISSUE THREAD

**Issue by Gonzalo-Avalos-Ribas** [bosskmk/pluto_grid#285]
When i try to use the parameters PlutoColumnType.number(###.###,00) it throws an error. How to change this?

**Comment by Macacoazul01** [comment]
Try using 5.0.6 or 5.1.0

**Comment by bosskmk** [comment]
@Gonzalo-Avalos-Ribas 

Comma decimal separator cannot be used in format.
https://api.flutter.dev/flutter/intl/NumberFormat-class.html

If you use PlutoGrid 5.0.6 or 5.1.0, you can set the number format according to locale.

https://weblaze.dev/pluto_grid/build/web/#feature/number-type-column
See the 3 decimal places with denmark locale column in the example above.
