### ISSUE TITLE
Is it possible to make the selection with one click instead of two clicks?

### ISSUE THREAD

**Issue by jeffersonmello** [bosskmk/pluto_grid#286]
The title says it all, I would like to know if there is any configuration for this effect, activate the onSelected event with just one click

**Comment by jeffersonmello** [comment]
Anyone?

**Comment by bosskmk** [comment]
Please check the link below.
When creating PlutoGrid in version 2.6.0 or later, onSelected callback is called with one tap with PlutoGridMode.selectWithOneTap in mode.

https://github.com/bosskmk/pluto_grid/releases/tag/2.6.0
