### ISSUE TITLE
Add support for a totalizer bottom row always visible on a table

### ISSUE THREAD

**Issue by Gonzalo-Avalos-Ribas** [bosskmk/pluto_grid#289]
This would be an awesome feature, is there ever going to be support for it? Thanks!

**Comment by bosskmk** [comment]
You can add it by implementing the `createFooter` callback.

Implement the `createFooter` callback when creating a `PlutoGrid`.

**Comment by Gonzalo-Avalos-Ribas** [comment]
Awesome, thank you very much. Any examples of this?

**Comment by MajedDH** [comment]
@bosskmk  I'm working on this now 😄

**Comment by bosskmk** [comment]
@MajedDH 
You are very nice.
Your work should start in the Develop branch.
