### ISSUE TITLE
Sorting programmatically does not apply

### ISSUE THREAD

**Issue by j0chn1** [bosskmk/pluto_grid#296]
Hey there,
when I want to sort the grid programatically, it does not work for me.  

`  plutoStateManager.appendRows(_passwordRows);

    if (plutoStateManager.getSortedColumn != null) {  
      switch (plutoStateManager.getSortedColumn!.sort) {  
        case PlutoColumnSort.ascending:  
          plutoStateManager.sortAscending(plutoStateManager.getSortedColumn!);  
          break;  
        case PlutoColumnSort.descending:  
          plutoStateManager.sortDescending(plutoStateManager.getSortedColumn!);  
          break;  
      }
    }`

The debugger correctly runs into on of the sortings but the rows are not sorted ascending or descending. They keep the sorting of the newly set _passwordRows.
Am I doing something wrong here?

**Comment by bosskmk** [comment]
Call the code below after change.

`plutoStateManager!.notifyListeners();`

**Comment by j0chn1** [comment]
Hey @bosskmk ,
thank you for the reply. 
That was the problem. I did not see it in your doku. Maybe you want to add it?
Anyway. It works now so the issue is closed. 
Thanks again.
