### ISSUE TITLE
[feature/select-mode] Continue commit 1ee7d583 

### ISSUE THREAD

**Issue by bosskmk** [bosskmk/pluto_grid#3]
cleanup code.
Whether or not to support PlutoSelectingMode.Horizontal when copying and pasting multiple selects.

**Comment by kevinxxq** [comment]
Hello, @bosskmk , Thank you for your package.
I am not sure the difficulty to select a area as excel. 
It is common with a mouse to select some cells in one row(column) or several and then to copy, paste or delete contents of the cells.
I just searched days and found the grid need be wrapped in a GestureDetector. I wonder that whether you have implented such work.  

![sample](https://user-images.githubusercontent.com/55800697/119735548-7ed9ea80-be4a-11eb-8507-158f90370ba7.png)

Thank you.

**Comment by kevinxxq** [comment]
I just saw a description on other  website, it shows pluto_grid can handle the selection like excel. Great.
I will try to figure out the mode. Thank you.

_Selection
Row mode - Select rows.
Square mode - Select a square area like Excel.
None mode - Not selectable.
(Row mode) - Select Row by Control(Meta on MacOs) + Click.
(Row, Square mode) - (Shift + arrow keys) or (shift + click) or (long tapping and move) to select.
Select all rows or cells. Control(Meta on MacOs) + A._
