### ISSUE TITLE
TextPainter: TextPosition throwing !_debugNeedsLayout Assertion Error

### ISSUE THREAD

**Issue by emile-o** [bosskmk/pluto_grid#300]
TextPainter is throwing !_debugNeedsLayout Assertion Error:

`TextPosition getPositionForOffset(Offset offset) {
    assert(!_debugNeedsLayout);
    return _paragraph!.getPositionForOffset(offset);
  }`

Debug Console:

Error: Assertion failed:
package:flutter/…/painting/text_painter.dart:952
!_debugNeedsLayout
is not true

**Comment by bosskmk** [comment]
May I know your flutter version and PlutoGrid version? Which action is causing the error?
