### ISSUE TITLE
Num keypad keys unable to edit cell

### ISSUE THREAD

**Issue by selvam920** [bosskmk/pluto_grid#302]
pressing num keys(1..9) the cell is not editing, other than those keys are editing the cell.

**Comment by selvam920** [comment]
pls resolve this issue, this is important for my application

**Comment by bosskmk** [comment]
Yes, I'll check.

**Comment by bosskmk** [comment]
I am testing the behavior of numpad.
My guess is that the code below should return true when any key is pressed with numlock on, but it doesn't.

```dart
// RawKeyEvent event
print(event.data.isModifierPressed(ModifierKey.numLockModifier));
```

It is not difficult to add the numpad action function, but it seems that there will be a delay due to the above problem.

**Comment by selvam920** [comment]
in chromebook keyboard number keys also not editing the cell
