### ISSUE TITLE
how to change cell value?

### ISSUE THREAD

**Issue by selvam920** [bosskmk/pluto_grid#303]
How to change particular cell value programmatically?

**Comment by bosskmk** [comment]
You can change the value through changeCellValue as shown below.

```dart
stateManager!.changeCellValue(
  stateManager!.rows.first!.cells['column1']!.key,
  'Changed!',
);
```

stateManager 
https://github.com/bosskmk/pluto_grid/wiki/pluto-state-manager-for-english

```dart
void changeCellValue(
 Key cellKey,
 dynamic value, {
 bool callOnChangedEvent = true,
 bool force = false,
 bool notify = true,
})
```
#### cellKey
The key of the cell.

#### value
The value you want to change.

#### callOnChangedEvent
The onChanged callback is called by default when the cell value changes. Decide whether to call it or not. (If you set the onChanged callback.)

#### force
You can change the value by force when the column of the cell is not editable.

#### notify
If the value is changed, re-rendering is performed.

### uneditable state
* The column of the cell has readOnly or enableEditingMode set to false
* If the grid was started with PlutoGridMode.select.

**Comment by selvam920** [comment]
this awesome package!! great. thanks
