### ISSUE TITLE
Change number format

### ISSUE THREAD

**Issue by ZdenekKrcal** [bosskmk/pluto_grid#305]
I would like in column with type number set format like: 12 355,23 but it is not possible now. What I can set now is only 12,355.23. Please add possibility to set format more flexible.

Thank you.

**Comment by bosskmk** [comment]
Is the number format you want supported from the link below?

https://pub.dev/documentation/intl/latest/intl/NumberFormat-class.html

**Comment by ZdenekKrcal** [comment]
Oh yes, I think I can put space in number by (' ') thank you.
