### ISSUE TITLE
External barcode scanner issue

### ISSUE THREAD

**Issue by selvam920** [bosskmk/pluto_grid#306]
the scanned characters is not binding properly in editable column, scanning barcode using external barcode scanner

original barcode value: 99585858585888
in editable column:  85858585888

same thing is working fine in flutter textbox widget

**Comment by selvam920** [comment]
and also onChanged event called twice when we edit the field

**Comment by bosskmk** [comment]
Cells in PlutoGrid have a normal state and an edit state by default.
When a character (a~z, etc.) key is input in the normal state, the key input is processed while changing to the edit state.
There is a problem with this process being called twice.
It seems that the current behavior may be changed to fix this problem.

The current operation is when the cell is in the normal state and the value is 1234.
If the user presses the a key, the cell is changed to edit state, the value 1234 is erased, and only the a key is input.

If it is difficult to correct the problem mentioned in the current structure, the behavior may be changed as follows.

If the cell is in normal state and the value is 1234.
If the user presses the a key, the cell is changed to edit state and the value is maintained as 1234.

**Comment by bosskmk** [comment]
For now, the only thing to do is to put the cell in edit state before the barcode event is fired.

**Comment by bosskmk** [comment]
The problem of onChanged callback being called twice has been fixed in version 2.6.1.
Can you test the barcode scanner on version 2.6.1?
I don't have a barcode scanner so I can't test it.

**Comment by selvam920** [comment]
https://user-images.githubusercontent.com/20491308/142794477-45f7de50-6670-4cb1-bac8-a3c279845e06.mp4

**Comment by bosskmk** [comment]
In the video, even in the edit mode, one number seems to have been omitted, is that correct?
So, are the normal and current editing modes both wrong?

**Comment by selvam920** [comment]
i have used flutter beta version, that issue exist in edit mode but in master branch that issue fixed.

**Comment by bosskmk** [comment]
If the active cell is always in edit state, will the problem be solved?

**Comment by bosskmk** [comment]
And the barcode scanner has an error in flutter, did you solve the problem in the master channel?

**Comment by selvam920** [comment]
yes, but specific column

**Comment by selvam920** [comment]
> And the barcode scanner has an error in flutter, did you solve the problem in the master channel?

yes, in edit mode master channel the problem will solve

**Comment by bosskmk** [comment]
Yes, I'm thinking of something like this:

PlutoGridEditingMode.cell - current feature state
PlutoGridEditingMode.row - only cells in current row
PlutoGridEditingMode.column - only cells in current column

bool stateManager.keepEditingMode - always edit state if true

But in the end it may change.
I'll comment and let you know when the work is done.

**Comment by selvam920** [comment]
ok thanks

**Comment by selvam920** [comment]
also provide option to stretch column width for particular column

**Comment by jackselvam** [comment]
Did you get chance to work on this?

**Comment by bosskmk** [comment]
I will be starting soon.
Now I can't do anything else.

**Comment by bosskmk** [comment]
@selvam920 
It will be added in the next version.
The next version has some interface changes and may require your code modifications.
(The readOnly property of PlutoColumnType is moved to PlutoColumn )

**Comment by bosskmk** [comment]
Development is complete and is in the Develop branch. It will be released after some code review and testing.

**Comment by selvam920** [comment]
great..

**Comment by bosskmk** [comment]
Deployed as version 2.7.0. Please refer to the link below.

https://github.com/bosskmk/pluto_grid/releases/tag/2.7.0

**Comment by selvam920** [comment]
auto editing feature enabled all the editable columns, but we not only one column in the table, how to do?

**Comment by selvam920** [comment]
and also <b>Added keyboard move option with left and right arrow keys when reaching the left and right ends of text in edit state.</b>
is not working

**Comment by bosskmk** [comment]
> auto editing feature enabled all the editable columns, but we not only one column in the table, how to do?

AutoEditing of all cells can be done with the `setAutoEditing` method of `stateManager`, and `autoEditing` of specific columns can be done with the properties of `PlutoColumn`.

**Comment by bosskmk** [comment]
> Added keyboard move option with left and right arrow keys when reaching the left and right ends of text in edit state. feature is not working

You need to enable the enableMoveHorizontalInEditing property in configuration.

**Comment by selvam920** [comment]
great, well done, everything is working as expected..
any new about fit particular column width?

**Comment by bosskmk** [comment]
> great, well done, everything is working as expected.. any new about fit particular column width?

You can adjust the width of the column to fit the content with `PlutoGridStateManager.autoFitColumn` or `auto fit` in the context menu on the right side of the column title.

**Comment by selvam920** [comment]
auto fit means stretch column width based on the screen width for the particular column

**Comment by bosskmk** [comment]
> auto fit means stretch column width based on the screen width for the particular column

Do you mean adjusting the width of the columns to fit the width of the screen? This is yet.

**Comment by jackselvam** [comment]
Ok thanks for your support, you have done good job

**Comment by selvam920** [comment]
Hi can you provide option to always editable cell for particular column
bcoz now when focus the cell only editing happening, when we press esc key in editing mode cell the cell changed to read only then next i'm unable to scan barcode it removed first 2 digit in the barcode.
