### ISSUE TITLE
customize header (colspan or rowspan)

### ISSUE THREAD

**Issue by BangPei** [bosskmk/pluto_grid#308]
hi, is it possible to design the header like this :
![image](https://user-images.githubusercontent.com/50818216/143396410-f12ed185-0269-47bc-b89f-a9b964c45ff1.png)

**Comment by bosskmk** [comment]
I will consider adding this feature.

**Comment by BangPei** [comment]
oh ok, thanks for the plugin.

**Comment by bosskmk** [comment]
It is not colspan or rowspan, but a function to group columns has been added.
Try it out and please comment.

https://github.com/bosskmk/pluto_grid/releases/tag/2.8.0
