### ISSUE TITLE
[Question/New Feature] Customize cell padding

### ISSUE THREAD

**Issue by henry2man** [bosskmk/pluto_grid#309]
I'm using custom cell renderers in order to show an advanced calendar grid.

One thing that are stopping us are the cell paddings presents whatever I've tried nor configured.

I've digging into source code and I've found `PlutoGridSettings` and `cellPadding` but this seems not to be customizable.

Is there any possibility to customize this padding? Please look the yellow details at the attached screenshot

<img width="330" alt="Captura de pantalla 2021-11-25 a las 12 41 15" src="https://user-images.githubusercontent.com/4610108/143447881-b4c83ddc-7f4c-4057-b6ac-7cf23bdaa6dd.png">

**Comment by bosskmk** [comment]
I would consider adding that feature.

**Comment by henry2man** [comment]
@bosskmk Please consider the changes in https://github.com/bosskmk/pluto_grid/pull/312

**Comment by bosskmk** [comment]
Deployed as version 2.7.0. Please refer to the link below.

https://github.com/bosskmk/pluto_grid/releases/tag/2.7.0

**Comment by henry2man** [comment]
@bosskmk Thank you. I leave you a screenshot so you can see the final appearance after applying the change, much better than the previous one: 

<img width="373" alt="Captura de pantalla 2021-12-09 a las 10 11 37" src="https://user-images.githubusercontent.com/4610108/145367355-92d84eab-9eb0-4fb0-a31c-34d02c6e68ae.png">

**Comment by bosskmk** [comment]
@henry2man 
I have no use for PlutoGrid other than development, so I was wondering how it is used.
thank you.

**Comment by bosskmk** [comment]
Multiple columns to be added in the next version are under development.
For reference, I am developing multiple columns that will be added in the next version.
Columns can be added to any depth and can be dragged and dropped.

**Comment by henry2man** [comment]
> @henry2man I have no use for PlutoGrid other than development, so I was wondering how it is used. thank you.

I'm using PlutoGrid for two main use cases:
- As support for a master and detail view in CRUD interfaces (Create, Read, Update, Delete). The grid is used to show the list of instances.
- As support for mounting an attendance calendar (the use case for this issue): The grid is used to show a list of people; columns are month days and every cell means presences / absences

**Comment by bosskmk** [comment]
The initial development intention made it possible to use it in various forms.
However, it cannot be used in all situations and you will need a different type of package. One of them is Detail Form.
So, there is one that has been developed before, and this is a prototype, and we plan to develop a new one.

The YouTube link below is a demo video, and the final look of it will be like Excel.
Cells can be merged, the border color of each merged cell can be changed, and the borderCollapse function, which is not supported by flutter's Table, will be added.

https://www.youtube.com/watch?v=AJJtw811Fqs

**Comment by henry2man** [comment]
@bosskmk For now I'm very happy with current PlutoGrid implementation!! For detail views I'm using "plain" Flutter Forms.

Anyway, please let us know if this plugin is going to be deprecated because it's a crucial dependency for my current project.

**Comment by bosskmk** [comment]
@henry2man 
PlutoForm and PlutoGrid in the YouTube demo video are used for different purposes.
Both are still in development.
