### ISSUE TITLE
BorderRadius popup.

### ISSUE THREAD

**Issue by bosskmk** [bosskmk/pluto_grid#310]
@bosskmk very usefull new feature, additionally it might lead to a more consistent look, if the borderRadius for the popUps can also be set :thinking:

_Originally posted by @jlnrrg in https://github.com/bosskmk/pluto_grid/issues/299#issuecomment-979353607_

**Comment by jlnrrg** [comment]
On a side note, I would argue that this should be seperate property, as people might prefer popups to be square and the table to be rounded. 👍

**Comment by bosskmk** [comment]
Deployed as version 2.7.0. Please refer to the link below.

https://github.com/bosskmk/pluto_grid/releases/tag/2.7.0
