### ISSUE TITLE
PlutoGridStateManager is not able to removeListener

### ISSUE THREAD

**Issue by lvyandev** [bosskmk/pluto_grid#313]
if I add a listener to PlutoGridStateManager and remove it in `dispose`
then
```
A PlutoGridStateManager was used after being disposed.
```

Meanwhile, is it possible to control a specific cell is editable in a column?
I use following listener as a temporary solution

```dart
void onCellSelectedListener() {
    final PlutoGridCellPosition? currentPosition =
        gridStateManager?.currentSelectingPosition;

    if (currentPosition != null) {
      final int rowIndex = currentPosition.rowIdx!;
      final int columnIndex = currentPosition.columnIdx!;
      final bool? cellEditable =
          widget.columns[columnIndex].cellEditableGetter?.call(rowIndex);
      gridStateManager?.setEditing(cellEditable ?? false);
    }
  }
```

**Comment by bosskmk** [comment]
Do you want to dynamically control the editing state of a specific cell?

**Comment by lvyandev** [comment]
Yes, our business has a lot of certain situations

**Comment by bosskmk** [comment]
An autoEditing function that automatically enters editing state when selecting all cells or cells in a specific column will be added.

In addition to this, consider adding the dynamically editing state feature you mentioned.

**Comment by lvyandev** [comment]
Thanks, it will be very helpful!

**Comment by bosskmk** [comment]
It would be helpful for me to add a function if I could know in what situations the mentioned function is used.

**Comment by lvyandev** [comment]
![016B3D3A-86B1-4BE4-BE29-6254871EB3FA](https://user-images.githubusercontent.com/18045999/144702613-be7dff81-64d8-4949-8e15-bb112d53c76a.png)

For example, we can select table data that some fields cannot be edited,
also, we can add data to let user fill in the fields.

**Comment by lvyandev** [comment]
I've also found that header column style is not customizable, I can't add the require `*` marks for column title

**Comment by bosskmk** [comment]
@lvyandev 
It will be added in the next version.
The next version has some interface changes and may require your code modifications.
(The `readOnly` property of `PlutoColumnType` is moved to `PlutoColumn` )

**Comment by bosskmk** [comment]
Development is complete and is in the Develop branch. It will be released after some code review and testing.

**Comment by bosskmk** [comment]
Deployed as version 2.7.0. Please refer to the link below.

https://github.com/bosskmk/pluto_grid/releases/tag/2.7.0
