### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by stoneLee81** [bosskmk/pluto_grid#315]
Target dart2js failed: Exception:                                       
../../../software/flutter/.pub-cache/hosted/mirrors.cloud.tencent.com%2547dart-pub/pluto_grid-2.6.1/lib/src/widgets/pluto_scrollbar.dart:433:11:
Error: No named parameter with the name 'supportedDevices'.
          supportedDevices: supportedDevices,
          ^^^^^^^^^^^^^^^^
Error: Compilation failed.

**Comment by bosskmk** [comment]
What is your flutter channel?
Currently, PlutoGrid is being tested and developed in the stable channel.

**Comment by stoneLee81** [comment]
Channel stable, 2.2.2

**Comment by bosskmk** [comment]
PlutoGrid 2.5.0 is compatible with flutter 2.5.0 and later versions.
You should be using version 2.4.1 or lower.

**Comment by stoneLee81** [comment]
Upgrade to the latest flutter 2.8, the problem is solved。
