### ISSUE TITLE
read a map or a list of lists with the table data after filtering anything

### ISSUE THREAD

**Issue by ldsouza93** [bosskmk/pluto_grid#318]
hi

Im trying to export an excel file as the current state of the pluto table after filtering some columns. Is it possible to get the current state of the data as a map, or something like that so I can work on it with other things?

**Comment by bosskmk** [comment]
The rows and refRows properties of stateManager are lists according to the current state of PlutoGrid.
The difference between the two is whether refRows is a reference or not.
If both values are filtered, the filtered result is returned.
Also, if pagination is performed, the list of the current page is returned, not the entire list.

`stateManager.rows` - Refers to rows on the current page, not all rows.
`stateManager.refRows` - Refers to rows on the current page, not all rows.
`stateManager.refRows.originalList` - Refers to all rows, whether filtering or paging.
`stateManager.refRows.filteredList` - If it is filtered regardless of whether it is paging or not, it refers to the filtered result rows.

**Comment by bosskmk** [comment]
Deployed in version 2.10.0.
Contributed by @henry2man.

**Comment by henry2man** [comment]
@ldsouza93 I think this can be closed now. Current export feature do takes into consideration filtered data and visible columns.
