### ISSUE TITLE
Rendering efficiency of list comparisons of columns or rows.

### ISSUE THREAD

**Issue by bosskmk** [bosskmk/pluto_grid#325]
A problem in which the list of columns or rows is re-rendered even if it has not been changed.

I'm struggling with this for rendering efficiency.

**Comment by MajedDH** [comment]
I've started working on this this week.

The main problem is using a change notifier. there are a lot of widgets and they're all getting notified of all events, most of the widgets don't care about most of the events (for example, a cell shouldn't get a notification when resizing a column). and that's causing the whole grid to be rebuilt, re-layouted, and re-painted unnecessarily.  I'm working on separating these events and their subscribers. It'll be a hard task, but I'll see what I can do. 

For now I've seen that the rendering performance when resizing a column is too bad for using a Row widget. I've changed it to another widget, I'm still doing tests, but we can't do this without separating the layout process.

Another thing we may do is to cache cell widgets whenever possible. 

I'll share my progress when I get some work done on the topic
