### ISSUE TITLE
Expandable/Collapsible row details

### ISSUE THREAD

**Issue by slavap** [bosskmk/pluto_grid#326]
I have not found such feature in demos, is it possible?

![image](https://user-images.githubusercontent.com/4129763/145659819-fddad45e-19a3-42b8-82e4-f973361fb9e7.png)

**Comment by bosskmk** [comment]
This feature is not yet available.
I'll let you know when development starts.

**Comment by bosskmk** [comment]
I am currently contemplating whether to improve the rendering performance or add more features.

**Comment by slavap** [comment]
@bosskmk Performance is always nice, but unfortunately features are selling point for customers :-( This particular one is quite important in many scenarios.

**Comment by bosskmk** [comment]
Yes, this is a necessary feature. will be added.

**Comment by slavap** [comment]
@bosskmk Thank you

**Comment by lvyandev** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/18045999/147442346-15599546-3b50-4037-89d9-f51238750729.png">
Is this a similar issue?

**Comment by bosskmk** [comment]
@lvyandev 
Yes. And DualGrid will add vertical positioning feature.
