### ISSUE TITLE
Server-side pagination plug-in.

### ISSUE THREAD

**Issue by bosskmk** [bosskmk/pluto_grid#332]
Hi @bosskmk,
Any progress on server-side pagination? 
Thanks for such a wonderful datagrid. 
Regards,
Jose

_Originally posted by @jamolina2021 in https://github.com/bosskmk/pluto_grid/issues/105#issuecomment-994115891_

**Comment by bosskmk** [comment]
@jamolina2021
It is within the scope of the plan. But it's not currently in progress. We will let you know when an update is made.

**Comment by lenhnv1305** [comment]
hopefully this feature will follow bloc pattern

**Comment by bosskmk** [comment]
Released PlutoGrid 5.3.0

Refer to below link.
https://github.com/bosskmk/pluto_grid/issues/601
