### ISSUE TITLE
Wrong position of grid content when resize column width.

### ISSUE THREAD

**Issue by Chuanbin-Wang** [bosskmk/pluto_grid#335]
Drag the scrollbar to the far right, then reduce the width of the last column. You can see that the content and the title cannot correspond.

![image](https://user-images.githubusercontent.com/76732400/146628671-dd86828e-fa60-4f83-8f3f-299ddf34b1f3.png)

**Comment by bosskmk** [comment]
The problem has been reproduced. I'll check.
If you scroll the row left and right, the width is displayed normally.
I'll fix it.
thank you.

**Comment by bosskmk** [comment]
Version 2.9.0 has been released.
https://github.com/bosskmk/pluto_grid/releases/tag/2.9.0
