### ISSUE TITLE
Vertical scrollbar not displayed in PlutoDualGrid

### ISSUE THREAD

**Issue by dweber-dpra** [bosskmk/pluto_grid#345]
Hello,

In our web app using PlutoDualGrid the vertical scrollbar is not displayed in either grids A or B.  Below is our code to create the grid.  Any help would be greatly appreciated.

Thanks.

```
PlutoDualGrid(
      gridPropsA: PlutoDualGridProps(
        columns: columns,
        rows: rows,
        configuration: PlutoGridConfiguration(
          enableColumnBorder: true,
          scrollbarConfig: const PlutoGridScrollbarConfig(
            isAlwaysShown: true,
            draggableScrollbar: true,
          ),
          columnTextStyle: TextStyle(
            color: Colors.black,
            decoration: TextDecoration.none,
            fontSize: 11,
            fontWeight: FontWeight.w600,
          ),
          cellTextStyle: TextStyle(
            color: Colors.black,
            fontSize: 11,
          ),
          rowHeight: 34,
        ),
        onChanged: (PlutoGridOnChangedEvent event) {
          print("onChanged");
          print(event);
        },
        onLoaded: (PlutoGridOnLoadedEvent event) {
          _stateManager = event.stateManager;
        },
      ),
      gridPropsB: PlutoDualGridProps(
        columns: picListColumns,
        rows: picListRows,
        onChanged: (PlutoGridOnChangedEvent event) {
          print(event);
        },
        onLoaded: (PlutoGridOnLoadedEvent event) {
          _picListStateManager = event.stateManager;
        },
        configuration: PlutoGridConfiguration(
          enableColumnBorder: true,
          scrollbarConfig: const PlutoGridScrollbarConfig(
            isAlwaysShown: true,
            draggableScrollbar: true,
          ),
          columnTextStyle: TextStyle(
            color: Colors.black,
            decoration: TextDecoration.none,
            fontSize: 11,
            fontWeight: FontWeight.w600,
          ),
          cellTextStyle: TextStyle(
            color: Colors.black,
            fontSize: 11,
          ),
          rowHeight: 34,
        ),
      ),
      display: const PlutoDualGridDisplayRatio(ratio: 0.75)
    );
```

**Comment by bosskmk** [comment]
Hello.

When I checked, the scroll bar appears. What about the flutter and PlutoGrid versions?

Note that the scrollbar does not appear horizontally and vertically at the same time.
And it doesn't appear unless the width or height is the size to scroll.
Dragging the scroll or grid across the scrollable width toggles the horizontal and vertical scrollbars.

**Comment by dweber-dpra** [comment]
Hi,

I found the issue was that our main app class was using the dark mode theme which changed the scroll bar color that made it not visible.  When I added a theme to the grid it was visible.  I've attached a sample Flutter app (see line 28) and line 172.  Thanks for the quick response, your grid is a great tool.

---

[main.zip](https://github.com/bosskmk/pluto_grid/files/7785698/main.zip)

**Comment by bosskmk** [comment]
Yep I'm glad if the problem was resolved.
Grid has PlutoGridConfiguration.dart to change color in dark mode. However, the theme must be put at the application level as in the link below.

Dart mode example
https://weblaze.dev/pluto_grid/build/web/#feature/dark-mode

Dart mode example source
https://github.com/bosskmk/pluto_grid/blob/master/demo/lib/screen/feature/dark_mode_screen.dart
