### ISSUE TITLE
How To Show Date Picker In Filter To Select The startDate And endDate ?

### ISSUE THREAD

**Issue by devahmedghanim** [bosskmk/pluto_grid#353]
How To Show Date Picker In Filter To Select The startDate And endDate  ?

And Also I hope To Change Date Picker Style If It Possible ?

**Comment by bosskmk** [comment]
There is currently no ability `to change the range` or `date picker`.
It will be added and improved in the future.

Before that, you can implement it directly with `cellRenderer`.
But you have to implement it yourself.

https://weblaze.dev/pluto_grid/build/web/#feature/cell-renderer

**Comment by mohammadeslim22** [comment]
@bosskmk  how to modify the filter value cell ? can you explain ?
