### ISSUE TITLE
change disabled filter cell color

### ISSUE THREAD

**Issue by daniel199881** [bosskmk/pluto_grid#354]
is there a way to change the color of filter input to white instead of the default color??
it would be really nice if there is

**Comment by bosskmk** [comment]
Which filter input is the color from?
The color of the filter input is the default white background.
It is gray when disabled.
The color is in `PlutoGridConfiguration`
You can change it to `cellColorInEditState, cellColorInReadOnlyState`.

**Comment by daniel199881** [comment]
thanks al lot
