### ISSUE TITLE
change title icon and filter input border color

### ISSUE THREAD

**Issue by daniel199881** [bosskmk/pluto_grid#355]
Is there a way to change the burger icon in the header row of the table or remove it?
And is there a way to change border color of the disabled filter fields? 
Thanks in advance.

**Comment by bosskmk** [comment]
The column's icon cannot be changed.
It will be added in the future.
To remove it, set the `enableContextMenu` property of the Column to false.
And, to change the border of the disabled filter field, set the `borderColor` of `PlutoGridConfiguration`.
