### ISSUE TITLE
[Question] How to capture keyboard input in text field

### ISSUE THREAD

**Issue by dweber-dpra** [bosskmk/pluto_grid#356]
Hello,

For a cell of type text() we want to capture all keypress values so we can use that to filter certain information, this is similar to implementing a typeahead feature.

Example: elements we want to filter are "bird", "bee", "before", "building"

User types "b", we display all elements "bird", "bee", "before", "building"
User types "e", we display "bee" and "before"
User types "e", we display "bee"

Any recommendation would be greatly appreciated.

Thanks

**Comment by bosskmk** [comment]
You can access the textEditingController in PlutoGridStateManager from the edit state of the cell.
You can also capture events from textField.

**Comment by dweber-dpra** [comment]
Hi, do you have any code examples you can point me to.

Thanks

**Comment by bosskmk** [comment]
You can implement it by referring to the two links below.

https://stackoverflow.com/questions/66935362/how-to-use-texteditingcontroller-from-autocomplete-widget-flutter

https://weblaze.dev/pluto_grid/build/web/#feature/cell-renderer
