### ISSUE TITLE
Changing column context menu icon.

### ISSUE THREAD

**Issue by bosskmk** [bosskmk/pluto_grid#357]
The column's icon cannot be changed.
It will be added in the future.
To remove it, set the `enableContextMenu` property of the Column to false.
And, to change the border of the disabled filter field, set the `borderColor` of `PlutoGridConfiguration`.

_Originally posted by @bosskmk in https://github.com/bosskmk/pluto_grid/issues/355#issuecomment-1003216165_

**Comment by daniel199881** [comment]
thanks a lot for your help and wish you a happy new year and all the best

**Comment by bosskmk** [comment]
PlutoGrid version 2.9.3 has been distributed.

A property is added to change the background color of the column.
* reference link
* https://weblaze.dev/pluto_grid/build/web/#feature/column-group

A property is added to change the icon of the column.
* reference link
* https://github.com/bosskmk/pluto_grid/commit/da904753ecece54e11918eb32255ba78d42e2f50

**Comment by vecharm** [comment]
I meet the quesion also, table header was simple at the present , I hope to customize header of pluto_grid

**Comment by bosskmk** [comment]
@vecharm 
Please refer to the link below to customize the column group.
You can add custom widgets with the PlutoColumnGroup.titleSpan property.
Please give it a try and suggest if there is something missing in the function.
thank you

https://github.com/bosskmk/pluto_grid/blob/master/lib/src/model/pluto_column_group.dart#L16
