### ISSUE TITLE
 No named parameter with the name 'expandedColumn'.

### ISSUE THREAD

**Issue by bartonhammond** [bosskmk/pluto_grid#358]
Steps to reproduce:
1) flutter create myapp
2) cd myapp
3) cp ../examples/pluto_grid/example/pubspec.yaml .
4) cp ../examples/pluto_grid/example/lib/main.dart lib/main.dart 
5) update pubspec.yml by deleting the path to pluto_grid
6) flutter pub add pluto_grid
7) flutter run -d chrome

Note: if I change the `pubspec.yml`, it works 
```
  pluto_grid:
    path: ../examples/pluto_grid/
```

Here is compile error
```
lib/main.dart:106:51: Error: No named parameter with the name 'expandedColumn'.
    PlutoColumnGroup(title: 'Id', fields: ['id'], expandedColumn: true),
                                                  ^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/pluto_grid-2.8.0/lib/src/model/pluto
_column_group.dart:33:3: Context: Found this candidate, but the arguments don't
match.
  PlutoColumnGroup({
  ^^^^^^^^^^^^^^^^
lib/main.dart:109:54: Error: No named parameter with the name 'expandedColumn'.
      PlutoColumnGroup(title: 'A', fields: ['role'], expandedColumn: true),
                                                     ^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/pluto_grid-2.8.0/lib/src/model/pluto
_column_group.dart:33:3: Context: Found this candidate, but the arguments don't
match.
  PlutoColumnGroup({
  ^^^^^^^^^^^^^^^^
lib/main.dart:133:32: Error: Cannot invoke a non-'const' constructor where a
const expression is expected.
Try using a constructor or factory that is 'const'.
          configuration: const PlutoGridConfiguration(
                               ^^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:128:34: Error: A value of type 'PlutoGridStateManager?' can't be
assigned to a variable of type 'PlutoGridStateManager' because
'PlutoGridStateManager?' is nullable and 'PlutoGridStateManager' isn't.
 - 'PlutoGridStateManager' is from
 'package:pluto_grid/src/manager/pluto_grid_state_manager.dart'
 ('../../../.pub-cache/hosted/pub.dartlang.org/pluto_grid-2.8.0/lib/src/manager/
 pluto_grid_state_manager.dart').
            stateManager = event.stateManager;
                                 ^
Waiting for connection from debug service on Chrome...             20.4s
Failed to compile application.
```
<details>
  <summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/bartonhammond/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/bartonhammond/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!

</details>

**Comment by bosskmk** [comment]
`expandedColumn` is a property for the next version and is included in the demo.
I will release the next version soon.
sorry.

**Comment by bosskmk** [comment]
Version 2.9.0 has been released.
https://github.com/bosskmk/pluto_grid/releases/tag/2.9.0
