### ISSUE TITLE
Editing Textbox, keylistener is not working with  Enter Key 

### ISSUE THREAD

**Issue by selvam920** [bosskmk/pluto_grid#360]
when press the enter key the below listener is not capturing, it was working previously.
stateManager!.keyManager!.subject
                .listener((PlutoKeyManagerEvent value) async {})

enableEditingMode :true
enterKeyAction: PlutoGridEnterKeyAction.none,

**Comment by bosskmk** [comment]
What action do you want to achieve?
If you explain it, I think an answer is possible.

**Comment by selvam920** [comment]
After type product code in textbox  press enter key i need to fetch the record from api

**Comment by selvam920** [comment]
It was working previously

**Comment by bosskmk** [comment]
Is "previously" mean version?

**Comment by selvam920** [comment]
I don't remember the version, but i have done my earlier it was working after update latest version is not working

**Comment by selvam920** [comment]
Other than enter key is working fine in the listener

**Comment by bosskmk** [comment]
I have confirmed the problem. I will distribute the modified version after confirmation.

**Comment by bosskmk** [comment]
2.9.1 has been released. thank you.

**Comment by selvam920** [comment]
it's working, thanks
