### ISSUE TITLE
delete all rows in table

### ISSUE THREAD

**Issue by daniel199881** [bosskmk/pluto_grid#361]
Is there a way to remove all the existing rows in the table having the PlutoGridStateManager i tried using stateManager!.removeRows(stateManager!.rows); but it didn't work.
if not is it possible to filter the current rows from a field comming from an input that is not in the table??
thanks in advance.

**Comment by bosskmk** [comment]
You can delete all rows as below.

```dart
widget.stateManager.removeRows(widget.stateManager.refRows.originalList);
```

**Comment by elgsylvain85** [comment]
Being a frequent operation, I think that a direct method will be welcome. Thank you for the work done so far.
For example :
 `stateManager.clearRows();`
