### ISSUE TITLE
🐛  [SEVERE] BUG: Double parsing is causing issues, removing decimals when Locale is not English

### ISSUE THREAD

**Issue by henry2man** [bosskmk/pluto_grid#367]
I'm using PlutoGrid to show some decimal numbers in a Spanish localized app, locale "es_ES" (I suspect this is relevant).

When I apply some number format to my numeric columns I'm always have weird numbers.

After some researching I've found that this line is causing issues.

https://github.com/bosskmk/pluto_grid/blob/4aaafc39c2dbd5ac0fee938e5a2be2686e748798/lib/src/model/pluto_column_type.dart#L239

Debugging this method I've found that an input value `double = 4.58` is converted to `double 458.0`:

Before the line execution:
<img width="736" alt="Captura de pantalla 2022-01-17 a las 21 08 02" src="https://user-images.githubusercontent.com/4610108/149831958-8bd052d0-44d9-4945-ba7d-2360cfdafc12.png">

After line execution, take notice of the new value of `num` variable:

<img width="738" alt="Captura de pantalla 2022-01-17 a las 21 08 17" src="https://user-images.githubusercontent.com/4610108/149832065-71eca789-fcd8-46dd-b392-f996bfbf9553.png">

I think that, with my locale, `double.toString()` is implicitly converted to `"4.58"` (String) and then the dot `.` is removed.

If we want to perform some checks, why don't we review the input type of `value` argument:

- if `value` is not `num`, run this block code
- if `value` is `num`, then simply format it (last line of method) and exit

**Comment by bosskmk** [comment]
Thanks for your report.
I will distribute the modifications after confirmation.
It will be released in 2.9.2, please let me know if you are using a different version. I will distribute that too.

**Comment by henry2man** [comment]
> Thanks for your report. I will distribute the modifications after confirmation. It will be released in 2.9.2, please let me know if you are using a different version. I will distribute that too.

@bosskmk As a workaround I've implemented this utility method & class, which can be used as a replacement and/or for inspiration for the bug:

```dart
/// PlutoGridUtils
static PlutoColumnType numberColumnType({
    dynamic defaultValue = 0,
    bool negative = true,
    String format = '#,###',
    bool applyFormatOnInit = true,
    bool allowFirstDot = false,
  }) {
    return FixedPlutoColumnTypeNumber(
      defaultValue: defaultValue,
      format: format,
      negative: negative,
      applyFormatOnInit: applyFormatOnInit,
      allowFirstDot: allowFirstDot,
    );
  }
...
class FixedPlutoColumnTypeNumber extends PlutoColumnTypeNumber {
  FixedPlutoColumnTypeNumber(
      {dynamic defaultValue,
      bool? negative,
      String? format,
      bool? applyFormatOnInit,
      bool? allowFirstDot})
      : super(
          defaultValue: defaultValue,
          negative: negative,
          format: format,
          applyFormatOnInit: applyFormatOnInit,
          allowFirstDot: allowFirstDot,
        );

  @override
  String applyFormat(dynamic value) {
    // If value is a number, then just format it
    if (value is num) {
      final f = intl.NumberFormat(format);
      if (negative == false && value < 0) {
        value = 0;
      }
      return f.format(value);
    } else {
      // Run current implementation
      return super.applyFormat(value);
    }
  }
}
```

**Comment by henry2man** [comment]
> I will distribute the modifications after confirmation.

@bosskmk Please take your time, I think this could be a little bit tricky to test and something that we don't want to broke more. I think the key here is have a good suite of tests cases. Let me know if you need any further info and/or some help.

**Comment by henry2man** [comment]
I think we would make two changes:

- On the one hand I think it is "dangerous" to be creating the `NumberFormat` constructor without specifying a locale. How about adding some `locale` parameter at the PlutoGrid configuration level? This could also apply to date formats. Do you have any plans on this?

- On the other hand, it would add the behavior that we have commented, doing the parsing only if the input data type of the argument is not a `num`

What do you think?

**Comment by bosskmk** [comment]
Thank you for your comments.
I'll add locale .
And I'll modify it so that locale is applied to number and date formats or other parts that are needed inside.
Lastly, I will modify the parsing condition of num to the content you suggested.

**Comment by henry2man** [comment]
> It will be released in 2.9.2, please let me know if you are using a different version. I will distribute that too.

I'm on latest 2.9.1, thanks for taking care of that 🥇

**Comment by henry2man** [comment]
@bosskmk FYI, this is the config of `f.symbols` for `locale=es`:

<img width="588" alt="Captura de pantalla 2022-01-18 a las 8 56 53" src="https://user-images.githubusercontent.com/4610108/149894564-ad840ddf-f6ee-47ea-b8f9-d7b67206fbfb.png">

In Spain we use dot `.` as **group separator**, which is the same as **decimal separator** in the default `double.toString()` implementation and also the decimal separator in Dart. 

Also here you'll find a list of common locales: https://en.wikipedia.org/wiki/Decimal_separator (`intl` package should be synced with this), so you can prepare some test for commonly used locales.

**Comment by bosskmk** [comment]
Updated to PlutoGrid 2.9.2 version.

Modified so that number format is applied according to intl locale.

```dart
/// change to static method
PlutoGrid.setDefaultLocale('es_ES');
PlutoGrid.initializeDateFormat();

/// or change it using your Intl package.
Intl.defaultLocale = 'es_ES';
initializeDateFormatting();
```

I haven't added any other features I mentioned before. (Add locale to settings and apply locale to date format.)

In the case of date, it is not necessary because it can be changed according to the format regardless of locale.

Also, adding locale to the configuration does not seem to be necessary now, as it only affects the number format.

If you have other opinions, please leave a comment.

thank you.

**Comment by henry2man** [comment]
@bosskmk I'll check the changes tomorrow and I'll tell you how it behaves with the new code. Thank you

**Comment by henry2man** [comment]
I have disabled my workarounds and apparently the fix is successful. I was already using `intl` to specify the locale, so the change didn't require anything else. Thanks, again.
