### ISSUE TITLE
How can I change header background without using createHeader?

### ISSUE THREAD

**Issue by christianarduino** [bosskmk/pluto_grid#369]

**Comment by bosskmk** [comment]
Header can only be created via createHeader .
What you are trying to change is the Column 's Background ?
That feature doesn't exist yet.

**Comment by christianarduino** [comment]
This is what I'm trying to implement:
![image](https://user-images.githubusercontent.com/54827354/151257453-b695ae91-d9b6-4f09-a76e-c4995df4e12e.png)

**Comment by bosskmk** [comment]
Yes, I understand.
You want to change the background color of the column and the icon on the right.
I hope to be added in the next version.

**Comment by nogosan** [comment]
This is an amazing library, and I also hope that column background feature added. thank you!

**Comment by bosskmk** [comment]
PlutoGrid version 2.9.3 has been distributed.

A property is added to change the background color of the column.
* reference link
* https://weblaze.dev/pluto_grid/build/web/#feature/column-group

A property is added to change the icon of the column.
* reference link
* https://github.com/bosskmk/pluto_grid/commit/da904753ecece54e11918eb32255ba78d42e2f50
