### ISSUE TITLE
Enhancement - tolerance for mismatched Columns to row data

### ISSUE THREAD

**Issue by jodymac** [bosskmk/pluto_grid#372]
My app has the ability to specify employees and fields in groups.  I build the rows and columns dynamically because the app users can create their own items, so it is different per use case.  If the user has a number of fields for several days and then adds a new field, the grid will crash.  

For example the column is date, item1, item2, item3.  They use this list for several days and then add item 4.  When I build the columns dynamically, the original data is missing item4 and the grid will not build.  

Am I missing a setting?  If not, I would request that if row data does not include the field id (item 4 of above example) that it create a blank cell (or ability to add color).   Hopefully I didn't miss something simple in the documentation or examples.

**Comment by bosskmk** [comment]
To add a row or column, check out the example below.

https://weblaze.dev/pluto_grid/build/web/#add-and-remove-column-row

**Comment by jodymac** [comment]
Thank you for taking the time to reply.  Unfortunately, that's not quite the issue I have, those functions work quite well once the grid is build.  My issue is with building the grid initially from my local app database.  Specifically when the number of columns changes in the latter half of the data.  So If have 4 rows of data that has 5 columns it all builds fine.  But if the latest row of data now has 6 columns, it crashes because the preceding 4 rows don't have that extra column.  My request is that in this situation, the grid autocorrects for missing columns by and/or row data by inserting a black cell.  

Without doing this, I will have to check each row to make sure the # of columns matches each row I plan on inserting.  In my use case, my user could start with 4 columns of data that is built every day.  4 months from now, the columns might have grown to 30.  If not possible, I'll just have to figure out how to sanitize my data appropriate.  I would also have to account for a column not existing in the beginning, existing in the middle, and not existing at the end.

**Comment by bosskmk** [comment]
Yes, I understand.

Do you want PlutoGrid to recognize and automatically fill in values corresponding to columns that are not in existing rows?

For example, rows 1 to 4 have values corresponding to columns a, b, and c.
Rows 5 to 6 have values corresponding to columns a, b, c, d, and e,
You want to automatically fill in the cell values corresponding to columns d and e in rows 1 to 4 with default values.

Is that right?

**Comment by jodymac** [comment]
Yes, you explained it perfectly.
