### ISSUE TITLE
pasting from excel

### ISSUE THREAD

**Issue by hamzaj9** [bosskmk/pluto_grid#375]
can when we paste 10 rows and i have 3 rows in pluto_grid, to add 7 more rows and paste all data in it?

**Comment by bosskmk** [comment]
The feature is not yet supported, the feature should be added.
I hope to be added in the next version.
thank you.

**Comment by hamzaj9** [comment]
i wrote a simple code for it, but i don't know if its a good one. @bosskmk wants me to share it ?

**Comment by hamzaj9** [comment]
@bosskmk this my code, i handled this in a different Crtl+V event:

```
int rowIdx = 0, totalRows = stateManager!.rows.length;
List<PlutoRow> selectedRows = stateManager!.currentSelectingRows;
if(stateManager!.currentCellPosition != null && stateManager!.currentCellPosition!.rowIdx != null){ //capture the selected cell row index
  rowIdx = stateManager!.currentCellPosition!.rowIdx!;
}
else if(selectedRows.isNotEmpty){ //capture the last selected row index
  rowIdx = selectedRows[selectedRows.length-1].sortIdx!;
}
int leftRows = totalRows - rowIdx;
ClipboardData? cdata = await Clipboard.getData(Clipboard.kTextPlain);
if(cdata != null){
  String copiedtext = cdata.text?? "";
  copiedtext = copiedtext.trim(); //since copying from excel will add \n at the end
  List<String> rows = copiedtext.split("\n");
  if(rows.length > leftRows){
    int sz = rows.length - leftRows;
    stateManager!.appendNewRows(count: sz);
  }
  List<List<String>> cellValues = [];
  for(int i = 0; i < rows.length; i++){
    if(rows[i].contains("\t")){
      cellValues.add(rows[i].split("\t"));
    }
  }
  stateManager!.pasteCellValue(cellValues);
}
```

**Comment by bosskmk** [comment]
Function development has been completed so that it can be added in the next version.

If you type the shortcut `Ctrl + Shift + v` (with 3 rows on the clipboard)
a. No rows (add 3 rows and paste)
b. If there is 1 row and the first cell is selected (2 new rows are added and pasted)

I'll let you know when the feature is released.
Also, if you have any comments about the features described above, please leave a comment.

thank you.

**Comment by hamzaj9** [comment]
I think this is good. but why you want to make it with ```Ctrl + Shirt + v``` it will be better with just ```Ctrl + v```. Add a parameter ```bool growable``` to the grid. ```if (growable) //add rows```

**Comment by a7mdragab** [comment]
what is new?
