### ISSUE TITLE
Can we Export rows and columns data to excel and pdf?? if so can anyone help??

### ISSUE THREAD

**Issue by anuragowly7** [bosskmk/pluto_grid#376]
**Can we Export rows and columns data to excel and pdf?? if so can anyone help??**

**Comment by edwinmacalopu** [comment]
@anuragowly7  for excel you can use this package https://pub.dev/packages/excel

**Comment by henry2man** [comment]
Please take a look at #121

**Comment by bosskmk** [comment]
Deployed in version 2.10.0.
Contributed by @henry2man.

**Comment by henry2man** [comment]
@anuragowly7 Recently deployed feature will let you export a CSV file. If you change the extension to `.xls` Excel will try to open it. Even if it is a flat file, it will recognize and import it as if it were a complex Excel file.

Regarding `.pdf`, I have some experience with [pdf](https://pub.dev/packages/pdf) (and companion [printing](https://pub.dev/packages/printing) package) but I'm not sure if we can develop something generic that **_will work with every possible grid_**. The main issues could be related to page size & column widths... If you want to give it a try you can take current CSV plugin as an example and adapt it to `pdf` using [Table](https://pub.dev/documentation/pdf/latest/widgets/Table-class.html) widget. Please tell us if you are successful 😄

**Comment by henry2man** [comment]
@anuragowly7 We have a draft implementation at https://github.com/bosskmk/pluto_grid/pull/440
