### ISSUE TITLE
programmatically set currentcell verticalscrollbar is not moving to row

### ISSUE THREAD

**Issue by selvam920** [bosskmk/pluto_grid#378]
i have two page in grid,when i button click i need to focus first row.
the result first row selected but scroll is not moving up

 stateManager!.setCurrentCell(
        stateManager!.rows[0].cells.entries.elementAt(0).value, 0);

**Comment by hamzaj9** [comment]
I think you can use ```moveScrollByRow```
you can check how he used it here:
https://github.com/bosskmk/pluto_grid/blob/master/demo/lib/screen/feature/add_and_remove_column_row_screen.dart
(in handleAddRows function)

``` 
widget.stateManager.moveScrollByRow(
  PlutoMoveDirection.up,
  rowIdx,
);
```

**Comment by selvam920** [comment]
yes, it's working
