### ISSUE TITLE
how to add icon into PlutoCell or some widget

### ISSUE THREAD

**Issue by amasahara** [bosskmk/pluto_grid#38]
I try to add an icon into cell example about status of row like use or not use but seem it not work, is any resole for me

**Comment by bosskmk** [comment]
Cell values are output as strings.
You can't output icons or other widgets as cell values.
This should add functionality.
Let me consider it.

**Comment by amasahara** [comment]
hope you will have solution for this soon

**Comment by rohitranjan1991** [comment]
Hi @bosskmk, any update on this ? really looking forward to add custom icons in each row for deleting, info, etc.

**Comment by bosskmk** [comment]
@rohitranjan1991 
Check out the example below. This function can be implemented with cell renderer.
https://weblaze.dev/pluto_grid/build/web/#feature/cell-renderer

**Comment by rohitranjan1991** [comment]
@bosskmk , Thanks for the link. But I am not able to understand it. So the image Image.asset is defined in the PlutoColumn which then gets displayed in each row. What if I want to show different Images in different rows?
