### ISSUE TITLE
programmatic filtering.

### ISSUE THREAD

**Issue by aphelps535** [bosskmk/pluto_grid#381]
I am trying to trigger a PlutoGridChangeColumnFilterEvent based on simply changing the filter in the dropdown, instead of changing the filter textfield. I need to add a IsEmpty and IsNotEmpty filter to the grid which will not require text, but currently the only way to trigger a filter is through the onChanged of that textfield. Is there any way around this?

**Comment by Franion03** [comment]
Same problem here
