### ISSUE TITLE
Question/Bug? - Do not request focus on show.

### ISSUE THREAD

**Issue by henry2man** [bosskmk/pluto_grid#386]
@bosskmk I'm displaying a complex screen that shows two `PlutoGrid` side by side, using a classic a master-detail pattern.

The second grid is not rendered until a row is selected in the first grid.

For whatever reasons, I have some keyboard handlers centralized on the first grid that aren't working **because the second grid is requesting the focus every time it is showed**. I'm using this `onLoaded` callback to disable focusing but I think that I'm missing something and/or this is not what I want:

```dart
                            onLoaded: (PlutoGridOnLoadedEvent event) {
                              stateManager = event.stateManager;
                              stateManager?.setKeepFocus(false); // <- I want to disable autofocus! 
                              stateManager!
                                   .setSelectingMode(PlutoGridSelectingMode.row);
                            },
```

Is there any possibility to make PlutoGrid not reclaim focus automatically?

EDIT: Also I've tried -without success- to cancel current focus using an extended callback:

```dart
                            onLoaded: (PlutoGridOnLoadedEvent event) {
                              stateManager = event.stateManager;
                              stateManager?.setKeepFocus(false); // <- I want to disable autofocus! 
                              stateManager!
                                   .setSelectingMode(PlutoGridSelectingMode.row);
                              
                              final FocusScopeNode currentScope =
                                  FocusScope.of(context);
                              if (!currentScope.hasPrimaryFocus &&
                                  currentScope.hasFocus) {
                                FocusManager.instance.primaryFocus!.unfocus();
                              }


                            },
```

**Comment by alberteije** [comment]
> @bosskmk I'm displaying a complex screen that shows two `PlutoGrid` side by side, using a classic a master-detail pattern.
> 
> The second grid is not rendered until a row is selected in the first grid.
> 
> For whatever reasons, I have some keyboard handlers centralized on the first grid that aren't working **because the second grid is requesting the focus every time it is showed**. I'm using this `onLoaded` callback to disable focusing but I think that I'm missing something and/or this is not what I want:
> 
> ```dart
>                             onLoaded: (PlutoGridOnLoadedEvent event) {
>                               stateManager = event.stateManager;
>                               stateManager?.setKeepFocus(false); // <- I want to disable autofocus! 
>                               stateManager!
>                                    .setSelectingMode(PlutoGridSelectingMode.row);
>                             },
> ```
> 
> Is there any possibility to make PlutoGrid not reclaim focus automatically?
> 
> EDIT: Also I've tried -without success- to cancel current focus using an extended callback:
> 
> ```dart
>                             onLoaded: (PlutoGridOnLoadedEvent event) {
>                               stateManager = event.stateManager;
>                               stateManager?.setKeepFocus(false); // <- I want to disable autofocus! 
>                               stateManager!
>                                    .setSelectingMode(PlutoGridSelectingMode.row);
>                               
>                               final FocusScopeNode currentScope =
>                                   FocusScope.of(context);
>                               if (!currentScope.hasPrimaryFocus &&
>                                   currentScope.hasFocus) {
>                                 FocusManager.instance.primaryFocus!.unfocus();
>                               }
> 
> 
>                             },
> ```

Did you solve it?

**Comment by henry2man** [comment]
No, the issue is closed but there aren't any changes in this behaviour, as far as I know
