### ISSUE TITLE
Support multiline text in column

### ISSUE THREAD

**Issue by FelixYew** [bosskmk/pluto_grid#389]
Please add support for multiline text in column.

**Comment by bosskmk** [comment]
@FelixYew 

multiline is to display multiple lines of text in one cell?

There is currently no function, but you can implement it using column 's renderer .

There is a reference link below, you can see the source by clicking the source code link.

Just implement the renderer callback function.

https://weblaze.dev/pluto_grid/build/web/#feature/cell-renderer

**Comment by uditrugman** [comment]
displaying with a renderer is a nice workaround. the question is how to support editing multiline text?

**Comment by ganapathyp** [comment]
Do we have a resolution for this issue?
