### ISSUE TITLE
Change Header Color

### ISSUE THREAD

**Issue by arindammitra06** [bosskmk/pluto_grid#390]
Hi Thanks for the wonderful package. I am successfully able to update the header TextStyle using the PlutoGridConfiguration. But I am unable to change the header background color. Is there any way to do so?

**Comment by bosskmk** [comment]
@arindammitra06 

PlutoGrid version 2.9.3 has been distributed.

A property is added to change the background color of the column.

reference link
https://weblaze.dev/pluto_grid/build/web/#feature/column-group

**Comment by huongtran84** [comment]
background color changed but title text color not supported

**Comment by bosskmk** [comment]
@huongtran84 

Please refer to the link below for column text color.
This can be changed with the `titleSpan` property.

https://github.com/bosskmk/pluto_grid/blob/master/lib/src/model/pluto_column.dart#L36

**Comment by SittiphanSittisak** [comment]
How to remove padding as image below?
![Web capture_7-4-2022_183812_weblaze dev](https://user-images.githubusercontent.com/59549741/162190427-d62ee001-a783-4c0d-8b84-fc775cd7fcbb.jpeg)
