### ISSUE TITLE
number column locale format vs infinite scrolling rows

### ISSUE THREAD

**Issue by huongtran84** [bosskmk/pluto_grid#392]
Firstly thanks team who was develop for a great lib.
currently lib did not.support column number with locale format and infinite scrolling rows, for load more.
I hope see it in new version.thanks

**Comment by bosskmk** [comment]
@huongtran84 

For locale application of number format, refer to the link below.

https://github.com/bosskmk/pluto_grid/issues/367#issuecomment-1023079673
