### ISSUE TITLE
Storing state

### ISSUE THREAD

**Issue by bastaware** [bosskmk/pluto_grid#393]
What is the best way to store the state of the grid? In particular, I would like to store the order of the columns and whether they are hidden after the user drags or hide/show a column.

I can't seem to find an event handler to subscribe to, that tells me when these things happen?

**Comment by bosskmk** [comment]
You can listen for state changes with `stateManager.addListener`.

`stateManager.refColumns.originalList` refers to the entire column list including hidden columns.

The column attribute has states such as `hide`, `frozen`, etc.

**Comment by bastaware** [comment]
Thanks for the fast reply.

I did look at addListener but it's triggered on every interaction e.g. resize columns. And as there is no event type it's not possible to determine if it's a state update.

So I hoped there was a more concise way. Well I can check for updates on every callback and only store state if it's changed, so it should work.

Keep up the good work!
