### ISSUE TITLE
How to change Column Filter

### ISSUE THREAD

**Issue by lie16** [bosskmk/pluto_grid#396]
I know that we can create a dropdown at cell using cel Renderers. What about filter, are there any approaches to changing the filter from text box to combo box or maybe date picker?

**Comment by bosskmk** [comment]
As for filters, there is no ability to add custom widgets yet. It is a necessary feature in the future, so I hope it will be added.

**Comment by SittiphanSittisak** [comment]
Hi, can we change the text on the filter?
I want to change these texts to my language(Thai).
![image](https://user-images.githubusercontent.com/59549741/162560088-63ba60be-c351-494f-bd00-3fd6d3b7367b.png)
