### ISSUE TITLE
Current focused row is not displayed, when list bigger than screen

### ISSUE THREAD

**Issue by NiranjanShah** [bosskmk/pluto_grid#40]
![Screenshot 2020-10-13 at 8 53 10 PM](https://user-images.githubusercontent.com/9315778/95881411-2d3a8f00-0d96-11eb-9816-a7a08f467502.png)

The current focus record is not visible, it moving beyond the viewport

**Comment by NiranjanShah** [comment]
ok, however it must be set to the height if the device, to avoid any concern

**Comment by bosskmk** [comment]
Yes. However, if the height of the description section at the top of the grid is large, the grid is not visible, so I set the height.
Thanks for your comment.
