### ISSUE TITLE
Adding new rows while using filters doesn't filter new rows.

### ISSUE THREAD

**Issue by MajedDH** [bosskmk/pluto_grid#401]
When `appendRows` is used while there is already column filters enabled, the newly added columns are added as-is, they're not filtered. I think the list must be both filtered and sorted whenever new rows are added. or at least make it optional to sort. but they must obey the filtering criteria.

**Comment by bosskmk** [comment]
When a row is added with `appendRows`, it is being appended after the existing row, regardless of the grid filter state.

This is my intention, and I agree to treat it as optional as you said.

**Comment by programmeraditya** [comment]
@bosskmk Is there way to implement this with available methods? Could you share an example? I'd like the filer to be enforced for new rows as well, and I haven't found a viable solution yet.
