### ISSUE TITLE
Feature Request : Dropdown menu fetch data from server

### ISSUE THREAD

**Issue by Baghdady92** [bosskmk/pluto_grid#403]
Hello everyone 
thanks alot for all the hard working here in this package 
i'd like to request this feature 
Dropdown menu fetch data from server
also i'd like a little enhancement for dropdown i'd like to put type map<String , dynamic> can also be a plus 
this request i'll pay or donate for it 
thanks

**Comment by bosskmk** [comment]
https://weblaze.dev/pluto_grid/build/web/#feature/cell-renderer

You can implement it yourself by referring to the link above.

You can change the cell to any widget you want, which allows you to implement a dropdown widget.
