### ISSUE TITLE
how to get all data from the row?

### ISSUE THREAD

**Issue by iagognunes** [bosskmk/pluto_grid#404]
How can I get all data from checked rows?

**Comment by Baghdady92** [comment]
first you need to make a list in your controller or repository or anyplace you love 
 rows = List<PlutoRow>.empty().obs;
then you add more rows or emply rows then the user change the values of it 
then you need to make a method in your controller or state 
 calling this  in the for loop 
row in rows :
row.cells['value_number']!.value 
that's it

**Comment by iagognunes** [comment]
Thank you very much, it helped a lot!
