### ISSUE TITLE
How to remove or refresh table?

### ISSUE THREAD

**Issue by SittiphanSittisak** [bosskmk/pluto_grid#406]
Hi, I want to replace all rows with new data.
For the example, I create a table widget that will return PlutoGrid, and this widget required List<PlutoRow> rows like this.
```
Widget tableForm({
  required List<PlutoRow> rows,
})
```
It's used on the main page like this below.
```
tableForm(rows: rowsInMainPage)
```
On the main page, I have a button to fetch new data and replace data in rowsInMainPage parm. This onTab function looks like this below.
```
void replaceRows() {
    setState(() {
      rowsInMainPage = [];
      rowsInMainPage = newDataFromAnotherFunction;
    });
  }
```
But it does not work. The data are changed but the row does not change, How to make it work?

**Comment by SittiphanSittisak** [comment]
Now, I change the widget to class like this below.
```
Widget tableForm({
  required List<PlutoRow> rows,
})
```
to
```
class TableForm {
  PlutoGridStateManager? stateManager;
  Wdiget showTable(){ ... }
  void createColumn({ required List<TableColObj> columnTitle }){ ... }
  void createRow({ required List<List<TableRowObject>> rowData }){ ... }
}
```
And I use the remove and append function in createRow() like this below.
```
try {
      stateManager!.removeRows(stateManager!.rows);
      rows = rowData
          .where((e) => e.length >= columnTitleLength)
          .map((e) => createPlutoRow(list: e))
          .toList();
      stateManager!.appendRows(rows);
    } catch (e) {
      rows = rowData
          .where((e) => e.length >= columnTitleLength)
          .map((e) => createPlutoRow(list: e))
          .toList();
    }
```
On the main page, I am using this class like this below.
```
TableForm tableForm = TableForm();

Future getDataFromApi() async {
    rowData = fetchAndFormatData;
    tableForm.createRow(rowData: rowData);
  }

@override
  void initState() {
    tableForm.createColumn(columnTitle: columnTitle);
    getDataFromApi();
    super.initState();
  }
```
This method can replace all rows(old data) with new rows(new data).
If you added something that can fix this issue better than my method. Please share it.

**Comment by kw2019ltd** [comment]
hi @SittiphanSittisak  how you add below Footer

![image](https://user-images.githubusercontent.com/47334522/163715385-3e8989c4-dca4-4485-a64f-3d3a62eec683.png)

**Comment by SittiphanSittisak** [comment]
This is custom with simple widget like Comtainer, DropdownButton, Text, IconButon. :)

**Comment by SittiphanSittisak** [comment]
> This is custom with simple widget like Comtainer, DropdownButton, Text, IconButon. :)



> hi @SittiphanSittisak how you add below Footer since the default one looks different
> 
> ![image](https://user-images.githubusercontent.com/47334522/163715385-3e8989c4-dca4-4485-a64f-3d3a62eec683.png)

This is custom with simple widget like Comtainer, DropdownButton, Text, IconButon. :)
