### ISSUE TITLE
The table did not show if not refresh the page. 

### ISSUE THREAD

**Issue by SittiphanSittisak** [bosskmk/pluto_grid#408]
My table only displays when refreshing the page. The table did not show if not refresh the page.  You can see the issue in the video below. I try to open this page by using the route name or typing in the search bar but it does not work.
How to fix it?
https://user-images.githubusercontent.com/59549741/162574429-b886b1a2-0cd0-4f04-999a-77f9472f9934.mp4

**Comment by SittiphanSittisak** [comment]
I don't know. Is my issue related to https://stackoverflow.com/questions/65807514/flutter-widget-is-not-showing-its-showing-in-hot-reload ?
But I try to use state management and It's working!
I can use setState to reset the UI.
However, if you have some ways to fix that, please give me.

**Comment by bosskmk** [comment]
A minimal sample code is required to verify your problem.
I would appreciate it if you could register a new issue by attaching a sample code to check the issue.
