### ISSUE TITLE
cell no border

### ISSUE THREAD

**Issue by JDongKhan** [bosskmk/pluto_grid#409]
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.4 at /Users/jd/fvm/versions/2.10.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

https://user-images.githubusercontent.com/4929805/162687437-00b36838-4ba5-4806-8adb-ee6eee030c86.mov

**Comment by bosskmk** [comment]
It used to happen on the web.

https://docs.flutter.dev/development/platform-integration/web/renderers

There are 2 web rendering modes, does it happen in both?

It seems to be a Flutter issue, but I'm not sure.
