### ISSUE TITLE
Differentiating between column titles for filtering and hiding columns when using column groups

### ISSUE THREAD

**Issue by manhaddo** [bosskmk/pluto_grid#411]
I am using column groups to group fields together so that the individual column titles do not have to be long; eg. Instead of having two columns with titles 'Weather Temperature' and 'Weather Condition' I have a column group with a title of 'Weather' and two columns with a title of 'Temperature' and 'Condition'.

The issue I'm having is when I have columns with the same title, but are in different groups and there is no way to differentiate them in the Set Columns and Set Filters dialog. Eg. I have another column group with a title of 'Water' and two columns with a title of 'Temperature' and 'Condition'. When I go into the Set Filters Dialog, I am unable to differentiate between the columns and which groups they belong to.

Is it possible to have an optional parameter for PlutoColumn where I could set the display title when viewed in the Set Filter and Set Column dialog to something else? eg. PlutoColumn title is 'Temperature' and columnFilterTitle is 'Weather Temperature'.

Thank you, and I appreciate the work you have put into this package. It's really great!

**Comment by bosskmk** [comment]
I will fix your problem in the next version.

**Comment by bosskmk** [comment]
@manhaddo 
Deployed PlutoGrid version 3.0.0.
It has been modified to display the group name when a group is set in the column filter pop-up and column setting pop-up.
Please let me know if you run into any issues using the above version.
thank you.

**Comment by bosskmk** [comment]
PlutoGrid version 3.0.0 has been canceled.
There is a problem when deploying to pub.dev .
It does not recognize the distribution for Flutter 3.0.0 yet, so it recognizes it as a problematic package.

Until pub.dev recognizes Flutter 3.0.0, please use the pre version below.
https://pub.dev/packages/pluto_grid/versions/3.0.0-0.pre

**Comment by manhaddo** [comment]
Thank you very much. I've had a look on 3.0.0-0.pre and it looks good.
