### ISSUE TITLE
How can i customize activatedBorder?

### ISSUE THREAD

**Issue by Zed-Null** [bosskmk/pluto_grid#412]
Can i set the width and cornerRadius for activatedBorder?

**Comment by bosskmk** [comment]
Currently it is not possible to set the cornerRadius of a row.
It doesn't seem right to use cornerRadius in the current UI.
Can I know your UI? Can you provide your UI so I can see why you need a cornerRadius ?

**Comment by Zed-Null** [comment]
I needed to create a table without borders. Also, when I clicked on a cell, a boarder would appear, and I wanted that stroke to have rounded corners. I was able to achieve this effect, but I had to set the roundings inside the TextCellState in the build method.
Below is the result:
<img width="443" alt="Снимок экрана 2022-05-10 в 23 01 11" src="https://user-images.githubusercontent.com/47459550/167713094-9f135e09-8916-4c81-817e-81d8b61b5fd4.png">

**Comment by bosskmk** [comment]
have you solved it yourself?
Good news for me.
Your UI is interesting.
Thanks for posting the answer.

**Comment by Zed-Null** [comment]
Yes, I have solved this problem for myself. I also think it's worth leaving my solution here:

The **_CellContainer** class, which is located in _src/ui/pluto_base_cell.dart_ file has a **_boxDecoration()** method that returns the appearance of the cell. 
You can modify this method to get curled corners.

For example, I changed the method as follows:
```
BoxDecoration _boxDecoration() {
    return BoxDecoration(
      color: _currentCellColor(),
      borderRadius: const BorderRadius.all(Radius.circular(6)),
      border: Border.all(
        color: hasFocus
            ? configuration.activatedBorderColor
            : configuration.inactivatedBorderColor,
        width: 2,
      ),
    );
  }
```
