### ISSUE TITLE
add support for DropDown with valid value and checkBox option not only TextField with "Contains" option

### ISSUE THREAD

**Issue by kw2019ltd** [bosskmk/pluto_grid#414]
hi

can we have something like below picture where instead of TextField "Contains"  i can set dropdown will valid values, or checkBox in case its true/false value

![image](https://user-images.githubusercontent.com/47334522/163715197-305c004c-1f12-4eb8-9ceb-7c1dfe6c8390.png)

**Comment by bosskmk** [comment]
This is a good feature suggestion.
