### ISSUE TITLE
Include a widget in a cell 

### ISSUE THREAD

**Issue by shellking4** [bosskmk/pluto_grid#418]
How can I include a widget in a cell ? For example, an edit iconButton in a cell and go to edit page on tap of this button. I can't find a way to do it

**Comment by bosskmk** [comment]
It seems to refer to the function of the link below.

https://weblaze.dev/pluto_grid/build/web/#feature/cell-renderer

**Comment by shellking4** [comment]
Thank you very much. Really helpful
