### ISSUE TITLE
Add parameter to PlutoRow to block edits

### ISSUE THREAD

**Issue by kevansaba-operium** [bosskmk/pluto_grid#422]
Hello @bosskmk ,

Hope you are doing well! thanks for this awesome package!

I am running into a use case where I need to block edits on certain rows. Do you think we could eventually have a `enableEditingMode` bool on the `PlutoRow` class? 

thanks,
K

**Comment by bosskmk** [comment]
You can restrict editing of rows in certain states.
However, it is limited to cells in a specific row.
Could you please refer to the link below?
If you add a row with add rows , you can edit the Id cell, but you cannot edit the Id cell for a row that has already been added.
Please try this and if it doesn't work, please comment again.

https://weblaze.dev/pluto_grid/build/web/#add-and-remove-column-row
