### ISSUE TITLE
Column Filter popup is out of place

### ISSUE THREAD

**Issue by JuanesAdriano** [bosskmk/pluto_grid#423]
Hello, i am having some trouble with the positioning of the column filter Popup.

I have a layout with a Router to display the contents,  this router is the RouterOutlet from the package "Modular" [https://github.com/Flutterando/modular](https://github.com/Flutterando/modular)
The routerOutlet renders the content wigets inside itself, according to the url.

If the rendered content has a PlutoGrid widget, the filter popup displays out of place, like if it was getting "pushed" by the menu in the left of the app and the navbar on the top.

I made some tests, puttting the same content directly on the 'main' container without using the RouterOutlet, and it works fine. I suspect that the popup positioning is being calculated by the total screen size and not the available space, causing the bug when rendered INSIDE the RouterOutlet.

here's some examples:
Rendering the Plutogrid inside the RouterOutlet results in misplacing of the popup:
![image](https://user-images.githubusercontent.com/11681859/167155840-7c250664-3961-4ef7-90b9-1b740969bc15.png)

The placing is alright putting the PlutoGrid directly in the content container:
![image](https://user-images.githubusercontent.com/11681859/167156589-8303977b-2d4b-434a-be22-b7dbfc45049f.png)

i've made this simplified example to show the issue:
[https://github.com/JuanesAdriano/plutogrid_sample](https://github.com/JuanesAdriano/plutogrid_sample)

**Comment by bosskmk** [comment]
Let me check the problem.
Thanks for reporting the problem.

**Comment by stingrayx** [comment]
I'm experiencing exactly the same issue (by using go_router). Any update on this issue?

Thanks a lot.

**Comment by bosskmk** [comment]
Fixed in PlutoGrid version 5.0.2.

I only tested it with flutter_modular , but go_router would have solved the same.
