### ISSUE TITLE
Add Excel Export

### ISSUE THREAD

**Issue by mehdigharibi** [bosskmk/pluto_grid#424]

**Comment by henry2man** [comment]
Please take a look at #121

**Comment by bosskmk** [comment]
Deployed in version 2.10.0.
Contributed by @henry2man.

**Comment by henry2man** [comment]
@mehdigharibi  Recently deployed feature will let you export a CSV file. If you change the extension to `.xls` Excel will try to open it. Even if it is a flat file, it will recognize and import it as if it were a complex Excel file.

If you're satisfied with this feature, we can consider this issue as closed.

**Comment by henry2man** [comment]
The brand new `pluto_grid_export` package incudes support for excel-like sheet, including UTF-8 (non ascii). You'll need to use this snippet:

```dart
import 'package:pluto_grid_export/pluto_grid_export.dart' as pgexport;
....
var exportCSV = pgexport.PlutoGridExport.exportCSV(state,
        fieldDelimiter: ";",
        textDelimiter: "",
        textEndDelimiter: "",
        eol: "\r\n");
    //FIXES https://github.com/bosskmk/pluto_grid/issues/428
    var bytes = const Utf8Encoder().convert(
        // FIX Add starting \u{FEFF} / 0xEF, 0xBB, 0xBF
        // This allows open the file in Excel with proper character interpretation
        // See https://stackoverflow.com/a/155176
        '\u{FEFF}$exportCSV');
```
