### ISSUE TITLE
LateInitializationError: Field '_column' has not been initialized.

### ISSUE THREAD

**Issue by huongtran84** [bosskmk/pluto_grid#437]
I used PlutoKeyManagerEvent for handle key when user f3 pressed .web show dialog for user choose an item  and then Pluto grid added a new row that then change value some cells.dialog dismissed .user edit another cells.bugs raised

`Another exception was thrown: LateInitializationError: Field '_column' has not been initialized.
[ERROR] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/pluto_grid/src/model/pluto_cell.dart 49:20                           get [_column]
packages/pluto_grid/src/model/pluto_cell.dart 47:29                           get column
packages/pluto_grid/src/manager/state/editing_state.dart 179:31               changeCellValue
packages/pluto_grid/src/ui/cells/text_cell.dart 138:25                        [_changeValue]
packages/pluto_grid/src/ui/cells/text_cell.dart 59:9                          <fn>`

**Comment by bosskmk** [comment]
@huongtran84 
Can you provide a minimal example code that throws the error?

I would appreciate it if you could give me the steps on how to get the error to check your problem.
