### ISSUE TITLE
List data filtering and refresh Problem

### ISSUE THREAD

**Issue by Sindyue** [bosskmk/pluto_grid#438]
After filtering the list data, refresh and load the data again. How to make the previous filtering conditions effective? Thanks！

**Comment by bosskmk** [comment]
@Sindyue 

Want to save the filtering state and reload it?

Please refer to the example code below.

```dart
import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

import '../dummy_data/development.dart';

class EmptyScreen extends StatefulWidget {
  static const routeName = 'empty';

  const EmptyScreen({Key? key}) : super(key: key);

  @override
  _EmptyScreenState createState() => _EmptyScreenState();
}

class _EmptyScreenState extends State<EmptyScreen> {
  late List<PlutoColumn> columns;

  late List<PlutoRow> rows;

  late PlutoGridStateManager stateManager;

  final List<PlutoRow> filterRows = [];

  @override
  void initState() {
    super.initState();

    columns = [
      PlutoColumn(
        title: 'column1',
        field: 'column1',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column2',
        field: 'column2',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column3',
        field: 'column3',
        type: PlutoColumnType.text(),
      ),
    ];

    rows = DummyData.rowsByColumns(length: 10, columns: columns);
  }

  void handleSaveFilter() {
    filterRows.clear();

    final List<PlutoRow> filters = stateManager.filterRows
        .map(
          (e) => PlutoRow(cells: {
            FilterHelper.filterFieldColumn: PlutoCell(
              value: e.cells[FilterHelper.filterFieldColumn]!.value,
            ),
            FilterHelper.filterFieldType: PlutoCell(
              value: e.cells[FilterHelper.filterFieldType]!.value,
            ),
            FilterHelper.filterFieldValue: PlutoCell(
              value: e.cells[FilterHelper.filterFieldValue]!.value,
            ),
          }),
        )
        .toList();

    filterRows.addAll(filters);
  }

  void handleLoadFilter() {
    stateManager.gridFocusNode?.unfocus();
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      stateManager.setFilterWithFilterRows(filterRows);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        padding: const EdgeInsets.all(15),
        child: PlutoGrid(
          columns: columns,
          rows: rows,
          onChanged: (PlutoGridOnChangedEvent event) {
            print(event);
          },
          onLoaded: (PlutoGridOnLoadedEvent event) {
            stateManager = event.stateManager;
            stateManager.setShowColumnFilter(true);
          },
          configuration: const PlutoGridConfiguration(),
          createHeader: (_) {
            return Row(
              children: [
                TextButton(
                  onPressed: handleSaveFilter,
                  child: const Text('save filter'),
                ),
                TextButton(
                  onPressed: handleLoadFilter,
                  child: const Text('load filter'),
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}
```

**Comment by Sindyue** [comment]
> After filtering the list data, refresh and load the data again. How to make the previous filtering conditions effective? Thanks！

Thanks，Sincerely！

**Comment by rickmeulendijks** [comment]
> @Sindyue
> 
> Want to save the filtering state and reload it?
> 
> Please refer to the example code below.
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:pluto_grid/pluto_grid.dart';
> 
> import '../dummy_data/development.dart';
> 
> class EmptyScreen extends StatefulWidget {
>   static const routeName = 'empty';
> 
>   const EmptyScreen({Key? key}) : super(key: key);
> 
>   @override
>   _EmptyScreenState createState() => _EmptyScreenState();
> }
> 
> class _EmptyScreenState extends State<EmptyScreen> {
>   late List<PlutoColumn> columns;
> 
>   late List<PlutoRow> rows;
> 
>   late PlutoGridStateManager stateManager;
> 
>   final List<PlutoRow> filterRows = [];
> 
>   @override
>   void initState() {
>     super.initState();
> 
>     columns = [
>       PlutoColumn(
>         title: 'column1',
>         field: 'column1',
>         type: PlutoColumnType.text(),
>       ),
>       PlutoColumn(
>         title: 'column2',
>         field: 'column2',
>         type: PlutoColumnType.text(),
>       ),
>       PlutoColumn(
>         title: 'column3',
>         field: 'column3',
>         type: PlutoColumnType.text(),
>       ),
>     ];
> 
>     rows = DummyData.rowsByColumns(length: 10, columns: columns);
>   }
> 
>   void handleSaveFilter() {
>     filterRows.clear();
> 
>     final List<PlutoRow> filters = stateManager.filterRows
>         .map(
>           (e) => PlutoRow(cells: {
>             FilterHelper.filterFieldColumn: PlutoCell(
>               value: e.cells[FilterHelper.filterFieldColumn]!.value,
>             ),
>             FilterHelper.filterFieldType: PlutoCell(
>               value: e.cells[FilterHelper.filterFieldType]!.value,
>             ),
>             FilterHelper.filterFieldValue: PlutoCell(
>               value: e.cells[FilterHelper.filterFieldValue]!.value,
>             ),
>           }),
>         )
>         .toList();
> 
>     filterRows.addAll(filters);
>   }
> 
>   void handleLoadFilter() {
>     stateManager.gridFocusNode?.unfocus();
>     WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
>       stateManager.setFilterWithFilterRows(filterRows);
>     });
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Container(
>         padding: const EdgeInsets.all(15),
>         child: PlutoGrid(
>           columns: columns,
>           rows: rows,
>           onChanged: (PlutoGridOnChangedEvent event) {
>             print(event);
>           },
>           onLoaded: (PlutoGridOnLoadedEvent event) {
>             stateManager = event.stateManager;
>             stateManager.setShowColumnFilter(true);
>           },
>           configuration: const PlutoGridConfiguration(),
>           createHeader: (_) {
>             return Row(
>               children: [
>                 TextButton(
>                   onPressed: handleSaveFilter,
>                   child: const Text('save filter'),
>                 ),
>                 TextButton(
>                   onPressed: handleLoadFilter,
>                   child: const Text('load filter'),
>                 ),
>               ],
>             );
>           },
>         ),
>       ),
>     );
>   }
> }
> ```

@bosskmk is there any way you can trigger "handleSaveFilter" without pressing a button? For example when some is filtering? I can't find a onFiltering event.

**Comment by bosskmk** [comment]
@rickmeulendijks 

There are currently no events for filtering settings. (There is an event while filtering is being entered by the user. PlutoGridChangeColumnFilterEvent)

I plan to add PlutoLazyPagination, PlutoInfinityScrollRows widgets in the next version. (Development is complete. Will be released after testing)

They both fetch data from the server side and enable pagination and infinite scrolling.

In this case, you can receive filtering and column sorting status as arguments in the callback function to get data from the server.

**Comment by rickmeulendijks** [comment]
Ok, thanks for the reply.
The options in the next version sounds like a solution.

Keep up the good work

**Comment by bosskmk** [comment]
@rickmeulendijks 
Released PlutoGrid 5.3.0

Refer to below link.
https://github.com/bosskmk/pluto_grid/issues/601

**Comment by rickmeulendijks** [comment]
Can you perhaps kick me in the good direction where to put the PlutoGridChangeColumnFilterEvent?

**Comment by bosskmk** [comment]
Below is example code that listens for filtering events or emits filtering events.

![pluto_grid_filtering_event](https://user-images.githubusercontent.com/5284141/197324562-83824c5d-5ee7-4514-ada9-becacf2e60ab.gif)

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

import '../dummy_data/development.dart';

class EmptyScreen extends StatefulWidget {
  static const routeName = 'empty';

  const EmptyScreen({Key? key}) : super(key: key);

  @override
  _EmptyScreenState createState() => _EmptyScreenState();
}

class _EmptyScreenState extends State<EmptyScreen> {
  late List<PlutoColumn> columns;

  late List<PlutoRow> rows;

  late PlutoGridStateManager stateManager;

  late final StreamSubscription<PlutoGridEvent> events;

  @override
  void initState() {
    super.initState();

    columns = [
      PlutoColumn(
        title: 'column1',
        field: 'column1',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column2',
        field: 'column2',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column3',
        field: 'column3',
        type: PlutoColumnType.text(),
      ),
    ];

    rows = DummyData.rowsByColumns(length: 10, columns: columns);
  }

  @override
  void dispose() {
    events.cancel();

    super.dispose();
  }

  void eventListener(PlutoGridEvent event) {
    if (event is PlutoGridChangeColumnFilterEvent) {
      // Column where the filtering event occurred
      print(event.column.field);
      // Filtering type
      print(event.filterType.title);
      // filter value
      print(event.filterValue);
    }
  }

  void _handlePubEventButton() {
     // If the filtering TextField has focus, the value changed through the event is
     // Temporary code to take the current focus as it may not change.
     // There are other ways, but for now simple.
    FocusScope.of(context).requestFocus(FocusNode());

     // Add event after focus is taken.
     // It doesn't matter if we just call addEvent except for addPostFrameCallback regardless of focus state.
     // However, if the filtering TextField has focus, the value may not be input.
     // Of course you can add it to your current filtering TextField's TextEditingController , but
     // In the example code, we did not do that, but made it simple.
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      stateManager.eventManager!.addEvent(
        PlutoGridChangeColumnFilterEvent(
          column: stateManager.refColumns.first,
          filterType: const PlutoFilterTypeContains(),
          filterValue: 'a',
        ),
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          padding: const EdgeInsets.all(15),
          child: PlutoGrid(
            columns: columns,
            rows: rows,
            onChanged: (PlutoGridOnChangedEvent event) {
              print(event);
            },
            onLoaded: (PlutoGridOnLoadedEvent event) {
              stateManager = event.stateManager;
              stateManager.setShowColumnFilter(true);
              events = stateManager.eventManager!.listener(eventListener);
            },
            createHeader: (e) => TextButton(
              onPressed: _handlePubEventButton,
              child: const Text('put event'),
            ),
            configuration: const PlutoGridConfiguration(),
          ),
        ),
      ),
    );
  }
}
```

**Comment by rickmeulendijks** [comment]
Awesome, thanks!!
