### ISSUE TITLE
update the single rowData

### ISSUE THREAD

**Issue by Sindyue** [bosskmk/pluto_grid#439]
Is there a method to refresh the single row data value method? reload all is Inefficient，thanks

**Comment by devahmedghanim** [comment]
I am tired of searching for the answer to this question
There must be a function inside the state
To update the table
And also a function inside the state row to update it

**Comment by Sindyue** [comment]
> I am tired of searching for the answer to this question There must be a function inside the state To update the table And also a function inside the state row to update it
Can you specify which method and interface it is？

**Comment by bosskmk** [comment]
@Sindyue 
Would you like to use the below method of stateManager ?

```dart
void insertRows(int rowIdx, List<PlutoRow> rows);

void removeRows(List<PlutoRow> rows);
```

**Comment by Sindyue** [comment]
> @Sindyue Would you like to use the below method of stateManager ?
> 
> ```dart
> void insertRows(int rowIdx, List<PlutoRow> rows);
> 
> void removeRows(List<PlutoRow> rows);
> ```
Thanks，Sincerely！
