### ISSUE TITLE
Pluto Grid issue

### ISSUE THREAD

**Issue by MOULNIA** [bosskmk/pluto_grid#442]
i tried to insert data into plutogrid their was a lot of data but after  filtering out the data their was just 100records so the output of API call was correct but its not displaying the data it says null value cant be implemented into null form and one more was string please can you help me with that for that issue i shifted to data table and its a hell a lot of work in that

**Comment by bosskmk** [comment]
@MOULNIA 
Can you provide a minimal example code for me to verify your problem?
