### ISSUE TITLE
Cells can't be changed by user but can be changed programmatically

### ISSUE THREAD

**Issue by hieugia3030** [bosskmk/pluto_grid#444]
I want a cell that acts like the title. 
For example, i have a grid with 3 columns(Area, Coefficent, Result) and 1 row. Like this picture: 
![example](https://user-images.githubusercontent.com/79356608/170453026-c09efd4c-cf58-4bef-8ba2-2ba3470d36fb.png)

What I want is:
  + User can't modify the cell in Result column
  + When user change the value of cells in Area or Coefficent column, the cell in Result column will automatically be changed according to the formula: area * coefficent / 100.

What I tried:
  + `readOnly: true,` this makes the cell can't be changed by the user but can't be changed programmaticcally also.
  + `enableEdittingMode: true,` this also has the same bad result.
  + Create a renderer that have GestureDetector or Listener: when users tap once, the cell is uneditable(this is what I want). However, when users tap it twice, the keyboard shows up and they can edit the cell(this is not what I want). 

I have struggled with this problem for 2 weeks! Does pluto_grid have some ways to deal with this ? Is there any way to solve my problem? Please let me know!

**Comment by bosskmk** [comment]
Check out the example.

```dart
import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

class EmptyScreen extends StatefulWidget {
  static const routeName = 'empty';

  const EmptyScreen({Key? key}) : super(key: key);

  @override
  _EmptyScreenState createState() => _EmptyScreenState();
}

class _EmptyScreenState extends State<EmptyScreen> {
  late List<PlutoColumn> columns;

  late List<PlutoRow> rows;

  late PlutoGridStateManager stateManager;

  @override
  void initState() {
    super.initState();

    columns = [
      PlutoColumn(
        title: 'Area',
        field: 'area',
        type: PlutoColumnType.number(),
      ),
      PlutoColumn(
        title: 'Coefficent',
        field: 'coefficent',
        type: PlutoColumnType.number(),
      ),
      PlutoColumn(
        title: 'Result',
        field: 'result',
        type: PlutoColumnType.number(),
        readOnly: true,
      ),
    ];

    rows = [
      PlutoRow(
        cells: {
          'area': PlutoCell(value: 100),
          'coefficent': PlutoCell(value: 70),
          'result': PlutoCell(value: 70),
        },
      ),
    ];
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        padding: const EdgeInsets.all(15),
        child: PlutoGrid(
          columns: columns,
          rows: rows,
          onChanged: (PlutoGridOnChangedEvent event) {
            stateManager.changeCellValue(
              event.row!.cells['result']!,
              event.row!.cells['area']!.value *
                  event.row!.cells['coefficent']!.value /
                  100,
              force: true,
              callOnChangedEvent: false,
            );
          },
          onLoaded: (PlutoGridOnLoadedEvent event) {
            stateManager = event.stateManager;
          },
          configuration: const PlutoGridConfiguration(),
        ),
      ),
    );
  }
}
```

**Comment by hieugia3030** [comment]
> @h3nr1ke Check out the example.
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:pluto_grid/pluto_grid.dart';
> 
> class EmptyScreen extends StatefulWidget {
>   static const routeName = 'empty';
> 
>   const EmptyScreen({Key? key}) : super(key: key);
> 
>   @override
>   _EmptyScreenState createState() => _EmptyScreenState();
> }
> 
> class _EmptyScreenState extends State<EmptyScreen> {
>   late List<PlutoColumn> columns;
> 
>   late List<PlutoRow> rows;
> 
>   late PlutoGridStateManager stateManager;
> 
>   @override
>   void initState() {
>     super.initState();
> 
>     columns = [
>       PlutoColumn(
>         title: 'Area',
>         field: 'area',
>         type: PlutoColumnType.number(),
>       ),
>       PlutoColumn(
>         title: 'Coefficent',
>         field: 'coefficent',
>         type: PlutoColumnType.number(),
>       ),
>       PlutoColumn(
>         title: 'Result',
>         field: 'result',
>         type: PlutoColumnType.number(),
>         readOnly: true,
>       ),
>     ];
> 
>     rows = [
>       PlutoRow(
>         cells: {
>           'area': PlutoCell(value: 100),
>           'coefficent': PlutoCell(value: 70),
>           'result': PlutoCell(value: 70),
>         },
>       ),
>     ];
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Container(
>         padding: const EdgeInsets.all(15),
>         child: PlutoGrid(
>           columns: columns,
>           rows: rows,
>           onChanged: (PlutoGridOnChangedEvent event) {
>             stateManager.changeCellValue(
>               event.row!.cells['result']!,
>               event.row!.cells['area']!.value *
>                   event.row!.cells['coefficent']!.value /
>                   100,
>               force: true,
>               callOnChangedEvent: false,
>             );
>           },
>           onLoaded: (PlutoGridOnLoadedEvent event) {
>             stateManager = event.stateManager;
>           },
>           configuration: const PlutoGridConfiguration(),
>         ),
>       ),
>     );
>   }
> }
> ```

Worked like a charm! Thank you ;)
