### ISSUE TITLE
how i can disable next row when i change data from row

### ISSUE THREAD

**Issue by amasahara** [bosskmk/pluto_grid#45]
after change value from first row, position will go to next when i press enter or after i choose value from selected box, so i can not update value to another column at first row, it will change value to next row. May i disable next rows on change or any solution for my error.

**Comment by bosskmk** [comment]
I will add that feature so that users can turn it on/off in the next change.

**Comment by amasahara** [comment]
hope i will see it in next update, i don't want to reload all table data after change 1 cell value. it not good idea

**Comment by bosskmk** [comment]
Check out version 0.1.19.

Added two options. Start the grid by changing the options in the configuration.

```dart
body: PlutoGrid(
  columns: columns,
  rows: rows,
  onChanged: (PlutoOnChangedEvent event) {
    print(event);
  },
  configuration: PlutoConfiguration(
    enableMoveDownAfterSelecting: false,
    enterKeyAction: PlutoEnterKeyAction.ToggleEditing,
  ),
),
```

**Comment by amasahara** [comment]
thank you very much, it very helpful for me
