### ISSUE TITLE
v3.1.1 web PlutoColumn: type: PlutoColumnType.date() does not show calendar if value is empty

### ISSUE THREAD

**Issue by Taron133** [bosskmk/pluto_grid#450]
Web version. Flutter version 3.0.1
If value is empty!
Calendar does not show after click on icon in column.
```
PlutoColumn(
        title: 'name',
        field: 'name',
        type: PlutoColumnType.date(),
        enableEditingMode: true,
      ),
```

**Comment by bosskmk** [comment]
@Taron133 
PlutoGrid version 3.1.2 has been released, in which the error has been corrected.
Thanks for your bug report.
