### ISSUE TITLE
How do I can the row index that was clicked.

### ISSUE THREAD

**Issue by robertjones1** [bosskmk/pluto_grid#456]

**Comment by bosskmk** [comment]
@robertjones1 

* https://weblaze.dev/pluto_grid/build/web/#feature/listing-mode
  PlutoGrid example for row selection.
  This is row selection only.
  Editing is possible programmatically using the PlutoGridStateManager .
  https://github.com/bosskmk/pluto_grid/wiki/pluto-state-manager-for-english


* https://github.com/bosskmk/pluto_grid/blob/master/lib/src/pluto_grid.dart#L43
  It listens for double-tap events. (instead of tap event)
  Editing is possible.

**Comment by robertjones1** [comment]
I think you for the information but still do not see a way to find the row index of the the cell or row clicked.

**Comment by bosskmk** [comment]
@robertjones1 

oh Now that I see, rowIdx is not returning.
sorry. This should be added.
I'll try to make sure it can be deployed in the next version.

**Comment by robertjones1** [comment]
Thanks.  You know when that could be?

**Comment by bosskmk** [comment]
Until then, try the code below.

```dart
stateManager.rows.indexOf(row);
```

**Comment by bosskmk** [comment]
I am preparing others for the next version as well.
It will be distributed within 1-2 weeks.

**Comment by robertjones1** [comment]
Undefined name 'row'.
Try correcting the name to one that is defined, or defining the name.

**Comment by bosskmk** [comment]
```dart
  onRowSecondaryTap: (e) {
    stateManager.rows.indexOf(e.row!);
  },
```

**Comment by robertjones1** [comment]
Thanks, that worked.

Also a suggestion would be on PlutoGridSelectingMode.row. So one can also single select rows besides Click hold and drag.  If this were implemented my boss would probably use Pluto on all screens with our new app.

**Comment by bosskmk** [comment]
@robertjones1 

Controll + Click on PlutoGridSelectingMode.row is a single row selection.

**Comment by robertjones1** [comment]
Yes Control click does work.  Our current software does not require a ctrl click to select multiple rows.  On a tablets and phones they don't have a ctrl to press and select different rows.

**Comment by bosskmk** [comment]
I will consider this for the next version.

**Comment by bosskmk** [comment]
@robertjones1 
How about considering a checkbox for row selection UX?
https://weblaze.dev/pluto_grid/build/web/#feature/row-with-checkbox

**Comment by robertjones1** [comment]
I am testing with checkboxes now which seems to work but still testing.  I notice the color difference between rows when using checkboxes and just row selection though.  Boss likes it better without the checkboxes and says it looks cleaner without them. We are trying to keep the data grid as close to what our customers are use to now.  The only difference now at this time is the multiple selection of rows.

**Comment by robertjones1** [comment]
We have to views the customer can switch between, a card view and datagrid view.  I need to keep track of the index's selected so the two keep in sync when switching between them.  They can multi select in the card view so need the same capabilities in the datagrid view.

**Comment by robertjones1** [comment]
As of now, no other datagrid controls in flutter have the capability of click hold and select multiple.  Yours does, as does in the python controls we are currently using.  We currently are in a python environment and switching to flutter. So combining the click, hold and drag to select and the single click to select multiple would be great.

**Comment by robertjones1** [comment]
@bosskmk Is there a way to get all selected row indexes?

**Comment by Amari-Mecheri** [comment]
hi,

Is it possible to be notified when the current cell or row changes?

**Comment by bosskmk** [comment]
@Amari-Mecheri 
onSelected only works when you set the mode property of the PlutoGrid constructor to PlutoGridMode.select or PlutoGridMode.selectWithOneTap .

@robertjones1 
You can get selected rows returned with stateManager.currentSelectingRows . You can get the index of each row with stateManager.refRows.indexOf .

**Comment by Amari-Mecheri** [comment]
@bosskmk Ok Thank you. Your datagrid control is probably the best available for flutter web.

**Comment by robertjones1** [comment]
Here is an example I am looking for.  I setup a listener for this to work.  Then only thing I did not complete is keeping the rows highlighted. Still working on that code. Then will can hide the checkboxes if client does not wish to see them. 

https://user-images.githubusercontent.com/95442926/172254286-cf6f61fd-b3ae-494f-8efa-d861b060815d.mp4

**Comment by bosskmk** [comment]
@robertjones1 
cool.
go for it
