### ISSUE TITLE
after moving from ver 3.1.2 to pluto_grid: ^4.0.0  table display is slow/stuck for a bit

### ISSUE THREAD

**Issue by kw2019ltd** [bosskmk/pluto_grid#468]
hi,

iam using regular PlutoGrid with static data (120 rows in total) with 4 pages. (production mode)

with verison 3.1.2 UI of the grid was smooth.

after moving to v4.0.0 the grid UI is laggy at the start .

could be related to "Rendering speed improvements."..

**Comment by bosskmk** [comment]
@kw2019ltd 
Do you have some minimal code to reproduce the problem?

Please try the link below.
https://weblaze.dev/pluto_grid/build/web/#feature/row-pagination

The demo above is a web version demo built in release mode.
Create 10 rows and 5000 rows and create a grid.
The page unit is 100.

Is the above link too slow?

And try to debug profile your code.
Perhaps your code has a CPU high task that freezes the rendering before the grid starts.

**Comment by bosskmk** [comment]
The link below is when I run 1,000 columns and 10,000 rows in profile mode on the Android emulator.
There doesn't seem to be any major performance issues.
Please provide me sample code so I can reproduce your problem so I can check it out.

https://github.com/bosskmk/pluto_grid/issues/446#issuecomment-1152772321
