### ISSUE TITLE
Multiple row items have same name and Id 

### ISSUE THREAD

**Issue by AL-YAFEA-KHALED** [bosskmk/pluto_grid#474]
Hi sir, if I got multiple rows that got same name and Id but the rest of details are different. in the grid. Like.. 
1    khaled      $             200      deposit
1    khaled      RS          1000     rental
1    khaled      £              300     service

So I wanna them to be display in the grid like this... 
'
                       
![1655138410454](https://user-images.githubusercontent.com/52946012/173402833-c6eab3f0-1087-487e-b877-74facb88afaa.jpg)

I don't want to repeat same name and same id for multiple rows 
How to implement this in the grid

**Comment by bosskmk** [comment]
@AL-YAFEA-KHALED 
Merge cells or group rows are not yet supported.
I plan to add more in the future.

https://weblaze.dev/pluto_grid/build/web/#feature/cell-renderer
It looks like it could be implemented similarly through the example link above, but it requires adding a function.

**Comment by AL-YAFEA-KHALED** [comment]
Okay sir thanks for replying me and if you can add on more thing that can have summary for multiple rows by name and ID for example you have several rows and each three rows have the same name and Id I want to show summary for each group of rows

**Comment by bosskmk** [comment]
Released 5.2.0 for row grouping.

Web demo
https://weblaze.dev/pluto_grid/build/web/#feature/row-group
