### ISSUE TITLE
Sum of specific rows and sum of range rows 

### ISSUE THREAD

**Issue by AL-YAFEA-KHALED** [bosskmk/pluto_grid#479]
Hi sir, I would like to get sum but not for all rows. I want to get for specific rows only like using where condition. And the second thing I want to get sum of two ranges like the sum of price between two selected rows only
Thanks sir and I hope you can help me in this

**Comment by bosskmk** [comment]
https://github.com/bosskmk/pluto_grid/issues/455#issuecomment-1147022088

Please refer to the link above.
If you modify the `calculateSum` function in the link above to the desired purpose, you will get the desired result. 

`stateManager.currentSelectingRows` accesses the currently selected rows.

**Comment by aadi-github** [comment]
> Hi sir, I would like to get sum but not for all rows. I want to get for specific rows only like using where condition. And the second thing I want to get sum of two ranges like the sum of price between two selected rows only Thanks sir and I hope you can help me in this


@AL-YAFEA-KHALED I had also done exactly same thing like MIN-MAX-SUM-AVG of selected rows column.
you need to add listener to stateManager when selecting by holding any rows or Columns.
