### ISSUE TITLE
have problem is wrong position to select cell (help me pls)

### ISSUE THREAD

**Issue by fluk053** [bosskmk/pluto_grid#48]
i use pluto_grid with lib zoom_widget but I do zoom out and select is select cell wrong .I thing position have problem but i zoom in side my screen i select cell Correct.
and i have 1 question to ask  i want to do cell can't select can or can't because i do all cell one column in left side i want to do same title column and i want to do can't click  

in picture i select 2cell but error to select wrong
![image](https://user-images.githubusercontent.com/51117956/97255696-c613e480-1843-11eb-9a13-216212b265b0.png)

picture dishere i want to close to click to select left side to title
![image](https://user-images.githubusercontent.com/51117956/97255642-a5e42580-1843-11eb-83fe-e2a7dc8f8e7f.png)

**Comment by bosskmk** [comment]
You can fix this by adding a button in the app to toggle the selection state.

```dart
FlatButton(
  onPressed: () {
    _stateManager.setKeyPressed(grid.PlutoKeyPressed(
      shift: !_stateManager.keyPressed.shift,
    ));
  },
  child: Text('Toggle Selection.'),
),
```

1. Add a selection toggle button outside the grid.
2. Tap the selection toggle button to change to the selected state.
3. Select a cell.

**Comment by fluk053** [comment]
thank i can fix it and i have 1 qus. 
How can I not click cell in 1 column in left side?
![Inked97255696-c613e480-1843-11eb-9a13-216212b265b0_LI](https://user-images.githubusercontent.com/51117956/97771940-9848db80-1b74-11eb-8908-ae989c68d0ac.jpg)

**Comment by bosskmk** [comment]
I don't understand your question well.
Do you want to prevent clicking on the cells in the first column?

**Comment by fluk053** [comment]
I want to do cell TPS in Blue circle to cell title(first row) I want to make it a box that cannot be pressed.

**Comment by fluk053** [comment]
> You can fix this by adding a button in the app to toggle the selection state.
> 
> ```dart
> FlatButton(
>   onPressed: () {
>     _stateManager.setKeyPressed(grid.PlutoKeyPressed(
>       shift: !_stateManager.keyPressed.shift,
>     ));
>   },
>   child: Text('Toggle Selection.'),
> ),
> ```
> 
> 1. Add a selection toggle button outside the grid.
> 2. Tap the selection toggle button to change to the selected state.
> 3. Select a cell.

You Have to code to fix Click drag select cell?

**Comment by bosskmk** [comment]
Yes. It is difficult.
The Zoom widget changes the size of the widgets (Cell, Row, etc...) of the Grid.
I have to adjust these according to the zoom ratio, but it doesn't seem easy.

If the button is uncomfortable, I would recommend adding another action to make the button function.
