### ISSUE TITLE
In pluto_grid 4.0.1, data is getting hidden if entire table put into ScrollView, Appears and disappears when Column header is no longer visible.

### ISSUE THREAD

**Issue by aadi-github** [bosskmk/pluto_grid#481]
@bosskmk I had updated this plugin yesturday only and I got to see weird things. Like mentioned In Question, I had put pluto_grid in a scrollable Screen. This was not the issue recently but after updating to latest version, when you drag your screen upward and your Column Headers no longer visible then the data from table dissapears and re appears when dragged down. I'm not getting any logs also. Everything is working fine only this shown like glitch to me.

**Comment by bosskmk** [comment]
@aadi-github 
Version 4 has logic to render cells depending on whether the column is visible or not, which is the problem.
Changed the logic in the next version so the problem will no longer occur.
Please use version 3 until version 4.1 is released.

The next version work is about 80% complete.

**Comment by aadi-github** [comment]
> @aadi-github Version 4 has logic to render cells depending on whether the column is visible or not, which is the problem. Changed the logic in the next version so the problem will no longer occur. Please use version 3 until version 4.1 is released.
> 
> The next version work is about 80% complete.

I'm just keeping it open in case of someone else encounters this issue. Thanks for your hard work, Sir.

**Comment by bosskmk** [comment]
PlutoGrid 5.0.0 has been deployed.
There are other changes from version 4, so please check the ChangeLog.
https://pub.dev/packages/pluto_grid/changelog#500---2022-7-11

The demo page has also been updated.
https://weblaze.dev/pluto_grid/build/web/#/

**Comment by aadi-github** [comment]
> PlutoGrid 5.0.0 has been deployed. There are other changes from version 4, so please check the ChangeLog. https://pub.dev/packages/pluto_grid/changelog#500---2022-7-11
> 
> The demo page has also been updated. https://weblaze.dev/pluto_grid/build/web/#/

Thanks, this new update has resolved my issue. Now I'm closing this one now.
