### ISSUE TITLE
How to avoid selection of particular type of column and it's data whille dragging?

### ISSUE THREAD

**Issue by aadi-github** [bosskmk/pluto_grid#482]
@bosskmk As I have mentioned in #479 that I managed to create a function for myself for MIN-MAX-AVG-SUM. In this we can get value by using _plutoGridStateManager!.rows[element.rowIdx!].cells[element.field!]!.value and I have checked that we can also get type by using _plutoGridStateManager!.rows[element.rowIdx!].cells[element.field!]!.column.type.isText or isNumber etc.

My question is can we avoid the selection of a particular column or cell of a specific type. If the Value contains the name or something it should not be selectable.

I have avoided it's value by using --- 
if (double.tryParse(cellValue) != null) {
_dataSelectedList.add(double.parse(cellValue));
}  
as mentioned in the answer for #479 
but it's not the solution I want. I'm asking is there any API that can help. Please let me know.

**Comment by bosskmk** [comment]
@aadi-github 
There is no function to exclude select any specific cell or row.
It seems like it would be a useful feature.
I will consider adding.
thank you.

**Comment by aditya-nahak** [comment]
Hello @bosskmk, do we have any update on this?

**Comment by bosskmk** [comment]
@aditya-nahak 
This feature has not been added yet.

**Comment by aditya-nahak** [comment]
@bosskmk Thank you for such a great plugin, really appreciate the customization options provided.
Also, do you have this in the pipeline? When can we expect this feature?

**Comment by bosskmk** [comment]
@aditya-nahak 
Currently, irregular selection is possible for rows.
However, in the case of cells, they must be selected consecutively.

In the case of rows under these conditions, a function to prevent selection depending on the condition could be added soon.

However, in the case of cells, selection should be made irregularly, and the copy/paste behavior should be modified accordingly.
Therefore, it may take some time for cells.

I will try my best.
thank you

**Comment by aditya-nahak** [comment]
Okay thank you.

**Comment by aditya-nahak** [comment]
@bosskmk Is there a callback when there is a focus change for every cell, if not can we expect that anytime soon?

**Comment by bosskmk** [comment]
@aditya-nahak 

This is possible via `stateManager.addListener` .
However, listener callbacks can be called very often, so doing excessive work directly in the callback is problematic.
In this case, you have to use a debounce function or debounce of a stream, etc.

```dart
class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<PlutoColumn> columns = [
    PlutoColumn(title: 'Id', field: 'id', type: PlutoColumnType.text()),
    PlutoColumn(title: 'Name', field: 'name', type: PlutoColumnType.text()),
    PlutoColumn(title: 'Age', field: 'age', type: PlutoColumnType.number()),
  ];

  final List<PlutoRow> rows = [
    PlutoRow(cells: {
      'id': PlutoCell(value: '1'),
      'name': PlutoCell(value: 'Kim'),
      'age': PlutoCell(value: 20),
    }),
    PlutoRow(cells: {
      'id': PlutoCell(value: '2'),
      'name': PlutoCell(value: 'Lee'),
      'age': PlutoCell(value: 20),
    }),
  ];

  late PlutoGridStateManager stateManager;

  PlutoCell? _currentCell;

  @override
  void dispose() {
    stateManager.removeListener(_listener);
    super.dispose();
  }

  void _listener() {
    if (_currentCell == stateManager.currentCell) {
      return;
    }

    print('changed focused cell');
    print(stateManager.currentCell?.value);
    // do something.

    _currentCell = stateManager.currentCell;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          padding: const EdgeInsets.all(15),
          child: PlutoGrid(
            columns: columns,
            rows: rows,
            onChanged: (PlutoGridOnChangedEvent event) {
              print(event);
            },
            onLoaded: (PlutoGridOnLoadedEvent event) {
              stateManager = event.stateManager;
              stateManager.addListener(_listener);
            },
            configuration: const PlutoGridConfiguration(),
          ),
        ),
      ),
    );
  }
}
```
