### ISSUE TITLE
RTL issue  ( bug ? )

### ISSUE THREAD

**Issue by ZeraW** [bosskmk/pluto_grid#485]
hi
i was working with ver : 2.10.3 and everything was fine but when i upgrade to 4.0.1 i got this 
![image](https://user-images.githubusercontent.com/8078469/177500948-6a99b388-c747-4517-829f-f9ae26568a55.png)

the column order is reversed and column title is LTR and cells RTL
i tried adding Directionality RTL but nothing changed

**Comment by bosskmk** [comment]
@ZeraW 
RTL is not yet supported.
Version 4.1 with RTL support will be released soon.

**Comment by bosskmk** [comment]
PlutoGrid 5.0.0 has been deployed.
There are other changes from version 4, so please check the ChangeLog.
https://pub.dev/packages/pluto_grid/changelog#500---2022-7-11

The demo page has also been updated.
https://weblaze.dev/pluto_grid/build/web/#/
