### ISSUE TITLE
Adding data from outside the grid

### ISSUE THREAD

**Issue by jrheisler** [bosskmk/pluto_grid#5]
FocusScope works to give focus to a modal bottomsheet, but when data is changed, even though the Pluto grid is in a streambuilder, and the rows get rebuilt on each change of data, the grids state is being rebuilt, but not with new data.

**Comment by bosskmk** [comment]
Is it the case of using by providing List<PlutoRow> to StreamBuilder?
```dart
            child: StreamBuilder<List<PlutoRow>>(
              stream: ...,
              builder: (context, snapshot) {
                return PlutoGrid(
                  columns: columns,
                  rows: rows,
                  onChanged: (PlutoOnChangedEvent event) {
                    message(context, event.toString());
                  },
                  onLoaded: (PlutoOnLoadedEvent event) {
                    stateManager = event.stateManager;
                  },
                );
              }
            ),
```

If that is not the case, I would like to know what is the case.

**Comment by jrheisler** [comment]
It was exactly as you described, but I didn't realize the stateManger was the route to do this. Thank you!!!

**Comment by bosskmk** [comment]
It is not documented yet. It is not enough to develop it alone. I will work hard.

**Comment by jrheisler** [comment]
I just ran into your pluto grid the other day. I am a new flutter dev, but have been doing pascal for decades. Your grid is what a business grid should be. I probably can not help code, but I will gladly test, or help with documentation if you like. Great job so far!!!

**Comment by bosskmk** [comment]
Yes, anything is good.

I've just created a grid, but I haven't used it except for testing.

That's why problems, methods, documentation, and tests that occur during use are all good.

The Pluto series aims to develop a package for Admin or Cms.

There is also one called [PlutoMenuBar](https://github.com/bosskmk/pluto_menu_bar).

I plan to keep making these things.

**Comment by jrheisler** [comment]
I will go over it this weekend, and see what I can do to help. I see that you have implemented stateManager.appendRows(), if you added a removeRows(), the stream updates would be simple. 

You have really done so much with key handling and everything. Bravo!

**Comment by bosskmk** [comment]
Thanks, I will finish adding the test code now, and I will work on adding removeRows().

**Comment by jrheisler** [comment]
Fantastic, thank you so much! I think you're on to a real desktop/web grid for businesses everywhere!

**Comment by asadamatic** [comment]
@bosskmk Hi there, just tried this feature of adding new rows, but there is a problem.

I am implementing a feature of copying and pasting rows, and what happens is that the newly added rows have same cell key as the ones copied and any change, even the click of mouse is depicted on the rows that were originally copied.

I have thought of a work around, that is the I get the data from the rows that are copied and create new PlutoRow for the data. Would you also recommend this workaround or is there something better?

**Comment by bosskmk** [comment]
You can create a row that matches the current column information with getNewRow and getNewRows of stateManager.

Change the cell value of the created row to the desired value.

After the change, create a row to be added with insertRows, prependRows, appendRows, etc. of the stateManager.

Please let me know if you need more explanation or examples.

**Comment by asadamatic** [comment]
1. Created a method that takes values from a row and creates a desired object(List) using `statemanager.currentSelectingRows`
2. Mapped the list of object to `PlutoRow`
2. Then appended the plutoGrid using `statemanager.appendRows`
