### ISSUE TITLE
[Help] How to set height for the table based on the list

### ISSUE THREAD

**Issue by kunalprabhu21** [bosskmk/pluto_grid#501]
how to set height for the table based on the list

**Comment by bosskmk** [comment]
@kunalprabhu21 
There is no function to set the height of the table according to the rows.
You have to set the height manually, such as with `Sizedbox` or `Container`.

**Comment by kunalprabhu21** [comment]
Ok thanks for your reply..will figure something out

**Comment by aadi-github** [comment]
> Ok thanks for your reply..will figure something out

I think I have done the same thing so you may figure it out by below code snippets.

 SizedBox(
            height: AppConstants.customTableTopHeaderHeight /*Top Header*/ +
                AppConstants
                    .customBottomPaginationHeight /*Bottom Pagination Widget if data is within shown range*/ +
                (AppConstants
                        .customTableRowAndDividerHeight /*Row's height + divider*/ *
                    _getRowsPerPageCount()) +
                2 /*Extra Height to manage inside scroll*/,
            child: PlutoGrid(

In above I have created _getRowsPerPageCount() which returns the no of rows by calculating between currently selected row count [10, 50, 100, 500, 1000] and the rows you have loaded by state manager.

You can set rowsPerPageCount directly if you not using pagination. But if yes, then you also need to update your page size and Page also like below whenever you select any of these [10, 50, 100, 500, 1000]

  void _handleChangeHeight() {
    _plutoGridStateManager!.setPageSize(_getRowsPerPageCount());
    _plutoGridStateManager!.setPage(1);
    Future.delayed(const Duration(milliseconds: 300)).then((value) {
      if (mounted) {
        setState(() {});
      }
    });
  } 

Change according to your need, hope this will help you.
