### ISSUE TITLE
Make the header design more modern

### ISSUE THREAD

**Issue by maurobotta** [bosskmk/pluto_grid#51]
Hi @bosskmk 

Is possibile make the header design more modern ?

or make a easy custom code for to change it ?

**Comment by bosskmk** [comment]
Can you provide an image or link for reference?

**Comment by maurobotta** [comment]
In the header, can i remove the small image of menu (toleft-toright...) ?

Can i change color of all borders ?

May you add a real selection-mode with checkbox ? 

like this 
https://raw.githubusercontent.com/kechankrisna/flutter_responsive_table/master/example/sreenshot.png



I love your project, it is unique and it is very important for the whole Flutter Community 👍

**Comment by bosskmk** [comment]
In the header, can i remove the small image of menu (toleft-toright...) ?
> when you set some columns, you can remove the column menu icon.
> enableContextMenu: false, 
> [column-definition](https://github.com/bosskmk/pluto_grid/wiki/column-definition)
> (The column menu will add functions and change the look and feel.)

Can i change color of all borders ?
> When creating a Grid, try defining the Configuration property.
>[configuration](https://github.com/bosskmk/pluto_grid/wiki/Configuration)

May you add a real selection-mode with checkbox ?
> I'll add it so that the user can select/deselect the checkbox in the row selection mode.
