### ISSUE TITLE
How to change the Sort icon for PlutoGrid

### ISSUE THREAD

**Issue by nikhil-s-b** [bosskmk/pluto_grid#512]
Is there a way to change the sort icon for the PlutoGrid table ? 

There is a way to change the columnContextIcon, columnResizeIcon in the PlutoGridStyleConfig class. Is there is a similar config available to change the sort icon or change the sort icon colors?

**Comment by bosskmk** [comment]
@nikhil-s-b 
Nothing changes the Sort icon.
I will add it in the next version.
Thanks for the suggestion.

**Comment by nikhil-s-b** [comment]
> @nikhil-s-b Nothing changes the Sort icon. I will add it in the next version. Thanks for the suggestion.

@bosskmk Awesome!. That would be great addition. Thanks!

**Comment by bosskmk** [comment]
@nikhil-s-b 
Added columnAscendingIcon and columnDescendingIcon to PlutoGridConfiguration.style.
It can be checked in PlutoGrid version 5.0.5.

**Comment by nikhil-s-b** [comment]
> @nikhil-s-b Added `columnAscendingIcon` and `columnDescendingIcon` to `PlutoGridConfiguration.style`. It can be checked in PlutoGrid version 5.0.5.

@bosskmk . Thats great!. Thanks for adding it.!
