### ISSUE TITLE
[Help] Passing model after double click

### ISSUE THREAD

**Issue by fanatico2020** [bosskmk/pluto_grid#516]
Data
![image](https://user-images.githubusercontent.com/6627132/179806195-92ab525e-ec5e-4b64-932c-23cebd8b7688.png)

I created a model and passed it, it worked, but what I wanted was to double click and get the index of the model that I loaded in the grid, passing it as a whole, without creating a new one and referencing it as I did.

![image](https://user-images.githubusercontent.com/6627132/179805893-3e2cce1f-4e07-419a-a0d8-98b29f5a099f.png)

**Comment by bosskmk** [comment]
```dart
if (event.row == null) {
  return;
}

DisponibilidadeModel model = DisponibilidadeModel(
  qD: event.row!.cells['qD']!.value,
);
```

The model is just declared and not assigned a value.

**Comment by fanatico2020** [comment]
thanks
