### ISSUE TITLE
[Feature] Strict column width

### ISSUE THREAD

**Issue by urielexis64** [bosskmk/pluto_grid#519]
I am currently facing an issue with the rendered cells, because even though I set a specific width, the table scales its column width as it pleases. So, I think it would be nice to have a boolean property on column called "strictWidth" or something like that, that it works respecting the given width, regardless of the type of autofit the table has.

Thank you for reading.

**Comment by bosskmk** [comment]
I will consider adding this in the next version.
thank you

**Comment by ted-marozzi** [comment]
Hey @bosskmk, Min width is also not respected by column ``autoSizeMode: PlutoAutoSizeMode.scale,``` could that be fixed without the need for this boolean?

**Comment by ted-marozzi** [comment]
Alternatively autoSizeMode: PlutoAutoSizeMode.scale, could take into account column heading width to set its size, right now it just truncades the title

**Comment by bosskmk** [comment]
@ted-marozzi 
It should be further developed.
It currently refers to the default minWidth , not the setting in PlutoColumn.minWidth.

**Comment by yairsts** [comment]
until the next version you can try this:

      final columns = state!.columns;
      for (var element in columns) {
        state!.resizeColumn(element, 0.1);
        state!.resizeColumn(element, -0.1);
      }
      state!.notifyResizingListeners();
    }
