### ISSUE TITLE
Can you to add PgUp/PgDown... key support in grid ?

### ISSUE THREAD

**Issue by maurobotta** [bosskmk/pluto_grid#52]
Hi @bosskmk 

Can you to add any keys support in grid ?

No edit mode, of course.

**Home** : move on first column, no change table record
**End**     : move on last column, no change table record 

**Ctrl+Home** : move on first record , no change column
**Ctrl+End**     : move on last record , no change column

**PgUp**          : Scroll one full page top
**PgDown**     : Scroll one full page bottom

Thank you :)

**Comment by bosskmk** [comment]
I was going to do it. However, my keyboard's home and end keys were recognized differently by flutter, so I couldn't yet. I'll try again soon.

Thanks for the comments.

**Comment by bosskmk** [comment]
Check out version 0.1.21.

In addition to your opinion.
Added a combination of shift keys.

Thank you.
