### ISSUE TITLE
[Feature] -  break down column title with \n

### ISSUE THREAD

**Issue by kw2019ltd** [bosskmk/pluto_grid#521]
hi
its possible i want column text to break down in case iam giving it ' \n' name like 
'southern \n United State \n food'

so final column ui will be like 
southern 
United State
food

![image](https://user-images.githubusercontent.com/47334522/180400020-2904587c-1c24-4f50-84b2-5c0f42209dfd.png)

**Comment by stoneLee81** [comment]
try PlutoColumn.titleSpan

**Comment by kw2019ltd** [comment]
> try PlutoColumn.titleSpan

actually i tried that and only the first part was shown in above example only "southern" was visible

**Comment by ted-marozzi** [comment]
I am having the same issue

**Comment by stoneLee81** [comment]
in fact, it's widget, base on flutter widgets, you can achieve the style you want in any form, for instance, WidgetSpan(child:Column(children:[Text('hello'), Text('word')]))

**Comment by kw2019ltd** [comment]
> WidgetSpan(child:Column(children:[Text('hello'), Text('world')]))

woks fine thanks
