### ISSUE TITLE
How i can disable change value to id when i click change from value formatter

### ISSUE THREAD

**Issue by amasahara** [bosskmk/pluto_grid#53]
when i click in value formatter it will showing id of it but i don't want this, it very uncomfortable and make user fell not well

**Comment by bosskmk** [comment]
I think it's good to show the actual value while you can modify it via keystroke.
How about showing the formatter value as an exception only in select mode?

**Comment by amasahara** [comment]
because key is value that i will save into database, it not need for end user. End user only need string of this like category name, they don''t need id of it. So when it change make end user will harder than when know what they will change

**Comment by bosskmk** [comment]
If the formatter is set on the column,
In the case of read-only or select mode,
It is possible to change the formatter value to be displayed.

In other words, if the cell value cannot be modified, it can be modified to show the formatter value.

Is this the same as what you want?

**Comment by amasahara** [comment]
![Untitled](https://user-images.githubusercontent.com/5392719/97774109-cb489a80-1b87-11eb-963d-e43f7e81b5ae.png)

hope this image will be easy for you to see my problem, when i click to change value from selector as number 1, value will be change to an number but showing on selector is character of it.

**Comment by bosskmk** [comment]
Do you want to change the value of 1 in the image to "Tang 1" instead of "12"?

**Comment by amasahara** [comment]
yes, that is what i want because 12 is ID of "Tang 1"

**Comment by bosskmk** [comment]
PlutoColumn's applyFormatterInEditing property will allow you to do whatever you want.

**Comment by amasahara** [comment]
How can i do that, could you give me an example
