### ISSUE TITLE
[Help] language change

### ISSUE THREAD

**Issue by fanatico2020** [bosskmk/pluto_grid#530]
How do I change the filter popup options to Portuguese, Example En-Us = Setfilter  for  Pt-br = Adiciona filtro

**Comment by bosskmk** [comment]
https://pluto.weblaze.dev/configuration

```dart
configuration: const PlutoGridConfiguration(
  localeText: PlutoGridLocaleText(
    setFilter: 'Adiciona filtro',
  ),
),
```

**Comment by Macacoazul01** [comment]
@fanatico2020:
configuration: const PlutoGridConfiguration(
    localeText: PlutoGridLocaleText.brazilianPortuguese(),
 );

**Comment by fanatico2020** [comment]
thanks for the feedback.

**Comment by Macacoazul01** [comment]
@fanatico2020 n esquece de fechar a issue se resolveu o problema
