### ISSUE TITLE
Resizing Dual Grid after initialization

### ISSUE THREAD

**Issue by caymanmckee** [bosskmk/pluto_grid#536]
Hopefully this is possible, but how do you change the Grid A vs Grid B display ratio after it has already been built? I have tried accessing the display from the state, but it is not possible to reassign a value. Changing the value passed into the widget also does not work since it is final:

display: new PlutoDualGridDisplayRatio(ratio: _subGridData.isNotEmpty ? 0.5 : 0.75),

As a side note, before we upgraded to the latest patch (we were behind about 2 major versions) the above code worked to programatically change the ratio

**Comment by bosskmk** [comment]
There is no function. should be added.
