### ISSUE TITLE
[Bug] Inverted definition in PlutoGridSelectingMode

### ISSUE THREAD

**Issue by Lorenzobettega** [bosskmk/pluto_grid#538]
**I think that you inverted the definition in PlutoGridSelectingMode, you changed the PlutoGridSelectingMode.row with PlutoGridSelectingMode.cell**

The image of demo code:

![demo code](https://user-images.githubusercontent.com/84482292/181925035-cda95e72-de4e-48e5-a1b4-53d09c685201.png)

A sample image of "row" mode selection(but is working as cell) in the first grid:

![grid1](https://user-images.githubusercontent.com/84482292/181925046-026715f0-2158-48d7-9c38-062e5630c1fc.png)

A sample image of "cell" mode selection(but is working as row) in the second grid:

![grid 2](https://user-images.githubusercontent.com/84482292/181925051-d6f64287-85e3-440a-8228-3fa890444ff9.png)

The demo code if you want to dowload:
[pluto grid example.zip](https://github.com/bosskmk/pluto_grid/files/9226842/pluto.grid.example.zip)

**Comment by bosskmk** [comment]
@Lorenzobettega 
selectionMode is the mode for selecting cells or rows.
Tap and hold to move the mouse or select a cell or row with Shift + Arrow keys.

**Comment by Macacoazul01** [comment]
@bosskmk the problem is that PlutoGridSelectingMode.row selects cells and not rows

**Comment by Macacoazul01** [comment]
And PlutoGridSelectingMode.cell selects rows and not cells. Something is inverted on the code

**Comment by bosskmk** [comment]
@Macacoazul01 
There seems to be no problem with the operation.
selectingMode selects a cell or row.

![test](https://user-images.githubusercontent.com/5284141/182147665-512cf5a9-c12a-4dd6-9bc7-b2efd6957481.gif)

```dart
Widget build(BuildContext context) {
  return Scaffold(
    body: Container(
      padding: const EdgeInsets.all(15),
      child: PlutoDualGrid(
        gridPropsA: PlutoDualGridProps(
          columns: columns,
          rows: rows,
          onLoaded: (e) {
            e.stateManager.setSelectingMode(PlutoGridSelectingMode.row);
          },
        ),
        gridPropsB: PlutoDualGridProps(
          columns: columnsB,
          rows: rowsB,
          onLoaded: (e) {
            e.stateManager.setSelectingMode(PlutoGridSelectingMode.cell);
          },
        ),
      ),
    ),
  );
}
```

**Comment by Macacoazul01** [comment]
The operation is ok. It works on both cases

**Comment by Macacoazul01** [comment]
The problem is that `PlutoGridSelectingMode.row` selects only one cell and `PlutoGridSelectingMode.cell` selects the cell with the row. It should behave the inverse way

**Comment by bosskmk** [comment]
PlutoGridSelectingMode.row assigns focus color to one cell with no selection.
When selected, the focus color is assigned to the selected rows.

PlutoGridSelectingMode.cell assigns focus color to one row with no selection.
When a selection is made, the focus color is assigned to the selected cell.

As I attached above, grid A is row selection mode and grid B is cell selection mode. As with the attached GIF, there is no problem in operation.

**Comment by Macacoazul01** [comment]
but don't you think that this behavior vs names confuses the dev?
We know what both options do because we're using the package for a while (and it's an awesome package), but for a new user it's not intuitive

**Comment by bosskmk** [comment]
This is intended to visually differentiate the current row or cell between unselected and selected states, depending on the selection mode.

In case of row selection, the focus color is set only to the current cell so that the user knows that no row is selected.

For cell selection, set the focus color to the current row so the user knows that no cell is selected.

If you have any other comments, please suggest them.

**Comment by Lorenzobettega** [comment]
I undertood your point, but I agree with @Macacoazul01that this is confusing, I think that the solution is the option row only select rows, independent if you are with Shift or now, and cells the same logic. That is my suggestion,, thanks for listening, the question is solved.
