### ISSUE TITLE
[Bug] Null check operator used on a null value

### ISSUE THREAD

**Issue by kevinxxq** [bosskmk/pluto_grid#540]
Hi there,
I updated the package recently from pluto_grid: ^4.0.1 to pluto_grid: ^5.0.4 which has break change.
After that, there may be an error as below:
`---------- ERROR ----------
Null check operator used on a null value

------- STACK TRACE -------
#0      LayoutState.rightFrozenLeftOffset (package:pluto_grid/src/manager/state/layout_state.dart:318)
#1      PlutoGridState.updateState (package:pluto_grid/src/pluto_grid.dart:445)
#2      PlutoGridState.initState.<anonymous closure> (package:pluto_grid/src/pluto_grid.dart:381)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1091)
#5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997)
#6      _rootRun (dart:async/zone.dart:1426)
#7      _CustomZone.run (dart:async/zone.dart:1328)
#8      _CustomZone.runGuarded (dart:async/zone.dart:1236)
#9      _invoke (dart:ui/hooks.dart:151)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
#11     _drawFrame (dart:ui/hooks.dart:115)`

I can't reproduce it because the errors can't hit every time.

The code located to below code block during debugging:
![image](https://user-images.githubusercontent.com/55800697/182558203-600861fe-3a69-4f37-8419-c13704da0cbc.png)

### Execution Environment
**Flutter version**
flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [版本
    10.0.19044.1826], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022
    17.2.6)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.69.2)
[√] Connected device (3 available)

Thank you.

**Comment by bosskmk** [comment]
It's hard to pinpoint the problem just from what you posted.
Is the problem intermittent?
Can you be more specific about what happens under what circumstances?
It would be better if you attach sample code.

**Comment by kevinxxq** [comment]
Hi @bosskmk ,
Thank you for quick response.

Yes, it is very diffcicult to figure out the cause from current situation.

It is intermittent, e.g. the first time or second time to load a new page, but not sure.

Yes, I will try to collect a reproduceable sample, it is hard too, since it is on the top of heritation. I tried your demo code on my local machine, it works well, so it is from my layout.

I suspect it is a size constraint(may be the width) is tighten(! check) and is hitted(or get the width before its parent lay out) in the version after 4.0.1. From the record, maxWidth is null.

Now I have to rollback to 4.0.1 and I will check it by remove the layout outside plutogrid and come back to you.

Thank you.

**Comment by bosskmk** [comment]
Can you test after modifying the `/src/pluto_grid.dart` file as follows?
I didn't upload a separate repository because you can easily edit it.

```dart
  @override
  void initState() {
    _initStateManager();

    _initKeyManager();

    _initEventManager();

    _initOnLoadedEvent();

    _initSelectMode();

    _initHeaderFooter();

    _disposeList.add(() {
      _gridFocusNode.dispose();
    });

    // WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
    //   updateState();
    // });

    // Comment out the above line and edit it as follows
    WidgetsBinding.instance.endOfFrame.then((_) {
      updateState();
    });

    super.initState();
  }
```

**Comment by kevinxxq** [comment]
Hi @bosskmk 
I tried your fix code but no luck.

Anyway, please leave it here and wait for my reproduceable sample, now, it is too hard to debug or fix it.

Thank you.

**Comment by shunsen** [comment]
I had the same problem。。。

**Comment by shunsen** [comment]
I had the same problem。

**Comment by kevinxxq** [comment]
Hi @bosskmk ,
Thank you evaluating it and now I have a minimum example, hope you can reproduce it on your computer. The problem may be from the tab.

`import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PlutoGrid Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const TestPlutoGrid(),
    );
  }
}

class TestPlutoGrid extends StatefulWidget {
  const TestPlutoGrid({Key? key}) : super(key: key);

  @override
  State<TestPlutoGrid> createState() => _TestPlutoGridState();
}

class _TestPlutoGridState extends State<TestPlutoGrid> {
  final tabs = <String>[];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: DefaultTabController(
        length: tabs.length,
        initialIndex: 0,
        child: Builder(
          builder: (ctx) {
            var tabBar = TabBar(
              isScrollable: true,
              tabs: tabs
                  .map<Widget>(
                    (element) => Text(
                      element,
                    ),
                  )
                  .toList(),
            );

            var tabBarView = TabBarView(
              children: tabs
                  .map<Widget>(
                    (element) => const PlutoGrid(
                      columns: [],
                      rows: [],
                    ),
                  )
                  .toList(),
            );

            return Scaffold(
              appBar: tabBar,
              body: tabBarView,
            );
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () {
          setState(
            () {
              tabs.add("New");
            },
          );
        },
      ),
    );
  }
}
`

Thank you.

**Comment by kevinxxq** [comment]
Hi @bosskmk ,
Thank you evaluating it and now I have a minimum example, hope you can reproduce it on your computer. The problem may be from the tab.

Please use the file as below to reproduce it.
[main.zip](https://github.com/bosskmk/pluto_grid/files/9532154/main.zip)
Thank you.

**Comment by kevinxxq** [comment]
Hi @bosskmk ,
After I figure out the minimal example, a workarround may be helpful:
```
LayoutBuilder(
                      builder: (context, constraint) {
                        if (constraint.maxWidth == 0) {
                          return Container();
                        }
                        return const PlutoGrid(
                          columns: [],
                          rows: [],
                        );
                      },
                    ),
```

@shunsen You can have a try on this.

Thank you.

**Comment by henry2man** [comment]
@bosskmk This issue is still present so it should be reopened.

**Comment by bosskmk** [comment]
@henry2man 
I tried the above example codes, but no problem occurred.
Tested on the latest version.
Flutter 3.3.4
PlutoGrid 5.3.0
