### ISSUE TITLE
[Help] Save state of columns on change 

### ISSUE THREAD

**Issue by DobreRadu** [bosskmk/pluto_grid#548]
Hello! I would like to save the state of a table for example if columns were reordered or changed in size or hidden,etc.
Is there a way to save the configuration of a table or trigger onChanged of a column,like if resizing trigger name of column new_width:...
Thank you!

**Comment by bosskmk** [comment]
This feature is not yet available.

**Comment by DobreRadu** [comment]
I understand thank you!
