### ISSUE TITLE
Add special selector for current row

### ISSUE THREAD

**Issue by maurobotta** [bosskmk/pluto_grid#55]
Hi

@bosskmk 

May to add special selector for current row ?  and plus button 

and a Drag and Drop between records? (not the columns)

See QuickBooks (  best online software )

https://quickbooks.intuit.com/global/
![2020-11-02 - GRID_ADD](https://user-images.githubusercontent.com/4833470/97890184-86f6ff00-1d2d-11eb-94f4-709d1b45f099.png)

Mauro Botta

p.s.
I sent you a lot of coffees, now, I hope you don't get a headache

**Comment by bosskmk** [comment]
I visited the quickbooks site you linked to, and I signed up to see the real screen.
I knew what function you wanted.
It seems that other users will also need that feature.
You will see it in the next version.
Thank you for donation and use.

**Comment by maurobotta** [comment]
@bosskmk 
I'm trying the "1.0 pre", great job :)

I can to see checkbox and drag features, now.

When user start to drag ( a row or a column )  and move mouse, is not visibible where the field/column will a will go to fit after. 
May you add colored a row/column for make easier to understand how the move will end?


Mauro Botta

**Comment by bosskmk** [comment]
I'm going to add a visual effect to indicate where the row will be moved when moving.

There is currently no onDragUpdate callback for draggable widgets. If this is added to flutter I will work on it, or I will work on it the other way around.

And I will add a method to add a new row above or below the current row. Combining this with a cell renderer will give you the same function as the plus button you want.

Thank you.

**Comment by bosskmk** [comment]
Created a new issue. Indicating the location to be moved when dragging.
#63
