### ISSUE TITLE
[Help]  Tree Data Grid / Expandable rows 

### ISSUE THREAD

**Issue by tobzilla90** [bosskmk/pluto_grid#551]
[Question]
Does Pluto Grid provides an easy way to implement a Tree Grid which groups over a column and then makes the row expandable to see the single data rows which are grouped together? 

Like in MUI: https://mui.com/x/react-data-grid/tree-data/

Screenshot: 
![Screen Shot 2022-08-16 at 13 55 13](https://user-images.githubusercontent.com/23441397/184801095-d99dbd57-27d9-4b29-80ed-828ccae97fcb.png)

**Comment by bosskmk** [comment]
This feature is not yet available.

**Comment by bosskmk** [comment]
Released 5.2.0 for row grouping.

Web demo
https://weblaze.dev/pluto_grid/build/web/#feature/row-group
