### ISSUE TITLE
[Feature] Tooltip - show cell text on mouse hover

### ISSUE THREAD

**Issue by thegioiso** [bosskmk/pluto_grid#552]
I have a table with some column dont have enough width. So, i hope that we will have tooltip feature on cells and we can see text whenever hover mouse on it. I think _renderer_ parameter can do this, but i will have to change my table so much...
My table:
![image](https://user-images.githubusercontent.com/106056252/185315282-935dd3ee-ce11-40a0-9911-3fa22f523222.png)
Tooltip flutter:
https://api.flutter.dev/flutter/material/Tooltip-class.html
![image](https://user-images.githubusercontent.com/106056252/185316004-a1dcc0bc-a36a-481b-b1de-f4fbd48d93e6.png)
Its just a feature i suggest. Whatever, thank you all for your great work, i love this project very much ^^

**Comment by thegioiso** [comment]
Dear @bosskmk, please take a look at this feature. Just let me know if you need anything else. Thank you so much.

**Comment by bosskmk** [comment]
Thanks for your comments.
I will refer to it for the next version development.

**Comment by EduardoYamauchi** [comment]
We have some prevision for this feature. Or @bosskmk can you share some guidance to how implement this feature?
