### ISSUE TITLE
[Help] Unable to set value on hide column

### ISSUE THREAD

**Issue by fcsorig** [bosskmk/pluto_grid#553]
Hello,

Anyone can help how to set value for hidden column.

![image](https://user-images.githubusercontent.com/29624592/185388363-552922ef-cb97-4723-a7cb-1e574679e082.png)

Thanks.

**Comment by nilroe** [comment]
same error here

**Comment by rickdroio** [comment]
Dear @agustin-garcia, did you find any solution for this issue?
