### ISSUE TITLE
Data not shown on first page of the grid when use footer pagination

### ISSUE THREAD

**Issue by asenthilkumarr** [bosskmk/pluto_grid#555]
### Steps to reproduce the bug
First page shows an empty screen when use pagination footer

### Expected results
Suppose to show data on the first page

### Actual results
Shows data after clicking page number or typing anywhere on the grid

### Code sample
PlutoGrid(
                      columns: columns,
                      rows: rows,
                      onLoaded: (PlutoGridOnLoadedEvent event) {
                        stateManager = event.stateManager;

                        /// When the grid is finished loading, enable loading.
                        stateManager.setShowLoading(true);
                        event.stateManager.setShowColumnFilter(true);
                      },
                      onChanged: (PlutoGridOnChangedEvent event) {
                        print(event);
                      },
                      onSelected: (PlutoGridOnSelectedEvent event) {
                        if (event.row != null) {
                          openDetail(event.row);
                        }
                        //stateManager.prependNewRows();
                      },
                      mode: PlutoGridMode.select,
                      /*rowColorCallback: (rowColorContext) {
                        if (rowColorContext.rowIdx % 2 == 0) {
                          return secondaryColor;
                        }
                        return secondaryColor;
                      },*/
                      configuration: PlutoGridConfiguration(
                        style: const PlutoGridStyleConfig(
                            gridBackgroundColor: Colors.black12,
                            activatedColor: Colors.blueGrey,
                            oddRowColor: secondaryColor,
                            evenRowColor: secondaryColor,
                            iconColor: Colors.blue,
                            borderColor: Colors.white10,
                            columnFilterHeight: 36.0,
                        ),
                        columnSize: PlutoGridColumnSizeConfig(
                          autoSizeMode: PlutoAutoSizeMode.scale,
                          resizeMode: PlutoResizeMode.normal,
                          restoreAutoSizeAfterInsertColumn: true,
                          restoreAutoSizeAfterRemoveColumn: true,
                        ),
                        columnFilter: PlutoGridColumnFilterConfig(
                          filters: const [
                            ...FilterHelper.defaultFilters,
                            // custom filter
                            ClassYouImplemented(),
                          ],
                          resolveDefaultColumnFilter: (column, resolver) {
                            if (column.field.contains('text')) {
                              return resolver<PlutoFilterTypeContains>() as PlutoFilterType;
                            } else if (column.field == 'number') {
                              return resolver<PlutoFilterTypeGreaterThan>()
                              as PlutoFilterType;
                            } else if (column.field == 'date') {
                              return resolver<PlutoFilterTypeLessThan>() as PlutoFilterType;
                            } else if (column.field == 'select') {
                              return resolver<ClassYouImplemented>() as PlutoFilterType;
                            }

                            return resolver<PlutoFilterTypeContains>() as PlutoFilterType;
                          },
                        ),
                      ),
                      createFooter: (stateManager) {
                        stateManager.setPageSize(100, notify: false); // default 40
                        return PlutoPagination(stateManager);
                      },
                    )

### Execution Environment
**Flutter version**
Flutter version is 3.0.5

**PlutoGrid version**
PlutoGrid version is 5.0.4

**OS**
Windows 10

**Comment by bosskmk** [comment]
Set `rows` after the `PlutoGrid` is loaded?
`stateManager.setPage(1);` Try calling

**Comment by asenthilkumarr** [comment]
Thanks for the reply its working
