### ISSUE TITLE
[Help] Missing columnGroups after export

### ISSUE THREAD

**Issue by yingming25** [bosskmk/pluto_grid#559]
Hi @bosskmk ~
After export  to csv,xls,pdf missing columnGroups.

**Comment by yingming25** [comment]
@bosskmk Thanks again for build this package.
Have plan to fix this?

**Comment by yingming25** [comment]
@bosskmk 
Is relative below issue?
https://github.com/flutter/flutter/issues/21594

**Comment by bosskmk** [comment]
@yingming25 
A column group must be applied to the export.
It is still undeveloped.
I will work on an update someday.

**Comment by yingming25** [comment]
Thank you :)
