### ISSUE TITLE
Number column keyboard without decimal point (IOS)

### ISSUE THREAD

**Issue by bastaware** [bosskmk/pluto_grid#560]
### Steps to reproduce the bug
Edit a cell that contains number with decimals on IPhone

Try opening https://weblaze.dev/pluto_grid/build/web/#feature/number-type-column on IPhone or in emulator.

### Expected results
When soft keyboard opens on IOS it should contain decimal point button.

### Actual results
Only 0 - 9 available.

### Code sample
```dart
PlutoColumn(
          enableContextMenu: false,
          title: 'Price',
          field: 'price',
          formatter: (str) => f.formatAmount(str, 'DKK'),
          type: PlutoColumnType.number(negative: false, format: '#,###.########')),
```

### Execution Environment
**Flutter version**
Flutter version is 3.0.5

**PlutoGrid version**
PlutoGrid version is 5.0.4

**OS**
IOS 15.6.1

<img width="438" alt="Skærmbillede 2022-08-27 kl  16 15 51" src="https://user-images.githubusercontent.com/1000036/187034221-7ff214bf-efad-4a9f-899b-f8b52cd0c1ba.png">

**Comment by bosskmk** [comment]
Would you like to try modifying the `pubspec.yaml` file as shown below? Please let me know if the issue is resolved and I will proceed with the update.

```yaml
dependencies:
  pluto_grid:
    git:
      url: https://github.com/bosskmk/pluto_grid.git
      ref: feature/keyboard
```

**Comment by bastaware** [comment]
Thanks for the fast response @bosskmk 

It works - well almost. The decimal point appears on the keyboard, but it doesn't do anything.

The problem seems to be that I'm in Denmark i.e. using comma as decimal point. If I change region to US I get the keyboard with dot as decimal point - and it works.

It doesn't seem to be my code that filters the comma away?

Danish keyboard (not working):
![IMG_6559](https://user-images.githubusercontent.com/1000036/187541228-8c901a2b-943b-4ee7-ad2d-f7fb39e1f4f0.jpg)

US keyboard (working):
![IMG_6558](https://user-images.githubusercontent.com/1000036/187541310-dc2bd653-1243-45bc-bac0-6fc243dadfe6.jpg)

N.B. I'm getting the error below in the XCode console (IPhone 12Pro, IOS 15.6.1). But it also appears with US keyboard. So I don't think is causing any problems.

_Can't find keyplane that supports type 8 for keyboard iPhone-PortraitChoco-DecimalPad; using 27100_PortraitChoco_iPhone-Simple-Pad_Default_

**Comment by bosskmk** [comment]
@bastaware 
Currently, it is filtered to prevent entering commas.
Could it be modified to enter commas instead of commas depending on the locale?

**Comment by bastaware** [comment]
Yes, I believe the correct solution would be to allow `,` in the textfield according to locale.
 Another solution is to allow both `,` and `.` in the textfield a simply trust the keyboard.
 If that is troublesome the next best solution is that `.` is always inserted, even though `,` is pressed on the keyboard.

**Comment by bastaware** [comment]
I'm not sure I understand your question. But if you mean how the number is stored in a backend database, it is stored using dot `.` as decimal - comma `,` is only in the GUI.

**Comment by bosskmk** [comment]
@bastaware 
I understood well.
I understand google sheets more clearly with Danish language setting.
The update will refer to Google sheets and work with the language setting as Danish.
I'll let you know when there's an update here.

**Comment by bosskmk** [comment]
@bastaware 

The work has been pushed to the develop branch.
Can you test it after modifying it as below?
I'd appreciate it if you let me know the results.

```yaml
dependencies:
  pluto_grid:
    git:
      url: https://github.com/bosskmk/pluto_grid.git
      ref: feature/develop
```

**Comment by bastaware** [comment]
It still doesn't work in the IOS simulator. When i press `,` nothing happens?

**Comment by bosskmk** [comment]
@bastaware 
Doesn't it work even if I set the locale to Denmark?

`PlutoGrid.setDefaultLocale('da_DK');`

or

`Intl.defaultLocale = 'da_DK';`

**Comment by bosskmk** [comment]
![test](https://user-images.githubusercontent.com/5284141/188069910-a0387200-e6be-4842-beec-258b74bd8e54.gif)

I don't have a Mac, so I tested it on Windows and Android.

**Comment by bastaware** [comment]
I think the problem is that PlutoGrid DecimalTextInputFormatter can't handle comma being the decimal separator.

If I remove the inputformatter in PlutoNumberCellState, then the textfield allows comma.

`inputFormatters = [];`

But when I leave the field, the value is 0,00 - probably because the toNumber method doesn't know how to handle comma?

Without inputformatter:
![comma](https://user-images.githubusercontent.com/1000036/188331812-d179adeb-a627-48db-872a-bd28471cbc88.gif)

Internationalizing is a hornet's nest 😖

**Comment by bastaware** [comment]
By the way. My PlutoColumn format still uses US formatting. I believe that the usual way in Flutter. I.e. disregard locale when defining formats.

My definition:
`PlutoColumnType.number(negative: false, format: '#,###.########'))`

**Comment by bosskmk** [comment]
@bastaware 

Did you try adding the `develop` branch to your dependencies, correct?
The old `feature/keyboard` branch is out of date.

And the format of `PlutoColumn` follows `NumberFormat` format of Intl package.
https://api.flutter.dev/flutter/intl/NumberFormat-class.html

**Comment by bastaware** [comment]
🤦‍♂️ My bad. Didn't notice the difference in the path. So sorry.

I assume the url is ref: develop (not ref: feature/develop)

It appears to work! 😀

**Comment by Macacoazul01** [comment]
@bosskmk this will be a nice update for us Brazilians also!

**Comment by bosskmk** [comment]
@bastaware 
@Macacoazul01 
Deployed in PlutoGrid version 5.0.6.
