### ISSUE TITLE
[Help] Error: No named parameter with the name 'disabledForegroundColor'.

### ISSUE THREAD

**Issue by ecardone** [bosskmk/pluto_grid#570]
Hello all!!! first at all, I want to thank you for your time. 
I'm trying to use pluto_grid but I get this error.
Waiting for connection from debug service on Edge...
/d:/flutter/.pub-cache/hosted/pub.dartlang.org/pluto_grid-5.0.6/lib/src/plugin/pluto_pagination.dart:142:7: Error: No named parameter with the name 'disabledForegroundColor'.
      disabledForegroundColor: Colors.transparent,
      ^^^^^^^^^^^^^^^^^^^^^^^
/d:/flutter/packages/flutter/lib/src/material/text_button.dart:145:22: Context: Found this candidate, but the arguments don't match.
  static ButtonStyle styleFrom({
                     ^^^^^^^^^
Failed to compile application.

Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (8 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

Can you help me?
regards
Eduardo

**Comment by bosskmk** [comment]
@ecardone 
It will be solved by upgrading the flutter version to 3.3.

**Comment by ecardone** [comment]
Thanks you @bosskmk, it works perfect now!!

**Comment by Macacoazul01** [comment]
@bosskmk created a pull request to explain this error on the changelog
