### ISSUE TITLE
[Help] Cell display change when I click on it

### ISSUE THREAD

**Issue by LiveRock** [bosskmk/pluto_grid#573]
I have a table with list of rows
Say 2 columns
1 - A
2 - B
3 -C

when I click on 'B', the cell display changes to 'C'
When I click outside the table, it reverts to its correct value 'B'
I noticed it doesn't matter which ROW I click, it will update the display to the last row's value.
But when I click outside the table, it will revert to its original value.

What am I doing wrong here?

**Comment by bosskmk** [comment]
@LiveRock 
It's hard for me to understand the problem with what you said.
Can you attach a minimal sample code to understand the problem?
