### ISSUE TITLE
Adding custom header in export as pdf

### ISSUE THREAD

**Issue by AL-YAFEA-KHALED** [bosskmk/pluto_grid#574]
How to add images barcode and different details in exporting pdf. And another issue is that font is not supported by English and Arabic languages. How to have both en and Arabic

**Comment by bosskmk** [comment]
@AL-YAFEA-KHALED 
It seems that PlutoGridExports plugin should add image and behavior for Arabic.
Is there anything I need to know to test the behavior for Arabic fonts?
