### ISSUE TITLE
Reordering columns programmaticaly

### ISSUE THREAD

**Issue by FloRul** [bosskmk/pluto_grid#575]
Is this still relevant ? because recently I had a similar solution that was working to store the columns order and restore it on the onLoaded event. Right now on the 5.0.6 version I have this bug :
 ════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown while rebuilding dirty elements:
Null check operator used on a null value

The relevant error-causing widget was
PlutoGrid
lib\main.dart:65
When the exception was thrown, this was the stack
#0      ContainerRenderObjectMixin._debugUltimatePreviousSiblingOf
package:flutter/…/rendering/object.dart:3627
#1      ContainerRenderObjectMixin._insertIntoChildList
package:flutter/…/rendering/object.dart:3709
#2      ContainerRenderObjectMixin.move
package:flutter/…/rendering/object.dart:3822
#3      PlutoVisibilityLayoutRenderObjectElement.moveRenderObjectChild
package:pluto_grid/…/miscellaneous/pluto_visibility_layout.dart:344
#4      RenderObjectElement._updateSlot
package:flutter/…/widgets/framework.dart:6071
#5      Element.updateSlotForChild.visit
package:flutter/…/widgets/framework.dart:3701
#6      ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4931
#7      Element.updateSlotForChild.visit
package:flutter/…/widgets/framework.dart:3703
#8      ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4931
#9      Element.updateSlotForChild.visit
package:flutter/…/widgets/framework.dart:3703
#10     Element.updateSlotForChild
package:flutter/…/widgets/framework.dart:3706
#11     Element.updateChild
package:flutter/…/widgets/framework.dart:3549
#12     RenderObjectElement.updateChildren
package:flutter/…/widgets/framework.dart:5964
#13     PlutoVisibilityLayoutRenderObjectElement.performRebuild
package:pluto_grid/…/miscellaneous/pluto_visibility_layout.dart:233
#14     Element.rebuild
package:flutter/…/widgets/framework.dart:4604
#15     BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2667
#16     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:882
#17     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:378
#18     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
#19     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1104
#20     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
#21     _invoke (dart:ui/hooks.dart:148:13)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#23     _drawFrame (dart:ui/hooks.dart:115:31)
The element being rebuilt at the time was index 0 of 1: PlutoVisibilityLayout
    renderObject: RenderCustomMultiChildLayoutBox#ed68f relayoutBoundary=up16 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
════════════════════════════════════════════════════════════════════════════════
Here is the link to a minimal project to reproduce (desktop build). The exception is thrown when I try to scroll horizontally.
https://bitbucket.org/FloRul/pluto_test/src/master/

_Originally posted by @FloRul in https://github.com/bosskmk/pluto_grid/issues/138#issuecomment-1242046901_

**Comment by bosskmk** [comment]
@FloRul 

I completed the example below by referring to the example code in the link you attached.

* Do not create columns and rows in the build method. (If you create these in the build method, the unique keys of `PlutoColumn` and `PlutoRow` are changed for every build.)
* The `sort` method has been modified to execute several methods for applying column changes.

```dart
import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

import '../dummy_data/development.dart';

class EmptyScreen extends StatefulWidget {
  static const routeName = 'empty';

  const EmptyScreen({Key? key}) : super(key: key);

  @override
  _EmptyScreenState createState() => _EmptyScreenState();
}

class _EmptyScreenState extends State<EmptyScreen> {
  late List<PlutoColumn> columns;

  late List<PlutoRow> rows;

  late PlutoGridStateManager stateManager;

  @override
  void initState() {
    super.initState();

    columns = [
      PlutoColumn(
          title: 'id', field: 'id', type: PlutoColumnType.text(), hide: true),
      PlutoColumn(
          title: 'period', field: 'period', type: PlutoColumnType.number()),
      PlutoColumn(
          title: 'breeder', field: 'breeder', type: PlutoColumnType.text()),
      PlutoColumn(
          title: 'province', field: 'province', type: PlutoColumnType.text()),
      PlutoColumn(
          title: 'building', field: 'building', type: PlutoColumnType.text()),
      PlutoColumn(
          title: 'entryDate', field: 'entryDate', type: PlutoColumnType.text()),
      PlutoColumn(
          title: 'releaseDate',
          field: 'releaseDate',
          type: PlutoColumnType.text()),
      PlutoColumn(
          title: 'hatchery', field: 'hatchery', type: PlutoColumnType.text()),
      PlutoColumn(title: 'mill', field: 'mill', type: PlutoColumnType.text()),
      PlutoColumn(
          title: 'speciesType',
          field: 'speciesType',
          type: PlutoColumnType.text()),
      PlutoColumn(
          title: 'speciesSpecification',
          field: 'speciesSpecification',
          type: PlutoColumnType.text()),
      PlutoColumn(
          title: 'forecastedHeadCount',
          field: 'forecastedHeadCount',
          type: PlutoColumnType.text()),
      PlutoColumn(
          title: 'forecastedUnitWeightKg',
          textAlign: PlutoColumnTextAlign.right,
          field: 'forecastedUnitWeightKg',
          type: PlutoColumnType.text()),
      PlutoColumn(
          title: 'forecastedKilo',
          textAlign: PlutoColumnTextAlign.right,
          field: 'forecastedKilo',
          type: PlutoColumnType.text()),
      PlutoColumn(
          title: 'livestockStatus',
          field: 'livestockStatus',
          type: PlutoColumnType.text()),
    ];

    rows = DummyData.rowsByColumns(length: 10, columns: columns);
  }

  var ix = [
    'id',
    'period',
    'breeder',
    'province',
    'building',
    'entryDate',
    'releaseDate',
    'hatchery',
    'mill',
    'speciesType',
    'speciesSpecification',
    'forecastedHeadCount',
    'forecastedUnitWeightKg',
    'forecastedKilo',
    'livestockStatus',
  ];

  void sort(PlutoGridStateManager manager) {
    ix.shuffle();
    var p = Map.fromEntries(ix.asMap().entries.map<MapEntry<String, int>>(
        (entry) => MapEntry(entry.value, entry.key)));

    manager.refColumns.sort((a, b) {
      if (p.containsKey(a.field) && p.containsKey(b.field)) {
        return p[a.field]!.compareTo(p[b.field]!);
      }
      return 0;
    });
    manager.refColumns.update();
    manager.updateVisibilityLayout();
    manager.clearCurrentCell();
    manager.notifyListeners();
  }

  PlutoGridStateManager? manager;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: PlutoGrid(
          onLoaded: (event) {
            manager = event.stateManager;
            sort(manager!);
          },
          columns: columns,
          rows: rows,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          sort(manager!);
        },
      ),
    );
  }
}
```
