### ISSUE TITLE
LateInitializationError

### ISSUE THREAD

**Issue by asenthilkumarr** [bosskmk/pluto_grid#580]
The following error occurred when using Grid on Tab, No issues if I use the grid on the 1st tab, throws an error if I use it on the 2nd Tab. 
LateInitializationError: Field 'stateManagerTrans' has not been initialized.

Any suggestions to avoid this error

Thanks in advance

**Comment by bosskmk** [comment]
Can you attach a simple sample code to reproduce the error?
