### ISSUE TITLE
PlutoPagination :how to set the total pageSize dynamically

### ISSUE THREAD

**Issue by Sindyue** [bosskmk/pluto_grid#585]
hello，
   is there a way  to set the total pageSize dynamically  when PlutoPagination

**Comment by bosskmk** [comment]
https://github.com/bosskmk/pluto_grid/blob/master/lib/src/plugin/pluto_pagination.dart

Create the widget you want by referring to the file in the link above.
And pass the widget to the footer like below.

```dart
class YourPagination extends StatefulWidget {
  final PlutoGridStateManager stateManager;

  YourPagination(this.stateManager);
}

PlutoGrid(
  createFooter: (stateManager) => YourPagination(stateManager);
);
```

**Comment by Sindyue** [comment]
thanks
