### ISSUE TITLE
To Show Grid on Left Side and Some Controls on Rights Side

### ISSUE THREAD

**Issue by asenthilkumarr** [bosskmk/pluto_grid#588]
Hi, Is it possible to set the width for the grid to show half of the page on the left side because have some controls to be shown on the right side, Currently I can show the grid half of the page horizontally which means can set the height to the grid but cannot able to vertically due cannot able to set the width, Can you please advice me?

Thanks

**Comment by bosskmk** [comment]
@asenthilkumarr 
I don't know if I understood your question well.

![test](https://user-images.githubusercontent.com/5284141/192158385-9d9fb5d1-4a69-4c60-8f6c-6a71e36e0499.gif)

Are you trying to display the PlutoGrid widget and your widgets horizontally as in the image above?
Do you mean represented by a Column widget like the one below in the image?
