### ISSUE TITLE
Setting field value between leaving one field and entering the next

### ISSUE THREAD

**Issue by bastaware** [bosskmk/pluto_grid#589]
When moving focus from one cell to another, I would like to be able to intercept onChange event before editing is initialized. This way it will be possible to set the value of the newly focused cell before it grabs the value to be edited.

My issue is that some cells are calculated based on others, but when auto-editing = true, and user moves focus to another cell, its value is not updated before editing starts and thus the calculated value disappears. As illustrated in this example:

![autoediting_on](https://user-images.githubusercontent.com/1000036/192148419-3295e2ce-f2a3-4ffd-97f6-fe6ead119d6e.gif)
(auto-editing on)

- Notice that when I type in **Price** and **Quantity**, **Total DKK** is updated = 100 (great!)
- But when I type 29 into **Fee** and move cursor directly to **Total DKK** it should be 129 (as seen in the console)

My code inside onChanged:

```
double totalAmount = price * quantity + fee;
stateManager!.changeCellValue(row.cells[totalAmount]!, totalAmount, callOnChangedEvent: false);
```
The only solution I can come up with, is to switch auto-editing off. But this is not good for the user experience, as two click are needed to edit next cell.

Also, is it possible to make the calendar open instantly when selecting a date cell? Even with auto-editing on you need two taps to open the calendar.

**Comment by bosskmk** [comment]
Deployed to PlutoGrid 5.1.1

![Image](https://user-images.githubusercontent.com/5284141/192156709-410050e8-e338-4c9a-9f60-b8df6c5379e0.gif)

This is an example of changing the value of the cell to be moved when moving to the next cell while maintaining the edit state.
Please note that this is a simple example.

Action Step Description
1. The value of column2 is edited in the edit state. (Status not reflected in data. Reflected in actual data is reflected when entering the Enter key or moving to another cell.)
2. Move to column3 with the tab key while maintaining column2 edit state
3. column2 is dispose. (If the value of column2 is changed in dispose, the action to reflect the change in the value of column2 is added to `WidgetsBinding.instance.addPostFrameCallback`)
4. Column3 is rendered, but the value of column2 has not yet changed
5. Rendering of column3 is completed and the value of column2 is changed with the callback registered in `3`.
6. With the current cell (column) changed to column3, the onChanged callback of column2 (if PlutoGrid.onChanged callback is set) is called.
7. Change the cell value of the current cell (column3) with PlutoGridStateManager.textEditingController (column3 has already been changed)

```dart
import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

import '../dummy_data/development.dart';

class EmptyScreen extends StatefulWidget {
  static const routeName = 'empty';

  const EmptyScreen({Key? key}) : super(key: key);

  @override
  _EmptyScreenState createState() => _EmptyScreenState();
}

class _EmptyScreenState extends State<EmptyScreen> {
  late List<PlutoColumn> columns;

  late List<PlutoRow> rows;

  late PlutoGridStateManager stateManager;

  @override
  void initState() {
    super.initState();

    columns = [
      PlutoColumn(
        title: 'column1',
        field: 'column1',
        type: PlutoColumnType.number(),
        enableAutoEditing: true,
      ),
      PlutoColumn(
        title: 'column2',
        field: 'column2',
        type: PlutoColumnType.number(),
        enableAutoEditing: true,
      ),
      PlutoColumn(
        title: 'column3',
        field: 'column3',
        type: PlutoColumnType.number(),
        enableAutoEditing: true,
        // readOnly: true,
      ),
    ];

    rows = DummyData.rowsByColumns(length: 10, columns: columns);

    for (final row in rows) {
      row.cells['column3']!.value =
          row.cells['column1']!.value + row.cells['column2']!.value;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        padding: const EdgeInsets.all(15),
        child: PlutoGrid(
          columns: columns,
          rows: rows,
          onChanged: (PlutoGridOnChangedEvent event) {
            print(event);
            if (event.column?.field != 'column3') {
              event.row?.cells['column3']!.value =
                  event.row?.cells['column1']!.value +
                      event.row?.cells['column2']!.value;

              if (stateManager.currentColumn?.field == 'column3') {
                stateManager.textEditingController?.text =
                    (event.row?.cells['column1']!.value +
                            event.row?.cells['column2']!.value)
                        .toString();
              }
            }
          },
          onLoaded: (PlutoGridOnLoadedEvent event) {
            stateManager = event.stateManager;
          },
          configuration: const PlutoGridConfiguration(),
        ),
      ),
    );
  }
}
```

**Comment by bastaware** [comment]
Thank you immensely for the always fast response! You are maintaining this project exemplary!

Donations incoming!
