### ISSUE TITLE
on arrow down key pressed onclick is called automatically

### ISSUE THREAD

**Issue by kunalprabhu21** [bosskmk/pluto_grid#591]
so i have implemnted pluto grid for my windows flutter application everything works fine,,until i press the arrow down key on the keyboard it navigates to  new screen which was supposed to opened only when i manually click on any rows,,,please help

**Comment by bosskmk** [comment]
@kunalprabhu21 
I can't understand your problem.
Please attach an image, video, etc. or explain again.

**Comment by kunalprabhu21** [comment]
i have implemented pluto grid library for my windows application
on click on any row i open a new page, but this method is called even when i hit the arrow key on my keyboard,,how can i avoid keyboard buttons?

**Comment by bosskmk** [comment]
Demo and source link.
See below.

The demo can open a window with two tabs (a single tap if the row is selected).
To change with one tap, modify as follows.

```dart
//mode: PlutoGridMode.select,
mode: PlutoGridMode.selectWithOneTap,
```

https://weblaze.dev/pluto_grid/build/web/#feature/listing-mode
https://github.com/bosskmk/pluto_grid/blob/master/demo/lib/screen/feature/listing_mode_screen.dart

**Comment by kunalprabhu21** [comment]
thanks a loot this fixed my issue...also can u tell me how do i change the row default (sky blue) color on tap of row??
