### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CGrandez** [bosskmk/pluto_grid#592]
### Steps to reproduce the bug
Error adding rows asynchronously and creating footer together, does not show the data of the first page until manually changing to the second page.

### Expected results
It was expected to see the data at the end of loading the waiting screen

### Actual results
Table with data, with first blank page, the data is shown when changing page.

### Execution Environment
**Flutter version**
Flutter version is 3.3.1

**PlutoGrid version**
PlutoGrid version is 5.1.2

**OS**
Windows 11

**Comment by bosskmk** [comment]
Handle page updates by calling `setPage` or `resetPage` after a row has been added.

If you are adding rows directly to `refRows` asynchronously, you will have to manually do the work required to update them.

```dart
PlutoGridStateManager.initializeRowsAsync(
  columns,
  fetchedRows,
).then((value) {
  stateManager.refRows.addAll(FilteredList(initialList: value));

  /// In this example,
  /// the loading screen is activated in the onLoaded callback when the grid is created.
  /// If the loading screen is not activated
  /// You must update the grid state by calling the stateManager.notifyListeners() method.
  /// Because calling setShowLoading updates the grid state
  /// No need to call stateManager.notifyListeners.
  
  ///stateManager.setShowLoading(false);
  stateManager.setPage(stateManager.page);
  // or
  stateManager.resetPage();
});
```
