### ISSUE TITLE
[Feature] Make grid non-editable

### ISSUE THREAD

**Issue by RedRozio** [bosskmk/pluto_grid#595]
Make it so that you can select text and rows, but not edit any values.
Also it would be nice to disable sorting and filtering, since I do this via queries for better performance.

I am sure this can be a useful feature for others too.

Thank you for great work on this package!
<3

**Comment by RedRozio** [comment]
Noticed that the option is available, but only in each column. I will add it to every one :). Works for now.

**Comment by Retr0sec7** [comment]
I see that this was closed as a not planned, did this feature already got implemented? Or the only way to toggle editing on the entire grid is still by columns?

**Comment by RedRozio** [comment]
Yes, the only way as of now is to apply the setting to each column. You may want to create either a cascading rule from the parent for less boilerplate, either option works.

**Comment by bosskmk** [comment]
`PlutoGridMode.readOnly` will be added.
Makes all cells non-editable, regardless of column settings.
It will be released in the next version.

**Comment by bosskmk** [comment]
Added in PlutoGrid version 5.3.1.
https://pluto.weblaze.dev/plutogridmode
