### ISSUE TITLE
Refresh records in datagrid by simple method [Feature] 

### ISSUE THREAD

**Issue by ZdenekKrcal** [bosskmk/pluto_grid#597]
It would be nice to have simple method to completly refresh and re-render records in datagrid.

PlutoGrid.refreshRecords(); ?

There is issue:
https://github.com/bosskmk/pluto_grid/issues/283

**Comment by bosskmk** [comment]
Please provide minimal sample code to solve your problem and I will check it out.
thank you

**Comment by ZdenekKrcal** [comment]
> Please provide minimal sample code to solve your problem and I will check it out. thank you

It is here:
https://github.com/bosskmk/pluto_grid/issues/283

**Comment by bosskmk** [comment]
Basically, when passing PlutoColum and PlutoRow to PlutoGrid, you should not create them in the build(BuildContext context) method.
PlutoGrid.columns and PlutoGrid.rows must be created and provided outside the build method.
If you want to add or new columns later, you need to process them with stateManager.removeRows or stateManager.insertRows.
I'll have to run your code to see what's wrong under these conditions.

**Comment by bosskmk** [comment]
If you need a context to provide a cell with custom rendering, you can get the context as a widget like Builder. A more definitive answer is possible if example code is provided.

**Comment by ZdenekKrcal** [comment]
Ahh, you are right, Builder is great solution for context, but I need ref too because I use Riverpod now but I would resolve that by converting StatelessWidget to StatefulWidget. 
Ok and what about case when values in rows are changing each 1 minute, you need refetch records and put into the PlutoGrid, so it is not about deleting or adding rows but just updating.

**Comment by bosskmk** [comment]
Yes, when your model is changed, you can notify the change with state management such as StateNotifier, and when a change occurs, you can handle something with stateManager.

**Comment by ZdenekKrcal** [comment]
You mean stateManager.notifyListeners() and add UniqueKey() into PlutoGrid?

**Comment by bosskmk** [comment]
https://github.com/bosskmk/pluto_grid/issues/105#issuecomment-1279901098

The example in the link above is sample code for server-side pagination.
In the code, when a pagination button click occurs, the `Future<_PaginationData> fetch` method is executed.

Similarly, when your model changes, you can call the `fetch` method to handle it.

**Comment by ZdenekKrcal** [comment]
Yes so, refreshing all rows is possible this way:
- remove all origin rows:
stateManager.refRows.clearFromOriginal();

- add updated rows
stateManager.insertRows(
      0,
      data.rows
          .map(
            (e) => PlutoRow(
              cells: {
                for (var v in e.entries) v.key: PlutoCell(value: v.value)
              },
            ),
          )
          .toList(),
    );

Is it correct?
