### ISSUE TITLE
[Bug]  Strange behaviour scroll with laptop trackpad (macos)

### ISSUE THREAD

**Issue by Baghdady92** [bosskmk/pluto_grid#600]
Hello 

i think there is a problem with vertical scroll using laptop trackpad in (macos)
with mouse scrolling everything working fine 

any idea for the problem  ? 
did anyone notice this strange behaviour ? or just me ? 
i'm using latest version pluto_grid: 5.1.3

btw in the web everything work fine 
Thanks in advance

**Comment by bosskmk** [comment]
Unfortunately I don't have a MacBook so I can't test it.
I think there was an issue with the trackpad in flutter, I'll check it out.
thank you

**Comment by benjamincombes** [comment]
I can confirm, it does not work on my side either, but I can scroll by going down using keyboard arrows.

**Comment by fredzhang** [comment]
Yes, I can confirm as well. I have MacBook Pro, the latest macOS, latest Chrome or Edge. The horizontal scrolling doesn't work. or very clunky using track pad.

**Comment by huangye0** [comment]
yes ,i meet this problem too.
windows can't scroll vertical or horizontal when using trackpad,but scroll using mouse is fine. 
macos meets the same problem too

**Comment by huangye0** [comment]
i meet this problem too.
windows can't scroll vertical or horizontal when using trackpad,but scroll using mouse is fine.
macos meets the same problem too

**Comment by huangye0** [comment]
> Unfortunately I don't have a MacBook so I can't test it. I think there was an issue with the trackpad in flutter, I'll check it out. thank you

not only macos but alse windows can't scroll vertical or horizontal when using trackpad,but scroll using mouse is fine.

**Comment by bosskmk** [comment]
The problem has been fixed in PlutoGrid version 5.4.4.
Problem caused by trackpad not being set in dragDevices.

https://pluto.weblaze.dev/scrollbar-and-scroll-behavior

**Comment by Baghdady92** [comment]
Yes the problem solved anded tested 
Thanks alot <3
