### ISSUE TITLE
[Help] How do you select a row with code so it may be highlighted?

### ISSUE THREAD

**Issue by SaltH2OFish** [bosskmk/pluto_grid#605]
In my application I use both onTap and OnRowDoubleTap.  When onRowDoubleTap occurs, I'd like to select the row so it is highlighted like how onTap behaves.  What should I do within the OnRowDoubleTap to select the row so that the activatedColor is visible.

**Use Case**
OnTap - update UI with additional details about the specific row tapped
OnDoubleTap - open a dialog which allows the user to modify record data upon double tap.

**Issue** 
After user double taps the row a popup dialog allows the user to modify data. When the user closes the dialog, the row they just modified is not highlighted/selected.

**Comment by bosskmk** [comment]
You can receive cell (PlutoCell) and rowIdx (int) in the onRowDoubleTap callback.
And you can update the current cell as below.
Are you asking this?

```dart
stateManager.setCurrentCell(cell, rowIdx);
```
