### ISSUE TITLE
frozen's PlutoColumn not working

### ISSUE THREAD

**Issue by devappbox** [bosskmk/pluto_grid#607]
Hello,

I have this piece of code (took from https://github.com/bosskmk/pluto_grid/blob/master/example/lib/main.dart)

PlutoColumn(
        title: 'ID',
        field: 'id',
        type: PlutoColumnType.text(),
        )

I just added property frozen: PlutoColumnFrozen.start, but the column not frozen. 

**Flutter version**

Flutter version is 3.3.4

**PlutoGrid version**

PlutoGrid version is 5.2.1

**OS**

Windows 8

**Comment by bosskmk** [comment]
Frozen columns will be unwrapped if the width of `PlutoGrid` is insufficient.
The width of the entire column in the body area, excluding the fixed column, must be at least 200.

**Comment by devappbox** [comment]
Thank's for your explanation.

**Comment by bosskmk** [comment]
Added comments in documentation and code.
thank you

https://pluto.weblaze.dev/columns
