### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by jozes** [bosskmk/pluto_grid#609]
Hi!
In certain cells we disabled the filter by setting  **enableFilterMenuItem** to false because the filter option has no sense. How I can set the colour of the empty space behind the non existing filter input widget to the same background colour as the rest of the grid? By default it is displaying a kind of a grey colour. See the attached picture.

Thanks in advance!
 
<img width="459" alt="Screenshot 2022-10-21 at 23 07 22" src="https://user-images.githubusercontent.com/13683961/197289081-afdf4a3d-7d7a-42ac-8741-b260afb37b9f.png">

**Comment by bosskmk** [comment]
This can be changed with the cellColorInReadOnlyState property.
This property also affects cells in rows (cells in readOnly columns).

```dart
configuration: PlutoGridConfiguration(
  style: PlutoGridStyleConfig(
    cellColorInReadOnlyState: Colors.lightGreen,
   ...
```

**Comment by jozes** [comment]
Thanks for so fast response. It works like a charm. Congratulations for great package, well done!
