### ISSUE TITLE
[Help] Is there a way to change the enableEditingMode of the columns dynamically with a button?

### ISSUE THREAD

**Issue by Retr0sec7** [bosskmk/pluto_grid#612]
So here my function that creates the columns:

```
List<PlutoColumn> getGridColumns(BuildContext context) {
    List<PlutoColumn> columns = <PlutoColumn>[
      PlutoColumn(
          title: 'Id',
          field: 'id',
          type: PlutoColumnType.text(),
          enableColumnDrag: false,
          enableRowDrag: false,
          enableEditingMode: false),
      PlutoColumn(
          title: 'Name',
          field: 'name',
          type: PlutoColumnType.text(),
          enableColumnDrag: false,
          enableRowDrag: false,
          enableEditingMode: state.enableEditingMode),
      PlutoColumn(
          title: 'Phone Number',
          field: 'phoneNumber',
          type: PlutoColumnType.text(),
          enableColumnDrag: false,
          enableRowDrag: false,
          enableEditingMode: state.enableEditingMode),
      PlutoColumn(
        title: 'Location',
        field: 'location',
        type: PlutoColumnType.text(),
        enableColumnDrag: false,
        enableRowDrag: false,
        enableEditingMode: state.enableEditingMode,
        renderer: (rendererContext) => Row(children: [
          Text(rendererContext.cell.value.toString()),
          const Spacer(),
          IconButton(
              icon: const Icon(Icons.location_on),
              onPressed: () => {
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => const MapScreen()))
                  })
        ]),
      ),
    ];
    return columns;
  }
```

I'm using bloc pattern to determine the mode of the columns (are columns on edit mode or not? True/False). So based on this state flag I'm setting the `enableEditingMode` option of the columns. this works with the initial state which is false , but when I click the button that changes this state variable to `true`, I can notice debugging it that the correct value is being set, but the columns are still not editables:

![image](https://user-images.githubusercontent.com/96405082/197424584-0e06b51c-10c6-4e97-bf32-5bee601dc6c3.png)

 I'm wondering if I must change something with the state manager as well. Any clues? Thanks

**Comment by bosskmk** [comment]
There is currently no functionality to dynamically change `enableEditingMode`.
You should use a function that dynamically limits whether to edit with the `checkReadOnly` callback.

The link below is an example of dynamically controlling the edit state by implementing the `checkReadOnly` callback for the `ID column`.

https://weblaze.dev/pluto_grid/build/web/#add-and-remove-column-row
https://github.com/bosskmk/pluto_grid/blob/master/demo/lib/screen/feature/add_and_remove_column_row_screen.dart

**Comment by bosskmk** [comment]
Memo: Functionality to change enableEditingMode dynamically.
