### ISSUE TITLE
Passing in a Custom ScrollController [Help] 

### ISSUE THREAD

**Issue by ashndev** [bosskmk/pluto_grid#616]
Hi There!

I need to be able to provide a custom vertical ScrollController to the Pluto grid. To be more specific, I initialize a ScrollController in a widget that sits above the PlutoGrid in the widget tree and need to be able to provide that to be used by the grid for vertical scrolling. Is this in any way possible and if not, are you planning to implement that as a feature?

Thanks in advance :)

**Comment by bosskmk** [comment]
Check out the example below.

```dart
import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

import '../dummy_data/development.dart';

class EmptyScreen extends StatefulWidget {
  static const routeName = 'empty';

  const EmptyScreen({Key? key}) : super(key: key);

  @override
  _EmptyScreenState createState() => _EmptyScreenState();
}

class _EmptyScreenState extends State<EmptyScreen> {
  late List<PlutoColumn> columns;

  late List<PlutoRow> rows;

  late PlutoGridStateManager stateManager;

  @override
  void initState() {
    super.initState();

    columns = [
      PlutoColumn(
        title: 'column1',
        field: 'column1',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column2',
        field: 'column2',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column3',
        field: 'column3',
        type: PlutoColumnType.text(),
      ),
    ];

    rows = DummyData.rowsByColumns(length: 30, columns: columns);
  }

  @override
  void dispose() {
    stateManager.scroll.bodyRowsVertical?.removeListener(
      _verticalScrollListener,
    );

    super.dispose();
  }

  void _verticalScrollListener() {
    print(stateManager.scroll.bodyRowsVertical?.offset);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          padding: const EdgeInsets.all(15),
          child: PlutoGrid(
            columns: columns,
            rows: rows,
            onChanged: (PlutoGridOnChangedEvent event) {
              print(event);
            },
            onLoaded: (PlutoGridOnLoadedEvent event) {
              stateManager = event.stateManager;
              stateManager.scroll.bodyRowsVertical?.jumpTo(100);
              stateManager.scroll.bodyRowsVertical?.addListener(
                _verticalScrollListener,
              );

              // You can create a new linked scroll controller.
              // https://pub.dev/packages/linked_scroll_controller
              // stateManager.scroll.vertical?.addAndGet();
            },
            configuration: const PlutoGridConfiguration(),
          ),
        ),
      ),
    );
  }
}
```

**Comment by bosskmk** [comment]
Doing so requires further development.
Can you please explain in which cases you need to create the `ScrollController` externally?

**Comment by ashndev** [comment]
I see, that's what I thought. I worked around this using callbacks for now, not ideal but it somewhat works. If you end up implementing this it would be much easier! This is needed because the same ScrollController is used when the screen size changes to display a different type of widget. So, on larger screens it would be the grid and on smaller screens it would be a custom ListView, but they both use the same ScrollController with a preset listener.

**Comment by bosskmk** [comment]
As far as I know a `ScrollController` cannot be attached to more than one scrollview.
Reusing `ScrollController` when widgets change due to screen size change?
If you have example code with use cases I think I'll understand a bit more clearly.
As of now, I'm not sure which part is not smooth.

**Comment by bosskmk** [comment]
If the use case is not clearly smooth, I will modify the `ScrollController` to receive externally.
