### ISSUE TITLE
[Feature] is there a method to change the whole rows value ?

### ISSUE THREAD

**Issue by Sindyue** [bosskmk/pluto_grid#618]
hello,
is there a method to change the whole rows value ? like the way to changeCellValue。 
```dart
stateManager.changeCellValue(
	stateManager.currentRow!.cells['column_1']!,
	value,
	force: true,
);
```

**Comment by bosskmk** [comment]
Is it correct to ask about changing multiple cell values as shown below?

```dart
import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

import '../dummy_data/development.dart';

class EmptyScreen extends StatefulWidget {
  static const routeName = 'empty';

  const EmptyScreen({Key? key}) : super(key: key);

  @override
  _EmptyScreenState createState() => _EmptyScreenState();
}

class _EmptyScreenState extends State<EmptyScreen> {
  late List<PlutoColumn> columns;

  late List<PlutoRow> rows;

  late PlutoGridStateManager stateManager;

  @override
  void initState() {
    super.initState();

    columns = [
      PlutoColumn(
        title: 'column1',
        field: 'column1',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column2',
        field: 'column2',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column3',
        field: 'column3',
        type: PlutoColumnType.text(),
      ),
    ];

    rows = DummyData.rowsByColumns(length: 10, columns: columns);
  }

  void _handlePaste() {
    // pasteCellValue works when any cell is in focus.
    // If there is a selected row, change the value of the selected row and
    // If no row is selected, change the value based on the current cell.
    if (stateManager.currentCell == null) {
      stateManager.setCurrentCell(stateManager.firstCell, 0);
    }

    stateManager.setCurrentSelectingRowsByRange(0, 2);
    stateManager.pasteCellValue([
      ['1', '2', '3'],
      ['4', '5', '6'],
    ]);
    stateManager.clearCurrentSelecting();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          padding: const EdgeInsets.all(15),
          child: PlutoGrid(
            columns: columns,
            rows: rows,
            onChanged: (PlutoGridOnChangedEvent event) {
              print(event);
            },
            onLoaded: (PlutoGridOnLoadedEvent event) {
              stateManager = event.stateManager;
              stateManager.setSelectingMode(PlutoGridSelectingMode.row);
            },
            createHeader: (e) => TextButton(
              onPressed: _handlePaste,
              child: Text('paste'),
            ),
            configuration: const PlutoGridConfiguration(),
          ),
        ),
      ),
    );
  }
}
```

**Comment by Sindyue** [comment]
> Is it correct to ask about changing multiple cell values as shown below?
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:pluto_grid/pluto_grid.dart';
> 
> import '../dummy_data/development.dart';
> 
> class EmptyScreen extends StatefulWidget {
>   static const routeName = 'empty';
> 
>   const EmptyScreen({Key? key}) : super(key: key);
> 
>   @override
>   _EmptyScreenState createState() => _EmptyScreenState();
> }
> 
> class _EmptyScreenState extends State<EmptyScreen> {
>   late List<PlutoColumn> columns;
> 
>   late List<PlutoRow> rows;
> 
>   late PlutoGridStateManager stateManager;
> 
>   @override
>   void initState() {
>     super.initState();
> 
>     columns = [
>       PlutoColumn(
>         title: 'column1',
>         field: 'column1',
>         type: PlutoColumnType.text(),
>       ),
>       PlutoColumn(
>         title: 'column2',
>         field: 'column2',
>         type: PlutoColumnType.text(),
>       ),
>       PlutoColumn(
>         title: 'column3',
>         field: 'column3',
>         type: PlutoColumnType.text(),
>       ),
>     ];
> 
>     rows = DummyData.rowsByColumns(length: 10, columns: columns);
>   }
> 
>   void _handlePaste() {
>     // pasteCellValue works when any cell is in focus.
>     // If there is a selected row, change the value of the selected row and
>     // If no row is selected, change the value based on the current cell.
>     if (stateManager.currentCell == null) {
>       stateManager.setCurrentCell(stateManager.firstCell, 0);
>     }
> 
>     stateManager.setCurrentSelectingRowsByRange(0, 2);
>     stateManager.pasteCellValue([
>       ['1', '2', '3'],
>       ['4', '5', '6'],
>     ]);
>     stateManager.clearCurrentSelecting();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: SafeArea(
>         child: Container(
>           padding: const EdgeInsets.all(15),
>           child: PlutoGrid(
>             columns: columns,
>             rows: rows,
>             onChanged: (PlutoGridOnChangedEvent event) {
>               print(event);
>             },
>             onLoaded: (PlutoGridOnLoadedEvent event) {
>               stateManager = event.stateManager;
>               stateManager.setSelectingMode(PlutoGridSelectingMode.row);
>             },
>             createHeader: (e) => TextButton(
>               onPressed: _handlePaste,
>               child: Text('paste'),
>             ),
>             configuration: const PlutoGridConfiguration(),
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```

thanks，sincerely！
but I find stateManager.changeCellValue(row, value, force: true)  work for me！
