### ISSUE TITLE
Seeing empty rows when grouping is enabled [Help] 

### ISSUE THREAD

**Issue by ashndev** [bosskmk/pluto_grid#620]
Hi, 

First of all, thanks so much for being so great at answering all of my questions. As I mentioned, I am trying to implement your grid into an existing app and that's where most of my difficulties are stemming from. So, I've got one more question for you :) 

As we've discussed earlier, when I get some updated data I reset the PlutoGrid rows with the new set of rows when the widget rebuilds by removing all rows and then inserting the new rows through the stateManager. Now, I enabled grouping using the below method in the onLoaded callback per the docs:

`stateManager.setRowGroup(PlutoRowGroupByColumnDelegate(columns: [columns[2]]));`

But as the records are updated only a portion of them seem to show up on the grid and the rows that do show up are blank, like in the screenshot. I am assuming this is because of the way I am updating the rows, wondering if there is anything I can do to resolve this. 

Thanks in advance!

<img width="2497" alt="Screen Shot 2022-10-27 at 2 38 55 PM" src="https://user-images.githubusercontent.com/87834445/198403420-ef20369b-1f9f-40c0-9cd1-50602d272c61.png">

**Comment by bosskmk** [comment]
When deleting and adding rows, you have to do it through `stateManager` as shown below.
If the above problem still occurs, please attach a minimal example code that I can try.

```dart
 stateManager.removeAllRows();
 stateManager.insertRows(
   0,
   DummyData.rowsByColumns(length: 30, columns: columns),
 );
```
