### ISSUE TITLE
[Help] listen for keypress

### ISSUE THREAD

**Issue by bastaware** [bosskmk/pluto_grid#622]
I'm using editing in the cells with setAutoEditing(true). Whenever a cell is changed (onChange) I calculate other cells as a response to the change.

But if the user doesn't leave the cell the other cells are not updated.

One way to solve it, would be to add a debouncing listener to the textEditingController. Whenever the cursor is idle for 3 seconds I would re-calculate the other fields.

How can I get hold of the textEditingController whenever editing changes - or is there a better way to solve this?

**Comment by bosskmk** [comment]
In the edit state, you must move to another cell or press the Enter key for the final value to be reflected.
If you want it to be reflected in real time, like you said, it seems better to do it with debounce.

**Comment by bastaware** [comment]
How do I get a reference to the textEditingController when the field goes into editing mode?

I've tried adding a listener to eventManager but it doesn't seem to send any events until later.

**Comment by bastaware** [comment]
Thanks! This was very helpful. Hadn't noticed the addListener() on statemanager.
