### ISSUE TITLE
onColumnMove

### ISSUE THREAD

**Issue by robertjones1** [bosskmk/pluto_grid#623]
Don't know if this feature was requested or not. Would like to see an onColumnMove event added like onSorted was added a while back.

**Comment by bosskmk** [comment]
I will add the `PlutoGrid.onColumnsMoved` callback in the next version.
thank you

**Comment by robertjones1** [comment]
Thank you.

**Comment by bosskmk** [comment]
Added in `PlutoGrid` 5.3.2.

`PlutoGrid(onColumnsMoved: (e) {});`

**Comment by robertjones1** [comment]
It is working.  Thanks.
