### ISSUE TITLE
[Feature] Disable/hide column resize icon

### ISSUE THREAD

**Issue by KamilSvoboda** [bosskmk/pluto_grid#626]
I need to minimize the column width. Therefore, among other things, I would need to remove the column resize icon which appears when I disable context menu/icon.

At this moment the only way to hide the icon is selecting minimal, almost invisible, icon.

**Comment by bosskmk** [comment]
You can hide the column as below.

```dart
PlutoColumn(
  title: 'column2',
  field: 'column2',
  type: PlutoColumnType.text(),
  enableContextMenu: false,
  enableDropToResize: false,
),
```

**Comment by KamilSvoboda** [comment]
Thank you for your reply. Unfortunately, this option will not allow you to change the column width. I would like to be able to change the width of the column but not see the icon. 
An option to set a transparent color for the icon itself, intended to increase the column width, could solve this. Unfortunately, now the color is set uniformly for all icons.

**Comment by bosskmk** [comment]
Please refer to the code below.

```dart
configuration: const PlutoGridConfiguration(
  style: PlutoGridStyleConfig(
    columnResizeIcon: IconData(0),
  ),
),
```

**Comment by KamilSvoboda** [comment]
Unfortunately this solution shows strange icon in my case.

**Comment by bosskmk** [comment]
Depending on the font, it seems that it is displayed as a question mark. My font didn't show anything.
It's not a solution.
I'll think of another way.
