### ISSUE TITLE
[Help] Is there a way to render a widget (at least one text) when PlutoGrid has no data?

### ISSUE THREAD

**Issue by Retr0sec7** [bosskmk/pluto_grid#627]
So I'm working on the initial view of the grid, suppose that a data source returns no data. Currently the grid looks completely blank. I would like to add a default widget like a Text to show and inform the user that there is no existing records in the data source.
E.g(I made this with paint just be clear here): 

![Untitled](https://user-images.githubusercontent.com/96405082/199343049-6f57df3e-a2f9-45b1-ab50-c91f1af1a84a.png)

**Comment by bosskmk** [comment]
I will add it in the next version.

**Comment by Retr0sec7** [comment]
Great! Thanks a lot. Let's label this one as an enhancement then.

**Comment by bosskmk** [comment]
Added in `PlutoGrid` 5.3.2.

Create a widget like the one below and pass it to `PlutoGrid.noRowsWidget`.
```dart
PlutoGrid(
  noRowsWidget: _NoRows(),
);


class _NoRows extends StatelessWidget {
  const _NoRows({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return IgnorePointer(
      child: Center(
        child: DecoratedBox(
          decoration: BoxDecoration(
            color: Colors.white,
            border: Border.all(),
            borderRadius: const BorderRadius.all(Radius.circular(5)),
          ),
          child: Padding(
            padding: const EdgeInsets.all(10),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              mainAxisAlignment: MainAxisAlignment.center,
              children: const [
                Icon(Icons.info_outline),
                SizedBox(height: 5),
                Text('There are no records'),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
