### ISSUE TITLE
[Help] Remove cell icon or shrink icon padding

### ISSUE THREAD

**Issue by KurtLa** [bosskmk/pluto_grid#628]
Hello,
I am trying to remove the symbol from the time cell. The column is quite small, so I reduced the size of the symbol, but unfortunately the large padding remains.
Does anyone know a solution to remove the symbol or minimize the padding?

<img width="102" alt="image" src="https://user-images.githubusercontent.com/9027932/199372204-1aef1aa5-2ade-4988-9cbe-893300baa077.png">

**Comment by bosskmk** [comment]
I will consider making improvements in the next version.

**Comment by KurtLa** [comment]
Thank you!

**Comment by bosskmk** [comment]
Updated to PlutoGrid version 5.4.0.

The popupIcon property has been added as shown below, and you can change the icon or remove the icon by setting it to null.

```dart
PlutoColumnType.time(
   popupIcon: null,
)
```
