### ISSUE TITLE
[Help] Is there a way to create column and row sticky header?

### ISSUE THREAD

**Issue by ken-aio** [bosskmk/pluto_grid#630]
Hello, thank you for creating a great plugin!

I would like to create a row and column sticky header like excel attached gif image.
Does pluto_grid support this feature?
Thank you.
![2018-10-04-excel-scroll-header-fixed-animation](https://user-images.githubusercontent.com/3462833/200127397-80dbb8a9-a01b-40d0-86b7-4fcdad2c9760.gif)

**Comment by bosskmk** [comment]
Currently, columns can be frozen, but rows cannot.

**Comment by ken-aio** [comment]
I see, is there any plans for sticky rows?

**Comment by bosskmk** [comment]
I don't have a plan yet, but I'll try to develop it.

**Comment by ken-aio** [comment]
Thank you very much!
