### ISSUE TITLE
[Help] How can I wrapping the text in column header ?

### ISSUE THREAD

**Issue by Cr1t1** [bosskmk/pluto_grid#631]
I want to wrapping the text for multiple line in column header.
What should I do ?

Thank you for response.

**Comment by thegioiso** [comment]
This will help.
`
PlutoColumn(
      title: title,
      field: field,
      type: PlutoColumnType.text(),
      titleSpan: WidgetSpan(
        child: Text(
          title,
        ),
      ),
    );
    `
