### ISSUE TITLE
[Help] I try to use riverpod to update the rows in realtime

### ISSUE THREAD

**Issue by DobreRadu** [bosskmk/pluto_grid#632]
I am trying to provide a list from riverpod as rows but doesn't seem to update the contents of the table.
`final actionariRows = StateProvider<List<PlutoRow>>((ref) => []);`
In plutogrid:`rows: ref.watch(actionariRows),`
I also tried to use stateManager.addAll but also seems to not work,with any array not just this array.
```
stateManager.refRows.addAll([
                    PlutoRow(cells: {
                      'name': PlutoCell(value: "Hello"),
                  ]);
```
Also there is a problem if I try to removeAllRows it also deletes the data in the stateProvider.I could use removeAll and then insertRows but it deletes everything even from the provider...
Any help would be great,or idea how to change this to work,thanks!

**Comment by bosskmk** [comment]
Currently, PlutoGrid does not update when the values change outside the PlutoGrid, unless columns and rows are changed using stateManager. (didUpdateWidget)

However, we are considering this feature.
To do that, classes like PlutoColumn, PlutoRow, PlutoCell, etc. must be immutable.

Consequently, in the current version you have to change the value via stateManager .

**Comment by bosskmk** [comment]
Can you attach the example code in question?

**Comment by DobreRadu** [comment]
import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter/material.dart' show Scaffold;

import 'package:pluto_grid/pluto_grid.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart' as riverpod;

class ActionariPageTest extends riverpod.ConsumerStatefulWidget {
  const ActionariPageTest({Key? key}) : super(key: key);

  @override
  _ActionariPageState createState() => _ActionariPageState();
}

final actionariRows = riverpod.StateProvider<List<PlutoRow>>((ref) => []);

class _ActionariPageState extends riverpod.ConsumerState<ActionariPageTest> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    double widthContext = MediaQuery.of(context).size.width;
    double heightContext = MediaQuery.of(context).size.height;

    return ScaffoldPage(
      header: PageHeader(
          title: Row(children: [
        Text("Pluto Grid"),
        FilledButton(
            child: Text("Add Row"),
            onPressed: () {
              //First try:

              // ref
              //     .read(actionariRows.notifier)
              //     .state
              //     .add(PlutoRow(cells: {'nume': PlutoCell(value: "HELOO")}));

              //Second try:
              List<PlutoRow> temp = ref.read(actionariRows.notifier).state;
              temp.add(PlutoRow(cells: {'nume': PlutoCell(value: "HELOO")}));
              ref.read(actionariRows.notifier).state = temp;
            })
      ])),
      content: SizedBox(
          width: widthContext,
          height: heightContext / 1.3,
          child: Scaffold(
            body: PlutoGrid(
              columns: [
                /// Text Column definition
                PlutoColumn(
                  title: "Name",
                  field: 'nume',
                  type: PlutoColumnType.text(),
                  backgroundColor: Colors.blue.lightest,
                  enableEditingMode: false,
                  enableAutoEditing: false,
                  readOnly: true,
                ),
              ],
              rows: ref.watch(actionariRows),
              onChanged: (PlutoGridOnChangedEvent event) {
                print("changed actionari");
              },
              onLoaded: (PlutoGridOnLoadedEvent event) async {},
              createFooter: (stateManager) {
                stateManager.setPageSize(25, notify: false); // default 40
                return PlutoPagination(stateManager);
              },
            ),
          )),
    );
  }
}

**Comment by DobreRadu** [comment]
So I tried with this:
`import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter/material.dart' show Scaffold;

import 'package:pluto_grid/pluto_grid.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart' as riverpod;

class ActionariPageTest extends riverpod.ConsumerStatefulWidget {
  const ActionariPageTest({Key? key}) : super(key: key);

  @override
  _ActionariPageState createState() => _ActionariPageState();
}

final actionariRows = riverpod.StateProvider<List<PlutoRow>>((ref) => []);

class _ActionariPageState extends riverpod.ConsumerState<ActionariPageTest> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    double widthContext = MediaQuery.of(context).size.width;
    double heightContext = MediaQuery.of(context).size.height;

    return ScaffoldPage(
      header: PageHeader(
          title: Row(children: [
        Text("Pluto Grid"),
        FilledButton(
            child: Text("Add Row"),
            onPressed: () {
              //First try:

              // ref
              //     .read(actionariRows.notifier)
              //     .state
              //     .add(PlutoRow(cells: {'nume': PlutoCell(value: "HELOO")}));

              //Second try:
              List<PlutoRow> temp = ref.read(actionariRows.notifier).state;
              temp.add(PlutoRow(cells: {'nume': PlutoCell(value: "HELOO")}));
              ref.read(actionariRows.notifier).state = temp;
            })
      ])),
      content: SizedBox(
          width: widthContext,
          height: heightContext / 1.3,
          child: Scaffold(
            body: PlutoGrid(
              columns: [
                /// Text Column definition
                PlutoColumn(
                  title: "Name",
                  field: 'nume',
                  type: PlutoColumnType.text(),
                  backgroundColor: Colors.blue.lightest,
                  enableEditingMode: false,
                  enableAutoEditing: false,
                  readOnly: true,
                ),
              ],
              rows: ref.watch(actionariRows),
              onChanged: (PlutoGridOnChangedEvent event) {
                print("changed actionari");
              },
              onLoaded: (PlutoGridOnLoadedEvent event) async {},
              createFooter: (stateManager) {
                stateManager.setPageSize(25, notify: false); // default 40
                return PlutoPagination(stateManager);
              },
            ),
          )),
    );
  }
}`

But is not working and then I create a variable to hold the PlutoGrid like this:
`import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter/material.dart' show Scaffold;

import 'package:pluto_grid/pluto_grid.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart' as riverpod;

class ActionariPageTest extends riverpod.ConsumerStatefulWidget {
  const ActionariPageTest({Key? key}) : super(key: key);

  @override
  _ActionariPageState createState() => _ActionariPageState();
}

final actionariRows = riverpod.StateProvider<List<PlutoRow>>((ref) => []);

PlutoGrid plutoGrid = PlutoGrid(
  columns: [
    /// Text Column definition
    PlutoColumn(
      title: "Name",
      field: 'nume',
      type: PlutoColumnType.text(),
      backgroundColor: Colors.blue.lightest,
      enableEditingMode: false,
      enableAutoEditing: false,
      readOnly: true,
    ),
  ],
  rows: [],
  onChanged: (PlutoGridOnChangedEvent event) {
    print("changed actionari");
  },
  onLoaded: (PlutoGridOnLoadedEvent event) async {},
  createFooter: (stateManager) {
    stateManager.setPageSize(25, notify: false); // default 40
    return PlutoPagination(stateManager);
  },
);

class _ActionariPageState extends riverpod.ConsumerState<ActionariPageTest> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    double widthContext = MediaQuery.of(context).size.width;
    double heightContext = MediaQuery.of(context).size.height;

    return ScaffoldPage(
        header: PageHeader(
            title: Row(children: [
          Text("Pluto Grid"),
          FilledButton(
              child: Text("Add Row"),
              onPressed: () {
                //First try:

                // ref
                //     .read(actionariRows.notifier)
                //     .state
                //     .add(PlutoRow(cells: {'nume': PlutoCell(value: "HELOO")}));

                //Second try:
                List<PlutoRow> temp = ref.read(actionariRows.notifier).state;
                temp.add(PlutoRow(cells: {'nume': PlutoCell(value: "HELOO")}));
                ref.read(actionariRows.notifier).state = temp;

                plutoGrid = PlutoGrid(
                  columns: [
                    /// Text Column definition
                    PlutoColumn(
                      title: "Name",
                      field: 'nume',
                      type: PlutoColumnType.text(),
                      backgroundColor: Colors.blue.lightest,
                      enableEditingMode: false,
                      enableAutoEditing: false,
                      readOnly: true,
                    ),
                  ],
                  rows: temp,
                  onChanged: (PlutoGridOnChangedEvent event) {
                    print("changed actionari");
                  },
                  onLoaded: (PlutoGridOnLoadedEvent event) async {},
                  createFooter: (stateManager) {
                    stateManager.setPageSize(25, notify: false); // default 40
                    return PlutoPagination(stateManager);
                  },
                );
                setState(() {});
              })
        ])),
        content: SizedBox(
          width: widthContext,
          height: heightContext / 1.3,
          child: Scaffold(body: plutoGrid),
        ));
  }
}
`
But still doesn't refresh until I change the entire page and create the page again which is weird...
I don't really know how to fix this...
Also for the stateManager if I removeAllRows() it also deletes the data in the provider,so it's a pointer to the data maybe?
`import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter/material.dart' show Scaffold;

import 'package:pluto_grid/pluto_grid.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart' as riverpod;

class ActionariPageTest extends riverpod.ConsumerStatefulWidget {
  const ActionariPageTest({Key? key}) : super(key: key);

  @override
  _ActionariPageState createState() => _ActionariPageState();
}

final actionariRows = riverpod.StateProvider<List<PlutoRow>>((ref) => []);

late PlutoGridStateManager stateManager;

class _ActionariPageState extends riverpod.ConsumerState<ActionariPageTest> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    double widthContext = MediaQuery.of(context).size.width;
    double heightContext = MediaQuery.of(context).size.height;

    return ScaffoldPage(
      header: PageHeader(
          title: Row(children: [
        Text("Pluto Grid"),
        FilledButton(
            child: Text("Add Row"),
            onPressed: () {
              //First try:

              // ref
              //     .read(actionariRows.notifier)
              //     .state
              //     .add(PlutoRow(cells: {'nume': PlutoCell(value: "HELOO")}));

              //Second try:
              debugPrint(ref.read(actionariRows).toString());
              List<PlutoRow> temp = ref.read(actionariRows.notifier).state;
              temp.add(PlutoRow(cells: {'nume': PlutoCell(value: "HELOO")}));
              ref.read(actionariRows.notifier).state = temp;
              debugPrint(ref.read(actionariRows).toString());

              stateManager.removeAllRows();
              debugPrint(ref.read(actionariRows).toString());
            })
      ])),
      content: SizedBox(
          width: widthContext,
          height: heightContext / 1.3,
          child: Scaffold(
            body: PlutoGrid(
              columns: [
                /// Text Column definition
                PlutoColumn(
                  title: "Name",
                  field: 'nume',
                  type: PlutoColumnType.text(),
                  backgroundColor: Colors.blue.lightest,
                  enableEditingMode: false,
                  enableAutoEditing: false,
                  readOnly: true,
                ),
              ],
              rows: ref.watch(actionariRows),
              onChanged: (PlutoGridOnChangedEvent event) {
                print("changed actionari");
              },
              onLoaded: (PlutoGridOnLoadedEvent event) async {
                stateManager = event.stateManager;
              },
              createFooter: (stateManager) {
                stateManager.setPageSize(25, notify: false); // default 40
                return PlutoPagination(stateManager);
              },
            ),
          )),
    );
  }
}
`
Ouput:
`[]
[Instance of 'PlutoRow']
[]`
I could have fixed it by deleteing all rows and then addAll() the array again but if it deletes the data I can't even do that...
Any ideas are welcome thanks alot!

**Comment by bosskmk** [comment]
Please attach the code as below.

<pre>
```dart
code here
```
</pre>

**Comment by DobreRadu** [comment]
I updated the code above

**Comment by bosskmk** [comment]
Your sample code I can't run.
So I don't know if it works by writing code without testing it.

I think you can do it like below,
Since PlutoGrid has internal state management, it is unnecessary to use a separate state management.

```dart
class _ActionariPageState extends riverpod.ConsumerState {
  @override
  void initState() {
    super.initState();
  }

  // Do not create columns in the build method.
  final columns = [
    /// Text Column definition
    PlutoColumn(
      title: "Name",
      field: 'number',
      type: PlutoColumnType.text(),
      backgroundColor: Colors.blue.lightest,
      enableEditingMode: false,
      enableAutoEditing: false,
      readOnly: true,
    ),
  ];

  final rows = <PlutoRow>[];

  late final PlutoGridStateManager stateManager;

  @override
  Widget build(BuildContext context) {
    double widthContext = MediaQuery.of(context).size.width;
    double heightContext = MediaQuery.of(context).size.height;

    return ScaffoldPage(
      header: PageHeader(
        title: Row(
          children: [
            const Text('Pluto Grid'),
            FilledButton(
              child: const Text('Add Row'),
              onPressed: () {
                List<PlutoRow> temp = ref.read(actionariRows.notifier).state;
                temp.add(PlutoRow(cells: {'nume': PlutoCell(value: "HELOO")}));
                ref.read(actionariRows.notifier).state = temp;
                stateManager.removeAllRows();
                stateManager.insertRows(0, [...temp]);
              },
            ),
          ],
        ),
      ),
      content: SizedBox(
          width: widthContext,
          height: heightContext / 1.3,
          child: Scaffold(
            body: PlutoGrid(
              columns: columns,
              rows: rows,
              onChanged: (PlutoGridOnChangedEvent event) {
                print("changed actionari");
              },
              onLoaded: (PlutoGridOnLoadedEvent event) {
                stateManager = event.stateManager;
              },
              createFooter: (stateManager) {
                stateManager.setPageSize(25, notify: false); // default 40
                return PlutoPagination(stateManager);
              },
            ),
          )),
    );
  }
}
```

**Comment by DobreRadu** [comment]
`The following TypeErrorImpl was thrown while handling a gesture:
Unexpected null value.`
Got this error,tested with `stateManager.refRows.addAll([...temp]);` instead but still doesn't update.

**Comment by DobreRadu** [comment]
I edited the comment up,and another question can I make a global stateManager?Or is only initalized when created?
I have a dart file controller where I change this array so I need to pass it somehow.It would be best if I can declare and set it to the plutogrid instead of being created on load.

**Comment by DobreRadu** [comment]
Yes I found some workarounds with stateManager thanks for help,it would be great in the future if it would be able to listen for changes like rows:ref.watch(rows).Thank you alot!
