### ISSUE TITLE
[Question] Setting PlutoGrid.select for value cell of custom filter

### ISSUE THREAD

**Issue by thegioiso** [bosskmk/pluto_grid#635]
Sample code: `https://weblaze.dev/pluto_grid/build/web/#feature/column-filtering`

In your example, i tried "Custom filter" which can filter multi filters with comma (ex: A,B,C...)
![image](https://user-images.githubusercontent.com/106056252/200987229-d4d947a6-0757-49d1-97b5-521572256ac8.png)

And when select "Set filter" it will show up below:
![image](https://user-images.githubusercontent.com/106056252/200987316-bb38bfd2-a720-4ea5-b071-98f67345b2b4.png)
![image](https://user-images.githubusercontent.com/106056252/200987343-f77aa6e0-bc7f-4f54-941b-e67719c8787c.png)

As you can see, "Value" column is `Textfield`, so if i want filter i will have to input "A,B,C..."
It fine with short values, but if these values is long, ex: "My value A,...", if will be harder to input.

Can i change it to PlutoGrid.select so i can select which value to filter? It will look like this one below:
![image](https://user-images.githubusercontent.com/106056252/200987798-7f1adc79-486c-45cb-a2a2-cf59e07be55f.png)

**Comment by bosskmk** [comment]
This feature is not yet supported.
I'll consider adding a feature.
thank you

**Comment by thegioiso** [comment]
@bosskmk hope we will have this feature in future. It will be the best column filter which one like what Excel had:

![image](https://user-images.githubusercontent.com/106056252/201249262-6e222f29-6684-41ee-8059-d06c57093b79.png)

Thank for you all great work very much!!!
