### ISSUE TITLE
[Bug] plutoPagination

### ISSUE THREAD

**Issue by Ahmed-elshorbagy** [bosskmk/pluto_grid#638]
### Steps to reproduce the bug

wrapping PlutoPagination in a column to add extra footer it gives error

### Expected results
show the footer correctly with no bugs

### Actual results
show the footer but with error in pagination
```
The following RangeError was thrown building:
RangeError (index): Invalid value: Not in inclusive range 0..1: 2
```

### Code sample
```dart
createFooter: (stateManager) {
          // stateManager.column
          stateManager.setPageSize(2, notify: true); // default 40
          return Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text("sad"),
              PlutoPagination(stateManager),
            ],
          );
        },
```

### Execution Environment
**Flutter version**

Flutter version is 3.3.4

**PlutoGrid version**

  PlutoGrid version is 5.4.0

**OS**

Windows 11

**Comment by bosskmk** [comment]
Instead of passing the PlutoPagination directly to createFooter , another widget becomes the parent.
setPage is not set.
Calling setPage manually will solve it.
```dart
createFooter: (stateManager) {
          // stateManager.column
          stateManager.setPageSize(2, notify: true); // default 40
          stateManager.setPage(1); // Added
          return Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text("sad"),
              PlutoPagination(stateManager),
            ],
          );
        },
```

**Comment by Ahmed-elshorbagy** [comment]
@bosskmk 
thanks 
but if I tried to change pages  from the footer in the ui, the footer increase in size leading to overflow error
