### ISSUE TITLE
[Help] Is there a way to completely disable selection/activation?

### ISSUE THREAD

**Issue by ncuillery** [bosskmk/pluto_grid#639]
My grid is read-only and I have call-to-actions on the right. I don't use the selection feature at all. How can I **not** have a row/cell selected in blue?

Things I tried:

`PlutoGridSelectingMode.none` doesn't do anything 🤔 

```dart
PlutoGrid(
  ...
  mode: PlutoGridMode.readOnly,
  onLoaded: (PlutoGridOnLoadedEvent event) {
    event.stateManager.setSelectingMode(PlutoGridSelectingMode.none);
  },
)
```

Hiding the selected state by declaring the same color as normal, it "works" in the sense that there is no color change when selecting a row, but still the vertical border disappears because the selected call border is bigger and hides the normal border

```dart
  configuration: PlutoGridConfiguration(
    style: PlutoGridStyleConfig(
      activatedBorderColor: Colors.white,
      activatedColor: Colors.white,
    ),
  ),
```

**Comment by bosskmk** [comment]
There are currently no features mentioned.
However, it seems that the intended purpose can be achieved by setting the widget to ignore updates as shown below.
The code below sets the internal widget _CellContainer to ignore updates.
Even if an event such as cell selection occurs, it is not updated.
thank you

```dart
PlutoGrid(
  columns: columns,
  rows: rows,
  notifierFilterResolver: _CustomNotifierFilter(),
),

class _CustomNotifierFilter extends PlutoNotifierFilterResolverDefault {
  @override
  Set<int> resolve(PlutoGridStateManager stateManager, Type type) {
    print(type.toString());
    // Set to ignore updates of internal widget _CellContainer.
    if (type.toString() == '_CellContainer') {
      return {-1};
    }
    return super.resolve(stateManager, type);
  }
}
```

**Comment by bosskmk** [comment]
Additionally, when the app is built, the name of _CellContainer may be changed.
If that's the case, I don't think this code will work.
I haven't tested whether it works after build.

**Comment by ncuillery** [comment]
@bosskmk the snippet above doesn't remove the row selection, but it does remove the cell selection: the one that adds the thick border.

So used in conjonction with the style property `activatedColor: Colors.white`, it does hide the visual effect of selection.

I'll go with that 👍 so thank you, but maybe can you consider this issue as a feature request?
