### ISSUE TITLE
[Help] Enter of num pad

### ISSUE THREAD

**Issue by bdemeure** [bosskmk/pluto_grid#641]
I would like that enter key of numeric pad react as the "normal" enter key ( go to next cell for example )
With the new shortcurt feature, i do this 
```
 shortcut: PlutoGridShortcut(
              actions: {
                // standard pluto actions.
                ...PlutoGridShortcut.defaultActions,
                // custom actions
                LogicalKeySet(LogicalKeyboardKey.numpadEnter): const PlutoGridActionDefaultEnterKey(),
              },
            ),
```
But it does not work, because the key is "skipped" by the event manager
The only way i found to make it working, is to modify the PlutoKeyManagerEvent as following : 
`bool get isEnter => event.logicalKey.keyId == LogicalKeyboardKey.enter.keyId || event.logicalKey.keyId == LogicalKeyboardKey.numpadEnter.keyId;`

is it a bug ?
is there a way to do that without modifying the manager ?

**Comment by bdemeure** [comment]
My numpadEnter.keyId is 8589935117

@bosskmk, you say "The Numpad Enter key works only when you add the attached code"
but i see no attached code in your post... 
Do you speak about the mine ( when i modify  PlutoKeyManagerEvent ) ?

mode : web ( chrome )
tested with Flutter 3.3.0 and Flutter 3.3.35
plutogrid 5.4.0

**Comment by bosskmk** [comment]
you're right. I didn't get your question right.
The numpadEnter key has been updated as shown below.

Updated to PlutoGrid 5.4.3.

* Add `iterateRowType` to `PlutoAggregateColumnFooter`.
* Modify enter key.(Included `numpadEnter`)
* Add `onToggled` to row group delegate.
   ```dart
  PlutoRowGroupTreeDelegate(
     resolveColumnDepth: (column) => stateManager.columnIndex(column),
     showText: (cell) => true,
     showFirstExpandableIcon: true,
     onToggled: ({required bool expanded, required PlutoRow row}) {
       print(row);
     },
  );
   ```

**Comment by bosskmk** [comment]
Incidentally, the key registered in the shortcut and the shortcut in the TextField (when the grid is in editing state) have separate actions.

Therefore, even if numpadEnter is registered in the shortcut, it does not work in TextField. When not in the editing state, the numpadEnter key registered in the shortcut works.

Therefore, I added numpadEnter to the enter key action in the updated version 5.4.3.

**Comment by bdemeure** [comment]
thanks for the fix
...and for your great job on plutogrid which is a usefull widget
