### ISSUE TITLE
[Bug] Export doesn't work in example

### ISSUE THREAD

**Issue by christianarduino** [bosskmk/pluto_grid#642]
I can only export to PDF from Chrome in the [example](https://weblaze.dev/pluto_grid/build/web/#feature/export) that you made

**Comment by bosskmk** [comment]
In the demo example, the download function is not implemented and commented out.

https://github.com/bosskmk/pluto_grid/blob/master/demo/lib/screen/feature/export_screen.dart

The download function must be implemented using a package that downloads files.
