### ISSUE TITLE
Sort By Group 

### ISSUE THREAD

**Issue by kalismeras61** [bosskmk/pluto_grid#646]
Hello first of all , thanks for the amazing package. 

Can we group by looking at the column information?

For example, there are 4 Columns

A Column | B Column | C Column | D Column
---------------------------------------------------------------- --------------
Pending | Test 2 | Column Text C | D Text
Pending | Test 2 | Column Tex 1 | D Text
Complated

if i say group by ColumnA it should create 2 tables which is the grouped by ColumnA

A Column (Pending)
Pending | Test 2 | Column Text C | D Text
Pending | Test 2 | Column Tex 1 | D Text

A Column
Complated

**Comment by kalismeras61** [comment]
> `Default Table` Apple, 1 Apple, 2 Banana, 1 Banana, 2
> 
> `TableA` Apple, 1 Apple, 2
> 
> `TableB` Banana, 1 Banana, 2
> 
> Is it a condition that `Default Table` should be created as `TableA`, `TableB`? This is not provided functionally.

I am not sure have you used before airtable ? If you select group any column it will show you grouped rows. 

Please look attached images ( grouped by priority)
[https://ibb.co/zRp1Kqm](url)

**Comment by bosskmk** [comment]
Are you referring to the presentation of a UI like the image below?

There is currently a groupby column feature, but it is not an image-like UI.

![image(45)](https://user-images.githubusercontent.com/5284141/202187150-023029ea-9470-4a2c-be79-ef617c355684.png)

**Comment by kalismeras61** [comment]
Yes, that's exactly it, can you share me the code for guidance?

**Comment by bosskmk** [comment]
Demo link
https://weblaze.dev/pluto_grid/build/web/#feature/row-group

Documentation link
https://pluto.weblaze.dev/row-grouping

**Comment by kalismeras61** [comment]
Can we do that programmatically ? Or it should be initially grouped ?

**Comment by bosskmk** [comment]
Documentation has been added to the link below.
See section Groupby columns dynamically.

https://pluto.weblaze.dev/row-grouping#heading-groupby-columns-dynamically
