### ISSUE TITLE
[Help]  Is there a way to adjust rows height?

### ISSUE THREAD

**Issue by Retr0sec7** [bosskmk/pluto_grid#647]
Im looking to style my `PlutoGrid()` something like this: 

![image](https://user-images.githubusercontent.com/96405082/202378511-a1027ff6-b11a-496e-bdf2-1bf3f6cd3285.png)

in order to show the user column cells correctly with an image, title and subtitle I'll need to adjust the height with a higher value. 
I've noticed that the there is a columnSize argument for the `PlutoGridConfiguration()` but not for the rows. I was wondering is this is still possible.

**Comment by thegioiso** [comment]
@Retr0sec7 this will help
 ```
 configuration: const PlutoGridConfiguration.dark(
              style: PlutoGridStyleConfig.dark(
                rowHeight: 100,
),)
              ```

**Comment by Retr0sec7** [comment]
Nice, it worked. Thanks for your help and time.
