### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MRKDaGods** [bosskmk/pluto_grid#650]
### Steps to reproduce the bug
Use PlutoGrid as a child of SliverFillRemaining
(I couldn't reproduce the issue in PlutoGrid 5.1.0)

### Expected results
![image](https://user-images.githubusercontent.com/25166537/203024571-e08574d9-69e7-46ac-9028-6b34d1179901.png)

### Actual results
![image](https://user-images.githubusercontent.com/25166537/203024616-a123905d-7cdb-46c6-9280-73b5b986f75b.png)

### Code sample
```dart
Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverAppBar(
              floating: true,
              snap: true,
              backgroundColor: Colors.transparent,
              elevation: 0,
              toolbarHeight: 50,
              title: Text(
                'test'
              ),
              actions: [
                IconButton(
                  //settings button
                  onPressed: () {},
                  icon: const Icon(Icons.filter_list),
                ),
              ],
            ),
            //fill remaining viewport with grid
            SliverFillRemaining(
              child: PlutoGrid(
                columns: [], // add any sample columns here
                // ignore: prefer_const_literals_to_create_immutables
                rows: [],
              ),
            ),
          ],
        ),
      );
```

### Execution Environment
**Flutter version**
Flutter version is 3.3.0

**PlutoGrid version**
PlutoGrid version is 5.4.3

**OS**
Windows 11

**Comment by bosskmk** [comment]
Adding a `SafeArea` seems to solve it.
Inside `PlutoGrid`, `viewPadding.top` is not handled.

**Comment by MRKDaGods** [comment]
> Adding a `SafeArea` seems to solve it. Inside `PlutoGrid`, `viewPadding.top` is not handled.

Yep, worked! Thank you
