### ISSUE TITLE
[Help] Replacing date picker

### ISSUE THREAD

**Issue by bastaware** [bosskmk/pluto_grid#651]
How can I replace the date picker? I'd like the same for the entire app.

I've tried rendering my own text field, with my own date pricker popup that responds to tap. This sort of works when the cell is initially clicked and doesn't have focus. But when the cell receives focus either by tap or tab (keyboard) then it goes into editing and the picker is not activated.

**Comment by bosskmk** [comment]
If you give me a simple sample code that I can run, I'll check it out.
