### ISSUE TITLE
[Feature] type.text() sorting wrong when using lowerCase

### ISSUE THREAD

**Issue by rickmeulendijks** [bosskmk/pluto_grid#653]
When using a lowerCase first letter in a text field, sorting descending is wrong:

<img width="81" alt="Station21" src="https://user-images.githubusercontent.com/74087191/204123774-e2ee9311-514e-453e-a4f2-09680bff09dd.png">

**Comment by bosskmk** [comment]
```
M : \u004d
m : \u006d
```
Lowercase letters have larger code units than uppercase letters, so it seems to be the correct alignment.
Sometimes, depending on the font, characters like `'амет'` and `'consectetur'` look identical, but the `a` in `'амет'` is not the letter `a`.
If you sort the two strings, the `consectetur` sorts after them.

**Comment by rickmeulendijks** [comment]
No, it's not alignment. A M is a M and also a m. So fields with m should be sorted within all other M's.

Can I sort by the lowerCase or upperCase cast value of the field?

**Comment by bosskmk** [comment]
The code below is an example code considering case, not code units sorting.
The example code below is the `equalsIgnoreAsciiCase` function from the `collection` package.

```dart
const int _lowerCaseA = 0x61;
const int _lowerCaseZ = 0x7a;
const int _asciiCaseBit = 0x20;

class CustomTextField extends PlutoColumnTypeText {
  @override
  int compare(a, b) {
    var defaultResult = 0; // Returned if no difference found.
    for (var i = 0; i < a.length; i++) {
      if (i >= b.length) return 1;
      var aChar = a.codeUnitAt(i);
      var bChar = b.codeUnitAt(i);
      if (aChar == bChar) continue;
      // Upper-case if letters.
      var aUpperCase = aChar;
      var bUpperCase = bChar;
      if (_lowerCaseA <= aChar && aChar <= _lowerCaseZ) {
        aUpperCase -= _asciiCaseBit;
      }
      if (_lowerCaseA <= bChar && bChar <= _lowerCaseZ) {
        bUpperCase -= _asciiCaseBit;
      }
      if (aUpperCase != bUpperCase) return (aUpperCase - bUpperCase).sign;
      if (defaultResult == 0) defaultResult = (aChar - bChar);
    }
    if (b.length > a.length) return -1;
    return defaultResult.sign;
  }
}

PlutoColumn(
  title: 'column3',
  field: 'column3',
  type: CustomTextField(),
),
```

**Comment by bosskmk** [comment]
I will consider adding a feature so that this feature can be applied optionally.
thank you

**Comment by rickmeulendijks** [comment]
Thx for the example code! This I can use in other cases 🚀
