### ISSUE TITLE
[Help] How change checked rows color programmatically?

### ISSUE THREAD

**Issue by Retr0sec7** [bosskmk/pluto_grid#656]
Hi, as mentioned in #330, there is a way to change the color of checked rows using `rowColorCallback` function. This seems to work, but is not working the same way as if you set this color in the `PlutoGridStyleConfig(checkedColor: Colors.MyColor)`. What I'm trying to do is to colorize Red the rows checked (rows marked for deletion) by clicking the trashcan  icon. So, in the first scenario where we use the `rowColorCallback` the functionality works as the following image can tell:

![image](https://user-images.githubusercontent.com/96405082/204161617-965e1433-a7bd-4221-b167-4c96d4adc036.png)

The problem is that when I click one of the cells of the just checked row, the default color (non-checked color which is transparent) will override the checked color:

After clicking Phone number cell:
![image](https://user-images.githubusercontent.com/96405082/204162776-d9d504ff-b8b2-40bf-ac6d-f1e8f44a0136.png)

If we use the second approach of using  `PlutoGridStyleConfig(checkedColor: Colors.MyColor)` and remove the `rowColorCallback` logic, the grid works and checked color remain as expected:

After clicking Phone number cell:
![image](https://user-images.githubusercontent.com/96405082/204162898-45a43c65-8dc6-45ed-8019-ccfd6ddf5123.png)

Also, I have planned to mark rows with two different colors based on an action done on it. e.g. if mark a row for deletion, it's color would be red, if I edit a row, that row would be green. I thought that `rowColorCallback` would help me with this determining the action done by reading some kind of value of the row object or something else and then change the row color. But I can't find a way to do this if the `rowColorCallback` is not working as it's `PlutoGridStyleConfig(checkedColor: Colors.MyColor)`. Maybe someone has a different approach for this? Thanks.

Here's my configuration and pluto grid invocation: 

```
final gridConfig = PlutoGridConfiguration(
      enableMoveDownAfterSelecting: false,
      enableMoveHorizontalInEditing: false,
      enterKeyAction: PlutoGridEnterKeyAction.toggleEditing,
      //localeText: language,
      style: PlutoGridStyleConfig(
        activatedColor: Colors.transparent,
        checkedColor: Colors.red.shade100,
        enableGridBorderShadow: true, rowHeight: 100,

        // ... [https://pluto.weblaze.dev/configuration]
      ),
      scrollbar: const PlutoGridScrollbarConfig(
        isAlwaysShown: true,
        scrollbarThickness: 8,
        scrollbarThicknessWhileDragging: 10,
      ),
      columnSize: const PlutoGridColumnSizeConfig(
        autoSizeMode: PlutoAutoSizeMode.scale,
      ));

// ...
// ...
 PlutoGrid(
                        createHeader: (stateManager) {
                          return _Header(stateManager, storesContext);
                        },
                        columns: storesContext
                            .read<WebUpdateStoresBloc>()
                            .getGridColumns(context),
                        rows: state.gridData ?? [],
                        noRowsWidget: NoDataMessage(
                          noDataReason: state.noDataReason,
                        ),

                        // columnGroups: columnGroups,
                        onLoaded: (PlutoGridOnLoadedEvent event) {
                          stateManager = event.stateManager;

                          stateManager.setGridMode(PlutoGridMode.readOnly);
                        },
                        onChanged: (PlutoGridOnChangedEvent event) {
                          storesContext
                              .read<WebUpdateStoresBloc>()
                              .saveNewGridDataToUpdate(event);
                          stateManager.notifyListeners();
                        },
                        configuration: gridConfig,
                        // rowColorCallback: (c) {
                        //   return c.row.checked == true
                        //       ? Colors.red.shade100
                        //       : Colors.transparent;
                        // },
                      ),

```

**Comment by bosskmk** [comment]
https://weblaze.dev/pluto_grid/build/web/#add-and-remove-column-row
The link above is an example of changing the text color of a cell when the cell value changes.
You could apply this to change the color of a row instead of changing the text color of a cell.
In addition, if the expression method of waiting to be deleted is replaced with a cell value of the select type, as in the example code, instead of check, the problem of `checkedColor` can be avoided.
Currently, `Color.alphaBlend` is applied when a row is checked.

**Comment by Retr0sec7** [comment]
@bosskmk sorry I did not understood your suggestion. The example you provided just changes the color of cell **text** value. The color is determined by that same value that the cells have and that color is assigned to text Widget: 


```
renderer: (rendererContext) {
          Color textColor = Colors.black;

          if (rendererContext.cell.value == 'saved') {
            textColor = Colors.green;
          } else if (rendererContext.cell.value == 'edited') {
            textColor = Colors.red;
          } else if (rendererContext.cell.value == 'created') {
            textColor = Colors.blue;
          }

          return Text(
            rendererContext.cell.value.toString(),
            style: TextStyle(
              color: textColor,
              fontWeight: FontWeight.bold,
            ),
          );
        },
```
This is not using to stateManager to modify the Grid's color. I need to be able to change to color of a row.
------------------

>if the expression method of waiting to be deleted is replaced with a cell value of the select type, as in the example code, instead of check, the problem of checkedColor can be avoided.
Currently, Color.alphaBlend is applied when a row is checked.

Also, can you elaborate more on this?

**Comment by bosskmk** [comment]
If `selectingMode` is set to row while maintaining `rowColorCallback`, only the current cell is changed to the focus color, not the entire row.
```dart
onLoaded: (PlutoGridOnLoadedEvent event) {
  stateManager = event.stateManager;
  stateManager.setSelectingMode(PlutoGridSelectingMode.row);
},
```

You can also override the color of the focused cell by changing activatedColor to transparent.
```dart
configuration: const PlutoGridConfiguration(
  style: PlutoGridStyleConfig(
    activatedColor: Colors.transparent,
  ),
),
```
![화면 캡처 2022-12-06 003904](https://user-images.githubusercontent.com/5284141/205678476-d5551e1c-6713-4d59-a7d8-1b3bc7d793f6.png)

```dart
import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

import '../dummy_data/development.dart';

class EmptyScreen extends StatefulWidget {
  static const routeName = 'empty';

  const EmptyScreen({Key? key}) : super(key: key);

  @override
  _EmptyScreenState createState() => _EmptyScreenState();
}

class _EmptyScreenState extends State<EmptyScreen> {
  late List<PlutoColumn> columns;

  late List<PlutoRow> rows;

  late PlutoGridStateManager stateManager;

  @override
  void initState() {
    super.initState();

    columns = [
      PlutoColumn(
        title: 'column1',
        field: 'column1',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column2',
        field: 'column2',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column3',
        field: 'column3',
        type: PlutoColumnType.select(['none', 'edit', 'delete']),
      ),
    ];

    rows = DummyData.rowsByColumns(length: 10, columns: columns);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          padding: const EdgeInsets.all(15),
          child: PlutoGrid(
            columns: columns,
            rows: rows,
            onChanged: (PlutoGridOnChangedEvent event) {
              print(event);
            },
            onLoaded: (PlutoGridOnLoadedEvent event) {
              stateManager = event.stateManager;
              stateManager.setSelectingMode(PlutoGridSelectingMode.row);
            },
            // configuration: const PlutoGridConfiguration(
            //   style: PlutoGridStyleConfig(
            //     activatedColor: Colors.transparent,
            //   ),
            // ),
            rowColorCallback: (c) {
              if (c.row.cells['column3']?.value == 'delete') {
                return Colors.red.shade100;
              } else if (c.row.cells['column3']?.value == 'edit') {
                return Colors.green.shade100;
              }

              return Colors.transparent;
            },
          ),
        ),
      ),
    );
  }
}
```
