### ISSUE TITLE
Buttons in Dialog [Help] 

### ISSUE THREAD

**Issue by eprivacy-org** [bosskmk/pluto_grid#660]
Hi,
I'm not sure how to add or set buttons in the dialog.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/97896547/204472954-e507ef50-2e8f-48a9-942f-2986ee9f70a6.png">

The reason I need it is that I have several seniors working with my app. On Desktop and Mobile. I have a lot of requests for "Save", "Undo" and a "Reset" Buttons.

Thanks in advance.

**Comment by bosskmk** [comment]
That's a feature that doesn't exist yet.
Are each button set?
Will the behavior change?
If you let me know more details, I will consider it in the next update.

**Comment by eprivacy-org** [comment]
Hi @bosskmk ,
thanks for considering this!

> _Are the types of each button determined?_

For our behaviour we only need three buttons
Ok/Accept
Reset/Revoke
Cancel/Abort

> Will the behaviour change?

Displayed button names could (in the respective language), methods per DialogType.

> _If you let me know more details, I will consider it in the next update._

As an example, here is a "dialog with buttons" screenshot:
<img width="233" alt="image" src="https://user-images.githubusercontent.com/97896547/204874393-a073001b-09dc-424f-b92e-ecd82e9c80ac.png">

I can imagine an implementation similar to AlertDialog:
`AlertDialog(
            title: const Text('DialogName'),
            content: const Text('DialogContent'),
            actions: [
              ElevatedButton(
                  onPressed: () => Navigator.of(context).pop(),
                  child: const Text("Cancel")),
              ElevatedButton(
                  onPressed: () => doStuff(),
                  child: const Text("Revert")),
              ElevatedButton(
                  onPressed: () => sendToBackendAndPop(),
                  child: const Text("Save")),
            ],
          );`

I don't know the exact layout regarding the individual screen sizes or architectures.

**Comment by thegioiso** [comment]
@eprivacy-org Pluto-grid use it's own DateTimePicker widget. If you want a custom dialog, change your cell to render mode:
```
PlutoColumn(renderer: renderer);
```
and the type to `Text type`.
Next, on your renderer widget, you can use a `onTap` and call your Dialog showup.
Use a DateTimePicker widget on that dialog like this one:
```
FormBuilderDateTimePicker(
        name: name,
        timePickerInitialEntryMode: TimePickerEntryMode.input,
        transitionBuilder: (BuildContext context, Widget? child) {
          return MediaQuery(
            data: MediaQuery.of(context).copyWith(alwaysUse24HourFormat: true),
            child: child ?? Container(),
          );
        },
        initialTime:
            TimeOfDay(hour: DateTime.now().hour, minute: DateTime.now().minute),
            )
```
`FormBuilder` will have a `Key` to collect data when you call them.

Just reload your Pluto grid and load new data to the cell.
