### ISSUE TITLE
Horizontal scrollbar not show on start

### ISSUE THREAD

**Issue by acamenhas** [bosskmk/pluto_grid#661]
Hi, I'm using pluto_grid ^5.4.4, my grid is very extensive horizontally and vertically.

I'm using this configuration:

`configuration: const PlutoGridConfiguration(
                          scrollbar: PlutoGridScrollbarConfig(
                              isAlwaysShown: true,...),`

But when the grid is first loaded its only shows the vertical scrollbar.
How can I do to show them both?

Thanks,
Artur

**Comment by bosskmk** [comment]
Currently, there is no function to display both horizontal and vertical scrollbars at the same time.
I will make sure to update it in the future.

**Comment by yeleibo** [comment]
I have the same problem.I think there should be a variable to control the horizontal scrollbar AlwaysShow, and a variable to control the vertical  scrollbar AlwaysShow。

**Comment by Justus-M** [comment]
+1
my app users may not realize you can scroll horizontally if the scrollbar is not shown

**Comment by haroonkhan335** [comment]
The issue still remains.. Horzontal scrollbar is not shown on Mobile devices even if we set isAlwaysShown flag to true

**Comment by Justus-M** [comment]
Yes this is still an issue for me too
