### ISSUE TITLE
[Feature] Dynamic row height

### ISSUE THREAD

**Issue by vixez** [bosskmk/pluto_grid#664]
Hello,

Is it possible to have dynamic row height?
Some of my rows use a `renderer` with a variable widget height. Since the height is currently fixed, the widgets are cut off.

Thanks!

**Comment by bosskmk** [comment]
This feature is not yet supported.
I'm considering adding this feature.

**Comment by thegioiso** [comment]
Me too, currently i use `Dialog` when user tap on it, it not too bad for a 2nd solution.
But a dynamic row height will better, we can create a more complex cell like multiline text,...

**Comment by vixez** [comment]
Hi @bosskmk 
That would be great, we currently use `data_table`, dynamic row height is the only thing that is preventing use from deploying PlutoGrid to production.

**Comment by Raonshi** [comment]
Not supported yet?

**Comment by OlegShNayax** [comment]
@bosskmk  Any updates?

**Comment by GoodReese** [comment]
A whole year passed
