### ISSUE TITLE
onRowChecked - handling event causes checkbox to uncheck

### ISSUE THREAD

**Issue by davoutuk** [bosskmk/pluto_grid#665]
I'm trying to use the 'onRowChecked' event to capture what rows have been selected, like:

```
onRowChecked: (PlutoGridOnRowCheckedEvent event) {
                  if (event.isChecked != null) {
                    setState(() {
                      if (event.isChecked == true) {
                        _selectedRows[event.rowIdx!] = event.row!;
                      } else {
                        _selectedRows.remove(event.rowIdx);
                      }
                    });
                  }

                },
```

However, with this event handling code in place the checkbox does  not remain checked.   If I remove the onRowChecked handler the checkbox does remain checked, but then  I have no way of determining what rows have been selected.

Any suggestions?

**Comment by davoutuk** [comment]
After further investigation the problem of the checkbox being unchecked appears to be caused by the inclusion of a 'setState' call inside the 'onRowChecked' handler. 
That seems like a grid design problem to me

**Comment by bosskmk** [comment]
I'm reproducing the problem now, but the problem doesn't occur.
Do you create `columns` or `rows` in `build` method?
In that case, the `key` is changed every `build`, and this problem may occur.

**Comment by davoutuk** [comment]
The grid rows are rebuilt as part of the 'build' method, because I am using a RiverPod StreamProvider 'watch' method to act as the trigger for refreshing content.
The reason for wanting to use the 'onRowChecked' event is that the page includes two buttons that are enabled/disabled based upon on whether the selected row count is greater than zero.

**Comment by davoutuk** [comment]
I managed to solve the issue by using a new RiverPod stateprovider and calling this within the 'onRowChecked'  handler
