### ISSUE TITLE
[Help] How to  set column type date condition start date when null value

### ISSUE THREAD

**Issue by yingming25** [bosskmk/pluto_grid#667]
@bosskmk Hi~
When value is null, can show date picker start date on today while first select ?

**Comment by thegioiso** [comment]
@yingming25  this will help
```
type: PlutoColumnType.date(
        defaultValue: value == null ?  TimeOfDay(hour: DateTime.now().hour, minute: DateTime.now().minute) : null,
      ),
```

**Comment by yingming25** [comment]
@thegioiso 
Thank you reply,
If i load data after pluto grid first loaded then defaultValue will be override.

**Comment by thegioiso** [comment]
@yingming25 how about change your cell to rendering mode, so you can show your custom DateTimePicker widget when user tap on it. I have a comment here #660 , maybe it will solve your problem.

**Comment by yingming25** [comment]
@yingming25 Thank you help :)
