### ISSUE TITLE
masking number on typing

### ISSUE THREAD

**Issue by BangPei** [bosskmk/pluto_grid#67]
Hi, i have a column with type PlutoColumnType.number(), can i format the number as like money format on typing the text?

thank you

**Comment by bosskmk** [comment]
There is no masking during input in TextField.
Only when displayed can the numeric value be expressed as desired.
Someone can add it, or I have to add it, but it's difficult right now. There is a lot to improve the current grid in and out, but time is short.
I will try.

**Comment by BangPei** [comment]
ok noted, thank you so much for your response.

**Comment by BangPei** [comment]
Hi, there are 2 parameter inside PlutoCell({dynamic value, dynamic originalValue}),
may i know what is originalValue purpose? and how to use it? coz  i tried set some value or widget in originalValue it's look like not printed.

**Comment by bosskmk** [comment]
Used in date popup.
Currently there is a formatter on the column so it can be deleted.

**Comment by BangPei** [comment]
ok noted, thanks for your response.

i have some function to handle my Shortcut keyboard, when the focus is in other widget there is no problem and working fine, but when the focus is in table (PlutoGrid) my function doesn't work even i have wrapped PlutoGrid with FocusScope().

so far the library very helpful and nice.

**Comment by bosskmk** [comment]
Currently PlutoGrid is supposed to return true from FocusNode's onKey handler.
This causes event propagation to stop unconditionally.

If I modify it, conditionally return false if it is not the key used by PlutoGrid to continue propagating the event.

Or maybe I should be able to add or edit keyboard events in the grid.

**Comment by BangPei** [comment]
ok thank you so much

**Comment by NiranjanShah** [comment]
If I modify it, conditionally return false if it is not the key used by PlutoGrid to continue propagating the event.

Ideally it must return false in case, if the key is not used by PlutoGrid.
Also it will be gr8, if you can let us know what all the keys used by PlutoGrid

**Comment by BangPei** [comment]
Hi, can we modified the padding inside PlutoColumn and PlutoRow?
