### ISSUE TITLE
PlutoGridDatePicker dispaly [Bug] 

### ISSUE THREAD

**Issue by iniwf** [bosskmk/pluto_grid#675]
### Steps to reproduce the bug

PlutoGridDatePicker week display cn wrong，
日 一 四 三 二 五 六

right is：
日 一 二 三 四 五 六

picture link：
微信图片_20221208115826.png
https://www.aliyundrive.com/s/wMW4UyGBt5u

### Code sample
```dart
/// If you have a code sample here, please attach it.
```

### Execution Environment
**Flutter version**
3.3.9

**PlutoGrid version**
5.4.7

**OS**
Windows 11

**Comment by bosskmk** [comment]
We will fix it in the next version.
Until then, you can use it like this:

```dart
configuration: const PlutoGridConfiguration(
  localeText: PlutoGridLocaleText.china(
    tuesday: '二',
    thursday: '四',
  ),
),
```

**Comment by bosskmk** [comment]
Fixed in PlutoGrid 5.4.8 version.
thank you
