### ISSUE TITLE
[Feature] change cell bg color programmatically?

### ISSUE THREAD

**Issue by kikyous** [bosskmk/pluto_grid#678]
is there a way to change cell bg color programmatically ?

**Comment by thegioiso** [comment]
@kikyous cell can be a widget with `renderer`, your a stateFulWidget for it.
```
PlutoColumn(
 renderer: renderer,
)
```

**Comment by GhRafik** [comment]
It would be wonderful if we could select multiple cells (using CTRL btn) and change their background colors.
