### ISSUE TITLE
How i can put an header filter on every column or some column that i need

### ISSUE THREAD

**Issue by amasahara** [bosskmk/pluto_grid#68]

**Comment by bosskmk** [comment]
Adding a filter was planned, but it hasn't been done yet. There is a lot to modify inside and outside the grid, but the time is limited, so it is difficult to do it alone.
I will try.

**Comment by amasahara** [comment]
yes, it is very important for every project. Hope it will be soon

**Comment by gcomm-trile** [comment]
Hope it will be soon

**Comment by bosskmk** [comment]
Yes I am working on it.

**Comment by exomaniac** [comment]
As we want to use this Grid in one of our Products and we also need to filter per column i would like to get insight to your plannings on this and if possible would like to help on this issue

**Comment by bosskmk** [comment]
@exomaniac 

I will share the status I am working on.
https://weblaze.dev/pluto_grid/build/development/index.html

In the link example above, tap the icon on the right of the column to display the menu.
If you tap SetFilter from that menu, a pop-up appears where you can set the filter.

There is more to work.

Add test code, improve performance, and visually represent filters applied.

The branch I'm working on is feature/filtering.

I welcome your comments or help.

Thank you.

**Comment by bosskmk** [comment]
Visual effects have been added when filters are applied to the column.

The filter icon appears to the right of the column heading.

When you tap the icon, the column setting popup appears.

https://weblaze.dev/pluto_grid/build/development/index.html
> If that doesn't work, try resetting the web cache.

**Comment by exomaniac** [comment]
Thank you very much! i will have a closer look at it

**Comment by amasahara** [comment]
that is help me very much for filter with big data, but if you can make an text field under header column, that will be better than this because it take me less time for click into multiple column header, and more easy for user when they want to change their value filter. Seem it also hard for user when use filter fuction if they want to filter. hope you can make an textfield and when they change value on filed, you can make an clear filter button for clear all of filter on each textfield

**Comment by bosskmk** [comment]
@amasahara 
I will consider making it possible to set up both the pop-up filter and the one you suggested.

**Comment by amasahara** [comment]
because end user they not know much it will take many time for make FAQ or contact to end user know how to use this function. Thank you very much for your help. I think if you can make like i suggested, popup will be unnecessary because it will be always search as content, not much people want popup. It hard for use with end user

**Comment by gcomm-trile** [comment]
![image](https://user-images.githubusercontent.com/58388336/101429886-7a6e5380-3936-11eb-91e5-7c0e7078e538.png)
agree with @amasahara .

**Comment by bosskmk** [comment]
Added filtering TextField below the column.

https://weblaze.dev/pluto_grid/build/development/index.html

I will add test code, and if there is no problem with operation and performance, I will distribute it.

**Comment by amasahara** [comment]
performance is very good, filter very fast, i try with more 10.000 row, seem can you lowercase filter or i can custom filter value because my language need some special custom

**Comment by bosskmk** [comment]
@amasahara Yes, filter types will be added.

**Comment by bosskmk** [comment]
Updated 1.0.0-pre.8.

**Comment by gcomm-trile** [comment]
File not found. Please check link demo for grid filter!

**Comment by bosskmk** [comment]
https://bosskmk.github.io/pluto_grid/build/preview/index.html

check out the above link.
v1.0.0-pre.8

**Comment by gcomm-trile** [comment]
It's so nice.
- By text column, it's ok but should have a small button to popup value for select
![image](https://user-images.githubusercontent.com/58388336/102300878-55a65b80-3f88-11eb-8997-d07decd70f3d.png)
- By date column, you should have a range filter value
![image](https://user-images.githubusercontent.com/58388336/102300933-71a9fd00-3f88-11eb-97ef-a78d15da541f.png)
Maybe can use range date picker
- By checkbox column, you should have a fast checkbox
![image](https://user-images.githubusercontent.com/58388336/102300640-e597d580-3f87-11eb-98f1-703dd314f290.png)

Thanks for your work hard.

**Comment by bosskmk** [comment]
@gcomm-trile  
Thanks for the good comment. I will refer to.

**Comment by gcomm-trile** [comment]
I used version pluto_grid: ^1.0.0-pre.8 and set enableFilterMenuItem is true but my UI dont have filter textfield below header.

**Comment by bosskmk** [comment]
@gcomm-trile 

enableFilterMenuItem is an option to enable an item in the context menu on the right side of the column. (Drop down)

```dart
      body: PlutoGrid(
        columns: columns,
        rows: rows,
        onLoaded: (PlutoOnLoadedEvent event) {
          event.stateManager.setShowColumnFilter(true);
        },
        onChanged: (PlutoOnChangedEvent event) {
          print(event);
        },
        configuration: PlutoConfiguration(
          /// If columnFilters is not set, default filters are set.
          /// The following is an example to add a custom filter.
          columnFilters: [
            PlutoFilterTypeContains(),
            PlutoFilterTypeEquals(),
            PlutoFilterTypeStartsWith(),
            PlutoFilterTypeEndsWith(),
            YourCustomFilter(),
          ],
        ),
      ),
```

You can enable or disable it with the stateManager in onLoaded (dynamically).
`event.stateManager.setShowColumnFilter(true);`

**Comment by gcomm-trile** [comment]
Thanks for your response. now it's work. By typing filter textfield under header,can I customize filter type for each column ? Sometime I need example Column A filter by StartsWith, column B filter by Contains. I think it will be flexible.

**Comment by bosskmk** [comment]
@gcomm-trile 

Would you like to set different filters applied to the TextField below the column?

It needs work.

Also, in the select pop-up that selects a filter for each column in the filter setting pop-up, the filter must appear differently for each column.

This also needs work.

These things are being planned.

**Comment by bosskmk** [comment]
https://bosskmk.github.io/pluto_grid/build/preview/index.html

check out the above link.
v1.0.0-pre.9

[ChangeLog]
https://github.com/bosskmk/pluto_grid/blob/master/CHANGELOG.md
