### ISSUE TITLE
row sortIdx value issue

### ISSUE THREAD

**Issue by selvam920** [bosskmk/pluto_grid#680]
there is issue to get row id when binding second time while use lazy loading.
the row id is inorder.

<img width="997" alt="image" src="https://user-images.githubusercontent.com/20491308/207370968-7e2438c0-a46e-4d9c-b960-788c167457e3.png">

<img width="992" alt="image" src="https://user-images.githubusercontent.com/20491308/207371113-c6420a2f-a497-4bb1-ae72-ce456c2a6a06.png">

**Comment by bosskmk** [comment]
There is a bug.
I'll fix it in the next version.
thank you

**Comment by bosskmk** [comment]
Fixed in PlutoGrid version 5.4.9.
thank you
