### ISSUE TITLE
[Help]  How to add row programmatically

### ISSUE THREAD

**Issue by rifaljhonatan1** [bosskmk/pluto_grid#681]
How to add rows programmatically, by simply pressing the down arrow on the keyboard, when the row position is at the end of the record or index and the last row is not empty..?

**Comment by thegioiso** [comment]
@rifaljhonatan1 First, add a listenner in initState of the gird for user keyboard activity by this class example:  
https://api.flutter.dev/flutter/services/PhysicalKeyboardKey-class.html
```
bool isDownKeyPress(){
//
}
```
and a listenner for your grid when a row is selected if needed:
```
onLoaded: (PlutoGridOnLoadedEvent event) {
            event.stateManager.addListener(gridHandler);
          }
        },
```
//
Check for last row:
```
bool isLastRow(){
if( gridStateManager?.currentRowIdx == listData.length){ //<= or your detect last row method here
return true;
}
return false;
}
```
//
Go next with add row method when 2 method above return true in listenner:
//ex: .add( <blank row data> ) for your listData
//call .setShowLoading if you need loading effect
```
void appendRow(){
gridStateManager?.removeAllRows();
gridStateManager?.resetCurrentState();
gridRows = buildRowA(gridRows); //<= new data for this build List<PlutoRow> 
gridStateManager?.appendRows(gridARows);
}

```

**Comment by rifaljhonatan1** [comment]
onLoaded: (PlutoGridOnLoadedEvent event) {
            event.stateManager.addListener(gridHandler);
          }
        },
what is gridHandler above mean...?

**Comment by thegioiso** [comment]
@rifaljhonatan1 gridHandler - name of my method for this listenner - which will call every time your grid is interacted by user, you can see an example here:  
https://weblaze.dev/pluto_grid/build/web/#feature/dual-mode

**Comment by rifaljhonatan1** [comment]
@thegioiso thank you very much...
