### ISSUE TITLE
[Help] Lazy Pagination not reload after call search API

### ISSUE THREAD

**Issue by thwestz** [bosskmk/pluto_grid#683]
i'm facing with the grid not re-load pagination footer, i follow this [sample ](https://weblaze.dev/pluto_grid/build/web/#feature/row-lazy-pagination)
step searching
1. Call method search to server side
2. Render data from server side
3. Try to change page ( worked )
4. Call method search again
5. Render data is success but paging not change too

![image](https://user-images.githubusercontent.com/15815392/207659227-fbe400b1-1bb9-49d6-b2c9-d545a90af903.png)
if i click the page 1 this pagination will update 
![image](https://user-images.githubusercontent.com/15815392/207659334-62a3a4f2-5f0d-4d64-9428-317ae1fac192.png)

how to fix this or work around for best ux/ui

thank you.

**Comment by bosskmk** [comment]
What search method are you talking about?

**Comment by thwestz** [comment]
search method is new function that i created for call data from server side

**Comment by bosskmk** [comment]
You should have sample code to reproduce the problem so you can verify it.
Your logic is unknown to me.
