### ISSUE TITLE
[Feature] Date Picker on Filter adding  

### ISSUE THREAD

**Issue by mohammadeslim22** [bosskmk/pluto_grid#684]
Can you add Date Picker & Time picker for filter date value input or time filter value input ? 
Instead of writing down the date or time we can really use a picker 

<img width="464" alt="image" src="https://user-images.githubusercontent.com/28827826/207660823-a64da56c-44f3-4926-aae0-f1dd832d3eb3.png">

Thank you

**Comment by bosskmk** [comment]
This feature does not currently exist.
Features should be added.
We will consider adding it in the next version.
thank you

**Comment by AL-YAFEA-KHALED** [comment]
And if it's possible to add select items in the filter input. Thanks
