### ISSUE TITLE
[Help] How do I have only the parent row checked

### ISSUE THREAD

**Issue by Xepora7** [bosskmk/pluto_grid#686]
![1](https://user-images.githubusercontent.com/35256632/207800995-1e61bdf1-14d8-4d02-b9b9-380d7726bc89.png)
![2](https://user-images.githubusercontent.com/35256632/207801001-3ef027f0-aca3-420f-92f3-9cb35708fb00.png)

Tks.

**Comment by bosskmk** [comment]
This feature does not currently exist.
Features should be added.
We will consider adding it in the next version.
thank you
