### ISSUE TITLE
[Help] Pluto grid - server side refresh

### ISSUE THREAD

**Issue by acamenhas** [bosskmk/pluto_grid#687]
Hello,

I'm working with PlutoLazyPagination using a fetch function to retrieve data from server.

When I click in a row, a popup with the row data is showed, the user update the data, press save and the popup hides.

I need to call the fetch method programmatically for the data to be refreshed, can I do it?

Thanks!

**Comment by thegioiso** [comment]
@acamenhas Maybe you can try my solution here:
1. Add a listenner to your grid with `onRowSelected`:
```
onLoaded: (PlutoGridOnLoadedEvent event) {
            event.stateManager.addListener(onRowSelected);
          }
        },
```
now, create a Dialog in that method:
```
onRowSelected(){
OneContext().showDialog() //<= custom your dialog with your data  here
}
```
save and popup hide is your code logic, i just put how to refresh your grid here:
```
//<= when your dialog onTap Save and receive respond from server, you can trigger setState() for easy reload
```
try #688 if you need reload grid without setState()

**Comment by acamenhas** [comment]
Hello,

setState() doesn't trigger my grid to update the current page data from server.

It makes sense for me, to have a method in the stateManager to "run" the fetch function?

Have a great 2023!!
