### ISSUE TITLE
How to add an loading indicator into pluto dual grid

### ISSUE THREAD

**Issue by amasahara** [bosskmk/pluto_grid#69]
when i change selected from gridPropsA i want add an loading into gridPropsB i try put it in onLoaded but it not work

**Comment by bosskmk** [comment]
The onLoaded event fires only once at the beginning.
You can detect state change with stateManager.addListener.

https://github.com/bosskmk/pluto_grid/blob/master/example/lib/screen/feature/dual_mode_screen.dart

See the gridAHandler method in the example above.
Hope this helps you.

**Comment by amasahara** [comment]
i try but seem addlistener need an void function not widget so i cannot return it

**Comment by bosskmk** [comment]
I will add the loading screen function, but until then you will have to implement it yourself with Stack and Positioned, etc. to display the loading screen.

**Comment by bosskmk** [comment]
Demo
https://weblaze.dev/pluto_grid/build/preview/#feature/dual-mode
Source
https://github.com/bosskmk/pluto_grid/blob/master/example/lib/screen/feature/dual_mode_screen.dart

Check out the example link above.
Loading Indicator has been added to version 1.0.0-pre.4.

**Comment by amasahara** [comment]
Thank you for your upgrade, it take me less code on screen page
