### ISSUE TITLE
[Help] Is there a way revert changes on cells programmatically?

### ISSUE THREAD

**Issue by Retr0sec7** [bosskmk/pluto_grid#693]
I have this Edit mode in my PlutoGrid which enables cell editing. I want to be able to revert/discard all changes done if the user gets out of the Editing mode by clicking a button.

 E.g.
User enters editing mode by clicking Edit button which is PlutoMenuItem -> edit one or two (or more) cell values -> User decides to start over or just discard changes -> Clicks on Cancel button which is also a PlutoMenuItem -> all changes done in the cells reverts back to it's old/original values.

**Comment by bosskmk** [comment]
I will add a function to return the modified cell value in the next version.

https://github.com/bosskmk/pluto_grid/pull/670

**Comment by Retr0sec7** [comment]
@bosskmk Just to clarify, #670  does not solve my question. That merge request is just for a way to get the original/old value of a cell, which already can be obtained with `PlutoGridOnChangedEvent` which is passed as argument on the `onChanged` PlutoGrid callback.

I need a way to restore the whole original/old row(s) programmatically.
