### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by muntazir143** [bosskmk/pluto_grid#694]
I'm using rendererContext to display the checkbox in a column but upon clicking a checkbox I want to update the value for that specific row just like others and for this, I want PlutoGridOnChangedEvent. Does anyone know how to do that?

Adding a checkbox option in column type was helpful but as its not available so I have to find a workaround.

**Comment by thegioiso** [comment]
@muntazir143  in your `onTap` widget:
```
gridStateManager?.setCurrentCell(renderer.cell, renderer.rowIdx);
    String id =
        renderer.stateManager.currentRow?.cells["ID"]?.value;
```
Now you can use this `ID` for search in your data and change it:
```
dynamic data =
        listData.firstWhere((element) => element["ID"] == id);
```
And reload your grid with new data. Done.
