### ISSUE TITLE
[Help] Overriding sort functionalities

### ISSUE THREAD

**Issue by AminBhst** [bosskmk/pluto_grid#698]
Is there currently a feature which enables overriding sort functions for each column?
e.g. I have a column which shows the size of a file in a readable format (e.g. 23MB). Because it is in a readable format and doesn't actually represent the file length in bytes, sorting on this column will not work as expected.

**Comment by muskaanshah** [comment]
Same question, were you bale to figure out a way?

**Comment by AminBhst** [comment]
@muskaanshah Unfortunately not

**Comment by Justus-M** [comment]
I need this too due to incorrect sorting

<img width="265" alt="Screen Shot 2023-06-07 at 15 40 09" src="https://github.com/bosskmk/pluto_grid/assets/37046316/cfa64b53-bba0-4d86-be45-4b45e156e9fb">

**Comment by AminBhst** [comment]
I think we should take it upon ourselves to implement this. I'm extremely busy on my own project but I'll definitely try to work on this feature of I find the time.
