### ISSUE TITLE
[Help] how to change the column footer height

### ISSUE THREAD

**Issue by majdkurdi** [bosskmk/pluto_grid#701]
how can I change the column footer widget height?

**Comment by majdkurdi** [comment]
the setter for column footer height is implemented in the stateManager:
stateManager.columnFooterHeight = {{value}};

**Comment by SteveBraich** [comment]
> the setter for column footer height is implemented in the stateManager: stateManager.columnFooterHeight = {{value}};

OK, and where exactly do we set that?  I tried setting it in the onLoaded event of the grid, but the height of the footer is not affected.
