### ISSUE TITLE
[Help] Is it possible to make a single (or several but not all)row editable/non-editable? 

### ISSUE THREAD

**Issue by Retr0sec7** [bosskmk/pluto_grid#704]
So my PlutoGrid has an edit mode where you can edit/delete rows from it. Once a row has been marked for deletion, I want that row to not be editable without making all other rows not editable since the only way I've found to make this is to change the whole colum's `enableEditingMode` which make the whole column non-editable if set to false or changing `GridMode` to readOnly which disable all rows.

Is there a way to achieve this?

**Comment by ujwalbasnet1** [comment]
+1
