### ISSUE TITLE
[Bug] pdf export text direction is only LTR even when wrapping the grid with directionality and set to RTL

### ISSUE THREAD

**Issue by majdkurdi** [bosskmk/pluto_grid#706]
arabic text in pdf is drawn LTR although the text direction is RTL
<img width="950" alt="Screen Shot 2022-12-28 at 8 11 59 PM" src="https://user-images.githubusercontent.com/83834210/209840355-8690d8a0-91c7-4c6a-ae1e-4ab32401b36e.png">

**Comment by AL-YAFEA-KHALED** [comment]
Hi bro, which font you used here?
