### ISSUE TITLE
[Feature] - Add menu context before each row

### ISSUE THREAD

**Issue by luismarquesnearsea** [bosskmk/pluto_grid#708]

**Comment by Milad-Akarie** [comment]
@luismarquesnearsea have you tried using a column with a custom renderer?

**Comment by luismarquesnearsea** [comment]
I'm talking something like this way
![Screenshot 2023-01-05 at 21 00 06](https://user-images.githubusercontent.com/89921126/210878982-08cbcccd-ed4f-41ac-a36a-83cc23cb97b9.png)

**Comment by Milad-Akarie** [comment]
@luismarquesnearsea I don't see why toy can't do that using a custom renderer and basic PopupMenuButton

**Comment by luismarquesnearsea** [comment]
Because the renderer is for the column, I need it for each row. And as I can see the renderer is applied after the checkbox and rowDrag and not before the entire column.

**Comment by Milad-Akarie** [comment]
Ya i don't think it's possible to do such thing with the current setup
