### ISSUE TITLE
[Help][solved] Error: LateInitializationError: Field 'stateManager' has not been initialized

### ISSUE THREAD

**Issue by cbotelho** [bosskmk/pluto_grid#713]
I'm trying to assemble a PlutoDataGrid and the error only appears when debugging: "Error: LateInitializationError: Field 'stateManager' has not been initialized". I'm submitting my code:

import 'dart:core';
import 'package:get/get.dart';
import 'package:infodoc_cloud/app/models/entidade_model.dart';
import 'package:infodoc_cloud/app/controllers/entidade_controller.dart';
import 'package:pluto_grid/pluto_grid.dart';
import 'package:flutter/material.dart';

class EntidadeListWidget extends StatefulWidget {
        
  @override
  State<EntidadeListWidget> createState() => _DataGridPageState();

  List<EntidadeModel> entidades;
  EntidadeController controller;
  EntidadeListWidget(
      {super.key, required this.entidades, required this.controller});
}

class _DataGridPageState extends State<EntidadeListWidget>{
  
  final List<PlutoColumn> columns = <PlutoColumn>[
    PlutoColumn(title: 'ID', field: 'id', type: PlutoColumnType.number(),),
    PlutoColumn(title: 'Entidade', field: 'entidade', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'Sub Entidade', field: 'descricao', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'CNPJ', field: 'cnpj', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'Telefone Entidade', field: 'telefone', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'Contato', field: 'contato', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'Telefone Contato', field: 'telefonecontato', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'Endereço', field: 'endereco', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'Número', field: 'numero', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'Complemento', field: 'conplemento', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'Cep', field: 'cep', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'Cidade', field: 'municipio', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'Estado', field: 'uf', type: PlutoColumnType.text(),),
    PlutoColumn(title: 'Logo', field: 'logo', type: PlutoColumnType.text(),),
  ];
  
  final List<PlutoRow> rows =[
    PlutoRow(
      cells: {
        'id'              : PlutoCell(value: '1'),
        'nome'            : PlutoCell(value: 'PREFEITURA DE MACAPÁ' ),
        'descricao'       : PlutoCell(value: 'SEMDUH SEC DE HABITAÇÃO' ),
        'cnpj'            : PlutoCell(value: '12.345.789/0001-45' ),
        'telefone'        : PlutoCell(value: '(96)99963-6843' ),
        'contato'         : PlutoCell(value: 'CONTATO' ),
        'telefonecontato' : PlutoCell(value: 'TELEFONE CONTATO' ),
        'endereco'        : PlutoCell(value: 'ENDEREÇO' ),
        'numero'          : PlutoCell(value: 'NÚMERO' ),
        'complemento'     : PlutoCell(value: 'COMPLEMENTO' ),
        'cep'             : PlutoCell(value: 'CEP' ),
        'bairro'          : PlutoCell(value: 'BAIRRO' ),
        'municipio'       : PlutoCell(value: 'CIDADE' ),
        'uf'              : PlutoCell(value: 'ESTADO' ),
        'logo'            : PlutoCell(value: 'https://semduh/logo/logo.png'),
        
      }
    ),

    PlutoRow(
      cells: {
        'id'              : PlutoCell(value: '2' ),
        'nome'            : PlutoCell(value: 'PREFEITURA DE SANTANA' ),
        'descricao'       : PlutoCell(value: 'SEMDUH SEC DE HABITAÇÃO' ),
        'cnpj'            : PlutoCell(value: '12.345.789/0001-45' ),
        'telefone'        : PlutoCell(value: '(96)99963-6843' ),
        'contato'         : PlutoCell(value: 'CONTATO' ),
        'telefonecontato' : PlutoCell(value: 'TELEFONE CONTATO' ),
        'endereco'        : PlutoCell(value: 'ENDEREÇO' ),
        'numero'          : PlutoCell(value: 'NÚMERO' ),
        'complemento'     : PlutoCell(value: 'COMPLEMENTO' ),
        'cep'             : PlutoCell(value: 'CEP' ),
        'bairro'          : PlutoCell(value: 'BAIRRO' ),
        'municipio'       : PlutoCell(value: 'CIDADE' ),
        'uf'              : PlutoCell(value: 'ESTADO' ),
        'logo'            : PlutoCell(value: 'https://semduh/logo/logo.png'),
        
      }
    ),

    PlutoRow(
      cells: {
        'id'              : PlutoCell(value: '3' ),
        'nome'            : PlutoCell(value: 'PREFEITURA DE BARCARENA'),
        'descricao'       : PlutoCell(value: 'SEC DE EDUAÇÃO'),
        'cnpj'            : PlutoCell(value: '12.345.789/0001-45'),
        'telefone'        : PlutoCell(value: '(96)99963-6843'),
        'contato'         : PlutoCell(value: 'CONTATO'),
        'telefonecontato' : PlutoCell(value: 'TELEFONE CONTATO'),
        'endereco'        : PlutoCell(value: 'ENDEREÇO'),
        'numero'          : PlutoCell(value: 'NÚMERO'),
        'complemento'     : PlutoCell(value: 'COMPLEMENTO'),
        'cep'             : PlutoCell(value: 'CEP'),
        'bairro'          : PlutoCell(value: 'BAIRRO'),
        'municipio'       : PlutoCell(value: 'CIDADE'),
        'uf'              : PlutoCell(value: 'ESTADO'),
        'logo'            : PlutoCell(value: 'https://semduh/logo/logo.png'),
        
      }
    ),

    PlutoRow(
      cells: {
        'id'              : PlutoCell(value: '4' ),
        'nome'            : PlutoCell(value: 'PREFEITURA DE FERREIRA GOMES'),
        'descricao'       : PlutoCell(value: 'SEC DE EDUAÇÃO'),
        'cnpj'            : PlutoCell(value: '12.345.789/0001-45'),
        'telefone'        : PlutoCell(value: '(96)99963-6843'),
        'contato'         : PlutoCell(value: 'CONTATO'),
        'telefonecontato' : PlutoCell(value: 'TELEFONE CONTATO'),
        'endereco'        : PlutoCell(value: 'ENDEREÇO'),
        'numero'          : PlutoCell(value: 'NÚMERO'),
        'complemento'     : PlutoCell(value: 'COMPLEMENTO'),
        'cep'             : PlutoCell(value: 'CEP'),
        'bairro'          : PlutoCell(value: 'BAIRRO'),
        'municipio'       : PlutoCell(value: 'CIDADE'),
        'uf'              : PlutoCell(value: 'ESTADO'),
        'logo'            : PlutoCell(value: 'https://semduh/logo/logo.png'),
        
      }
    ),
  ];

  
  late final PlutoGridStateManager? stateManager; **<= where the error appears**

  @override
  Widget build(BuildContext context){

    return Container(
      padding: const EdgeInsets.all(15),
      child: PlutoGrid(
        columns: columns, 
        rows: rows,
        onLoaded: (PlutoGridOnLoadedEvent event){stateManager = event.stateManager;},
        onChanged: (PlutoGridOnChangedEvent event){print(event);},
        configuration: const PlutoGridConfiguration(),
      ),
    );
  } 
}

**Comment by upperxcode** [comment]
Hello, I have a similar problem, only during development, in case of doing a hot-reload, the stateManager becomes invalid. How did you manage to solve it?

**Comment by VittorioParagallo** [comment]
> Hello, I have a similar problem, only during development, in case of doing a hot-reload, the stateManager becomes invalid. How did you manage to solve it?

I have the same issue, how did you solve it?
