### ISSUE TITLE
[Help] How to get filtering changes when the user is typing in filtering field.

### ISSUE THREAD

**Issue by sachintha-s** [bosskmk/pluto_grid#724]
I want to get updates when the user types something in the filtering field and makes a network call to the server to get filtered data. I used `stateManager.addListener(() { functionForAPICall()})` but it triggers every time. only I want to trigger the function when the user is typing. I see there is a function that triggers when the sort is happening (ex:  `onSorted: (event) {print(event)}`), but didn't find anything like that for filtering so can you help me? thank you.

**Comment by bosskmk** [comment]
https://pluto.weblaze.dev/rows-from-server-side

If you are importing data from the server, please refer to the link above.

**Comment by sachintha-s** [comment]
> https://pluto.weblaze.dev/rows-from-server-side
> 
> If you are importing data from the server, please refer to the link above.

@bosskmk  If I use a custom footer How can I use the fetch() function inside it?
