### ISSUE TITLE
[Help] How can I implement "command + click" to select multiple rows?

### ISSUE THREAD

**Issue by maximum-maximum** [bosskmk/pluto_grid#726]
Thank you for providing us with a great library.
https://weblaze.dev/pluto_grid/build/web/#development
In this demo it looks like you can select and deselect rows by "command + click", how can this be implemented?
As far as I could find in the documentation, I could not seem to find it.

**Comment by motucraft** [comment]
@maximum-maximum 

How about this?
https://zapp.run/edit/flutter-zp1e06bep1f0?entry=lib/main.dart&file=lib/main.dart

**Comment by maximum-maximum** [comment]
@motucraft 
This is exactly what I wanted to do!
I see that setting the event on onLoad is the key.
Thank you for including the sample code!
