### ISSUE TITLE
cell color and line height

### ISSUE THREAD

**Issue by upperxcode** [bosskmk/pluto_grid#73]
First of all thanks for the widget, it is really very good.
Seeing the documentation, I realized that the customization of the lines and cells will be done in the future. Do you have any plans to include height of lines and colors by cells?

**Comment by bosskmk** [comment]
First of all, thank you for your interest in PlutoGrid.
I would like to add the features requested in Issue, including the ones you said.
I will try.

**Comment by upperxcode** [comment]
> Em primeiro lugar, obrigado pelo seu interesse no PlutoGrid.
> Gostaria de acrescentar os recursos solicitados na edição, inclusive os que você falou.
> Eu vou tentar.

thanks!

**Comment by upperxcode** [comment]
It was very good, I saw that it took some work to set the height of the line. Thank you very much for the excellent work.
