### ISSUE TITLE
[Bug] PlutoGridStateManager listener no longer called when column is resized

### ISSUE THREAD

**Issue by dsyrstad** [bosskmk/pluto_grid#730]
### Steps to reproduce the bug
1.Create a `PlutoGrid` and, when when `onLoaded()` is called, add a listener with `PlutoGridStateManager.addListener()`. 
2. In the UI, resize a column width.

### Expected results
The listener is called when the column is resized. This was working in 4.0.1.

### Actual results
After upgrading to 6.0.1 today, the listener is no longer called. I also cannot find any alternate way of getting this event.

### Code sample
Seems to be reproducible with any grid.

### Execution Environment
**Flutter version is 3.3.10**

**PlutoGrid version is 6.0.1**

**OS**
Web, Linux

**Comment by bosskmk** [comment]
You can call a callback function when resizing a column as shown below.
However, when adding actual logic, debounce may be required due to very frequent calls.

```dart
stateManager.resizingChangeNotifier.addListener(() {
  print('resize');
});
```

**Comment by dsyrstad** [comment]
@bosskmk `resizingChangeNotifier` works perfect. Thank you!
