### ISSUE TITLE
[Help] How to assign column groups dynamically ?

### ISSUE THREAD

**Issue by kpahuja** [bosskmk/pluto_grid#731]
How do I use the stateManager to assign coulmn groups dynamically? 
When I remove old columns and insert new ones, the column groups go away.
I see a function setGroupToColumn() but encounter the following issue while trying to invoke it: 

the member 'setGroupToColumn' can only be used within instance members of subclasses of 'package:pluto_grid/src/manager/state/column_group_state.dart'.

Thanks.

**Comment by KamilSvoboda** [comment]
Same situation - column groups are lost when I remove and insert columns using stateManager. 

```
      resStateManager!.removeAllRows();
      var hasGroups = resStateManager!.hasColumnGroups;    //TRUE
      resStateManager!.removeColumns(resStateManager!.columns);
      resStateManager!.insertColumns(0, _getColumns(context));
      haGroups = resStateManager!.hasColumnGroups;  //FALSE!
```
