### ISSUE TITLE
[Help] Dependency with intl

### ISSUE THREAD

**Issue by DBOutlink** [bosskmk/pluto_grid#742]
I have a problem with last versione of pluto_grid:

![image](https://user-images.githubusercontent.com/104137428/216979582-f252dcbd-bbf4-4347-99a8-7a188af1cf97.png)

Any ideas?

**Comment by mmasdivins** [comment]
Same problem

**Comment by sandapilrius** [comment]
Temporarily overrides dependencies.
![cursor](https://user-images.githubusercontent.com/104423465/218732209-d8b32adc-18cb-45e5-9c45-3137614aab89.png)

**Comment by mmasdivins** [comment]
Thanks, is what I did.
Is this because flutter still does not use intl 0.18.0?

**Comment by sandapilrius** [comment]
> 


that's right. It's a problem with the flutter sdk supported version. :)
