### ISSUE TITLE
[Help] Mouse scrolling issues

### ISSUE THREAD

**Issue by unvestigate** [bosskmk/pluto_grid#743]
I have two issues with PlutoGrid related to scrolling. I hope you can help me figure out if these are limitations/bugs with the library or if I am doing something wrong and/or can work around the issues.

- The first issues is that if I quickly click and grab a scrollbar thumb it doesn't react to the mouse movement. I need to press the mouse button down while keeping the mouse still for a second or so (perhaps shorter) and then move the mouse to have the thumb follow the mouse movement. Why is this? Can I make the thumbs react to instant click-and-drag (as any other scrollbar I have used works)?

- The second issue is also related to dragging the scrollbar thumbs with the mouse. The scrolling works more or less how I expect it to, but when I let go of the mouse the view always scrolls up/down a little bit more, almost as if I had swiped the view with a finger on a touch display. Can this "scrolling inertia" be turned off completely for the PlutoGrid?

Otherwise, thanks for an excellent widget!

**Comment by unvestigate** [comment]
Both of the issues can be experienced here: https://weblaze.dev/pluto_grid/build/web/#feature/add-rows-asynchronously

Click and drag the thumb of the vertical scrollbar with a mouse. Quite often it doesn't get dragged by the mouse at all, unless you press, then keep the mouse still for a while, and then move the mouse. Additionally, quite often when letting go of the thumb the view scrolls wildly up or down.

**Comment by unvestigate** [comment]
Maybe my explanation of the second issue was a bit vague. What I mean is this: If I Click and drag the thumb of the scrollbar I naturally expect the view to scroll. If I then stop moving the mouse and let go of the button, I expect the view to stay where it is. However, quite often (it seems to depend on how far/quickly the mouse was moved previously) the view stays still while the button is pressed (as long as the mouse isn't moving of course) but as soon as the I let go of the button the view scrolls up or down, even though the mouse is still not moving. I would like to get rid of this last movement of the view.

**Comment by bosskmk** [comment]
I'm not sure if I understood the two issues well. I applied the fix to the branch below.
1. When you stop dragging the scroll bar, it no longer scrolls.
2. Make the mouse down event time of the scroll bar immediately responsive.

Please try running PlutoGrid with the branch version below and give us a response.

```yaml
dependencies:
  pluto_grid:
    git:
      url: https://github.com/bosskmk/pluto_grid.git
      ref: feature/scrollbar-test
```

**Comment by unvestigate** [comment]
Awesome! Based on a 5-minute test the scrollbar-test branch fixes all the issues I listed above. Thank you!

**Comment by bosskmk** [comment]
Updated to PlutoGrid 6.0.4.
You can set as below.

enableScrollAfterDragEnd: If set to false, scrolling will stop as soon as the scrollbar is released.
longPressDuration: Sets the long press duration for moving the scroll bar.

```dart
configuration: const PlutoGridConfiguration(
  scrollbar: PlutoGridScrollbarConfig(
    enableScrollAfterDragEnd: false,
    longPressDuration: Duration(milliseconds: 1),
  ),
),
```

**Comment by unvestigate** [comment]
Great, thanks!
