### ISSUE TITLE
[Help] setState() or markNeedsBuild() called when widget tree was locked.

### ISSUE THREAD

**Issue by PudgeKim** [bosskmk/pluto_grid#749]
I got an error below.
```
The following assertion was thrown while dispatching notifications for PlutoGridStateManager:
setState() or markNeedsBuild() called when widget tree was locked.
```

Is it possible that this is related to `stateManager.setEditing` method?

**Comment by bosskmk** [comment]
I can't figure out your logic, but it looks like the problem is caused by executing a method in the build phase.
Try changing the problematic call to the following:

```dart
WidgetsBinding.instance.addPostFrameCallback(() {
   // do something
});
```

**Comment by PudgeKim** [comment]
hmm.. I regeister the `stateManager` into the Provider.
Is this kind of code fine?
```
late final PlutoGridStateManager stateManager;

return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => stateManager),
      ],
 ```
 or this can occurr some problem when it listens the event?

**Comment by bosskmk** [comment]
Passing the `stateManager` as `ChangeNotifierProvider` seems to cause the entire `PlutoGrid` to be rebuilt whenever the `stateManager` changes. (`stateManager` can change very frequently. Internally, appropriate widgets are implemented to react.)

If you explain more about the intent you need to pass to provider , I think I can give you an answer.

`setEditing` changes whether the currently selected cell is in the editing state.
Depending on the edit state, the cell will render a `TextField` and allow the cell value to be edited.

**Comment by PudgeKim** [comment]
so If I do `setEditing(true)`, it will render a `TextField` right?

When I delete stateManager from Provider, the error is gone.
The reason why I need to use  `stateManager` with `Provider` is ..

I have a main stateManager and when a user press the specific key, another stateManager is created. (Because sub-screen is opened so new stateManager is needed.)

For example, I created a class which handles saving file like this.
```
class SaveFileAction extends PlutoGridShortcutAction {
  BuildContext context;

  SaveFileAction(this.context);

  @override
  void execute({required PlutoKeyManagerEvent keyEvent, required PlutoGridStateManager stateManager}) {
    var mainStateManager = Provider.of<PlutoGridStateManager>(context, listen: false);

    if (identical(stateManager, mainStateManager)) { // If these are identical, it means there is no sub-screen.
      stateManager.setEditing(false); // Do I need this?
      handleSave(context, stateManager);
    }
  }
}
```
