### ISSUE TITLE
[Help] Combine external filters with column header filters

### ISSUE THREAD

**Issue by BilPat** [bosskmk/pluto_grid#753]
Hello,

First of all thank you for your superb work, i really like Plutogrid!
I have a question about filtering by external code, as I'm using a daterangepicker to filter my data, which as far as i know, is not possible with the column head filters - the corresponding code for my filter is down below.
The issue is, that whenever I'm using my external filter the column header filters are overwritten (obviously, since I'm setting a new one) and vice versa. That brings my to the question: Is there any way of adding this external filter to the already existing ones?

Thank you in advance!

```
filterByDate(startdate, enddate) {
    var correctedStartdate =
        DateTime(startdate.year, startdate.month, startdate.day);
    var correctedEnddate = DateTime(enddate.year, enddate.month, enddate.day);
    stateManager.setFilter((element) {
      var deliverydate = DateFormat("dd.MM.yyyy")
          .parse(element.cells.entries.elementAt(8).value.value);
      if ((correctedStartdate.isBefore(deliverydate) &&
              correctedEnddate.isAfter(deliverydate)) ||
          correctedStartdate.isAtSameMomentAs(deliverydate) ||
          correctedEnddate.isAtSameMomentAs(deliverydate)) {
        return true;
      } else {
        return false;
      }
    });
  }
```

**Comment by bosskmk** [comment]
hello.
Would you like to know how to add custom filters?
Please refer to the link below.

https://pluto.weblaze.dev/configuration#heading-user-defined-column-filters
