### ISSUE TITLE
[Bug] Add Rows Asynchronously Demo is wrong

### ISSUE THREAD

**Issue by CesareIsHere** [bosskmk/pluto_grid#754]
### Steps to reproduce the bug
1. Open  Add Rows Asynchronously Demo
2. No empty row provided at the start of the grid

### Expected results
Should be provided an empty row at the start of the grid.

**Comment by bosskmk** [comment]
hello.
What problems are you experiencing?
When I start the grid with an empty list, which means empty rows, the problem doesn't happen.
Can you provide a minimal sample code that I can reproduce?

**Comment by CesareIsHere** [comment]
Sorry for my poor explanation. 
I'm talking about this: https://weblaze.dev/pluto_grid/build/web/#feature/add-rows-asynchronously
The example should have an empty row at the start of the grid right? Or did I misunderstand?

**Comment by bosskmk** [comment]
This example shows an example of adding a row asynchronously.
By default, PlutoGrid provides rows on startup with data ready, but how to do otherwise (fetching data from DB, etc.). (from source link)

**Comment by CesareIsHere** [comment]
Okay, clear. Thank you!
