### ISSUE TITLE
[Feature] Add onChangedRow callback

### ISSUE THREAD

**Issue by mmasdivins** [bosskmk/pluto_grid#755]
Hello, first of all thanks for this amazing project.
I would like to request a feature to add and onRowChanged callback, it will be helpful since, in my case I make an API request to update every row after they are changed. Right now I can track the cells changed and when the user changes the row or submits I send the tracked changes to the server.
It would be easier if there was a callback when a row is changed with the old value of the row and the new value.
Thanks!

**Comment by ganapathyp** [comment]
You can use gridMode.select and implement a custom dialog for user input. You can update or add new row with a submit button (on custom dialog)... There is a sample in the demo page as well.

**Comment by mmasdivins** [comment]
I didn't want to do it with a dialog, I prefer the inline edit. I forked the project and added and onRowChanged for my own use.
Thanks!
