### ISSUE TITLE
[Help]  입력란의 커서 위치 설정을 도저히 못 찾겠어요

### ISSUE THREAD

**Issue by sandapilrius** [bosskmk/pluto_grid#756]
멋진 패키지 감사히 잘 쓰고 있습니다.
다름이 아니라, 테이블 안에서나 검색 팝업에서의 텍스트 필드가 스크린샷에서 보시는 것처럼 범위를 벗어나 있어요. 제 글꼴 테마나 material 테마 설정 문제인가 싶어 모두 지우고 runApp 이후에 material만 넣고 바로 불러와도 저렇게 보이네요.

신기한 건, 지금도 데모로 올려 놓으신 웹에선 아무 문제 없이 잘 보이고 있단 말이죠.
어느 곳에서 제 문제를 찾아봐야 할 지 힌트를 부탁드려도 될까요.

![cursor](https://user-images.githubusercontent.com/104423465/218731428-620b2780-2ee1-4826-be0d-5fa809582be8.png)

**Comment by bosskmk** [comment]
안녕하세요.
해당 문제를 재현해 볼수는 있는데,
그냥은 안되고 강제로 내부에서 사용되는 `TextField` 의 `BorderSide.none` 을 제거하면 가능은 합니다.
하지만 내부 소스코드를 수정하지 않는이상 동일한 문제를 재현 할 수는 없었습니다.
`useMaterial3: true` 문제인가도 봤는데 역시 문제는 없었습니다.
사용중이신 다른 패키지에서 문제를 발생 시킬 수도 있지 않을까 생각해봅니다.

**Comment by bosskmk** [comment]
아마도 특정 환경이나 특정 버전, 특정 패키지 등의 사용등의 문제로 보여집니다.
혹시 예상되는 것들이 있으시다면 댓글로 알려주세요. 확인해보겠습니다.
감사합니다.

**Comment by sandapilrius** [comment]
> 

너무 허무하게 찾았어요. theme 관련 패키지인 flex_color_scheme가 문제였습니다. input decoration을 설정할 수 있는 간단한 enum 타입의 메서드를 주는데 제공하는 둘 중 무엇을 골라도 textfield를 가만히 놔두지 않더군요. 패키지 지우고는 아주 잘 동작합니다.

메일로 현재 개발 중인 앱의 간단한 스크린샷을 보내드렸어요.
