### ISSUE TITLE
Save current editted cell

### ISSUE THREAD

**Issue by baptistesx** [bosskmk/pluto_grid#757]
Hi!

First thank you for this very nice package I've discovered today and starting to use in my project.

I started from this example: [add-and-remove-column-row](https://weblaze.dev/pluto_grid/build/web/#add-and-remove-column-row)

I have a question:
When editting a cell then clicking on "save all", the editted cell didn't get the status "editted" so i cannot save it...

Is there a way in the "save all" function, to retrieve the cell which is currently getting editted, mark it as "edited"?

Thank in advance :)

**Comment by bosskmk** [comment]
Please refer to the code below with the handleSaveAll method modified in the example.
If the current cell is being edited, the currently entered value is changed to a value in `TextEditingController` and then the logic is processed.

```dart
void handleSaveAll() {
  if (widget.stateManager.isEditing &&
      widget.stateManager.currentCell != null) {
    widget.stateManager.changeCellValue(
      widget.stateManager.currentCell!,
      widget.stateManager.textEditingController?.text,
    );
  }

  widget.stateManager.setShowLoading(true);

  Future.delayed(const Duration(milliseconds: 500), () {
    for (var row in widget.stateManager.refRows) {
      if (row.cells['status']!.value != 'saved') {
        row.cells['status']!.value = 'saved';
      }

      if (row.cells['id']!.value == '') {
        row.cells['id']!.value = 'guest';
      }

      if (row.cells['name']!.value == '') {
        row.cells['name']!.value = 'anonymous';
      }
    }

    widget.stateManager.setShowLoading(false);
  });
}
```

**Comment by baptistesx** [comment]
Awesome thank you so much for your reactivity!
