### ISSUE TITLE
[Bug] - Getting error on 6.0.0 to 6.0.2

### ISSUE THREAD

**Issue by luismarquesnearsea** [bosskmk/pluto_grid#760]
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/pluto_grid-6.0.2/lib/src/helper/show_column_menu.dart:85:27: Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../Downloads/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try accessing using ?. instead.
      Overlay.of(context).context.findRenderObject() as RenderBox;
                          ^^^^^^^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/pluto_grid-6.0.2/lib/src/ui/columns/pluto_column_title.dart:82:17: Error: The getter 'mounted' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../Downloads/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'mounted'.
    if (context.mounted) {
                ^^^^^^^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/pluto_grid-6.0.2/lib/src/ui/miscellaneous/pluto_visibility_layout.dart:421:11: Error: Superclass has no method named 'performRebuild'.
    super.performRebuild();
          ^^^^^^^^^^^^^^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/pluto_grid-6.0.2/lib/src/helper/show_column_menu.dart:85:27: Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../Downloads/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try accessing using ?. instead.
      Overlay.of(context).context.findRenderObject() as RenderBox;
                          ^^^^^^^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/pluto_grid-6.0.2/lib/src/ui/columns/pluto_column_title.dart:82:17: Error: The getter 'mounted' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../Downloads/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'mounted'.
    if (context.mounted) {
                ^^^^^^^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/pluto_grid-6.0.2/lib/src/ui/miscellaneous/pluto_visibility_layout.dart:421:11: Error: Superclass has no method named 'performRebuild'.
    super.performRebuild();
          ^^^^^^^^^^^^^^

**Comment by bosskmk** [comment]
Is your Flutter version 3.7 or higher?
