### ISSUE TITLE
Add / Remove Rows

### ISSUE THREAD

**Issue by WeApplifyTechSource** [bosskmk/pluto_grid#77]
Grid must take focus after clicking on Add/Remove Rows, as of now the Button "Add/Remove" gains the focus and focus remains on the button only. The focus must go back to the grid

**Comment by bosskmk** [comment]
Is the problem you mentioned in the Demo?

I would appreciate it if you can tell me how to reproduce it.

**Comment by NiranjanShah** [comment]
Apologies for delayed response, the problem is happening in Demo

**Comment by bosskmk** [comment]
In the demo, tapping the add or remove rows button confirms that the grid retains focus.
demo link : https://weblaze.dev/pluto_grid/build/web/#add-and-remove-rows
