### ISSUE TITLE
[Help] How to set image, colors or icons in plutocell

### ISSUE THREAD

**Issue by intxx1** [bosskmk/pluto_grid#770]
Hi,

I want to know how to set images, text colors or icons in a plutocell. Thanks.

**Comment by GP4cK** [comment]
I'm just a random guy passing by and evaluating this package for potential future use.
I've quickly checked the source code and it looks like you may be able to do what you want if you give a `PlutoColumnRenderer` to your `PlutoColumn`. There's a nice example in the code:
https://github.com/bosskmk/pluto_grid/blob/4d30d579c975a99900ca585757f1d03cd554acb2/lib/src/model/pluto_column.dart#L120
