### ISSUE TITLE
[Bug] PlutoRow expand true does not expand

### ISSUE THREAD

**Issue by neholouis** [bosskmk/pluto_grid#775]
Hi there ! 

### Steps to reproduce the bug
Create PlutoRow that type are group.
Set to expand: true

### Expected results
The row is expanded by default and shows its children.

### Actual results
The row is not expanded but the arrow is shown as if the row was expanded

### Code sample
```dart
PlutoRow(
        type: node.children.isNotEmpty
            ? PlutoRowType.group(
            expanded: true,
            children: FilteredList<PlutoRow>(
                initialList:
                _generateRows(context, node.children, questionResults)))
            : const PlutoRowTypeNormal(),
        cells: {
          'team': PlutoCell(value: node.label),
          'score': PlutoCell(value: result?.score),
          'minScore': PlutoCell(value: result?.minScore),
          'maxScore': PlutoCell(value: result?.maxScore),
          'average': PlutoCell(value: result?.average)
        });
```

### Execution Environment
**Flutter version**
Flutter version is 3.7.5

**PlutoGrid version**
PlutoGrid version is 6.0.2

**OS**
MacOS
Web

Thanks !

**Comment by bosskmk** [comment]
Fixed in version 6.0.3.
Please check and please comment if you have any problems.
thank you
