### ISSUE TITLE
Row data not updating according to dropdown values  and when user changes the api value its is not saved 

### ISSUE THREAD

**Issue by sandhyashrestha016** [bosskmk/pluto_grid#787]
`// ignore_for_file: depend_on_referenced_packages, prefer_const_literals_to_create_immutables, prefer_const_constructors, avoid_print, prefer_typing_uninitialized_variables, file_names, unrelated_type_equality_checks, constant_identifier_names

import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:nb_utils/nb_utils.dart';
import 'package:pluto_grid/pluto_grid.dart';

import '../../config/my_config.dart';
import '../../helper/constants.dart';
import '../../riverpod/models/ClassForTableDropdownModel.dart';
import '../../riverpod/models/ExamModel.dart';
import '../../riverpod/models/SectionModel.dart';
import '../../riverpod/models/SubjectModel.dart';
import '../../riverpod/provider/ClassForTableDropdownProvider.dart';
import '../../riverpod/provider/TeacherMarkentryProvider.dart';
import '../../services/baseDio.dart';
import '../../utils/text_const.dart';

class _Product {
  factory _Product.fromJson(Map<String, dynamic> json) => _Product(
        examMarkEntryDetailId: json["examMarkEntryDetailId"],
        studentId: json["studentId"],
        rollNo: json["rollNo"],
        studentName: json["studentName"],
        theoryFullMarks: json["theoryFullMarks"],
        practicalFullMarks: json["practicalFullMarks"],
        theoryObtainedMarks: json["theoryObtainedMarks"],
        theoryStatus: json["theoryStatus"],
        practicalObtainedMarks: json["practicalObtainedMarks"],
        practicalStatus: json["practicalStatus"],
        totalMarks: json["totalMarks"],
        narration: json["narration"],
        isPractical: json["isPractical"],
        isTheory: json["isTheory"],
        id: json["id"],
      );

  _Product({
    this.examMarkEntryDetailId,
    this.studentId,
    this.rollNo,
    this.studentName,
    this.theoryFullMarks,
    this.practicalFullMarks,
    this.theoryObtainedMarks,
    this.theoryStatus,
    this.practicalObtainedMarks,
    this.practicalStatus,
    this.totalMarks,
    this.narration,
    this.isPractical,
    this.isTheory,
    this.id,
  });

  String? examMarkEntryDetailId;
  String? studentId;
  int? rollNo;
  String? studentName;
  double? theoryFullMarks;
  double? practicalFullMarks;
  double? theoryObtainedMarks;
  int? theoryStatus;
  double? practicalObtainedMarks;
  int? practicalStatus;
  double? totalMarks;
  String? narration;
  bool? isPractical;
  bool? isTheory;
  dynamic id;
}

// var sectionSelectedvalue = "00000000-0000-0000-0000-000000000000";

// var subjectSelectedvalue = "0e5eb25e-4bac-4392-54f8-08db0fe53802";

// var examSelectedvalue = "f7921ec9-1c36-4b80-81f9-08db0fe53818";

// var _classselectedItem = "518b4a9b-784a-4c05-d446-08db0fe537ad";
enum ExamStatus { Absent, Present, Expelled }

class StudentMarksEntries extends ConsumerStatefulWidget {
  const StudentMarksEntries({super.key});

  @override
  ConsumerState<ConsumerStatefulWidget> createState() =>
      _StudentMarksEntriesState();
}

class _StudentMarksEntriesState extends ConsumerState<StudentMarksEntries> {
  ClassForTableDropdown? _classselectedItem;

  //  PlutoGridStateManager? stateManager;
  // Get the PlutoGridStateManager
  // PlutoGridStateManager stateManager = PlutoGridStateManager(
  //     columns: [], gridFocusNode: null, rows: [], scroll: null);

  final _formKey = GlobalKey<FormState>();
  // List<PlutoRow> updatedRows = [];

  @override
  Widget build(BuildContext context) {
    bool allSelected = _classselectedItem != null &&
        sectionSelectedvalue != null &&
        subjectSelectedvalue != null &&
        examSelectedvalue != null;
    final height = MediaQuery.of(context).size.height;
    final width = MediaQuery.of(context).size.width;
    final classForTableDropdown = ref.watch(classForTableDropdownDataProvider);
    dynamic newdata;
// // Get the updated data for row 1
//     PlutoRow updatedRow = stateManager!.getNewRow();

// // Get the value of a specific column in the updated row
//     String updatedValue = updatedRow.cells['tom']!.value;

// // Print the updated value
//     print(updatedValue);
    // dynamic newvalue;

    return Scaffold(
      appBar: getSmallAppBar(context, "Student Marks Entries"),
      body: SingleChildScrollView(
        child: Padding(
          padding: EdgeInsets.symmetric(
              horizontal: width * 0.04, vertical: height * 0.03),
          child: Column(
            children: [
              Align(
                  alignment: Alignment.topRight,
                  child: ElevatedButton.icon(
                      onPressed: save,
                      icon: Icon(Icons.check_box_sharp),
                      label: Text("Save"))),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          " Class",
                          style: getsubtitleSize(context),
                        ),
                        SizedBox(height: height * 0.01),
                        classForTableDropdown.when(
                          data: (value) => DropdownButtonFormField(
                            isExpanded: true,
                            isDense: true,
                            decoration: InputDecoration(
                              hintText: "Select Class",
                              hintStyle: getSimple(context, 0.022),
                              enabledBorder: OutlineInputBorder(
                                borderSide: const BorderSide(
                                    color: Colors.grey, width: 2),
                                borderRadius: BorderRadius.circular(10),
                              ),
                              border: OutlineInputBorder(
                                borderSide: const BorderSide(
                                    color: Colors.grey, width: 2),
                                borderRadius: BorderRadius.circular(10),
                              ),
                            ),
                            validator: (value) =>
                                value == null ? 'Field is required' : null,
                            onChanged: (var value) {
                              setState(() {
                                _classselectedItem = value!;

                                getExam();
                                getSection();
                                getSubject();
                                print("select = $_classselectedItem");
                              });
                            },
                            value: _classselectedItem,
                            items: value.map((item) {
                              return DropdownMenuItem(
                                value: item,
                                child: Text(item.displayName.toString(),
                                    overflow: TextOverflow.ellipsis),
                              );
                            }).toList(),
                          ),
                          loading: () => const Center(child: Text("")),
                          error: (e, __) => Center(child: Text(e.toString())),
                        ),
                      ],
                    ),
                  ),
                  SizedBox(width: width * 0.08),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          " Exam",
                          style: getsubtitleSize(context),
                        ),
                        SizedBox(height: height * 0.01),
                        DropdownButtonFormField(
                          isExpanded: true,
                          isDense: true,
                          decoration: InputDecoration(
                            hintText: "Select Exam",
                            hintStyle: getSimple(context, 0.022),
                            enabledBorder: OutlineInputBorder(
                              borderSide: const BorderSide(
                                  color: Colors.grey, width: 2),
                              borderRadius: BorderRadius.circular(10),
                            ),
                            border: OutlineInputBorder(
                              borderSide: const BorderSide(
                                  color: Colors.grey, width: 2),
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                          value: examSelectedvalue,
                          items: examlist.map((item) {
                            return DropdownMenuItem(
                              value: item,
                              child: Text(item["displayName"].toString(),
                                  overflow: TextOverflow.ellipsis),
                            );
                          }).toList(),
                          onChanged: (var newValue) {
                            setState(() {
                              examSelectedvalue = newValue!;
                            });
                          },
                          validator: (value) =>
                              value == null ? 'Field is required' : null,
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              SizedBox(height: height * 0.04),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          " Section",
                          style: getsubtitleSize(context),
                        ),
                        SizedBox(height: height * 0.01),
                        DropdownButtonFormField(
                          isExpanded: true,
                          isDense: true,
                          decoration: InputDecoration(
                            hintText: "Select Section",
                            hintStyle: getSimple(context, 0.022),
                            enabledBorder: OutlineInputBorder(
                              borderSide: const BorderSide(
                                  color: Colors.grey, width: 2),
                              borderRadius: BorderRadius.circular(10),
                            ),
                            border: OutlineInputBorder(
                              borderSide: const BorderSide(
                                  color: Colors.grey, width: 2),
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                          value: sectionSelectedvalue,
                          items: sectionlist.map((item) {
                            return DropdownMenuItem(
                              value: item,
                              child: Text(item["displayName"].toString(),
                                  overflow: TextOverflow.ellipsis),
                            );
                          }).toList(),
                          onChanged: (var newValue) {
                            setState(() {
                              sectionSelectedvalue = newValue!;
                            });
                          },
                          validator: (value) =>
                              value == null ? 'Field is required' : null,
                        ),
                      ],
                    ),
                  ),
                  SizedBox(width: width * 0.08),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          " Subject",
                          style: getsubtitleSize(context),
                        ),
                        SizedBox(height: height * 0.01),
                        DropdownButtonFormField(
                          isExpanded: true,
                          isDense: true,
                          decoration: InputDecoration(
                            hintText: "Select Subject",
                            hintStyle: getSimple(context, 0.022),
                            enabledBorder: OutlineInputBorder(
                              borderSide: const BorderSide(
                                  color: Colors.grey, width: 2),
                              borderRadius: BorderRadius.circular(10),
                            ),
                            border: OutlineInputBorder(
                              borderSide: const BorderSide(
                                  color: Colors.grey, width: 2),
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                          value: subjectSelectedvalue,
                          items: subjectlist.map((item) {
                            return DropdownMenuItem(
                              value: item,
                              child: Text(item["displayName"].toString(),
                                  overflow: TextOverflow.ellipsis),
                            );
                          }).toList(),
                          onChanged: (var newValue) {
                            setState(() {
                              subjectSelectedvalue = newValue!;
                            });
                          },
                          validator: (value) =>
                              value == null ? 'Field is required' : null,
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              SizedBox(height: height * 0.04),
              allSelected
                  ? SizedBox(
                      height: height * 0.55,
                      child: FutureBuilder(
                        future: fetchSummary(),
                        builder: (ctx, snapshot) {
                          if (snapshot.hasData) {
                            List<_Product>? data = snapshot.data;
                            bool a = data!
                                .where((element) => element.isTheory == true)
                                .toList()
                                .isNotEmpty;
                            return Form(
                              key: _formKey,
                              child: PlutoGrid(
                                //key: _plutoGridKey,
                                columns: [
                                  PlutoColumn(
                                    enableColumnDrag: false,
                                    title: 'ROLL NO',
                                    field: 'Roll No',
                                    enableContextMenu: false,
                                    type: PlutoColumnType.number(
                                      negative: false,
                                    ),
                                    // frozen: PlutoColumnFrozen.start,
                                    enableSorting: false,
                                    enableEditingMode: false,
                                  ),
                                  PlutoColumn(
                                    width: 200,
                                    enableColumnDrag: false,
                                    title: 'STUDENT NAME',
                                    field: 'stu_name',
                                    enableContextMenu: false,
                                    type: PlutoColumnType.text(),
                                    readOnly: true,
                                  ),
                                  PlutoColumn(
                                    hide: true,
                                    width: 200,
                                    enableColumnDrag: false,
                                    title: 'THEORY FULL MARK',
                                    field: 'tfm',
                                    enableContextMenu: false,
                                    type: PlutoColumnType.number(
                                      negative: false,
                                    ),
                                  ),
                                  PlutoColumn(
                                    width: 200,
                                    enableColumnDrag: false,
                                    title: 'THEORY OBTAINED MARK',
                                    field: 'tom',
                                    enableContextMenu: false,
                                    type: PlutoColumnType.number(
                                      negative: false,
                                    ),
                                  ),
                                  PlutoColumn(
                                    width: 200,
                                    enableColumnDrag: false,
                                    title: 'THEORY STATUS',
                                    field: 'ts',
                                    type: PlutoColumnType.select(
                                        ["Absent", "Present", "Expelled"]),
                                    enableContextMenu: false,
                                  ),
                                  if (!a)
                                    PlutoColumn(
                                      hide: true,
                                      width: 200,
                                      enableColumnDrag: false,
                                      title: 'PRACTICAL FULL MARK',
                                      field: 'pfm',
                                      enableContextMenu: false,
                                      type: PlutoColumnType.number(
                                        negative: false,
                                      ),
                                    ),
                                  if (!a)
                                    PlutoColumn(
                                      width: 200,
                                      enableColumnDrag: false,
                                      title: 'PRACTICAL OBTAINED MARK',
                                      field: 'pom',
                                      enableContextMenu: false,
                                      type: PlutoColumnType.number(
                                        negative: false,
                                      ),
                                    ),
                                  if (!a)
                                    PlutoColumn(
                                      width: 200,
                                      enableColumnDrag: false,
                                      title: 'PRACTICAL STATUS',
                                      field: 'ps',
                                      type: PlutoColumnType.select(
                                          ["Absent", "present", "expelled"]),
                                      enableContextMenu: false,
                                    ),
                                  PlutoColumn(
                                    width: 200,
                                    enableColumnDrag: false,
                                    title: 'TOTAL MARK',
                                    field: 'tm',
                                    type: PlutoColumnType.number(
                                      negative: false,
                                    ),
                                    readOnly: true,
                                    enableContextMenu: false,
                                  ),
                                  PlutoColumn(
                                    width: 200,
                                    enableColumnDrag: false,
                                    title: 'NARRATION',
                                    field: 'narration',
                                    type: PlutoColumnType.text(),
                                    enableContextMenu: false,
                                  ),
                                ],

                                rows: data
                                    .map((country) => PlutoRow(
                                          cells: country.isTheory == true
                                              ? {
                                                  'Roll No': PlutoCell(
                                                      value: country.rollNo),
                                                  'stu_name': PlutoCell(
                                                      value: country.studentName
                                                          .toString()),
                                                  'tfm': PlutoCell(
                                                      value: country
                                                          .theoryFullMarks
                                                          .toString()),
                                                  'tom': PlutoCell(
                                                      value: country
                                                          .theoryObtainedMarks
                                                          .toString()),
                                                  'ts': PlutoCell(
                                                      value: country
                                                                  .theoryStatus ==
                                                              0
                                                          ? "Present"
                                                          : country.theoryStatus ==
                                                                  1
                                                              ? "Absent"
                                                              : "Expelled"
                                                                  .toString()),
                                                  'tm': PlutoCell(
                                                      value: country.totalMarks
                                                          .toString()),
                                                  'narration': PlutoCell(
                                                      value: country.narration
                                                          .toString()),
                                                }
                                              : {
                                                  'Roll No': PlutoCell(
                                                      value: country.rollNo),
                                                  'stu_name': PlutoCell(
                                                      value: country.studentName
                                                          .toString()),
                                                  'pfm': PlutoCell(
                                                      value: country
                                                          .practicalFullMarks
                                                          .toString()),
                                                  'pom': PlutoCell(
                                                      value: country
                                                          .practicalObtainedMarks
                                                          .toString()),
                                                  'ps': PlutoCell(
                                                      value: country
                                                          .practicalStatus
                                                          .toString()),
                                                  'tm': PlutoCell(
                                                      value: country.totalMarks
                                                          .toString()),
                                                  'narration': PlutoCell(
                                                      value: country.narration
                                                          .toString()),
                                                },
                                        ))
                                    .toList(),

                                onLoaded: (PlutoGridOnLoadedEvent event) {
                                  // event.stateManager.setShowColumnFilter(false);
                                  print(event);
                                },
                                onChanged: (PlutoGridOnChangedEvent event) {
                                  newdata = event.value;
                                  print("new: $newdata");
                                  print(event);
                                  // newvalue = event.row.toJson();
                                  // print(newvalue);
                                  if (event.column.field == 'tom' &&
                                      event.row.cells['tom']!.value >
                                          event.row.cells['tfm']!.value) {
                                    setState(() {
                                      event.row.cells['tom']!.value = 0;
                                      event.row.cells['tm']!.value = event
                                          .row.cells['tom']!.value
                                          .toString();
                                      Fluttertoast.showToast(
                                          msg:
                                              "obtained marks cannot be greater than full marks");
                                    });
                                  } else if (event.column.field == 'tom' &&
                                      event.row.cells['tom']!.value <=
                                          event.row.cells['tfm']!.value) {
                                    setState(() {
                                      event.row.cells['tm']!.value = event
                                          .row.cells['tom']!.value
                                          .toString();
                                      print(event.row.cells['tm']!.value = event
                                          .row.cells['tom']!.value
                                          .toString());
                                    });
                                  } else if (event.column.field == 'pom' &&
                                      event.row.cells['pom']!.value <=
                                          event.row.cells['pfm']!.value) {
                                    setState(() {
                                      event.row.cells['tm']!.value = event
                                          .row.cells['pom']!.value
                                          .toString();
                                      print(event.row.cells['tm']!.value = event
                                          .row.cells['pom']!.value
                                          .toString());
                                    });
                                  } else if (event.column.field == 'pom' &&
                                      event.row.cells['pom']!.value >
                                          event.row.cells['pfm']!.value) {
                                    setState(() {
                                      event.row.cells['pom']!.value = 0;
                                      Fluttertoast.showToast(
                                          msg:
                                              "obtained marks cannot be greater than full marks");
                                    });
                                  } else if (event.column.field ==
                                      'narration') {
                                    setState(() {
                                      var narration = event
                                          .row.cells['narration']!.value
                                          .toString();
                                      print(narration.toString());
                                    });
                                  } else if (event.column.field == 'ts' ||
                                      event.row.cells['ps']!.value) {
                                    setState(() {
                                      var ts = event.row.cells['ts']!.value
                                          .toString();
                                      var ps = event.row.cells['ps']!.value
                                          .toString();
                                      print(ts.toString());
                                      print(ps.toString());
                                    });
                                  }
                                },

                                configuration: PlutoGridConfiguration(
                                  enterKeyAction: PlutoGridEnterKeyAction
                                      .editingAndMoveDown,
                                  tabKeyAction:
                                      PlutoGridTabKeyAction.moveToNextOnEdge,
                                ),

                                // createFooter: (stateManager) {
                                //   stateManager.setPageSize(10, notify: false); // default 40
                                //   return PlutoPagination(stateManager);
                                // },
                              ),
                            );
                          } else if (snapshot.hasError) {
                            return Text(snapshot.hasError.toString());
                          }
                          // By default, show a loading spinner.
                          return Center(
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: <Widget>[
                                CircularProgressIndicator(),
                                SizedBox(height: 20),
                                Text('This may take some time..')
                              ],
                            ),
                          );
                        },
                      ),
                    )
                  : Text("No Data on the table"),
            ],
          ),
        ),
      ),
    );
  }

  Future<void> save() async {
    if (_formKey.currentState!.validate()) {
      ref.read(teacherNotifierProvider.notifier).createoredit(
          _classselectedItem!.id.toString(),
          examSelectedvalue["id"],
          sectionSelectedvalue["id"],
          subjectSelectedvalue["id"],
          datas.toList(),
          context);
      print(datas);
      await setValue(teacherclass, _classselectedItem!.id.toString());
      await setValue(teacherexam, examSelectedvalue["id"]);
      await setValue(teachersubject, subjectSelectedvalue["id"]);
      await setValue(teachersection, sectionSelectedvalue["id"]);
    }
  }

//Exam
//
  var examSelectedvalue;

  List examlist = [];
  Future<List<Exam>> getExam() async {
    String getexamdetails =
        "/api/services/app/TeacherExam/GetExamForTableDropdown?classId=${_classselectedItem!.id}";
    print(getexamdetails);
    final response = await Api().get(MyConfig.appUrl + getexamdetails);
    print(response.statusCode);

    if (response.statusCode == 200) {
      var jsonData = json.decode(response.data)["result"];
      setState(() {
        examlist = jsonData;
      });
    }

    List<Exam> a = [];
    return a;
  }

  //
//Section
//
  var sectionSelectedvalue;

  List sectionlist = [];
  Future<List<Section>> getSection() async {
    String getresultdetails =
        "/api/services/app/TeacherAcademic/GetSectionForTableDropdown?classId=${_classselectedItem!.id}";
    print(getresultdetails);
    final response = await Api().get(MyConfig.appUrl + getresultdetails);
    print(response.statusCode);

    if (response.statusCode == 200) {
      var jsonData = json.decode(response.data)["result"];
      setState(() {
        sectionlist = jsonData;
      });
    }

    List<Section> a = [];
    return a;
  }

  //
//Subject
//
  var subjectSelectedvalue;

  List subjectlist = [];
  Future<List<Subject>> getSubject() async {
    String getsubjectdetails =
        "/api/services/app/TeacherAcademic/GetSubjectForTableDropdown?classId=${_classselectedItem!.id}";
    print(getsubjectdetails);
    final response = await Api().get(MyConfig.appUrl + getsubjectdetails);
    print(response.statusCode);

    if (response.statusCode == 200) {
      var jsonData = json.decode(response.data)["result"];
      setState(() {
        subjectlist = jsonData;
      });
    }

    List<Subject> a = [];
    return a;
  }

  List<dynamic> datas = [];
  Future<List<_Product>> fetchSummary() async {
    String getallMarkLoaddetails =
        "/api/services/app/TeacherExam/GetAllExamMarkLoadTeacher?examId=${examSelectedvalue["id"]}&classId=${_classselectedItem!.id}&subjectId=${subjectSelectedvalue["id"]}&sectionId=${sectionSelectedvalue["id"]}";
    print(getallMarkLoaddetails);
    final response = await Api().get(MyConfig.appUrl + getallMarkLoaddetails);
    print(response.statusCode);

    if (response.statusCode == 200) {
      Map<String, dynamic> map = json.decode(response.data);
      datas = map["result"];

      return datas.map((row) => _Product.fromJson(row)).toList();
    } else {
      print('Error, Could not load Data.');
      throw Exception('Failed to load Data');
    }
  }
`

**Comment by baryalenn** [comment]
Did you find a solution ?
