### ISSUE TITLE
[Help] Save on edit

### ISSUE THREAD

**Issue by nilroe** [bosskmk/pluto_grid#817]
Hi!

I'm implementing this awesome grid to a log admin panel and I'm strugling on how to update the data on edit, cause I cannot see any onchanged or like in the plutocells

Here is a picture of my app
![image](https://user-images.githubusercontent.com/56450489/231517750-13f3e816-c81d-4f0c-882b-3db53cf30f96.png)

and one of the plutocolumns 
`PlutoColumn(
        title: 'User',
        field: 'usuario',
        type: PlutoColumnType.text(),
        enableSorting: true,
        enableDropToResize: true,
        enableEditingMode: true,
        enableColumnDrag: true),
    PlutoColumn(
        title: 'Movement',
        field: 'movimiento',
        type: PlutoColumnType.select(<String>[
          'ENTRADA',
          'SALIDA',
          'COMM',
        ]),
        enableSorting: true,
        enableEditingMode: true,
        enableDropToResize: true,
        enableColumnDrag: true),`

I work via API to get, insert and delete, wich are working fine

thanks in advance!!

**Comment by selvam920** [comment]
you need to use onChanged event in the plutogrid
PlutoGrid(
onChanged: (PlutoGridOnChangedEvent event) {
            if (event.column.field == 'usuario')
