### ISSUE TITLE
[Feature] Change the property enableEditingMode to allow enabling/disabling specific cells

### ISSUE THREAD

**Issue by mmasdivins** [bosskmk/pluto_grid#818]
If we change the enableEditingMode of the pluto column to a function:
```dart
  bool? Function(PlutoCell)? enableEditingMode;
```

Then in a column we can have more control to disable or enable editing:
```dart
PlutoColumn(
        enableEditingMode: (cell){
          if (cell.value == 10)
            return false;
          return true;
        },
        enableSorting: false,
        title: 'Some Number'.i18n,
        field: 'number',
        type: PlutoColumnType.number(),
      ),
```

If there is already a way to do it I didn't see it.

Thanks for this amazing project.

**Comment by ujwalbasnet1** [comment]
is there already available such a feature? and/or may be with statemanager as well?
