### ISSUE TITLE
[Bug] pluto_grid_export 1.0.4 not compatible with pluto_grid 7.0.1

### ISSUE THREAD

**Issue by ScottAtRedHawk** [bosskmk/pluto_grid#837]
### Steps to reproduce the bug
1. Add `pluto_grid: 7.0.1` to your `pubspec.yaml`.
2. Add `pluto_grid_export: 1.0.4` to your `pubspec.yaml`

### Expected results
We should see `exit code 0` in the terminal.

### Actual results
```
Because pluto_grid_export 1.0.4 depends on pluto_grid >=3.0.2 <7.0.0 and myproject depends on pluto_grid 7.0.1, pluto_grid_export 1.0.4 is forbidden.
So, because myproject depends on pluto_grid_export 1.0.4, version solving failed.
exit code 1
```

### Code sample
N/A

### Execution Environment
**Flutter version**
Flutter version is 3.10.0

**PlutoGrid version**
PlutoGrid version is 7.0.1

**OS**
macOS Ventura 13.3.1 (a)

**Comment by Ammarmahmoud1995** [comment]
same happening to me here  ... I think we `ll have to wait for version 1.05

**Comment by bosskmk** [comment]
Updated to PlutoGridExport 1.0.6.

**Comment by ScottAtRedHawk** [comment]
Awesome! Thank you @bosskmk. I'll close this.
