### ISSUE TITLE
[Feature] Add options to remove outer border of grid

### ISSUE THREAD

**Issue by dzakyraf** [bosskmk/pluto_grid#856]
Thankyou for amazing package, but i have difficulties when remove outer border of the grid because it connected with border inside the grid so i can't fully implement my design. Is possible add options to just remove outer border ? thankyou.

**Comment by Macacoazul01** [comment]
@leedstyh  you can change this on your local version of pluto grid
https://github.com/bosskmk/pluto_grid/issues/870#issuecomment-1646393778

or just change the import to my fork:
pluto_grid:
    git: https://github.com/Macacoazul01/pluto_grid
