### ISSUE TITLE
[Help] Setting selection

### ISSUE THREAD

**Issue by ARPP3** [bosskmk/pluto_grid#862]
Hello, I am not sure if this is possible with the existing API or not, so this might end up being a feature request. 

I am trying to set a cell selected. Not just upon initialization. I have no preference if it's via row/column, or a reference to the `PlutoRow` + offset into the cell, or the `PlutoCell `itself. 

This functionality, if it exists, has eluded me. Is there a way I can do this? 

Thank you,

**Comment by marianodrz** [comment]
I have the same problem.
Trying to select specific row is not possible or havent find any solution that works.
