### ISSUE TITLE
[Feature] PlutoGrid Styles/Configuration

### ISSUE THREAD

**Issue by Lorenzobettega** [bosskmk/pluto_grid#870]
### **I'm trying to do this in PlutoGrid:**

![image](https://github.com/bosskmk/pluto_grid/assets/84482292/f3d7dfd9-4782-450e-a863-d23959b6c7e5)

But, I'm missing some Features to change the grid colors:

**1- First of all, I had to change one per one the column background:**

![image](https://github.com/bosskmk/pluto_grid/assets/84482292/e8b9ceeb-c2a3-437e-92ca-dfcc6a0cd6c8)
```
PlutoColumn(
    title: 'column1',
    field: 'column1',
    type: PlutoColumnType.text(),
    enableRowChecked: true,
    enableColumnDrag: false,
    enableContextMenu: false,
    enableDropToResize: false,
    backgroundColor: Color.fromRGBO(0,67,0,1),
),
```

**2- After I did that, I found 3 problems:**

![image](https://github.com/bosskmk/pluto_grid/assets/84482292/adf33a01-8ab9-41d4-adbf-d314824a5899)
1) Red Problem: I didn't have any option to change only the First Check Box color, that is hidden because have the same tone of the background.
2) Orange Problem: For a uknown reason appear a green line between any Column, that I also cannot modify.
3) Blue Problem: It still missing switch the border of the top, that I tried any option but none of them can do that.

**2 and 3 can be "solve" changing `gridBackgroundColor` (Part 1), but that way afect in the in the rest that I dont want(Part 2):**

![image](https://github.com/bosskmk/pluto_grid/assets/84482292/6c19d947-51c5-4d48-9c47-6e1d774b4658)

**Comment by Lorenzobettega** [comment]
@bosskmk

**Comment by Macacoazul01** [comment]
The problem is on line  1539 of \pluto_grid\lib\src\pluto_grid.dart

static const double gridPadding = 2.0;

this doesn't make any sense
