### ISSUE TITLE
[Bug] Anyone can use this package successfully? I even can not refresh the datagrid after feteched data from my backend service.

### ISSUE THREAD

**Issue by denghejun** [bosskmk/pluto_grid#873]
Anyone can use this package successfully? I even can not refresh the datagrid after fetched data from my backend service.

**Comment by denghejun** [comment]
```
HubService.instance.getOrders({}).then((orders) {
      var rows1 = [
        PlutoRow(
          cells: {
            'order_id': PlutoCell(value: 'e.xxxx'),
            'order_status': PlutoCell(value: 'e.status?.name'),
            'customer_name': PlutoCell(value: 'e.customer?.name'),
            'created_date': PlutoCell(value: '2020-09-09'),
            'created_person': PlutoCell(value: 'e.createUserID'),
            'modify_date': PlutoCell(value: '2020-09-09'),
            'modify_person': PlutoCell(value: 'e.modifyUserID'),
          },
        )
      ];

      PlutoGridStateManager.initializeRows(
        columns,
        rows1,
      );
      stateManager?.setShowLoading(false);
    });
```

**Comment by graemep-nz** [comment]
PlutoGrid works for me but it took me ages to find out how to change the content of the grid after the constructor runs.
The docs here help
https://pluto.weblaze.dev/series/pluto-grid
https://pluto.weblaze.dev/add-and-remove-columns-and-rows

so now what I do in the build method is this
        stateManager?.removeAllRows(notify:false);
        stateManager?.appendRows(plutoRows);

**Comment by jesussmile** [comment]
Damn! i too have to remove and append rows else it wont show from backend, any this else to keep in mind ?
