### ISSUE TITLE
[Help] How to reset/refresh columns state?

### ISSUE THREAD

**Issue by Retr0sec7** [bosskmk/pluto_grid#882]
So I have some columns that I need to toggle between editable and non-editable. I also have a state variable that toggles between `true/false` which is set to the `enableEditingMode` on the columns definition. The problem is that whenever call `setState` to reload the table and the columns, the columns stays the same and don't toggle between editable and noneditable. I tried to call `resetCurrentState`  and  `notifyListeners` but it doesn't seems to work.

**Comment by graemep-nz** [comment]
I think you can use the callback PlutoColumnCheckReadOnly instead of setting readOnly true in the constructor.  I found this by looking at the readOnly argument in the plutoGrid source code.

https://github.com/bosskmk/pluto_grid/releases/tag/2.7.0
