### ISSUE TITLE
[Help] I wanna export table using with footerRenderer but footer not seen in docs. Is there any method for export footer

### ISSUE THREAD

**Issue by mucahitbircan** [bosskmk/pluto_grid#887]

**Comment by mucahitbircan** [comment]
footerRenderer: (rendererContext) {
          return PlutoAggregateColumnFooter(
            rendererContext: rendererContext,
            type: PlutoAggregateColumnType.sum,
            format: '#,###',
            alignment: Alignment.center,
            titleSpanBuilder: (text) {
              return [
                TextSpan(
                  text: text,
                    style: TextStyle(fontWeight: FontWeight.bold)
                )
              ];
            },
          );
        },

**Comment by sathar123** [comment]
u can found any method?

**Comment by mucahitbircan** [comment]
If you are calculating total values, adding it as the last row in tableview seems to be the only solution.
