### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by kholyphoenix0** [bosskmk/pluto_grid#898]
Hello guys!
Could someone explain to me how do I change these names when clicking on the column menu?
Would it be possible to change that name "Contains" to another one too?
Thanks!

![image](https://github.com/bosskmk/pluto_grid/assets/98181179/a434f110-8f4a-4af4-b0f9-d6bf544267e1)

**Comment by jesussmile** [comment]
that is required to search , it is globally accepted.
