### ISSUE TITLE
How can I make validation on the cell when it is editing, not after editing?  [Help] 

### ISSUE THREAD

**Issue by design2023** [bosskmk/pluto_grid#900]
During the updating on the content of the cell, I want to make validation, How Can I do That?

**Comment by Infinity-1729** [comment]
i want the same thing,
have you found any solution in pluto_grid?
like SfDataGrid has canSumbitCell function to validate before submitting.

**Comment by Infinity-1729** [comment]
> During the updating on the content of the cell, I want to make validation, How Can I do That?

i have added canSubmitCell function (default null) and shouldResetOnFailure flag (default false) in PlutoColumn to achieve what i needed, ping me if you still need this

**Comment by design2023** [comment]
Hi @Infinity-1729 
Can you give me your solution, please?
