### ISSUE TITLE
[Feature] auto fit?

### ISSUE THREAD

**Issue by lublak** [bosskmk/pluto_grid#920]
Currently i use `PlutoInfinityScrollRows`.
But currently most columns are to big and not fit.
I also tried all combinations of:
```dart
autoSizeMode: PlutoAutoSizeMode.scale,
resizeMode: PlutoResizeMode.none,
```
I also tried to trigger the autofit method:

```dart
onLoaded: (PlutoGridOnLoadedEvent event) {
  stateManager = event.stateManager;
  stateManager.setShowColumnFilter(true);
  stateManager.setSelectingMode(PlutoGridSelectingMode.row);
  stateManager.addListener(() {
    for (var col in stateManager.columns) {
      stateManager.autoFitColumn(
        stateManager.gridKey.currentContext!,
        col,
      );
    }
  });
},
```

But the colums not auto resize.
![grafik](https://github.com/bosskmk/pluto_grid/assets/44057030/b45a5746-3146-4ec3-8e42-1afb3b93292f)

**Comment by lublak** [comment]
The issue is the resize mode:
```dart
configuration: const PlutoGridConfiguration(
  columnSize: PlutoGridColumnSizeConfig(
    resizeMode: PlutoResizeMode.none,
  ),
),
```

you need to enable resize before autofit the columns:

```dart
stateManager.addListener(() {
  stateManager.setColumnSizeConfig(
    const PlutoGridColumnSizeConfig(
      resizeMode: PlutoResizeMode.normal,
    ),
  );
  for (var col in stateManager.columns) {
    stateManager.autoFitColumn(
      stateManager.gridKey.currentContext!,
      col,
    );
  }
  stateManager.setColumnSizeConfig(
    const PlutoGridColumnSizeConfig(
      resizeMode: PlutoResizeMode.none,
    ),
  );
});
```

**Comment by TienLen2808** [comment]
onLoaded: (PlutoGridOnLoadedEvent event) {
     for(int i = 0 ;i < (columns.length - 3); i++)
            {
               event.stateManager.autoFitColumn(context, columns[i+3]);
             }
    },

i am used auto fix autoFitColumn !!

**Comment by TienLen2808** [comment]
use index of column , to know which columns need to be auto-fixed
