### ISSUE TITLE
[Help] I want to use drop down menu or a custom widget for column filter 

### ISSUE THREAD

**Issue by doonfrs** [bosskmk/pluto_grid#926]
Hi everyone,
I am trying to use a drop-down menu or a custom widget for the column filter, currently, I can only use a simple text box which is not enough.
I searched the documentation but I could not find anything helpful.

**Comment by nikhil-s-b** [comment]
@doonfrs Did you find anything for custom widget filter?

**Comment by doonfrs** [comment]
@nikhil-s-b 
https://github.com/doonfrs/pluto_grid_plus
merged here, use filterWidget 
please provide feedback on the new fork
https://github.com/doonfrs/pluto_grid_plus
and here is the pub.dev
https://pub.dev/packages/pluto_grid_plus
