### ISSUE TITLE
[Bug] Design issue : issue with GridMode & SelectionMode

### ISSUE THREAD

**Issue by vd3d** [bosskmk/pluto_grid#929]
Hi,

I have the feeling that there is a design issue with the grid, but please tell me if I'm wrong.

I'm trying to have a grid:
- read only
- row selectable only
- receive events for rows selection
- ability to set the selected row by code

I have play with PlutoGridMode & PlutoGridSelectingMode, but no way... I can't find a way to have such grid.

To me, here we mix multiples concepts:
- read only / editable (to me it should even be a cell property)
- none / cell / row selection
- single / multiple selection

For example, the Syncfusion grid has such properties: https://help.syncfusion.com/flutter/datagrid/editing
          allowEditing: true,
          selectionMode: SelectionMode.single,
          navigationMode: GridNavigationMode.cell

Also, I noticed 2 issues:
- when I select a row, I should be able to receive the event, in any situation. The row is highlighted but the event not send.
- same situation, if I try to select a row with setCurrentSelectingRowsByRange, it should select it. It is not always the case.

The kind of combination I have tried:

PlutoGridMode.selectWithOneTap & PlutoGridSelectingMode.horizontal
PlutoGridMode.select & PlutoGridSelectingMode.row
PlutoGridMode.normal& PlutoGridSelectingMode.row
...

But there is no way to solve :-(

A'm I wrong ?

**Comment by kAliert** [comment]
I also struggle to find a way to do this. Would be happy if someone finds a way to solve this problem. 

My requirement: 

- PlutoGridMode.selectWithOneTap
- PlutoGridSelectingMode.row
- selecting rows programmatically and clear any previous selected cell / row
