### ISSUE TITLE
[Help]  Rename `contains` to something else.

### ISSUE THREAD

**Issue by JeffConexus** [bosskmk/pluto_grid#943]
How to rename the `contains` text to something else?

**Comment by Yusufihsangorgel** [comment]
++

**Comment by muammerakilli** [comment]
PlutoGrid(
                    configuration: const PlutoGridConfiguration(
                      localeText: PlutoGridLocaleText(filterContains:'FFFFF' )
                    ),
  ),

PlutoGrid(
                  configuration: const PlutoGridConfiguration(
                      localeText: PlutoGridLocaleText.turkish(filterContains:"Filtre"),
                    ),
  ),

**Comment by Yusufihsangorgel** [comment]
> PlutoGrid( configuration: const PlutoGridConfiguration( localeText: PlutoGridLocaleText(filterContains:'FFFFF' ) ), ),
> 
> PlutoGrid( configuration: const PlutoGridConfiguration( localeText: PlutoGridLocaleText.turkish(filterContains:"Filtre"), ), ),

sağolasın Muammer hocam
