### ISSUE TITLE
[Help] How to select a row by code.

### ISSUE THREAD

**Issue by ricardo-guimaraes-tcepr** [bosskmk/pluto_grid#946]
Hi, I need some help to know how to select a row by line of code. I have tried this without success:

1. Using currentSelectingRows 
  stateManager.currentSelectingRows.clear();
  stateManager.currentSelectingRows.add(rendererContext.row);  
  
2. Using toggleSelectingRow
	stateManager.toggleSelectingRow(currentRowkr, notify: true);
	
3. Using setCurrentSelectingRowsByRange
	stateManager.setCurrentSelectingRowsByRange(currentRowkr, currentRowkr);
	
**My PlutoGrid definition:**
PlutoGrid(
	mode: PlutoGridMode.selectWithOneTap,
	columns: columns,
	rows: rowsDados,
	onSelected: (event) {
	  currentRowkr = event.rowIdx ?? -1; 
	},
	onLoaded: (PlutoGridOnLoadedEvent event) {
	  stateManager = event.stateManager;
	  stateManager
		  .setConfiguration(
				stateManager.configuration.copyWith(localeText: 
								const PlutoGridLocaleText.brazilianPortuguese(), 
								columnSize: PlutoGridColumnSizeConfig(
									autoSizeMode: PlutoAutoSizeMode.none)));
	  stateManager.setSelectingMode(PlutoGridSelectingMode.row);  
	},
  )

**Comment by Acacio2000** [comment]
**select**
 event.row!.setChecked(true);
 stateManager.notifyListeners();

**unselect**
 event.row!.setChecked(false);
 stateManager.notifyListeners();
