### ISSUE TITLE
[Feature] Advanced filtering option (AND, OR, ...)

### ISSUE THREAD

**Issue by jubnl** [bosskmk/pluto_grid#956]
Problem :
All filters seem to be AND filters. I need to filter a column based on several possible values.

Examples:

Initial table:
| Col1 | Col2 |
|--------|--------|
| A | D |
| A | E |
| B | E | 
| C | F | 

Filter: Col1(value = A OR B) 
| Col1 | Col2 |
|--------|--------|
| A | D |
| A | E |
| B | E | 

Filter: Col1(value = B OR C)
| Col1 | Col2 |
|--------|--------|
| B | E | 
| C | F | 

At the moment I haven't found a way other than filtering the rows myself, then removing all rows and adding my filtered rows.

**Comment by Acacio2000** [comment]
**This Example to every text fields use custom filter and CaseInsensitive** 
I converted every text fields to UPPER 
Use COMMA to separate words: Ex:  "A,B" "B,C" in any order:  "A,B" = "B,A"  

**String toUpperCaseWithoutAccents(String input) {**
  input = removeDiacritics(input).trim().toUpperCase();
  return input;
}

**class ClassFilterContainAllWords implements PlutoFilterType {**
  const ClassFilterContainAllWords();
  @override
  get compare => ({
        required String? base,
        required String? search,
        required PlutoColumn? column,
      }) {
        if (search != null) {
          search = toUpperCaseWithoutAccents(search);
        }
        var keys = search!.split(',').map((e) => e.trim().toUpperCase()).toList();
        return keys.every((key) => base!.toUpperCase().contains(key));
      };
  @override
  String get title => 'Custom filter';
}


**columnFilter: PlutoGridColumnFilterConfig(**
        filters: const [
          ...FilterHelper.defaultFilters,
          ClassFilterContainAllWords(),
        ],
        resolveDefaultColumnFilter: (column, resolver) {
          if (column.type is PlutoColumnTypeText) {
            return resolver<ClassFilterContainAllWords>() as PlutoFilterType;
          }
          return resolver<PlutoFilterTypeContains>() as PlutoFilterType;
        },
      ),
