### ISSUE TITLE
Is it possible to disable the `FocusScope`?

### ISSUE THREAD

**Issue by busslina** [bosskmk/pluto_grid#964]
I love this package, but when the Table get the focus it is breaking my shortcuts logic. I would love to be able to perform all the shortcuts actions manually from my shortcuts if you provide also an API to those actions

**Comment by taosif7-dreamorbit** [comment]
Any updates on this?

**Comment by doonfrs** [comment]
@taosif7-dreamorbit I think the project was discontinued, it wasn't updated for 6 months, I hope the maintainers announce that, so we can start a new maintained clone.

**Comment by taosif7-dreamorbit** [comment]
@bosskmk Please announce if that's the case
