### ISSUE TITLE
[Help] i want to reload all data when click button

### ISSUE THREAD

**Issue by dkakkuk** [bosskmk/pluto_grid#969]
hi. i have cateogires . if i select category i want clear all data and set new data, can some one help me how to do that. thank you

this is my code

import 'dart:convert';

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:pluto_grid/pluto_grid.dart';
import 'package:wms/pages/sale/invoice_column.dart';
import 'package:wms/pages/sale/sale_item_list.dart';

import 'package:wms/utils/call_api.dart';
import 'package:wms/utils/utils.dart';
import 'package:wms/widget/account_popup_widget.dart';
import 'package:wms/widget/store_dropdown_widget.dart';

class InvoicePage extends StatefulWidget {
  final String customerId;
  const InvoicePage({
    super.key,
    required this.customerId,
  });

  @override
  State<InvoicePage> createState() => _InvoicePageState();
}

class _InvoicePageState extends State<InvoicePage> {
  
  late PlutoGridStateManager stateManager;

  final List<PlutoColumn> columns = invoiceColumns();
  final List<PlutoRow> rows = [];

  Future<PlutoLazyPaginationResponse> fetch(PlutoLazyPaginationRequest request) async {
   

    final response = await CallApiService.callApi("invoice/invoice_list_new");
    final toJson = jsonEncode(response['data']);

    final dataFromServer = await Future.value("""
    {
      "totalPage": $recordsPages,
      "data": $toJson
    }
    """);

    final parsedData = jsonDecode(dataFromServer);
    final rows = parsedData['data'].map<PlutoRow>((rowData) {
      return PlutoRow.fromJson(rowData);
    });

    return PlutoLazyPaginationResponse(
      totalPage: parsedData['totalPage'],
      rows: rows.toList(),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("title"),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
      ),
      body: PlutoGrid(
        columns: columns,
        rows: rows,
        onLoaded: (PlutoGridOnLoadedEvent event) {
          event.stateManager.setSelectingMode(PlutoGridSelectingMode.cell);
          stateManager = event.stateManager;
        },
        onSelected: (PlutoGridOnSelectedEvent event) {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => SaleItemList(
                invoiceId: event.row?.cells['id']?.value,
                invoiceNum: event.row?.cells['invoice_number']?.value,
              ),
            ),
          );
        },
        mode: PlutoGridMode.select,
        createFooter: (stateManager) {
          return PlutoLazyPagination(
            initialPage: 1,
            fetch: fetch,
            stateManager: stateManager,
          );
        },
      ),
    );
  }
}

**Comment by taosif7-dreamorbit** [comment]
Any updates on this? Solution?

**Comment by dhanesh12twice** [comment]
You can use statemanager.notifyListeners() to reload
