### ISSUE TITLE
Is there a way to pre-assign filters to specific columns during Grid rendering?

### ISSUE THREAD

**Issue by LucasHenriqueAbreu** [bosskmk/pluto_grid#972]
Hello everyone,

I'm working on a project where users configure filters to facilitate future queries. I would like to know if there is a feature or method available in the package that allows pre-assigning a filter to a specific column during the rendering of the Grid.

This functionality would be extremely useful for my project, as it would help pre-configure the filters according to the user's needs, saving time and enhancing the overall experience.

I appreciate in advance any information or suggestions that may help achieve this goal.

By the way, I would like to take this opportunity to congratulate the team for the excellent work done on this package. The existing features are very useful and significantly contribute to the project's efficiency.

Thank you!

**Comment by doonfrs** [comment]
Please open the feature request here
https://github.com/doonfrs/pluto_grid_plus 
I will manage to develop it.
