### ISSUE TITLE
How to rows data refresh(update) with loader on click button

### ISSUE THREAD

**Issue by IrfanHangingPanda** [bosskmk/pluto_grid#975]
### **_I want the rows data to be refreshed with loader when the  refresh icon is clicked. Even if we remain on any pagination number, when the tab is refreshed, it shows us the data of pagination 1._**

**On refresh **_fetchData_** should call _currentPage_ 1**
`await fetchData(currentPage, false, list);`

**Here the image  refresh icon with data**
<img width="611" alt="Screenshot 2023-11-16 at 3 46 52 PM" src="https://github.com/bosskmk/pluto_grid/assets/109954332/f72bfd82-f5a1-49c6-afea-0ea09e4b24ad">

**Here the fetch function code**
` Future<PlutoLazyPaginationResponse> fetch(
    PlutoLazyPaginationRequest request,
  ) async {
    currentPage = request.page;
    await fetchData(currentPage, false, list);

    return PlutoLazyPaginationResponse(
      totalPage: (totalNumber / rowsPerPage).ceil(),
      rows: getRowsFromDbData(),
    );
  }`
  
  **Here the getRowsFromDbData code**

  `  List<PlutoRow> getRowsFromDbData() {
    return databaseData.map((row) {
      return PlutoRow(
        cells: {
          'id': PlutoCell(value: row['id'].toString()),
          'visitor_name': PlutoCell(value: row['visitor_name']),
          'nvr_name': PlutoCell(value: row['nvr_name']),
        },
      );
    }).toList();
  }`
  
  **Plutogrid code**

  `PlutoGrid(
          key: _plutoGridKey,
          columns: columns,
          rows: databaseData.isNotEmpty ? getRowsFromDbData() : [],
          // columnGroups: columnGroups,

          onLoaded: (PlutoGridOnLoadedEvent event) {
            stateManager = event.stateManager;
            stateManager!.setShowColumnFilter(true);
            /// When the grid is finished loading, enable loading.
            stateManager!.setShowLoading(true);
          },
          onChanged: (PlutoGridOnChangedEvent event) {
            print(event);
          },
          rowColorCallback: (rowColorContext) {
            return Color(rowColorContext.rowIdx);
          },
          noRowsWidget: Center(
            child:
                Text('Data not found', style: TextStyle(color: Colors.white)),
          ),
          createFooter: (stateManager) {
            return PlutoLazyPagination(
              initialPage: currentPage,
              initialFetch: true,
              fetchWithSorting: true,
              fetchWithFiltering: true,
              fetch: fetch,
              stateManager: stateManager,
            );
          },
          configuration: PlutoGridConfiguration.dark(
              columnSize: PlutoGridColumnSizeConfig(
                  autoSizeMode: PlutoAutoSizeMode.equal)),
        )`

**Comment by mstestlp** [comment]
I need that.
I am currently resolving the issue and hope that the official can provide a better solution
`event.stateManager.eventManager?.addEvent(
              PlutoGridChangeColumnSortEvent(
                  column: PlutoColumn(
                      field: "id", title: "id", type: PlutoColumnType.text()),
                  oldSort: PlutoColumnSort.ascending));`
