### ISSUE TITLE
[Bug]  Deploy web 

### ISSUE THREAD

**Issue by Guimarte** [bosskmk/pluto_grid#977]
### Code sample
```dart
/// If you have a code sample here, please attach it.
```

### Execution Environment
**Flutter version**

**PlutoGrid version**

**OS**

**Comment by freddydrodev** [comment]
Check this out #978

**Comment by Guimarte** [comment]
> Check this out #978 in particular my [last comment ](https://github.com/bosskmk/pluto_grid/issues/978#issuecomment-1817604873)

hi, did you see this error?

![image](https://github.com/bosskmk/pluto_grid/assets/66447422/cdee941a-d3e4-4f25-affe-942656da647d)


im using the last version flutter and pluto_grid from git like comented

**Comment by freddydrodev** [comment]
When I was trying to solve the issue I had to upgrade my flutter version. After doing it, I have faced another issue, I don't know how to explain but my flutter version was upgraded when I checked it with ```sh
flutter --version
```
But the local files were not updated. Try this solution and tell me if it works at each step

### SOLUTION ONE

Do ```sh
flutter channel stable && flutter upgrade && flutter doctor -v
```
And restart your computer 

### SOLUTION TWO

From your project folder don't forget to do
```sh 
flutter clean && flutter pub get
```

### SOLUTION THREE
Open to the flutter base folder with VSCode mine looks like `/User/myuser/.flutter/flutter`
And do a pull request from the git tab on the left side. You can also do the git pull from terminal if you are comfortable with it
