### ISSUE TITLE
[Bug] New Version Flutter - Error

### ISSUE THREAD

**Issue by Guimarte** [bosskmk/pluto_grid#981]
### Code sample
```dart
/// If you have a code sample here, please attach it.
```

### Execution Environment
**Flutter version**

**PlutoGrid version**

**OS**

![image](https://github.com/bosskmk/pluto_grid/assets/66447422/92c5e560-e647-4428-aa95-b09ece2bee56)

**Comment by doonfrs** [comment]
Maintained version here: https://pub.dev/packages/pluto_grid_plus
