### ISSUE TITLE
virtual scroll to support more than 10 million records 

### ISSUE THREAD

**Issue by Haugpro** [bosskmk/pluto_grid#989]
currently pluto_grid is not really usable with a million PlutoRows. Instead of attaching a prefilled List<PlutoRow> to the grids 'rows' property I'd like to provide a function like 'PlutoRow rowOfIndex( int index)' and a new 'rowCount' that will be set to the maximum of the original dataset. I do not ask for infinite scrolling, the max. number of rows is known in advance so that the scrollbar can reflect that size correctly.
Reason: I have large log-files locally (on desktop) containing about 50 million records in binary format. There is no problem loading that binary file, but it is impossible (or at least unusable) to create a List<PlutoRow> containing all the records and assign that to pluto_grid. 
With flutters ListView.builder function this is quite easy possible and performant, since only the list items are created, that are currently in the view. But having this with pluto_grid would save a lot of datagrid related work.
Maybe there is a way already to do virtual scrolling in that sense or it is easy to implement?
Thank you

**Comment by doonfrs** [comment]
I think you need to implement pagination outside plutogrid
