### ISSUE TITLE
[Other] How to Change Text Color within "filterContains" in PlutoGrid?

### ISSUE THREAD

**Issue by SentezEurope** [bosskmk/pluto_grid#992]
Hello PlutoGrid Support Team,
![ornek](https://github.com/bosskmk/pluto_grid/assets/86019743/1d14bb8e-be2f-424e-aff5-df604efe5ee3)

I hope this message finds you well. I have been using the PlutoGrid package in my Flutter application and I'm trying to customize the text color within the "filterContains" feature.

I have multiple themes in my application, and I would like to know how I can change the text color specifically within the "filterContains" functionality. Could you please provide guidance or code examples on how to achieve this?

If possible, I would also like to understand which section or property in the PlutoGrid configuration is responsible for controlling the text color within the "filterContains" feature.
Thank you in advance for your assistance.

Best regards,
Umut ALYU

**Comment by SrS2225a** [comment]
I just look at the class that pluto grid uses for styling as a reference to figure out what I can change with it.  I think that could help you as well. That class has all the styling options you can currently change on your grids. Here is the class: 
https://github.com/bosskmk/pluto_grid/blob/master/lib/src/pluto_grid_configuration.dart#L193
