### ISSUE TITLE
[Help] Get Column ID and Name

### ISSUE THREAD

**Issue by softplaceio** [bosskmk/pluto_grid#998]
Hello, guys!

How can I get the Column ID and Name using:
```
onSelected:
onRowDoubleTab:
nowSecondaryTap:
```

Thanks a lot !

**Comment by vincetphanee** [comment]
Are you able to run the sample code ? I have many error with it so I would like to know if the latest version works

**Comment by softplaceio** [comment]
I give up on "pluto_grid".
Researching a little and using ChatGPT I am using "PaginatedDataTable" to create the Grid, 
Filter and interaction with the Grid cell.

![image](https://github.com/bosskmk/pluto_grid/assets/82031362/1b15c5a3-4bb1-4e22-90d0-e5329bbf0bb9)
